### ISSUE TITLE
Hack: Provide better information on error when related to different line

### ISSUE THREAD

**Issue by SiebelsTim** [facebook/nuclide#1]
You could often receive an error like this:

```
... This is an int
... It is incompatible with object of type...
```

Nuclide however shows only the `This is an int` error on the line where it's an int. You'd have to start `hh_client` to find the erroring line.

Example with error with different implementations in inheritance:
The real error is in a child class, which can be confusing.
![nucl3](https://cloud.githubusercontent.com/assets/1153003/7788488/a4e4d206-023c-11e5-8fec-16e88c1a3f67.png)

**Comment by mostafaeweda** [comment]
that was fixed by the introduction of traces with the new diagnostics framework
