### ISSUE TITLE
remote server generate symbol fail

### ISSUE THREAD

**Issue by yuankaiz** [facebook/nuclide#1007]
### Issue and Steps to Reproduce
So I've added a remote project folder from my server, and when I tried to generate symbols for my project, it fails with error message "'/Users/XXXXX/.atom/packages/symbol-gen/vendor/ctags-darwin' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."
Is nuclide compatible with symgol-gen package?   
If so, how should I generate .ctags file for a remote project folder?  

### Expected Behavior
It should generate a .ctags file in the project root folder. 

### Actual Behavior
Nothing gets generated. 
Error message "'/Users/XXXXX/.atom/packages/symbol-gen/vendor/ctags-darwin' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process."

### Versions
* Atom: 1.31.1 x64
* Nuclide: 0.201.0
* Client OS: macOS El Capitan 10.11.6 (15G1108)
* Server OS (optional): Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-57-generic x86_64)

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (25) /Users/XXXXX/.atom/packages
├── autocomplete-python@1.8.28
├── haskell-grammar@0.4.0
├── highlight-line@0.12.0
├── highlight-selected@0.12.0
├── kite@0.6.7
├── language-babel@2.50.1
├── language-graphql@0.8.0
├── language-ini@1.17.0
├── language-latex@1.0.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── minimap@4.26.7
├── minimap-highlight-selected@4.5.0
├── nuclide@0.201.0
├── nuclide-format-js@0.0.36
├── project-manager@3.3.3
├── script@3.14.1
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── symbol-gen@1.3.1
├── symbols-tree-view@0.13.2
└── tool-bar@1.0.1

**Comment by hansonw** [comment]
It looks like `symbol-gen` is **not** compatible with Nuclide's remote projects (in general, we don't have a good way for third-party packages to work with remote files and directories at the moment).

However, if you generate a `tags` file remotely by yourself, Nuclide can pick that up and use it in the Cmd-T results as well as for Hyperclick support. You can probably just copy https://github.com/weskinner/symbol-gen/blob/master/lib/.ctags into your remote project and run ctags by yourself :)

**Comment by yuankaiz** [comment]
Thanks, @hansonw   
I'm not quite sure what this `.ctags` file do...  
Should I just copy it into my remote project root folder and run `ctags -R .` there?  
Anything else I need to do in order for Nuclide to pick up the `tags` file?   

Thanks

**Comment by hansonw** [comment]
The `.ctags` file is the configuration for ctags. looks like the `symbol-gen` package runs `ctags --config=<path to .ctags>` but it might just pick it up automatically.. probably `ctags --help` will reveal everything :)

Nothing else should be necessary. Note that we unfortunately cannot support remote cmd-r and cmd-shift-r at the moment, as there is currently no API within Atom to integrate with these.

**Comment by yuankaiz** [comment]
Great, will test it out. Thanks!

**Comment by yuankaiz** [comment]
Is it related to https://github.com/atom/symbols-view/pull/204 ?

**Comment by hansonw** [comment]
Yes, exactly :)
