### ISSUE TITLE
Mercurial: failed to subscribe to watchman! on start up

### ISSUE THREAD

**Issue by pishty1** [facebook/nuclide#1008]
Hello,

i am getting this error on atom start up "Mercurial: failed to subscribe to watchman! on start up"
File highlighting is working when file is changed, however diff view isnt working with "Revisions not loaded" in the source control navigator.

nuclide : 0.201.0
Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
watchman: 4.8.0

update: managed to get rid of the error by running "watchman --no-spawn --no-local shutdown-server",
however diff view still isnt working

**Comment by mostafaeweda** [comment]
Since the file highlighting worked while mercurial / watchman weren't setup correctly, I assume you are working on a git repository - while the Diff View currently supports Mercurial repositories only.
See https://nuclide.io/docs/features/hg/ & https://github.com/facebook/nuclide/issues/436

**Comment by pishty1** [comment]
am working on a mercurial repo 
Mercurial Distributed SCM (version 3.7.3).

show history, revert and toggle blame work, but not diff view

**Comment by mostafaeweda** [comment]
Could you not have the repository folder not set as your current working directory?
If not, right click the folder and click "Set to Current Working Root"
Also, are you sure you are using the latest Nuclide/Atom/Watchman/Mercurial? - check the install guide at https://nuclide.io/docs/editor/setup/#quick-install

If none of that help, I'd check Atom's console for error messages (Open using `CMD+SHIFT+I`).
