### ISSUE TITLE
Q: iOS Tooling Support

### ISSUE THREAD

**Issue by shooley** [facebook/nuclide#101]
I watched the video from F8 with the iOS demo and was wondering if its possible to use this in the current release?  Just reading through the source for the tests for Clang it looks like not just yet?

**Comment by colmdoyle** [comment]
The initial release only supports Hack / React / Flow I believe.

**Comment by myusuf3** [comment]
Ideas on when this will be released for everyone else! Super excited here and would like to stop using 3 IDEs. :)

**Comment by jamesgpearce** [comment]
No, but we're working fast! What you saw in the demo is what we are shooting for...
