### ISSUE TITLE
Version mismatch with no updates

### ISSUE THREAD

**Issue by LoganDark** [facebook/nuclide#1020]
### Issue and Steps to Reproduce
My server version is at 205 and my client version is at 197. For some reason none of them have updates. This is preventing me from connecting to my VPS and fixing a critical issue affecting some of my services.

### Expected Behavior
The client should have an update available!!!!!

### Actual Behavior
No package updates for `nuclide`

### Versions
* Atom: 1.12.7
* Nuclide: 197
* Client OS: macOS Sierra 10.12.2
* Server OS (optional): Ubuntu 16.04 LTS x64

### Additional Details
* Installed packages (`apm ls --installed`):
![](https://puu.sh/tUKNa/f8f89bfe4d.png)

Plaintext:
```
Community Packages (8) /Users/LoganDark/.atom/packages
├── Remote-FTP@0.9.4
├── atom-format-lua@0.1.5
├── autocomplete-python@1.8.26
├── hyperclick@0.0.40
├── kite@0.7.13
├── language-lua@0.9.11
├── nuclide@0.197.0
└── terminal-plus@0.14.5

└── (empty)
```

**Comment by jgebhardt** [comment]
You are running an outdated version of Atom. Atom won't offer to upgrade packages that require a higher version of Atom than what you have installed.
Upgrade to at least Atom 1.13 (1.14.0, released today, should work as well). You should be seeing package upgrades. Please re-open this issue if that did not fix it.

**Comment by LoganDark** [comment]
I cannot reopen this issue if it is closed by a collaborator. But I will try it, thanks

**Comment by LoganDark** [comment]
Yes, the Nuclide update has shown up. Thanks
