### ISSUE TITLE
Flow support warning for symbolic links as folders

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#1024]
### Issue and Steps to Reproduce
I receive the below warning every time I start Atom/Nuclide. This is new behavior as of 0.206.0.

![image](https://cloud.githubusercontent.com/assets/12532733/22911487/d2e8a212-f214-11e6-8a77-ac8584166e7f.png)

The actual physical path is `/Volumes/SuperData/Sites/` but I work in a folder that's a symbolic link to that folder.

### Versions
* Atom: 1.14.1
* Nuclide: 0.260.0
* Client OS: Mac OS 10.12.3

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (25) /Users/samh/.atom/packages
├── autocomplete-modules@1.6.7
├── expose@0.13.0
├── git-time-machine@1.5.6
├── haskell-grammar@0.4.0
├── highlight-selected@0.12.0
├── js-refactor@0.7.5
├── language-babel@2.54.1
├── language-graphql@0.8.0
├── language-ini@1.17.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@1.11.23
├── linter-eslint@8.1.1
├── merge-conflicts@1.4.4
├── minimap@4.26.8
├── nuclide@0.206.0
├── nuclide-format-js@0.0.36
├── nuclide-test-runner-jest@0.3.0
├── refactor@0.11.3
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── todo-show@1.10.0
└── tool-bar@1.0.1
```

**Comment by ebluestein** [comment]
Hey ffxsam,

This is a limitation due to new behavior in Atom 1.14. Symlinks are no longer resolved in project paths, which can cause issues with your Flow results. Our recommendation is no mount the actual canonical project path rather than the symlink to stop seeing that warning on launch.


Thank you for using Nuclide!
