### ISSUE TITLE
Unexpected Error when trying to connect to remote server

### ISSUE THREAD

**Issue by zakiaziz** [facebook/nuclide#1028]
### Issue and Steps to Reproduce
I'm unable to connect to remote server. I've installed the apm packing locally on my machine, and the npm on the remote server (note: `npm install -g nuclide` didn't work, `sudo npm install -g nuclide` did). I put in the relevent connection info in the remote connection window and hit connect. This error popped up:
![screen shot 2017-02-23 at 3 03 50 pm](https://cloud.githubusercontent.com/assets/940281/23276716/63d142a4-f9d9-11e6-9f45-e629d8acbd08.png)
and this is the content of that file:
```
/usr/lib/node_modules/nuclide/pkg/nuclide-server/lib/nuclide-main.js:17
const {__DEV__} = require('../../nuclide-node-transpiler/lib/env');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

### Expected Behavior
Should have connected to the remote server.

### Actual Behavior
Did not connect to remote server. Error message displayed.

### Versions
* Atom: v1.14.3
* Nuclide: v0.207.0
* Client OS: OSX 10.12.2
* Server OS (optional): Ubuntu 14.04

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (1) /Users/zakiaziz/.atom/packages
└── nuclide@0.207.0
```

**Comment by nmote** [comment]
It looks like you have an old version of Node installed on the server. You currently need at least Node 6.5.0: https://nuclide.io/docs/help/troubleshooting/#installation
