### ISSUE TITLE
Diagnostics painfully slow, especially with flow

### ISSUE THREAD

**Issue by joncursi** [facebook/nuclide#1029]
I have disabled my atom-linter package in favor of nuclide's built in diagnostics. However, I am experiencing very poor performance in the time it takes for diagnostics to report new results after a file is saved, both with ESLint, but especially for flow. The loading indicator spins for 20-30 seconds on every save. I don't understand why this is, since atom-linter is able to report instantly, and running `flow` from terminal also checks in under 1 second.

Hardware:

<img width="253" alt="screen shot 2017-02-24 at 1 05 02 am" src="https://cloud.githubusercontent.com/assets/4974609/23292401/7b65b13a-fa2d-11e6-972d-425b7f7ffbda.png">

My Mac is running at pretty hot temps with nuclide. However, on the health dashboard, the overall CPU metric never goes above 4% which feels contradictory. Any ideas on why things are slowing down inside of nuclide, but not when run from outside?

PS> I have tried using global flow-bin and local flow-bin, same result.

**Comment by joncursi** [comment]
Looks like the health stats reported in nuclide do not correlate to those that are reported by Activity Monitor. Looks like flow processes running in the BG thru nuclide are killing my machine:

![screen shot 2017-02-24 at 1 50 07 am](https://cloud.githubusercontent.com/assets/4974609/23293349/b079cae0-fa33-11e6-8a58-922eb3528c6f.png)

Every time I save a file, my mac's fans start roaring.

**Comment by nmote** [comment]
This is pretty much a known issue with Flow. I'm closing because this isn't specific to Nuclide, but feel free to open an issue on the facebook/flow repository.

**Comment by joncursi** [comment]
Fixed for me in 0.209.0 / flow 0.41.0
