### ISSUE TITLE
Not offered update past Nuclide 0.205.0

### ISSUE THREAD

**Issue by LegNeato** [facebook/nuclide#1039]
### Issue and Steps to Reproduce
I have Nuclide version `0.205.0` installed and Atom doesn't see an update to the latest version (`0.208.0`).

### Expected Behavior
I should get an update to the latest Nuclide.

### Actual Behavior
No update, stuck on old version.

#### OS
```
Software:

    System Software Overview:

      System Version: macOS 10.12.3 (16D32)
      Kernel Version: Darwin 16.4.0
      Time since boot: 16 days 8:24
````
#### Atom
Atom is `1.14.0` in the UI.

#### Misc

```sh
$ apm -v
apm  1.15.3
npm  3.10.5
node 4.4.5 x64
python 2.7.12
git 2.10.1
```

### Repro

```sh
$ apm ls | grep nuclide
├── nuclide@0.205.0
├── nuclide-test-runner-jest@0.3.0
```

```sh
$ apm upgrade
Package Updates Available (0)
└── (empty)
```

Oddly, when I use `show` I can see it and I am prompted to install:

```sh
$ apm show nuclide
nuclide
├── 0.208.0
├── https://github.com/facebook/nuclide
├── A unified developer experience for web and mobile development, built as a suite of features on top of Atom to provide hackability and the support of an active community.
├── 327486 downloads
└── 111 stars

Run `apm install nuclide` to install this package.
```

I haven't installed that way (I am sure it will work) in order to help track down a root cause.

**Comment by jgebhardt** [comment]
The minimum required Atom version for Nuclide 206+ is 1.14.2. Update your Atom and you should see Nuclide in the list of available package updates.
