### ISSUE TITLE
[FileTree] Add ability to hide gitignored files

### ISSUE THREAD

**Issue by grabbou** [facebook/nuclide#105]
The standard Atom sidebar has this option so I can easily `exclude` files I am not interested in seeing (node_modules, entry_ and other side-effects like tmp). Would be cool to either take the list from `.gitignore` or add an ability to `Exclude` a file like in WebStorm.

**Comment by grabbou** [comment]
Closing as duplicate of #76

**Comment by Nagato23** [comment]
sorry...Could you give me a briefing on this project
