### ISSUE TITLE
Annoying code highlighting

### ISSUE THREAD

**Issue by hmeerlo** [facebook/nuclide#1053]
### Issue and Steps to Reproduce
Since one of the last upgrades of Nuclide it has started to highlight code parts in a very annoying way and I don't know how to turn it off:
![screen shot 2017-03-15 at 15 14 17](https://cloud.githubusercontent.com/assets/448150/23955183/7b43ea20-0999-11e7-97ff-446cd3c7815b.png)

### Expected Behavior
No code highlighting

### Actual Behavior
See screenshot

### Versions
* Atom: 1.15.0
* Nuclide: 0.209.0
* Client OS: MacOS 10.12.3
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

```
16:13 $ apm ls --installed
Community Packages (15) /Users/hmeerlo/.atom/packages
├── haskell-grammar@0.4.0
├── highlight-selected@0.12.0
├── language-babel@2.56.2
├── language-graphql@0.8.0
├── language-ini@1.18.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── nuclide@0.209.0
├── nuclide-format-js@0.0.36
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0
```

**Comment by nmote** [comment]
You have enabled the experimental "Highlight identifier references" option in the settings for Flow, which warns in its description that "it is still under-development, so the results may not be what you expect."

**Comment by hmeerlo** [comment]
Mea culpa
