### ISSUE TITLE
Flow syntax highlighting: no syntax highlighting after first function declaration

### ISSUE THREAD

**Issue by kuuup-at-work** [facebook/nuclide#1058]
### Issue and Steps to Reproduce
When you declare functions only the first declaration has syntax highlighting.

### Expected Behavior
All function declarations should have syntax highlighting

### Actual Behavior
No syntax highlighting after first declaration (example from mobx)
![image](https://cloud.githubusercontent.com/assets/7289171/24035367/9c0dc7d2-0af5-11e7-92a0-f3a2a9797bdc.png)

### Versions
* Atom: 1.15.0 x64
* Nuclide: 0.210.0
* Flow: 0.41.0
* Client OS: Ubuntu 16.04
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── file-icons@2.0.17
├── nuclide@0.210.0
└── tool-bar@1.1.0

**Comment by nmote** [comment]
Nuclide doesn't do any syntax highlighting for JS/Flow code. We recommend checking out the language-babel package which does a pretty good job.
