### ISSUE TITLE
Uncaught Error: Timeout after 60000 for id: 76, Calling remote method fetchBookmarks..

### ISSUE THREAD

**Issue by rexyl** [facebook/nuclide#1059]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.210.52418942

### Stack Trace

Uncaught Error: Timeout after 60000 for id: 76, Calling remote method fetchBookmarks..

```
At /opt/facebook/nuclide/0.210.52418942/nuclide/node_modules/rxjs/bundles/Rx.min.js:34

Error: Timeout after 60000 for id: 76, Calling remote method fetchBookmarks..
  at Call._timeout (/opt/facebook/nuclide/0.210.52418942/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:142:20)
  at Call._timerId.setTimeout (/opt/facebook/nuclide/0.210.52418942/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:112:12)

```

### Commands

```
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
language-babel 2.55.4 
language-graphql 0.8.0 
language-ini 1.18.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.7 
merge-conflicts 1.4.4 
nuclide 0.210.52418942 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.0.1 
```

**Comment by aadisriram** [comment]
This could mean 'hg' was holding the lock for some other operation, is this a consistent issue for you? If there is a set of steps you have to repro this feel free to reopen and update the steps.
