### ISSUE TITLE
Flow errors don't show up until I do a new edit

### ISSUE THREAD

**Issue by 0xR** [facebook/nuclide#106]
1. Edit a file
2. Save file
3. No errors show up
4. Add a new line
5. Error show up instantly

The flow server does show the errors on the commandline instantly. I just don't see them updated in atom.

I'm using atom 1.0.0, flow 0.12.0, nuclide-flow 0.0.22 and linter 1.0.6

Normal lint seems to have the same issue.

**Comment by danneu** [comment]
@0xR: Uninstall `linter` and install `linter-plus`.

**Comment by pveyes** [comment]
@0xR I had some issues until I disabled 'linter on the fly' setting in `linter` packages (but now I have to save the file to get flow analyze my code).

Seems like this is `linter` issues after they merged with `linter-plus`

**Comment by ssorallen** [comment]
@danneu, the linter-plus package has been replaced by linter. That team was planning on unpublishing linter-plus, and it looks like that happened yesterday.

**Comment by 0xR** [comment]
Disabling on the fly seem to solve the issue. Also `linter-plus` was indeed unavailable when I was installing.

On another note it would make sense if nuclide would install its own dependencies. Also I found the fact that I needed linter at all in another issue on github while it should be in the installation documentation.

**Comment by nmote** [comment]
There's been a lot of churn with the linters lately. I'm inclined to wait a few days and revisit this if it is still a problem.

**Comment by nmote** [comment]
I can no longer repro this on the latest source version of Nuclide. I assume it's been fixed in the linter package. Please reopen if you still have this problem when using the source version of Nuclide.
