### ISSUE TITLE
Uncaught Error: merge conflicts quit with no active repository!

### ISSUE THREAD

**Issue by leebyron** [facebook/nuclide#1061]
[Enter steps to reproduce:]

1. hg rebase a bookmark which has merge conflicts
2. (see atom/nuclide automatically show merge conflicts)
3. solve merge conflicts and complete rebase in terminal
4. (notice atom/nuclide still shows pending merge conflicts)
5. Press "Quit" in merge conflict panel to dismiss

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.210.52418942

### Stack Trace

Uncaught Error: merge conflicts quit with no active repository!

```
At /opt/facebook/nuclide/0.210.52418942/nuclide/pkg/nuclide-hg-conflict-resolver/lib/MercurialConflictContext.js:172

Error: merge conflicts quit with no active repository!
  at MercurialConflictContext.quit (/opt/facebook/nuclide/0.210.52418942/nuclide/pkg/nuclide-hg-conflict-resolver/lib/MercurialConflictContext.js:172:13)
  at MergeConflictsView.quit (/packages/merge-conflicts/lib/view/merge-conflicts-view.coffee:78:20)
  at /packages/merge-conflicts/node_modules/space-pen/lib/space-pen.js:220:36)
  at HTMLButtonElement.dispatch (/packages/merge-conflicts/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/packages/merge-conflicts/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Non-Core Packages

```
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
language-babel 2.56.2 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
merge-conflicts 1.4.4 
nuclide 0.210.52418942 
nuclide-format-js 0.0.36 
opened-files 0.3.6 
set-syntax 0.3.2 
shadow 0.1.0 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by aadisriram** [comment]
I tried the repro steps you gave and the conflict resolution completed successfully and nuclide removed the merge conflicts pane. Is this a 100% repro for you?

**Comment by leebyron** [comment]
I've gotten a consistent repro the last 3 times I've rebased commits like this over the last couple days, yes.

**Comment by aadisriram** [comment]
I've been trying to repro this but it seems to be working fine, on a side note I did fix a couple of bugs in the merge conflict flow, maybe this was a side effect of the previous bugs. Can you update to v211 and update if this is still happening?

**Comment by leebyron** [comment]
Just updated to the latest version and still see this error pretty regularly with the same repro steps.

**Comment by aadisriram** [comment]
Lets track this internally, i'm unable to repro this case.
