### ISSUE TITLE
Deprecated os. tmpdir() issue

### ISSUE THREAD

**Issue by Chathula** [facebook/nuclide#1063]
### Issue and Steps to Reproduce
i can't install nuclide. it shows this error 

> (node:5359) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead

### Versions
* Atom: 1.14.1
* Nuclide: 0.209.0
* Client OS: Linux (Manjaro Deepin 16.10.3)
* Server OS (optional):

**Comment by aadisriram** [comment]
Are you still facing issues installing Nuclide?

What is your system node version?
Nuclide automatically uses tmpdir or tmpDir based on your node version.

Please reopen if issue persists.
