### ISSUE TITLE
support ed25519 ssh key format

### ISSUE THREAD

**Issue by stefreak** [facebook/nuclide#1068]
### Issue and Steps to Reproduce
I want to work remotely on a server that only allows connections via ed25519.

### Expected Behavior
Authentication via ed25519 private / public keypair incl. certificates should work.

### Actual Behavior
SSH-Agent: Nuclide asks for password.
Private key file: ```Cannot parse privateKey: Unsupported key format```

### Versions
* Atom: 1.15.0
* Nuclide: 0.211.0
* Client OS: Mac OS 10.11.6 
* Server OS (optional): Ubuntu 16.04 Xenial

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (1) /Users/stefreak/.atom/packages
└── nuclide@0.211.0
```

**Comment by aadisriram** [comment]
You should convince this to happen https://github.com/mscdex/ssh2/issues/352 :)
We use the external ssh library

**Comment by stefreak** [comment]
@aadisriram thanks, I poked them.
