### ISSUE TITLE
Flow not working with Fish set to default shell

### ISSUE THREAD

**Issue by jazmon** [facebook/nuclide#1069]
### Issue and Steps to Reproduce
Flow doesn't start up properly if shell is not posix compatible (Fish shell). Doesn't matter if project flow-bin or global set in settings. I tested this by changing my default shell back to bash and everything started to work. Also tried a fresh install of atom. Flow *does* start w/ fish shell once every blue moon.

0. (install Fish shell) 
1. Set shell to fish and `chsh -s [FISH SHELL PATH]`
2. Reboot computer
3. Launch Atom
4. Open a project with flowtype enabled
5. Error shows up

Possibly related, includes screenshot of the error: https://github.com/facebook/nuclide/issues/911

### Expected Behavior
Flow should work

### Actual Behavior
Atom shows error "Flow not found"

### Versions
* Atom: 1.15.0
* Nuclide: 0.211.0
* Client OS: Mac OS 10.12.3
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (42)[/Users/ahuh/.atom/packages
├── api-docs@0.0.6
├── atom-beautify@0.29.17
├── autoclose-html@0.23.0
├── autocomplete-emojis@2.5.0
├── code-peek@1.4.17
├── color-picker@2.2.5
├── docblockr@0.9.3
├── double-tag@0.7.0
├── editorconfig@2.2.2
├── elm-format@2.1.0
├── elmjutsu@5.5.0
├── emmet@2.4.3
├── file-icons@2.1.1
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── html-to-elm@0.2.0
├── language-babel@2.57.1
├── language-elm@1.5.0
├── language-groovy@0.6.0
├── language-ini@1.19.0
├── language-ocaml@1.1.2
├── language-scala@1.1.8
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── lebab@0.10.0
├── linter@2.1.2
├── linter-elm-make@0.23.2
├── linter-eslint@8.1.4
├── linter-stylelint@3.9.0
├── linter-tidy@2.3.1
├── merge-conflicts@1.4.4
├── minimap@4.26.8
├── minimap-bookmarks@0.4.2
├── nuclide@0.211.0
├── pigments@0.39.1
├── prettier-atom@0.24.0
├── project-manager@3.3.4
├── sort-lines@0.14.0
├── sync-settings@0.8.1
├── todo-show@1.11.0
├── tool-bar@1.1.0
└── tool-bar-main@0.0.10

**Comment by aadisriram** [comment]
There is no active plan to add support for this but the team would be willing to review a PR for this if you'd like to work on it :)

**Comment by princed** [comment]
It works when Atom is started from Fish itself.
