### ISSUE TITLE
Atom 1.0

### ISSUE THREAD

**Issue by Fatxx** [facebook/nuclide#107]
Can't install nuclide with Atom 1.0, is this supported? I'm on elementary OS.

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@0.10.35 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v0.22.0/node-v0.22.0.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: connect ETIMEDOUT
gyp ERR! stack     at errnoException (net.js:905:11)
gyp ERR! stack     at Object.afterConnect [as oncomplete] (net.js:896:19)
gyp ERR! System Linux 3.16.0-41-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.22.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/fatxx/.atom
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
```

**Comment by bolinfest** [comment]
I'm not sure that's our code doing that. I don't think we, or any of our transitive deps, would have you fetch `atom-shell`?

**Comment by grabbou** [comment]
I had no problems with installing Nuclide on Atom 1.0 although I've been experiencing other weird issues related to CPU usage (another issue)

**Comment by Fatxx** [comment]
What do you mean "fetch atom-shell"? I did a fresh installation of atom, tried to install nuclide-installer through packages and from terminal but none of those worked.

When I run `apm -v` it prints:

```
apm -v
apm  1.0.1
npm  2.5.1
node 0.10.35
python 2.7.6
git 1.9.1
```

**Comment by draconteus** [comment]
Nuclide requires Node 0.12.0 or later.

**Comment by Fatxx** [comment]
Uhm nice catch I've 0.12 but atom is using 0.10.35. Thank you!

**Comment by draconteus** [comment]
More than welcome ;)

**Comment by Fatxx** [comment]
Well idk why he's using 0.10.35, both users (me/sudo) are using 0.12 and nvm as well.

**Comment by Fatxx** [comment]
> Well idk why he's using 0.10.35

It seems atom comes with 0.10.35 bundled...

**Comment by Fatxx** [comment]
@bolinfest you have some related topic here https://github.com/atom/apm/issues/312. Any thoughts on this?

**Comment by reflog** [comment]
so... if Atom bundles 0.10 and Nuclide needs 0.12 - how do we make it work?

**Comment by bolinfest** [comment]
@Fatxx If apm updates the version of Node that is bundled with it, then I'll update the setup scripts to use the version of Node that is bundled with apm, which should make the setup scripts simpler to run.

@reflog Today, the setup scripts will use whatever version of Node is on your `$PATH`, so install Node v0.12.x yourself via https://nodejs.org/ and make sure it appears before any other versions of Node you have on your `$PATH`.

**Comment by bolinfest** [comment]
I'm going to close this issue because installing Nuclide alongside Atom 1.0 works.

I'm not sure if there's still an outstanding problem here, but if so, feel free to create a new GitHub issue with a title identifying the specific problem.

**Comment by jonathanstiansen** [comment]
Node is on my path, and yet it is not working for me. Platform OS X See: 
<img width="124" alt="screen shot 2015-08-08 at 4 00 28 pm" src="https://cloud.githubusercontent.com/assets/2357736/9152689/c873dca4-3de6-11e5-9f97-c058835e46d8.png">
