### ISSUE TITLE
Nuclide changes priority of autocomplete and snippets

### ISSUE THREAD

**Issue by loschtreality** [facebook/nuclide#1074]
### Issue and Steps to Reproduce

Been using atom for nearly 2 years and haven't had this issue until recently installing Nuclide. Out of the box, atom prioritizes snippets over declared variables. Searching for solution to restore the default behavior.

**Nuclide Prioritization:**
![actual](https://cloud.githubusercontent.com/assets/13910998/24475040/8f0e7cd8-1483-11e7-929d-3ec67b67e928.png)

**Atom prioritization (Nuclide disabled):**
![expected](https://cloud.githubusercontent.com/assets/13910998/24475060/9ad2617e-1483-11e7-833b-2eff8c5b8a85.png)

Steps to reproduce:
1. Install Atom
2. Install Nuclide
3. Install recommended packages from Nuclide

### Expected Behavior

Expect snippets to have higher priority than variables in snippet / autocomplete list.

### Actual Behavior

Variables have higher priority in the list.

### Versions
* Atom: 1.15.0
* Nuclide: 0.210.0
* Nuclide-format-js: 0.0.36 
* Client OS: OS Sierra 10.12.4 (16E195)

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (52) ~/.atom/packages
├── atom-beautify@0.29.17
├── atom-clock@0.1.3
├── atom-material-syntax@1.0.2
├── atom-material-ui@1.3.9
├── atom-react-native-autocomplete@0.0.27
├── atomic-chrome@0.3.0
├── blocky@0.10.0
├── busy@0.7.0
├── color-picker@2.2.5
├── file-icons@2.0.15
├── genesis-ui@0.5.0
├── gruvbox-plus-syntax@1.3.1
├── haskell-grammar@0.4.0
├── highlight-selected@0.12.0
├── jumpy@3.1.3
├── language-babel@2.57.0
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-javascript-jsx@0.3.7
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@1.11.23
├── linter-eslint@8.1.1
├── linter-js-standard@3.9.0
├── linter-rubocop@0.5.3
├── merge-conflicts@1.4.4
├── minimap@4.26.8
├── minimap-highlight-selected@4.5.0
├── node-debugger@1.10.1
├── nuclide@0.210.0
├── nuclide-format-js@0.0.36
├── open-in-browser@0.4.7
├── pigments@0.39.0
├── platformio-ide-terminal@2.2.3
├── qolor@0.4.1
├── react@0.16.2
├── rspec@0.3.2
├── rubocop-auto-correct@1.5.1
├── ruby-block-converter@3.5.0
├── run-in-atom@1.0.5
├── sass-autocompile@0.13.3
├── script@3.14.1
├── set-syntax@0.3.2
├── snow-dark-material-syntax@0.1.1
├── snow-dark-syntax@0.1.1
├── solarized-dark-ui@0.3.2
├── sort-lines@0.14.0
├── tool-bar@1.1.0
├── turbo-javascript@1.4.0
└── vim-mode-plus@0.82.2

Git Packages (1) ~/.atom/packages
└── seti-syntax@1.1.2 (jesseweed/seti-syntax#fe9b3566)
```

**Comment by nmote** [comment]
There's a setting for this -- look in the Nuclide settings page under the "Flow" header

**Comment by loschtreality** [comment]
@nmote Found it, thanks
