### ISSUE TITLE
Where did the Outline View go?

### ISSUE THREAD

**Issue by jrwm** [facebook/nuclide#1078]
In previous versions I could toggle on the Outline View from the Nuclide menu. Since version 0.214.0 it's gone

**Comment by tjfryan** [comment]
Are you still able to toggle it from keyboard (⌘I), from the View menu, or via the command palette (Nuclide Outline View: Toggle)?

**Comment by jrwm** [comment]
@tjfryan ⌘I brings some Context View. But I managed to get Outline View by Atom's command palette. Thank you!
