### ISSUE TITLE
Nuclide linter results are inconsistent with hh_client results

### ISSUE THREAD

**Issue by doublecompile** [facebook/nuclide#108]
I have just performed a fresh install of Nuclide on a fresh install of Atom 1.0.0 and HHVM 3.7.2 on a fresh install of Ubuntu 14.04. 

After all of the Nuclide packages finished installing, I created an empty folder with only two files: an empty `.hhconfig`, and a `Foo.hh` that looks like this:

```hack
<?hh
class Foo
{
    public function bar() : \SplObjectStorage
    {
        return [];
    }
}
```

The editor displays `No Errors Foo.hh` in the status bar.

When running hh_client, I get:

```
/home/…/Foo.hh:6:16,16: Invalid return type (Typing[4110])
  /home/…/Foo.hh:4:29,45: This is an object of type SplObjectStorage
  /home/…/Foo.hh:6:16,16: It is incompatible with an array
```

No matter how many times I fool with the file and save it, the editor's status of `No Errors` never changes.

# Steps to Reproduce
1. Install Ubuntu 14.04 (I'm on AMD64).
2. Install the HHVM .deb
3. Install the Atom .deb
4. I installed `git` and `nodejs`
5. Execute `apm install nuclide-installer`
6. Fire up Atom and wait, wait, wait until all packages have been installed (for me, that meant I didn't see `npm` or `apm` in the process list anymore).
7. Install the linter package
8. Restart everything! Why not?
9. Create folder with empty `.hhconfig` and `Foo.hh` class as specified above.
10. Add project folder to Atom.
11. Witness no errors.

**Comment by bolinfest** [comment]
The linter package has gone through quite a bit of change recently. I believe that one change is that you have to modify the file before it triggers the linter.

I realize this is a confusing user experience (I have also been confused), so we're going to be working with the linter maintainers to make sure that we have the APIs we need to create the right experience.

**Comment by doublecompile** [comment]
I found that even editing the file (both minor and substantial edits) and saving it triggers no update.

**Comment by scv119** [comment]
@doublecompile do you still reproduce this error, also, could you verify 1) you have nuclide-hack installed; 2) anything weired in your /tmp/nucliide-logs/nuclide.log?

**Comment by doublecompile** [comment]
@scv119 I have upgraded all Nuclide packages to 0.0.22 and also Linter to 1.1.0.

I no longer have problems with the Linter results. In addition, code completion works now! ᕕ( ᐛ )ᕗ
