### ISSUE TITLE
React Native app stuck on blank white screen with remote debugging

### ISSUE THREAD

**Issue by valeriik** [facebook/nuclide#1080]
### Issue and Steps to Reproduce
Apply all operations from [the instruction](https://nuclide.io/docs/platforms/react-native/):

1. Create blank React Native project with "$ react-native init [project name]"

2. From the [command Palette](https://nuclide.io/docs/editor/basics/#command-palette) (Cmd-Shift-P) choose "Nuclide React Native: Start Packager" to start the React Native Server.

3. After starting the server, you can prime the React Native Debugger for when the application begins running. From the [command Palette](https://nuclide.io/docs/editor/basics/#command-palette) (Cmd-Shift-P), launch "Nuclide React Native: Start Debugging".

4. Ensure that you are in the root directory of the React Native project, then run the application from the command-line: "$ react-native run-ios" (or choose other existing simulator, for example react-native run-ios --simulator="iPhone4s"). (**Important**: this step should follow AFTER step 3 and chrome debugger should be closed).

5. From the iOS simulator press Cmd-D (Ctrl-D on Linux). This will bring up the debug options for your application. Select "Debug JS Remotely".

### Expected Behavior
A blank white screen does not appear.

### Actual Behavior
After "Debug JS Remotely" is clicked I see ***white screen only***
![white screen](https://i.gyazo.com/de42e11ba073072d604655381569dffb.png)
As soon as I turn off remote debugging, everything loads fine again.
![fine again](https://i.gyazo.com/bfefe05f0a8328d9329ce925e6428392.png)

### Versions
* Atom: 1.15.0
* Nuclide: 0.214.0
* Client OS: MacOS 10.12.3
* React Native version: 0.42.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info Simulator/Device? - Simulator iOS 10.2 / iOS 8.1
* Debug/Release? - Debug

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (17)
├── atom-beautify@0.29.17
├── atom-react-native-autocomplete@0.0.27
├── atom-react-native-css@1.1.3
├── busy-signal@1.3.0
├── file-icons@2.0.17
├── flow@0.5.3
├── intentions@1.1.2
├── language-babel@2.57.2
├── language-javascript-jsx@0.3.7
├── linter@2.1.2
├── linter-ui-default@1.2.2
├── minimap@4.27.0
├── nuclide@0.214.0
├── react-es6-snippets@0.3.0
├── react-native-snippets@0.3.0
├── react-snippets@0.7.2
└── redux-snippets@0.2.2

Separate question was created on [stackoverflow](http://stackoverflow.com/questions/43154551/react-native-app-stuck-on-blank-white-screen-with-remote-debugging-using-nuclide).

**Comment by oliviachang29** [comment]
Getting this error too.

**Comment by su8hash** [comment]
Are you using physical device here ,You Need to be in same network and device should be able to connect to server (Android Steps Below)
1). If Using USB Debugging then run 'adb reverse tcp:8081 tcp:8081' from your "C:\Users\<UserName>\AppData\Local\Android\sdk\platform-tools"
this will forward mobile's call for localhost:8081 to PC's localhost:8081,  here 8081 is port your server is running

2). If over Wifi on same network shake phone to open developer menu and go to 'Dev Setting' and enter Debug Server Host and Port  as <your_PC_IP>:8081 here

I think this should help it does takes a few seconds sometime for app to load

**Comment by huynguyencong** [comment]
I have same problem now.

**Comment by sportsbench** [comment]
Upgrading to RN V-0.45.1 and react v16.0.0-alpha.12 caused the same error for me. Everytime I press "reload" I get a white screen where as pushing play in XCode runs the app like normal.

**Comment by shubham-aneja** [comment]
Getting the same error while running the application in MI note4

**Comment by EclipticWld** [comment]
They dropped support for React native and node. Check out release notes [v0.236.0](https://github.com/facebook/nuclide/releases/tag/v0.236.0)

**Comment by valeriik** [comment]
Ok, who knows another way to «deeply» debug react native applications?

**Comment by EclipticWld** [comment]
Probably another debugger tool could be [react-native-debugger](https://github.com/jhen0409/react-native-debugger)

**Comment by burkaslarry** [comment]
I run npm start and got this response. Should we wait ? 
<img width="563" alt="screenshot 2017-08-23 19 31 35" src="https://user-images.githubusercontent.com/5709615/29613666-b4788232-8839-11e7-836d-eaa9da31c2bf.png">

**Comment by flyher** [comment]
@sportsbench 
The new version show the same issue as yours after i upgrade , it happened some times but not every time, i don't know why~~~

**Comment by Airomad** [comment]
Got the White Screen Error when my phone was connected via **USB and WiFi at the same time!**
Fix:
- Turn off USB cable;
- Close your App;
- Launch your App;
I'm a sleepy noob :rofl:

**Comment by shubham-aneja** [comment]
@Airomad That's also worked. Sometimes it could be a problem with simulator environment not with react-native. So this worked. Cheers ...

**Comment by kholiavko-roman** [comment]
@Airomad, but how to enable remote debugger in this case ?

**Comment by Timoteus78** [comment]
I have the _"stuck on blank white screen with remote debugging"_ issue also. I am NOT using nuclide.

**Comment by shubham-aneja** [comment]
@Timoteus78 A hit and trial solution I found was, close the application. Remove it from the cache. Relaunch the application. Do not restart the packager meanwhile.
If not works, remove the application data. Then Uninstall the application, and install it again.
That was hit and trial but worked for me.
Wish you the luck.

**Comment by nhuthan** [comment]
same problem, solution above not help

**Comment by avalko** [comment]
@shubham-aneja Thank you.....

**Comment by mostafaeweda** [comment]
The new React Native debugger should have this fixed, plz try it out.

**Comment by hoshealee** [comment]
uninstall your app, then install it in your device or simulator again solved my problem.

**Comment by pouyajabbarisani** [comment]
same problem, solution above not help

**Comment by MedinaGitHub** [comment]
same problem, solution above not help

**Comment by pelmers** [comment]
@pouyajabbarisani @MedinaGitHub Since this issue is pretty old and the react native debugger has since been completely changed, could you file new issues for the white screen bug? It would be most helpful to include the host platform (windows/mac/linux), the target platform/device, and your react-native version.

Also it may be helpful to review documentation at https://nuclide.io/docs/platforms/react-native/#debugging

**Comment by MujtabaFR** [comment]
I had the same problem, but solved by opening `http://localhost:8081/debugger-ui/` in the browser instead of the IP `http://192.168.2.100:8081/debugger-ui/`

**Comment by agrinko** [comment]
Thank you @MujtabaFR !
Surprisingly, that simple fix helped me! Although both URLs were working in browser, only with "localhost" was I able to see my app UI on the device

**Comment by nitishtandia** [comment]
just uninstall the app from your simulator and build is again it will work.
