### ISSUE TITLE
Flow highlights too much code when hovering over components & props

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#1089]
### Issue and Steps to Reproduce
Flow seems to highlight huge blocks of JSX, no matter where I hover.

### Expected Behavior
I would expect it to just highlight the immediate area where I'm hovering and show syntax for those props.

### Actual Behavior
The entire containing code block gets highlighted.

### Versions
* Atom: 1.15.0
* Nuclide: 0.216.0
* Client OS: Mac OS 10.12.4

### Additional Details
* Installed packages (`apm ls --installed`):
```
[36mCommunity Packages (29)[39m /Users/samh/.atom/packages
├── MagicPython@1.0.9
├── autocomplete-modules@1.6.9
├── dash@1.7.1
├── expose@0.14.0
├── file-icons@2.1.2
├── git-time-machine@1.5.9
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── js-refactor@0.7.5
├── language-babel@2.57.2
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.1.2
├── linter-eslint@8.1.4
├── merge-conflicts@1.4.4
├── minimap@4.27.1
├── nuclide@0.216.0
├── nuclide-format-js@0.0.36
├── pigments@0.39.1
├── prettier-atom@0.26.0
├── refactor@0.11.4
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── todo-show@1.11.0
└── tool-bar@1.1.0
```

**Comment by nmote** [comment]
This is an issue with Flow, not Nuclide. Nuclide simply displays what Flow returns. Feel free to re-open on the Flow repo.

With that said, we are tracking various issues like this with Flow's IDE features, and I've made a note of this one. A specific repro case would be helpful so that I can catalogue it. I'm hoping we can get a bunch of this stuff done in the next few months.

**Comment by ffxsam** [comment]
Is it really Flow that's the issue though? It's returning valid information, it seems, but where I mouse over (in Nuclide) seems to make no difference. In other words, Nuclide is displaying the wrong thing.

Also, I forgot to attach a screencap. See below.

![licecap](https://cloud.githubusercontent.com/assets/12532733/24821900/eae7d7ae-1bb6-11e7-8d57-10ce344b51cd.gif)

**Comment by mwalkerwells** [comment]
@ffxsam You figure out how to turn this off?

**Comment by ffxsam** [comment]
I disabled type hints.

![image](https://user-images.githubusercontent.com/12532733/27556127-fca4fff6-5a79-11e7-834a-346fe9fd0fd7.png)
