### ISSUE TITLE
PHP debugging on Zend doesn't show array entries or object properties

### ISSUE THREAD

**Issue by jesseschalken** [facebook/nuclide#1090]
### Issue and Steps to Reproduce

I am debugging this PHP script:

```php
<?php

namespace Blah;

class Foo {
  private $bob = array(1,2,3,4);
  public function bob() {
    $x = $this->bob;
    print \count($x)."\n";
  }
}

$foo = new Foo();
$foo->bob();
```

With a breakpoint on the `print` line, there is a difference between HHVM and Zend when inspecting local variables.

![image](https://cloud.githubusercontent.com/assets/1559204/24828564/23664844-1ca3-11e7-8a5f-f023a498bf74.png)

### Expected Behavior

On HHVM, I get the expected behaviour of seeing the contents of `$this`, `$this->bob` and `$x`. Although for some reason I had to "step into" once to get `$this` to show up.

![image](https://cloud.githubusercontent.com/assets/1559204/24828582/665a6eb4-1ca3-11e7-86fa-f94cae8364b6.png)

### Actual Behavior

On Zend, the contents of `$x` don't show, and the instead of `$this` having a property called `bob`, the array entries of `$this->bob` appear directly as properties of `$this`.

![image](https://cloud.githubusercontent.com/assets/1559204/24828553/d8f8c14c-1ca2-11e7-8b6c-347e58e49c91.png)

### Versions
* Atom: 1.15.0
* Nuclide: 0.216.0
* Client OS: Windows 10
* Server OS (optional): Ubuntu 16.04 (PHP 7.0.15, Xdebug 2.4.0)

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (41) C:\Users\Jesse\.atom\packages
├── atom-material-syntax@1.0.2
├── atom-material-syntax-dark@0.2.7
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@1.3.9
├── atom-monokai@0.10.9
├── contrast-syntax@0.8.1
├── contrast-ui@0.53.0
├── firewatch-syntax@1.1.1
├── genesis-syntax@1.0.9
├── genesis-ui@0.5.0
├── github-atom-light-syntax@0.3.2
├── gruvbox-plus-syntax@1.3.1
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.57.2
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.1.2
├── MagicPython@1.0.9
├── markdown-preview-plus@2.4.9
├── merge-conflicts@1.4.4
├── minimal-syntax@0.21.0
├── minimal-syntax-dark@0.6.0
├── minimap@4.27.1
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── monokai@0.22.0
├── monokai-dark@1.3.0
├── nuclide@0.216.0
├── nuclide-format-js@0.0.36
├── sepia-syntax@1.1.0
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── tool-bar@1.1.0
└── vim-mode-plus@0.87.0
```

**Comment by ebluestein** [comment]
@jesseschalken, sorry but we currently only officially support HHVM in the Nuclide debugger. Since we use the xdebug protocol, it is likely that other compatible PHP servers will work (at least to some extent) with Nuclide, but those setups are neither tested nor supported by our team.

Of course, if you encounter an issue, pull requests are always welcome ;-)
