### ISSUE TITLE
Uncaught Error: Remote Error: Invariant violation: "result" processing message {"protocol":"servi...

### ISSUE THREAD

**Issue by dezfx** [facebook/nuclide#1091]
[Enter steps to reproduce:]

1. Manual nuclide server install on a BSD system
2. Try to connect to remote project folder

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.216.54642442

### Stack Trace

Uncaught Error: Remote Error: Invariant violation: "result" processing message {"protocol":"service_framework3_rpc","type":"call","method":"FbArcanistService/isArcSupported","id":9,"args":{"filePath":"/usr/home/austinv/pbr"}}
"Error: Invariant violation: \"result\"\n    at ServiceRegistry.getFunctionImplemention (/usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/ServiceRegistry.js:137:13)\n    at RpcConnection._getFunctionImplemention (/usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:668:34)\n    at /usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:437:18\n    at Generator.next (<anonymous>)\n    at step (/usr/local/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)\n    at /usr/local/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:27:14\n    at /usr/local/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12\n    at RpcConnection._callFunction (/usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:441:7)\n    at /usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:642:26\n    at Generator.next (<anonymous>)"

```
At /opt/facebook/nuclide/0.216.54642442/nuclide/node_modules/rxjs/bundles/Rx.min.js:15

Error: Invariant violation: "result"
    at ServiceRegistry.getFunctionImplemention (/usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/ServiceRegistry.js:137:13)
    at RpcConnection._getFunctionImplemention (/usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:668:34)
    at /usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:437:18
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
    at /usr/local/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:27:14
    at /usr/local/lib/node_modules/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12
    at RpcConnection._callFunction (/usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:441:7)
    at /usr/local/lib/node_modules/nuclide/pkg/nuclide-rpc/lib/RpcConnection.js:642:26
    at Generator.next (<anonymous>)
```

### Commands

```
```

### Non-Core Packages

```
ex-mode 0.14.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.57.2 
language-graphql 0.8.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
nuclide 0.216.54642442 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
vim-mode-plus 0.87.0 
```

**Comment by rightparen** [comment]
Thanks for reporting.  Unfortunately, BSD is not a supported platform for nuclide server.
