### ISSUE TITLE
Scroll Bar is white

### ISSUE THREAD

**Issue by bernatfortet** [facebook/nuclide#1092]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
The scroll bar of tree view is white instead of normal dark color of Atom

### Expected Behavior
The scroll bar should be dark (like the scrollbar seen on the right side of the screenshot)

### Versions
* Atom: 1.15.0
* Nuclide: 0.216.0
* Client OS: Mac Os El Capitan

![image](https://cloud.githubusercontent.com/assets/390010/24881242/119e1bfa-1df2-11e7-9363-f98ab4cf94fe.png)

**Comment by bernatfortet** [comment]
I found out this was a problem with the UI Theme,

probably there was a change on the css from Nuclide's part?

**Comment by penx** [comment]
I'm also getting this issue - nuclide 0.245.0, Mac OS X 10.13.1.

Likely only happens when you have a mouse plugged in, as this results in Mac OS X (+Chrome) changing scrollbar behaviour.

**Comment by penx** [comment]
Any reason this was closed? Can it be reopened?

**Comment by penx** [comment]
Duplicate of https://github.com/facebook/nuclide/issues/1253
