### ISSUE TITLE
Uncaught Error: hg errorstderr: killed!stdout: [ {  "active": false,  "bookmark": "change_p...

### ISSUE THREAD

**Issue by justinjhendrick** [facebook/nuclide#1093]
Repro:
1. come back from computer sleep

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.216.54642442

### Stack Trace

Uncaught Error: hg error
stderr: killed!

stdout: [
 {
  "active": false,
  "bookmark": "change_pass_order_rme_dce",
  "node": "885b6b81e30436f25c4f69faca5b0331c01d9349",
  "rev": 2011680
 },
 {
  "active": false,
  "bookmark": "compiler_flags",
  "node": "9deb3514771b5dc74949e2ddcea6bf8778fd7e7f",
  "rev": 1984226
 },
 {
  "active": false,
  "bookmark": "fix_peephole_output_register_state",
  "node": "f1d8ee6fcf698e1a92aef6684c5692af19e992fd",
  "rev": 1987324
 },
 {
  "active": false,
  "bookmark": "peephole_with_v2",
  "node": "fe310ffd8e2dc7b18fd5927d7dc11825b015d556",
  "rev": 1968148
 },
 {
  "active": false,
  "bookmark": "redundant_move_elim",
  "node": "f11e3ed01d310689a6d78bfff785d0b617aebd05",
  "rev": 2007703
 },
 {
  "active": true,
  "bookmark": "rme_representative_reg",
  "node": "300d4b535d2560dac515205a7ccfc16423d74611",
  "rev": 2011741
 }
]

```
At /opt/facebook/nuclide/0.216.54642442/nuclide/node_modules/rxjs/bundles/Rx.min.js:58

Error: hg error
stderr: killed!

stdout: [
 {
  "active": false,
  "bookmark": "change_pass_order_rme_dce",
  "node": "885b6b81e30436f25c4f69faca5b0331c01d9349",
  "rev": 2011680
 },
 {
  "active": false,
  "bookmark": "compiler_flags",
  "node": "9deb3514771b5dc74949e2ddcea6bf8778fd7e7f",
  "rev": 1984226
 },
 {
  "active": false,
  "bookmark": "fix_peephole_output_register_state",
  "node": "f1d8ee6fcf698e1a92aef6684c5692af19e992fd",
  "rev": 1987324
 },
 {
  "active": false,
  "bookmark": "peephole_with_v2",
  "node": "fe310ffd8e2dc7b18fd5927d7dc11825b015d556",
  "rev": 1968148
 },
 {
  "active": false,
  "bookmark": "redundant_move_elim",
  "node": "f11e3ed01d310689a6d78bfff785d0b617aebd05",
  "rev": 2007703
 },
 {
  "active": true,
  "bookmark": "rme_representative_reg",
  "node": "300d4b535d2560dac515205a7ccfc16423d74611",
  "rev": 2011741
 }
]

  at logAndThrowHgError (/opt/facebook/nuclide/0.216.54642442/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:190:11)
  at /opt/facebook/nuclide/0.216.54642442/nuclide/pkg/nuclide-hg-rpc/lib/hg-utils.js:23:7
  at undefined.next (<anonymous>:null:null)
  at step (/opt/facebook/nuclide/0.216.54642442/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
  at /opt/facebook/nuclide/0.216.54642442/nuclide/node_modules/async-to-generator/async-to-generator.js:21:13

```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.3.0 
haskell-grammar 0.4.0 
highlight-selected 0.12.0 
intentions 1.1.2 
language-babel 2.56.2 
language-graphql 0.8.0 
language-ini 1.18.0 
language-lua 0.9.11 
language-ocaml 1.1.2 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.1.0 
linter-eslint 8.1.4 
linter-ui-default 1.1.0 
MagicPython 1.0.9 
merge-conflicts 1.4.4 
minimap 4.26.8 
nuclide 0.216.54642442 
nuclide-format-js 0.0.36 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
vim-mode-plus 0.84.1 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by mostafaeweda** [comment]
This will be fixed in the next release as we take the source control navigator out of the open source release - since it's adding more trouble than value.
