### ISSUE TITLE
Error: Flow was not found when attempting to start it

### ISSUE THREAD

**Issue by ugendrang** [facebook/nuclide#1095]
Environment:
Atom version: 1.15.0
flow: flow-win64-v0.43.1
nuclide: 0.216.0
OS: Windows 10

I have included the flow-win64-v0.43.1 file path in Environment Variable, also My project's .flowconfig file includes below line
[version]
^0.43.1

On opening i got notification "Flow was not found when attempting to start it in ..."

CTRL+Click is not working and also flow coverage is not showing in Atom status bar. It looks flow is not working.

**Comment by ebluestein** [comment]
@ugendrang, what does it say if you run `where flow` at a command prompt?

**Comment by ugendrang** [comment]
@ebluestein, on running where flow in command prompt, it says
C:\softwares\flow-win64-v0.43.1\flow\flow.exe

**Comment by ugendrang** [comment]
@ebluestein <https://github.com/ebluestein>, on running where flow in
command prompt, it says
C:\softwares\flow-win64-v0.43.1\flow\flow.exe

Do you have any update on the reported issue.

**Comment by ebluestein** [comment]
That path looks reasonable, I would expect this to work.

You may want to try installing the flow-bin npm package:
https://www.npmjs.com/package/flow-bin
