### ISSUE TITLE
Compatibility with other language packages

### ISSUE THREAD

**Issue by janosimas** [facebook/nuclide#1096]
There are some features of Nuclide that are filetype-wise, like outline, these features don work if I use a non-default language pack, like [language-cpp14](https://atom.io/packages/language-cpp14).

Is there a way to make them compatible?

**Comment by hansonw** [comment]
This is because we have activation hooks tied to the grammar names. I just added `language-cpp14` to it - you can also modify `pkg/nuclide-clang/package.json` manually, or activate the `nuclide-clang` package manually in the meantime :)
