### ISSUE TITLE
Writing jsx in .js files, tab does not close the tabs as it does in .jsx files

### ISSUE THREAD

**Issue by itsmeek** [facebook/nuclide#1097]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
On .js files, (Which most existing projects are in) It does not seem to support autoclosing of jsx tags. The tab just behaves as a normal tab. Only on .jsx file extensions does this expected behavior works

### Expected Behavior
On .js files, if im writing some jsx, Ex. i type "Text" and press tab, it should output <Text>

### Actual Behavior
The default tab behaviour occurs

### Versions
* Atom: 1.15.0
* Nuclide: 0.217.0
* Client OS: osx
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
emmet

**Comment by mostafaeweda** [comment]
Nuclide should've auto-installed the `language-babel` apm package, which is the default for `js` and `jsx` syntax highlighting.
However, I can't seem to reproduce the `Text` & tab behavior neither in `js` nor `jsx` files.

Could you give a more detailed description of what you're trying to do / expect, and how is it related to Nuclide?

**Comment by mostafaeweda** [comment]
Closing for missing details / repro steps, please re-open if this is still and issue and help with more details.
