### ISSUE TITLE
Duplicating a file should show the file path

### ISSUE THREAD

**Issue by ooade** [facebook/nuclide#1099]
### Issue and Steps to Reproduce
I think duplicating a file on the file tree should show the file path and not just the `file`-copy.`ext`

### Expected Behavior
For instance, let's say i'm in the lib directory, i should be getting lib/file-copy.ext when i click on duplicate, just in case i want to make a copy to the root directory or any other. It would be a lot better if the `-copy` is stripped off too and let users decide that themselves.

### Actual Behavior
It just won't allow me make a copy to the root directory or any other, which kinda sucks.

### Versions
* Atom: 1.15.0
* Nuclide: 0.217.0
* Client OS: Opera 44.0.2510.1159
* Server OS (optional): Ubuntu 16.04

### Additional Details
* Installed packages (`apm ls --installed`): 
├── MagicPython@1.0.9
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.57.2
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.8.0
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── language-vue@0.21.2
├── merge-conflicts@1.4.4
├── nuclide@0.217.0
├── nuclide-format-js@0.0.36
├── pp-markdown@0.0.2
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0

**Comment by hansonw** [comment]
You can actually type in relative paths like `../file-copy.ext` to make copies above the current directory! For our use cases displaying the full relative path tends to be too long, so we likely won't do that, sorry :(
