### ISSUE TITLE
nuclide plugin causes wrong autocomplete for javascript file

### ISSUE THREAD

**Issue by alinz** [facebook/nuclide#11]
After installing the plugin, javascript development becomes a little bit hassle. I constantly need to press `Esc` key to ignore wrong autocomplete. 

for example, after simple type of `'use strict';` I get `export{}`, image is provided.

![screen shot 2015-05-27 at 10 37 32 am](https://cloud.githubusercontent.com/assets/967050/7838790/cc83c548-045c-11e5-9452-bda49518ba8b.png)

so I have to hit `Esc` key and then press `Enter` key. :(

**Comment by nmote** [comment]
I think https://github.com/facebook/nuclide/commit/746090718fe19222a88c1d34e23c06428dc294c9 should have fixed this.
