### ISSUE TITLE
Remote server fails to start if tmp directory is on another drive

### ISSUE THREAD

**Issue by Keno** [facebook/nuclide#110]
```
kfischer@julia:~$ cat ~/nuclide.nohup.out
[2015-06-27T20:09:00.903Z] [INFO] nuclide - NuclideServer started on port 9000.
[2015-06-27T20:09:00.911Z] [ERROR] nuclide - uncaughtException: { [Error: EXDEV, rename '/tmp/nuclide-node-transpiler115527-86041-1o9ypgt']
  errno: -18,
  code: 'EXDEV',
  path: '/tmp/nuclide-node-transpiler115527-86041-1o9ypgt' }
```
I assume it's trying to compile into /tmp and then moving it somewhere more permanent.

**Comment by Keno** [comment]
Even after setting a different TMPDIR, I'm unfortunately still not getting a successful version check on the port, so please let me know what I should do to debug.

**Comment by ssorallen** [comment]
This looks like the same issue as #88. The /tmp directory is likely mounted and effectively on a different device.

**Comment by Keno** [comment]
Correct.
