### ISSUE TITLE
Can't start server from client, but can from command

### ISSUE THREAD

**Issue by CodeAn** [facebook/nuclide#1104]
### Issue and Steps to Reproduce
Connecting to server. Connecting to server seems to work, starting the server however doesn't.

### Expected Behavior
Connection should be happening.

### Actual Behavior
Unexpected error occurred: The log file can be found at /tmp/nuclide-root-logs/server-start/nuclide-2017-04-18T22:56:57.nohup.out. .
Original error message:
 The log file can be found at /tmp/nuclide-root-logs/server-start/nuclide-2017-04-18T22:56:57.nohup.out.

Output of log file:
nohup: failed to run command ânodeâ: No such file or directory

However, when running nuclide-start-server it is successfully starting, no errors.
Using the same user (in terminal and connection details).

### Versions
* Atom: 1.16.0
* Nuclide: 0.218.0
* Client OS: Windows 10
* Server OS (optional): Ubuntu 14.04

**Comment by hansonw** [comment]
Hmm... where is the path of your `node` binary on your server? Is it in your `$PATH` at login time?

**Comment by CodeAn** [comment]
Sorry, I'm not too familiair with Ubuntu, command line, etc. 

But I think this is the info you need.
Path to node:
/root/.nvm/versions/node/v6.10.2/bin

However, when running whereis node, it shows:
/urs/bin/node

That path however, is empty.
