### ISSUE TITLE
Find in project failed to search in remote project

### ISSUE THREAD

**Issue by 0x413x** [facebook/nuclide#1106]
### Issue and Steps to Reproduce
Find in remote project failed (shift + command + F)

### Expected Behavior
Normal search function

### Actual Behavior
Found nothing in remote project
![2017-04-18_17-49-12](https://cloud.githubusercontent.com/assets/3228984/25125248/b5ad58c2-2460-11e7-9378-34e319d4dcce.png)

### Versions
* Atom: 1.16.0 x64
* Nuclide: 0.218.0
* Client OS: macOS 10.12.4
* Server OS (optional): minideb (docker jotadrilo/nuclide-remote)

### Additional Details
* Installed packages (`apm ls --installed`):
├── file-icons@2.1.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.57.3
├── language-docker@1.1.7
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.8.0
├── language-slim@0.5.0
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── language-vue@0.21.2
├── linter@2.1.4
├── linter-docker@0.2.0
├── linter-ruby@1.2.5
├── linter-slim@1.0.0
├── merge-conflicts@1.4.4
├── nuclide@0.218.0
├── nuclide-format-js@0.0.36
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0

**Comment by hansonw** [comment]
can you check your Nuclide server logs for any errors? `/tmp/nuclide-$USER-logs/nuclide.log`

**Comment by 0x413x** [comment]
No any logs when search.

but got an error log when close ATOM 

![2017-04-20_12-05-50](https://cloud.githubusercontent.com/assets/3228984/25213281/32e568e0-25c2-11e7-854d-593dc2fba9cc.png)

**Comment by hansonw** [comment]
Anything in the Atom console when searching? (cmd-option-i)

**Comment by 0x413x** [comment]
No any info...

![2017-04-20_13-25-11](https://cloud.githubusercontent.com/assets/3228984/25214935/e69a661a-25cc-11e7-97a5-7c8fb6f3b812.png)

**Comment by 0x413x** [comment]
[resolved v0.219.0](https://github.com/facebook/nuclide/releases/tag/v0.219.0)
