### ISSUE TITLE
Nuclide Server won't run neither in terminal nor in Atom

### ISSUE THREAD

**Issue by pitylee** [facebook/nuclide#1111]
### Issue and Steps to Reproduce
What I'm experiencing is: when trying to run nuclide-start server, installed from the repo, with all the dependencies I get error.
**I'm sure my SSH is correct** and **I have installed as requested in the official tutorial**
_All of my software both on the server and the client machine are up to date_

### Expected Behavior
Nuclide server start?

### Actual Behavior
Gives error with the below output if I run it with nuclide-start-server in terminal, and on atom add remote project folder action the other output below.

### Versions
* Atom: 1.16.0 x64 (latest)
* Nuclide: 0.218.0
* Client OS: 
- LSB Version:	core-9.20160110ubuntu5-amd64:core-9.20160110ubuntu5-noarch:security-9.20160110ubuntu5-amd64:security-9.20160110ubuntu5-noarch
- Distributor ID:	Ubuntu
- Description:	Ubuntu 16.10
- Release:	16.10
- Codename:	yakkety

* Server OS (optional):
- No LSB modules are available.
- Distributor ID:	Ubuntu
- Description:	Ubuntu 16.04.2 LTS
- Release:	16.04
- Codename:	xenial

* Atom Form
![screenshot from 2017-04-21 03-16-23](https://cloud.githubusercontent.com/assets/4678981/25257775/10aa085e-2643-11e7-81ac-46a1f2e91f75.png)

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (39) /home/pitylee/.atom/packages
├── MagicPython@1.0.9
├── ShayHoweBrowser@4.0.0
├── atom-beautify@0.29.23
├── atom-react-preview@2.0.0
├── browser-plus@0.0.87
├── browser-refresh@0.9.0
├── docs-snippets@0.8.0
├── emmet@2.4.3
├── extract-web@0.3.2
├── git-control@0.9.0
├── git-time-machine@1.5.9
├── goto-definition@1.3.2
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── hyperclick@0.0.40
├── language-babel@2.57.5
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.8.0
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── local-history@4.0.1
├── markdown-preview-plus@2.4.9
├── markdown-writer@2.6.4
├── merge-conflicts@1.4.4
├── minimap@4.27.1
├── nativebase-snippets-atom@2.0.2
├── nord-atom-syntax@0.9.1
├── nucleus-dark-ui@0.11.17
├── nuclide@0.218.0
├── nuclide-format-js@0.0.36
├── nuclide-test-runner-jest@0.3.0
├── pane-browser@1.6.0
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── terminal-plus@0.14.5
├── tool-bar@1.1.0
└── toolbar-iconshortcuts@3.10.0

* Output Server Terminal
`
{"succes": false, "logs": ["2017-04-21 03:10:18,809 - root - INFO - Invoked nuclide_server_manager...", "2017-04-21 03:10:18,809 - NuclideServerManager - INFO - NuclideServerManager was created with these options: {'certs_dir': None, 'json_output_file': None, 'timeout': 10, 'dump_core': True, 'insecure': False, 'inspect': False, 'quiet': False, 'debug': False, 'command': 'start', 'workspace': None, 'common_name': None, 'port': None, 'verbose': False}", "2017-04-21 03:10:18,810 - NuclideServerManager - INFO - Starting to clean up old Nuclide processes/files.", "2017-04-21 03:10:18,818 - NuclideServerManager - INFO - Cleaning up old certificate files...", "2017-04-21 03:10:18,819 - NuclideServerManager - INFO - Finished cleaning up old Nuclide processes/files.", "2017-04-21 03:10:18,819 - root - WARNING - Failed to clean up old core dumps ([Errno 2] No such file or directory: '/var/tmp/cores')", "2017-04-21 03:10:18,819 - NuclideServerManager - INFO - Trying to determine the port to use for Nuclide server...", "2017-04-21 03:10:18,828 - NuclideServerManager - INFO - Found an open port: 9090.", "2017-04-21 03:10:18,828 - NuclideServerManager - INFO - Initialized NuclideServer.", "2017-04-21 03:10:18,837 - NuclideServerManager - INFO - Starting NuclideServer...", "2017-04-21 03:10:18,837 - NuclideServerManager - INFO - Using https.", "2017-04-21 03:10:18,838 - NuclideServerManager - INFO - Checking if certificate dir /home/myuser/.certs exists.", "2017-04-21 03:10:18,919 - NuclideServerManager - INFO - Initialized NuclideCertificatesGenerator with common_name: myuser.nuclide.ubuntu-pityu", "2017-04-21 03:10:18,919 - NuclideServer - INFO - NuclideServer start/restarting with the following arguments:\n              timeout: 10\n              cert:    /home/myuser/.certs/nuclide.Ck1OVK.server.crt\n              key:     /home/myuser/.certs/nuclide.Ck1OVK.server.key\n              ca:      /home/myuser/.certs/nuclide.Ck1OVK.ca.crt\n              force:   False\n              quiet:   False\n              debug:   False\n              inspect: False\n              expiration_days: 15", "2017-04-21 03:10:18,927 - NuclideServer - INFO - Opening node server subprocess.", "2017-04-21 03:10:18,928 - NuclideServer - INFO - Trying to ping the Nuclide server...", "2017-04-21 03:10:29,129 - NuclideServer - ERROR - Attempted to start Nuclide server on port 9090, but timed out after 10 seconds."]}
The log file can be found at /tmp/nuclide-myuser-logs/server-start/nuclide-2017-04-21T03:10:18.nohup.out.
`
* Atom Nuclide Remote Add Project Folder
`
2017-04-21 03:16:03.210 INFO (pid:2296) nuclide-hack - Hack ensureProcesses. 
2017-04-21 03:16:03.214 DEBUG (pid:2296) nuclide-hack - Observing diagnostics local, hack.observe-diagnostics
2017-04-21 03:16:03.216 DEBUG (pid:2296) nuclide-hack - observeDiagnostics
2017-04-21 03:16:03.216 INFO (pid:2296) nuclide-hack - observing connections
2017-04-21 03:16:04.255 DEBUG (pid:2296) nuclide - Created new remote atom config at /tmp/.nuclide/command-server/0 for port 43375 family IPv4
2017-04-21 03:17:19.637 ERROR (pid:3372) nuclide - Error while talking to watchman:  { Error: Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn watchman',
  path: 'watchman',
  spawnargs: [ '--no-pretty', 'get-sockname' ],
  stackTrace: 
   [ { functionName: 'exports._errnoException',
       methodName: null,
       fileName: 'util.js',
       lineNumber: 1026,
       columnNumber: 11,
       evalOrigin: 'util.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'ChildProcess._handle.onexit',
       methodName: 'onexit',
       fileName: 'internal/child_process.js',
       lineNumber: 193,
       columnNumber: 32,
       evalOrigin: 'internal/child_process.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'onErrorNT',
       methodName: null,
       fileName: 'internal/child_process.js',
       lineNumber: 359,
       columnNumber: 16,
       evalOrigin: 'internal/child_process.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_combinedTickCallback',
       methodName: null,
       fileName: 'internal/process/next_tick.js',
       lineNumber: 74,
       columnNumber: 11,
       evalOrigin: 'internal/process/next_tick.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_tickCallback',
       methodName: '_tickCallback',
       fileName: 'internal/process/next_tick.js',
       lineNumber: 98,
       columnNumber: 9,
       evalOrigin: 'internal/process/next_tick.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false } ] }
2017-04-21 03:17:19.695 ERROR (pid:3372) nuclide - Watchman client disconnected, reconnecting a new client!
2017-04-21 03:17:19.701 WARN (pid:3372) nuclide - Could not update path sets for /path/to/customers/folder/www. Searches may be stale { Error: The client was ended
    at Client.cancelCommands (/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js:52:15)
    at Client.end (/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js:315:8)
    at Client.<anonymous> (/home/myuser/.atom/packages/nuclide/pkg/nuclide-watchman-helpers/lib/WatchmanClient.js:102:16)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at spawnError (/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js:170:10)
    at ChildProcess.<anonymous> (/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js:193:5)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
  stackTrace: 
   [ { functionName: 'Client.cancelCommands',
       methodName: 'cancelCommands',
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js',
       lineNumber: 52,
       columnNumber: 15,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'Client.end',
       methodName: 'end',
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js',
       lineNumber: 315,
       columnNumber: 8,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-watchman-helpers/lib/WatchmanClient.js',
       lineNumber: 102,
       columnNumber: 16,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-watchman-helpers/lib/WatchmanClient.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emitOne',
       methodName: null,
       fileName: 'events.js',
       lineNumber: 96,
       columnNumber: 13,
       evalOrigin: 'events.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emit',
       methodName: 'emit',
       fileName: 'events.js',
       lineNumber: 188,
       columnNumber: 7,
       evalOrigin: 'events.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'spawnError',
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js',
       lineNumber: 170,
       columnNumber: 10,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js',
       lineNumber: 193,
       columnNumber: 5,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/fb-watchman/index.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emitOne',
       methodName: null,
       fileName: 'events.js',
       lineNumber: 96,
       columnNumber: 13,
       evalOrigin: 'events.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emit',
       methodName: 'emit',
       fileName: 'events.js',
       lineNumber: 188,
       columnNumber: 7,
       evalOrigin: 'events.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'ChildProcess._handle.onexit',
       methodName: 'onexit',
       fileName: 'internal/child_process.js',
       lineNumber: 213,
       columnNumber: 12,
       evalOrigin: 'internal/child_process.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false } ] }
2017-04-21 03:17:19.723 INFO (pid:3372) nuclide - Watchman client re-initialized, restoring subscriptions
2017-04-21 03:17:45.686 ERROR (pid:2296) nuclide - SshHandshake failed: UNKNOWN, Remote shell execution failed { Error: The log file can be found at /tmp/nuclide-myuser-logs/server-start/nuclide-2017-04-21T03:16:44.nohup.out.

  at Channel.<anonymous> (/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js:405:96)
  at undefined.next (<anonymous>:null:null)
  at step (/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
  at /home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:27:14
  at Channel.<anonymous> (/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12)
  at Channel.stream.on (/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js:412:25)
  at emitOne (events.js:101:20)
  at Channel.emit (events.js:188:7)
  at Channel.<anonymous> (/home/myuser/.atom/packages/nuclide/node_modules/ssh2/lib/Channel.js:135:18)
  at Channel.g (events.js:286:16)
  at emitNone (events.js:91:20)
  at Channel.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

  stackTrace: 
   [ { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js',
       lineNumber: 405,
       columnNumber: 96,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'next',
       methodName: 'next',
       fileName: null,
       lineNumber: null,
       columnNumber: null,
       evalOrigin: null,
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'step',
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       lineNumber: 11,
       columnNumber: 30,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       lineNumber: 27,
       columnNumber: 14,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       lineNumber: 8,
       columnNumber: 12,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'stream.on',
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js',
       lineNumber: 412,
       columnNumber: 25,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emitOne',
       methodName: null,
       fileName: 'events.js',
       lineNumber: 101,
       columnNumber: 20,
       evalOrigin: 'events.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emit',
       methodName: 'emit',
       fileName: 'events.js',
       lineNumber: 188,
       columnNumber: 7,
       evalOrigin: 'events.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/ssh2/lib/Channel.js',
       lineNumber: 135,
       columnNumber: 18,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/ssh2/lib/Channel.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'g',
       methodName: null,
       fileName: 'events.js',
       lineNumber: 286,
       columnNumber: 16,
       evalOrigin: 'events.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emitNone',
       methodName: null,
       fileName: 'events.js',
       lineNumber: 91,
       columnNumber: 20,
       evalOrigin: 'events.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emit',
       methodName: 'emit',
       fileName: 'events.js',
       lineNumber: 185,
       columnNumber: 7,
       evalOrigin: 'events.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'endReadableNT',
       methodName: null,
       fileName: '_stream_readable.js',
       lineNumber: 974,
       columnNumber: 12,
       evalOrigin: '_stream_readable.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_combinedTickCallback',
       methodName: null,
       fileName: 'internal/process/next_tick.js',
       lineNumber: 74,
       columnNumber: 11,
       evalOrigin: 'internal/process/next_tick.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_tickCallback',
       methodName: '_tickCallback',
       fileName: 'internal/process/next_tick.js',
       lineNumber: 98,
       columnNumber: 9,
       evalOrigin: 'internal/process/next_tick.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false } ] }
2017-04-21 03:17:45.872 DEBUG (pid:2296) nuclide - { Error: The log file can be found at /tmp/nuclide-myuser-logs/server-start/nuclide-2017-04-21T03:16:44.nohup.out.

  at Channel.<anonymous> (/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js:405:96)
  at undefined.next (<anonymous>:null:null)
  at step (/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
  at /home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:27:14
  at Channel.<anonymous> (/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js:8:12)
  at Channel.stream.on (/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js:412:25)
  at emitOne (events.js:101:20)
  at Channel.emit (events.js:188:7)
  at Channel.<anonymous> (/home/myuser/.atom/packages/nuclide/node_modules/ssh2/lib/Channel.js:135:18)
  at Channel.g (events.js:286:16)
  at emitNone (events.js:91:20)
  at Channel.emit (events.js:185:7)
  at endReadableNT (_stream_readable.js:974:12)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)

  stackTrace: 
   [ { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js',
       lineNumber: 405,
       columnNumber: 96,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'next',
       methodName: 'next',
       fileName: null,
       lineNumber: null,
       columnNumber: null,
       evalOrigin: null,
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'step',
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       lineNumber: 11,
       columnNumber: 30,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       lineNumber: 27,
       columnNumber: 14,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       lineNumber: 8,
       columnNumber: 12,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/async-to-generator/async-to-generator.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'stream.on',
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js',
       lineNumber: 412,
       columnNumber: 25,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/pkg/nuclide-remote-connection/lib/SshHandshake.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emitOne',
       methodName: null,
       fileName: 'events.js',
       lineNumber: 101,
       columnNumber: 20,
       evalOrigin: 'events.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emit',
       methodName: 'emit',
       fileName: 'events.js',
       lineNumber: 188,
       columnNumber: 7,
       evalOrigin: 'events.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: null,
       methodName: null,
       fileName: '/home/myuser/.atom/packages/nuclide/node_modules/ssh2/lib/Channel.js',
       lineNumber: 135,
       columnNumber: 18,
       evalOrigin: '/home/myuser/.atom/packages/nuclide/node_modules/ssh2/lib/Channel.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'g',
       methodName: null,
       fileName: 'events.js',
       lineNumber: 286,
       columnNumber: 16,
       evalOrigin: 'events.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emitNone',
       methodName: null,
       fileName: 'events.js',
       lineNumber: 91,
       columnNumber: 20,
       evalOrigin: 'events.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'emit',
       methodName: 'emit',
       fileName: 'events.js',
       lineNumber: 185,
       columnNumber: 7,
       evalOrigin: 'events.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: 'endReadableNT',
       methodName: null,
       fileName: '_stream_readable.js',
       lineNumber: 974,
       columnNumber: 12,
       evalOrigin: '_stream_readable.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_combinedTickCallback',
       methodName: null,
       fileName: 'internal/process/next_tick.js',
       lineNumber: 74,
       columnNumber: 11,
       evalOrigin: 'internal/process/next_tick.js',
       isTopLevel: true,
       isEval: false,
       isNative: false,
       isConstructor: false },
     { functionName: '_tickCallback',
       methodName: '_tickCallback',
       fileName: 'internal/process/next_tick.js',
       lineNumber: 98,
       columnNumber: 9,
       evalOrigin: 'internal/process/next_tick.js',
       isTopLevel: false,
       isEval: false,
       isNative: false,
       isConstructor: false } ] }
`

**Comment by pitylee** [comment]
After this I updated watchman, and installed with npm as this:
`cd ~
sudo npm -g install watchman
`

**Comment by pitylee** [comment]
**UPDATE**
`sudo npm cache clean -f && sudo npm install -g n && sudo n stable`
seems to have resolved the issue :+1:

**Comment by hansonw** [comment]
Glad you were able to fix it!
