### ISSUE TITLE
Wrong highlighting of Flow errors for intersection types 

### ISSUE THREAD

**Issue by PinkaminaDianePie** [facebook/nuclide#1112]
### Issue and Steps to Reproduce
When using intersection types nuclide didn't show error on wrong data assignment, it shows only error on type declaration.

### Expected Behavior
Wrong data should be highlighted, like when using normal types.
![image](https://cloud.githubusercontent.com/assets/1625500/25267964/9e07b764-267f-11e7-9e98-ff7100403d2e.png)

### Actual Behavior
Wrong data not highlighted, we could see error only in type declaration.
![image](https://cloud.githubusercontent.com/assets/1625500/25267931/71751570-267f-11e7-92b3-92776d6b2cbb.png)

### Versions
* Atom: 1.16.0
* Nuclide: 0.218.0
* Client OS: Ubuntu 16.04

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (28) /home/igor/.atom/packages
├── MagicPython@1.0.9
├── atom-ternjs@0.18.2
├── autocomplete-modules@1.6.9
├── autocomplete-plus@2.35.4
├── busy-signal@1.3.0
├── docblockr@0.9.4
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── hyperclick@0.0.40
├── intentions@1.1.2
├── language-babel@2.57.5
├── language-ejs@0.4.0
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.8.0
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.1.4
├── linter-eslint@8.1.6
├── linter-ui-default@1.2.3
├── merge-conflicts@1.4.4
├── minimap@4.27.1
├── nuclide@0.218.0
├── nuclide-format-js@0.0.36
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0

**Comment by nmote** [comment]
Nuclide simply reports the errors at the locations Flow gives us. Feel free to report this here: https://github.com/facebook/flow

Yes, the error location may look better on the Flow CLI, but if we took the location that appears first on the CLI there are other errors that would end up in the wrong position. This needs to be fixed by Flow.
