### ISSUE TITLE
click-to-definition and flow coverage not working in Windows10

### ISSUE THREAD

**Issue by ugendrang** [facebook/nuclide#1113]
Environment:
Atom: 1.16.0
Nuclide: 0.218.0
OS: Windows 10
flow: flow-win64-v0.44.1
react: 15.4.1
react-native: 0.40.0

on executing "where flow" in command prompt:
C:\softwares\flow-win64-v0.44.1\flow\flow.exe

projects .flowconfig file:
[version]
^0.44.1

After all on opening Atom, got the following message, "Flow was not found when attempting to start it..."

Even i tried by installing flow-bin, but non works

>>>>>
But Flow works fine in below configuration,
Environment:
Atom: 1.15.0
Nuclide: 0.200.0
OS: Windows7

It looks click-to-definition and flow coverage not working in Windows10

**Comment by hansonw** [comment]
Open "Nuclide Settings" from the command palette and look for a flow path setting - try manually setting that to `C:\softwares\flow-win64-v0.44.1\flow\flow.exe`. Not sure why the auto-detect would be broken though :(

**Comment by ugendrang** [comment]
I tried @hansonw suggestion, by adding the path 'C:\softwares\flow-win64-v0.44.1\flow\flow.exe' to 'Nuclide Settings' under the category 'Nuclide-Flow', but it also didn't work.

**Comment by ebluestein** [comment]
This should be working on Windows now. Please let is know if you still have an issue.

**Comment by ugendrang** [comment]
@ebluestein, issue still occurs even after uninstalling the old nuclide package and installing it to latest nuclide version 0.229.0 and with flow-win64-v0.47.0

**Comment by ugendrang** [comment]
@ebluestein, issue still occurs even after uninstalling the old nuclide package and installing it to latest nuclide version 0.229.0 and with flow-win64-v0.47.0
