### ISSUE TITLE
Broken UI for Working Sets

### ISSUE THREAD

**Issue by MikaelCarpenter** [facebook/nuclide#1115]
### Issue and Steps to Reproduce
Left hand sidebar text for "Working Sets" is off. Not sure if you're interested in fixing this as it is UI Theme dependent. Specifically for the `atom-material-ui` theme, but possibly others.

![screen shot 2017-04-24 at 1 20 47 pm](https://cloud.githubusercontent.com/assets/8742292/25357209/d189725c-28f1-11e7-9c3a-1468f98c5e47.png)
![screen shot 2017-04-24 at 1 22 18 pm](https://cloud.githubusercontent.com/assets/8742292/25357208/d18705f8-28f1-11e7-9a0a-4281b06cacd2.png)

To replicate install the atom material theme and you should see it right away.

### Expected Behavior
The text should be clearly visible for any theme and any sidebar width (with a min width breaking point if necessary).

The current location of the button is a little precarious in general because it's inline with project dependent text rather than given it's own row.

It would likely benefit from relocation to either the buttons at the bottom or being inline with the "Folder" text. Or just a change in design to make it more light weight. (smaller, possibly just an icon because it is displayed inline)

For example, on another theme, at the min width for the buttons at the bottom, the Working Sets button is overlapping with project text. So you end up with a design with two different breaking min-widths 
![screen shot 2017-04-24 at 1 37 51 pm](https://cloud.githubusercontent.com/assets/8742292/25357695/a0247c3c-28f3-11e7-80ec-881eb7018f66.png)

### Actual Behavior
Certain UI themes are capable of making the "working sets" text break. 

### Versions
* Atom: 1.16.0
* Nuclide: 0.218.0
* Client OS: OSX

### Additional Details
* atom-material-ui: 1.3.9

**Comment by shushz** [comment]
Yes, sorry about that. The `atom-material-ui` changes a lot of things.
While we strive to make a reasonable effort for Nuclide to be compatible with themes, due to the resources constraints, we only officially support `One Dark`, `One Light`, `Atom Dark` and `Atom Light` themes.
