### ISSUE TITLE
nuclide 0.220.0

### ISSUE THREAD

**Issue by hamednourhani** [facebook/nuclide#1118]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:
* Nuclide:
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by shushz** [comment]
That's not very informative.
