### ISSUE TITLE
Code coloring problem with a RegExp ending with a / after an ||

### ISSUE THREAD

**Issue by erikras** [facebook/nuclide#1121]
### Issue and Steps to Reproduce
The javascript coloring is being thrown off by an escaped `/` at the end of a regular expression.

```js
const addProtocol = (url: string): string =>
	(!url || /^https?:\/\//.test(url) ? url : `http://${url}`)
```
![regexp](https://cloud.githubusercontent.com/assets/4396759/25493209/aa2e0a84-2b75-11e7-8caa-aa1bad2ec8ef.jpg)

Interestingly, if you remove the `!url ||` before the RegExp, it works fine. Something about the `||` is throwing it off.

### Expected Behavior
Should understand that this is not a comment.

### Actual Behavior
It's colored as if it's a comment.

### Versions
* Atom: 1.16.0
* Nuclide: 0.220.0
* Client OS: Mac 10.12.4

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── atom-ungit@0.5.3
├── busy-signal@1.4.1
├── color-picker@2.2.5
├── debugger@0.4.5
├── flow-ide@1.4.2
├── git-log@0.4.1
├── git-plus@7.7.0
├── intentions@1.1.2
├── jsformat@0.9.3
├── language-javascript-jsx@0.3.7
├── linter@2.1.4
├── linter-flow@5.6.0
├── linter-ui-default@1.2.3
├── merge-conflicts@1.4.4
├── nuclide@0.220.0
├── nuclide-test-runner-mocha@0.1.1
├── platformio-ide-terminal@2.5.0
├── prettier-atom@0.29.0
├── react@0.16.2
└── vim-mode-plus@0.91.0
```

**Comment by shushz** [comment]
I think you might be getting this syntax highlighting from the `language-javascript-jsx` package, rather than from the default `language-javascript`

![screen shot 2017-04-27 at 11 51 43 am](https://cloud.githubusercontent.com/assets/8860623/25499370/0e2bba08-2b40-11e7-96cf-eaf89ff845bf.png)

**Comment by erikras** [comment]
Confirmed. Thanks!
