### ISSUE TITLE
Quick questions

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/nuclide#1140]
I'm working on a nuclide test runner for create-react-app + jest

just a few questions:

1. when writing a package nuclide should I follow this guide even if the package will live outside of the main nuclide repo? https://github.com/facebook/nuclide/wiki/Writing-Packages

2. if I want to use flow for my package, how do I import the types nuclide has already prewritten? add it as a dependency for my package? or is there a better way of pulling in the types?

3. Thanks for all the great open source. ✨

**Comment by jgebhardt** [comment]
Hi @lifeiscontent, sorry for the delay! To answer your questions (and in case anyone else is wondering):
1) No, you don't need to follow the Nuclide package guide for regular Atom packages. However, many of the recommendations (ie., everything besides the package creation script and the `import` vs `require` guidance) still hold true for non-Nuclide Atom packages.
2) I believe pulling in nuclide as a dev dependency and using `import type` is the way to go for now. It's not ideal but currently your best bet.
3) Thanks! I'm curious, how did your test runner project go?
