### ISSUE TITLE
No inline flow errors

### ISSUE THREAD

**Issue by hmeerlo** [facebook/nuclide#1141]
### Issue and Steps to Reproduce
I did a clean install of nuclide (as the only installed package along with the recommended dependencies). I pointed to the flow executable and a flow error is shown in the diagnostics pane, but no errors are ever shown inline. 

### Expected Behavior
I expected a red triangle in the gutter and on hover I would expect a detailed error message.

### Actual Behavior
No inline error, no red triangle in the gutter

### Versions
* Atom: 1.16.0
* Nuclide: 0.223.0
* Client OS: macOS 10.12.4
* Server OS (optional): NA

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (16) /Users/hmeerlo/.atom/packages
├── MagicPython@1.0.10
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.61.0
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.8.0
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── nuclide@0.223.0
├── nuclide-format-js@0.0.36
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0

**Comment by nmote** [comment]
I'm willing to bet this is a dupe of #662

The `strip_root` config option is confusing and I think it should be removed altogether. It serves no useful purpose (running `flow status` already strips the root). The only thing it does is confuse editors.

**Comment by hmeerlo** [comment]
You just won the bet, removing `strip_root` from `.flowconfig` fixed it. Thanks.

**Comment by nmote** [comment]
As of https://github.com/facebook/flow/commit/79b4997cce208dbca9d2b07ff4629e3ce15ff2e2, the `strip_root` option can no longer be specified in `.flowconfig`. Once that's released this problem should be permanently solved.
