### ISSUE TITLE
Source line breakpoints not set, or move.

### ISSUE THREAD

**Issue by raould** [facebook/nuclide#1142]
I am working on a React Native app for iOS. I can mostly sort of kinda debug things from Nuclide, cool! But... there are some times when I try to click in the gutter at some source code in order to set a breakpoint, and the IDE decides that either (a) the breakpoint is not possible at all where I clicked or (b) is possible elsewhere and puts in a (?) icon where I clicked. There does not appear to be any obvious rhyme or reason to how/why, so I haven't sussed out any workarounds, either. Might anybody know what is going on with that? Thanks!

### Versions
* Atom: 1.16.0 x64 (funny how the "copy this version string" button in Atom itself doesn't include the "x64" part of the string?!)
* Nuclide: 0.223.0
* Client OS: iOS 10.3 (simulator) and Mac OS 10.12.4

### Additional Details
* Installed packages (`apm ls --installed`):
[36mCommunity Packages (16)[39m /Users/raould/.atom/packages
├── MagicPython@1.0.10
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.61.0
├── language-graphql@0.8.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.8.0
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── nuclide@0.223.0
├── nuclide-format-js@0.0.36
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0

**Comment by adgarcia** [comment]
same issue here

**Comment by ebluestein** [comment]
Unfortunately we are not supporting the react native debugger right now from Nuclide due to several issues such as this one.

**Comment by HessiPard** [comment]
any update for this? with the recent update of nuclide (0.270.0) I still cant set breakpoint in react native and all the breakpoints will turn to unresolved (?) state.

**Comment by pelmers** [comment]
see https://github.com/facebook/nuclide/issues/1389, v0.271 will have the fix which makes the react native debugger selectable

**Comment by HessiPard** [comment]
@pelmers  I dont have problem in find and attaching debuger ... I followed #1389 before and after modifying `main.js` and commenting `return` statement, I am able to attach react native debugger.
my problem is unresolved breakpoints ... my breakpoints dont hit.

**Comment by pelmers** [comment]
@HessiPard ah thanks, I misunderstood your situation. could you make a new issue for your bug and include the react-native version?

ideally some code/repro example would be very helpful.

just an initial hunch: an old node bug (because atom uses old electron which uses old node) sometimes prevents setting breakpoints at launch. it may work if you set the breakpoints after launch and reload the app.
