### ISSUE TITLE
File tree shows up in main pane instead of side pane

### ISSUE THREAD

**Issue by seekshiva** [facebook/nuclide#1144]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

File tree shows up in the main pane along with the other files. It doesn't show up in the side pane. Even if I manually split panes and move tree view to the side, when I click on a file name, file opens in the side pane itself rather than main pane. Deleting and reinstalling nuclide doesn't help. Pressing Cmd+/ to toggle tree view toggles it in main pane itself rather than side pane.

### Expected Behavior
Tell us what should happen.

Tree view should open in side 

### Actual Behavior
Tell us what happens instead.

Tree view opens in main pane

### Versions
* Atom: 1.17.0
* Nuclide: 0.226.0
* Client OS: MacOS Sierra 10.12.4
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (11) /Users/shiva/.atom/packages
├── atomic-chrome@0.3.0
├── file-icons@2.1.5
├── language-babel@2.61.0
├── linter@2.1.4
├── linter-eslint@8.1.7
├── nuclide@0.226.0
├── oceanic-next@1.0.0
├── oceanic-next-italic@1.0.1
├── oceanic-next-italic-white@0.1.3
├── prettier-atom@0.31.0
└── tool-bar@1.1.0
```

**Comment by seekshiva** [comment]
Uninstalling atom, removing `~/.atom` and reinstalling atom and nuclide doesn't help either.

**Comment by crucialfelix** [comment]
This started with Atom release: https://github.com/atom/atom/releases/tag/v1.17.0

This is what we are seeing:

![Uploading Screen Shot 2017-05-19 at 11.09.20.png…]()

It opens on top of which ever pane you have currently focused. I think it is just a css issue due to renamed or restructured classes.

When selecting a file it closes, so maybe this is meant to be a new modal dialog; but it isn't working right at all.

Thanks !

**Comment by crucialfelix** [comment]
Actually I'm getting the same behavior with nuclide disabled. It happens if I split the pane.

**Comment by pjkarlik** [comment]
Having the same problem, Also for me the toolbar at the top is missing to now..

**Comment by crucialfelix** [comment]
I would guess this has to do with the new docks feature: http://blog.atom.io/2017/05/16/atom-1-17.html

It's good that there is an official API for sidebars and panels.

**Comment by matthewwithanm** [comment]
If you drag the tab back into the left dock does it stay there?

**Comment by seekshiva** [comment]
@matthewwithanm It stays in the left, but any files opened from tree view also stay in the same pane.

![nuclide-tree-pane](https://cloud.githubusercontent.com/assets/484349/26335428/6f26e00a-3f89-11e7-9f75-f53b7252aa33.gif)

**Comment by matthewwithanm** [comment]
@seekshiva awesome for! It looks like you're just splitting the center pane? Can you drag it further, into the left dock?

**Comment by seekshiva** [comment]
@matthewwithanm I had to drag it to the arrow meant for left dock. Works now! Thanks!

![nuclide-tree-pane-drag](https://cloud.githubusercontent.com/assets/484349/26336665/6a7f0d9a-3f91-11e7-8e27-696296c5dcaf.gif)

**Comment by seekshiva** [comment]
also, when I click on any diagnostics message, the list of errors and warnings becomes empty. Clicking on source files again shows the error.

![nuclide-diagnostics-selection](https://cloud.githubusercontent.com/assets/484349/26338941/e0e51140-3fa1-11e7-89b8-0a9b5e9ab537.gif)

**Comment by crucialfelix** [comment]
Oh. Very non-obvious. Glad you figured it out, thanks !

You can also drag the diagnostics down to the bottom pane.

**Comment by crucialfelix** [comment]
Sorry, this is still really unusable.  You can drag the file tree into a sidebar, but the next time you open the project it is back to the main. Double click a file in the file tree and it opens in the SAME pane as the file tree.

![screen shot 2017-05-27 at 15 01 46](https://cloud.githubusercontent.com/assets/218738/26521646/a7b8a824-42ed-11e7-8651-48ad8c87a8d6.png)

**Comment by matthewwithanm** [comment]
@crucialfelix Can you provide a repo? I can't repro this behavior.

**Comment by crucialfelix** [comment]
Install nuclide.

  I will post other packages that are installed but I don't know what could possibly cause this other than nuclide tree view itself.

Split panes ? Off the top of my head that is core atom.

**Comment by crucialfelix** [comment]
It might have been this https://atom.io/packages/pane-layout-plus that caused it.

Though it looks like it is just calling atom core pane API: https://github.com/chemoish/atom-pane-layout/blob/master/lib/pane-layout-formatter.coffee

I've disabled it and it seems fine for now.

This is what I've seen:

![screen shot 2017-06-12 at 11 38 56](https://user-images.githubusercontent.com/218738/27028023-c59b5062-4f63-11e7-80d0-31ff6c9579d1.png)
 
It affects all nuclide panels (File Tree, Diagnostics, Outline View)

**Comment by matthewwithanm** [comment]
@crucialfelix Thanks so much for the followup! This seems like something that'll have to be addressed in that package then, so I'm gonna close.

Thanks again!
