### ISSUE TITLE
nuclide-flow - linux trouble

### ISSUE THREAD

**Issue by sauerman** [facebook/nuclide#115]
Hey,
I cant get flow to work in atom. When I start flow in the foreground w/ "flow server" I get following output when I change a flow-monitored file in atom:

Couldn't autocomplete
Failure("tvar 25318 not in file /home.......")

The number changes everytime. If I run flow in the terminal everything works as expected.

**Comment by nmote** [comment]
Can you clarify where that output appears? Is it in the output from `flow server`?

Which parts of flow "do not work" in Atom? This seems like it's related to autocomplete -- do Flow errors appear in the editor?

What do you mean by "everything works as expected?" What commands are you running from the command line? And what version of Flow do you have?

**Comment by sauerman** [comment]
Its the output from "flow server" yep.

I dont get anything from flow in atom. Its like I have no nuclide installed.

if I run "flow" in the projectdirectory I get the flow errors.
Version is the latest from flowtype.org

**Comment by nmote** [comment]
Interesting, I will see if I can reproduce. A couple more questions -- what distro/version of Linux are you running? And can you give me the output of `flow --version`? There was just a new release yesterday so I want to make sure you're on the latest version.

**Comment by sauerman** [comment]
Manjaro (Arch)
flow is 0.12.0

**Comment by nmote** [comment]
Thanks for the report; I will check this out.

**Comment by pluma** [comment]
I also can't get the error highlighting to work.

1. Clean checkout of https://github.com/foss-haas/rotunda/tree/d1d9adbf6884db8b22548693dbcfef83762f7501
2. `npm install`
3. `flow server`
4. start atom when "Server is READY" appears
5. open `test/router.js`
6. in line 14 add `it('hello', 5);`

Result:

```
[2015-07-02 20:06:32] Initializing Server (This might take some time)
[2015-07-02 20:06:32] executable=/home/pluma/bin/flow
[2015-07-02 20:06:32] version=0.13.1
[2015-07-02 20:06:37] Server is READY
[2015-07-02 20:06:37] Took 4.778385 seconds to initialize.
Couldn't autocomplete
Failure("Couldn't parse file")
Couldn't autocomplete
Failure("Couldn't parse file")
Couldn't autocomplete
Failure("tvar 59095 not found in file /home/pluma/projects/rotunda/test/router.js")
Couldn't autocomplete
Failure("tvar 60279 not found in file /home/pluma/projects/rotunda/test/router.js")
Couldn't autocomplete
Failure("tvar 61463 not found in file /home/pluma/projects/rotunda/test/router.js")
Couldn't autocomplete
Failure("tvar 68573 not found in file /home/pluma/projects/rotunda/test/router.js")
Couldn't autocomplete
Failure("tvar 69758 not found in file /home/pluma/projects/rotunda/test/router.js")
Couldn't autocomplete
Failure("Couldn't parse file")
Couldn't autocomplete
Failure("tvar 70943 not found in file /home/pluma/projects/rotunda/test/router.js")
recheck 1 files:
1/1: /home/pluma/projects/rotunda/test/router.js
```

**Comment by nmn** [comment]
I was having similar problems till recently. Nuclide-flow wouldn't work at all for me. It would just make atom-helper run at 100% Cpu.

Today I updated to the latest version of both flow and nuclide-flow and I at least got autocomplete to work for a while. 

Still didn't see any errors highlighted though.

Info: I'm using OS X, 10.10.4
Latest release of Atom.
I have Autocomplete-plus installed.
I have linter installed. (linter-plus no longer exists)
I am on a macbook air early 2014.

Additional info, flow from the command line gave me some trouble as well today. I will do more tests and report back.

**Comment by Fatxx** [comment]
Same here on elementary os

**Comment by nmote** [comment]
I'm interested in the

> Failure("Couldn't parse file")

lines. @pluma, thanks for posting a detailed repro case. I will try it out. This sounds like it may be an issue with Flow itself, in which case I'll file a bug with them.

@nmn, if you have trouble with Flow from the command line, then you can file an issue directly with https://github.com/facebook/flow . If you do, I would appreciate it if you CC me or refer to this issue.

**Comment by nmn** [comment]
@nmote flow works fine from the command line. There was one version that locked up, but that only happened once and I've not been able to reproduce any more problems.

Nuclide-flow however, still doesn't do any linting at all. Autocomplete works fine now, and Atom doesn't seem to be wasting CPU cycles when I turn on Nuclide-flow

For what it's worth, I built my own linter plugin (github.com/nmn/linter-flow-plus) which works just fine. There are some JSON parsing problems which is a trivial fix away, but it works well enough most of the time.

There is also another atom plug-in called `ide-flow` that works decently well. It has auto-complete which is on par with Nuclide, linting support and types on hover. However, it only lints on save, and my plug-in lints as you type, which is why I wan't happy with ide-flow. Further, ide-flow isn't integrated with linter and it's linting styles can only be editing with CSS directly.

**Comment by nmote** [comment]
@pluma: Thanks again for the detailed repro instructions. I can reproduce your issue. If I disable the "Lint on Fly" option in the linter package, the issue goes away (but then you have to save to get errors). It looks like we don't send the current file contents to Flow when linting on the fly, which is obviously wrong. I'll fix that.

@sauerman: I think the autocomplete errors you're getting are a separate issue. It looks similar to an issue with type hints that the Flow team just fixed. I suspect that the reason you aren't getting those errors when running from the terminal is just that you aren't querying Flow for autocomplete suggestions when you run it from the terminal. Do click-to-definition and typehints work for you? If so, I think you're experiencing the same issue as everyone else in the thread.

@nmn I haven't experienced the issue with Atom Helper pegging the CPU. How do you know it was nuclide-flow causing that? Are other nuclide-flow features working, or is it just linting that's broken? If you disable "Lint on Fly" does linting start working? I hope that we can soon get to the level of quality where you won't feel the need to maintain your own linter package :)

**Comment by nmn** [comment]
@nmote I have some updates:

- The high cpu usage is most likely an issue with Atom and not Nuclide-Flow, as I've had the problem from time to time, even after disabling nuclide-flow. It seems to be connected to the Settings screen. Earlier, this problem seemed to be happening when Nuclide-flow was enabled, and so the co-incidences fooled me.

- *Linting*: After the very latest update, linting works. It feels like `Lint on Fly` doesn't work. As I type, the errors that show up reflect the state of the last save, and not what is on-screen. To make matters worse, linter doesn't update anything on save.
For example, let's say there is a flow error when I save a file. After that as I type, the error will stay even if I fix the error. The error will stay when I save the fix. But will then disappear when I type something.

- *Autocomplete*: This feature has been hit or miss from the very beginning, but this is probably an issue with flow or autocomplete plus. I get good autocomplete for complex types like promises, but not for simple types like numbers and strings. This is true for ide-flow as well. There is an option in the Api for autocomplete plus that lets you hide lower priority options. So it's possible some other package is hiding the suggestions from Nuclide-flow

- Type Hints on hover have never worked for with Nuclide.
- Go-to-Symbol definition, sometimes works, but only with my own custom keyboard shortcut. Atom doesn't seem to like overriding cmd+click.

**Comment by nmn** [comment]
Quick update: While working on my own linter plug-in, (which works almost flawlessly now!) I've added support for traces. Best example of Traces is with the render method annotated with ReactElement.

When you return null from such a method, flow, correctly, complains. But it also points to the type definition of ReactElement as a trace. The actual error message is broken up between the main error and the trace.

Nuclide-flow currently just concats the error string together, but otherwise ignore the trace. Since it would only require changes to a single file, I'll make a patch to fix this in Nuclide.

**Comment by sauerman** [comment]
After updating the nuclide-* packages linting works (only gets triggerd on save). No typehinting no click-to-symbol, same error for autocomplete.

**Comment by nmote** [comment]
@nmn Yes, lint on fly is broken but I will have a fix for it shortly. Yes, we've been meaning to expose those errors more intelligently but haven't gotten around to it. A PR for that would definitely be welcome.

I'm not sure why autocomplete and typehints aren't working; I've never had any issues with them even when I was using my Fedora machine to try to reproduce these issues. @nmn or @sauerman, Are you getting any errors in the developer console?

**Comment by nmn** [comment]
@nmote I'll make pr for on the fly linting / trace support shortly. (My own linter has gotten very good, and I'll be sad to deprecate it :( )

about auto-complete, I want re-iterate that autocomplete works for me. I just don't get as many suggestions as I should. I tried over and over and for a function returning a promise, autocomplete ALWAYS works.

So the problem is either with flow itself, or that the suggestions being returned by Nuclide are low priority and being hidden by other suggestions from other sources. I will keep an eye out for more details.

typehint, just don't work though.

**Comment by nmote** [comment]
Don't bother with on the fly linting, I've already got that being reviewed internally.

Thanks for clarifying about autocomplete. Yes, the results leave something to be desired. I haven't personally looked into it, but I have observed it.

Not sure why typehints aren't working. I added them pretty recently; I wonder if you have that version of nuclide-flow? Check in the nuclide-flow settings for an "enable type hints" option. If it's not there it just means you don't have that version.

**Comment by nmn** [comment]
@nmote I just started coding and autocomplete working much better. One really annoying bug though: using the autocomplete eats up the prefix. In particular, I typed a dot and got a list of options. When I used one of the options, it removed the dot.

If you don't want on the fly linting, Ill give a pr in a couple of hours at most. I can pretty much copy-paste my code!

**Comment by nmn** [comment]
@nmote I can confirm, the autocomplete does give suggestions at a very low priority.

**Comment by nmn** [comment]
https://github.com/facebook/nuclide/pull/139

pull request which adds support for traces in Nuclide Errors. Also it treats warning as warnings, instead of making everything an error. Code has been ported over from my own linter so it's well tested over the last few days.

**Comment by nmote** [comment]
I think the only unresolved issue here is the autocomplete priority. Please correct me if I'm wrong.

@nmn, it sounds like you still haven't gotten type hints working -- did you double-check that you have the "enable type hints" option in nuclide-flow, and that the box is checked?

**Comment by nmn** [comment]
@nmote Autocomplete priority is the only thing pending, yes.

I still haven't got type-hints to work. The checkbox is checked. I tried to troubleshoot and and I reinstalled the type-hint package, but to no avail. Other people seem to have it working though, so I will keep troubleshooting when I have time. (it's the lowest priority feature for me). Once I have some positive results, I will report back here, perhaps with a documentation PR. (For example, it wasn't clear that `nuclide-type-hint` was a dependency in the documentation. Only Linter and Autocomplete-plus were explicitly mentioned.)
Nuclide-Click-to-Symbol is the other thing that doesn't work for me. I'm going to try to install the demo providers to test these packages, and then check back for flow.

**Comment by nmote** [comment]
Nuclide is intended to be used with all of its packages installed; using it piecemeal is not supported. If you followed the installation instructions (running the `setup` script if you're developing from source, installing `nuclide-installer` if you are not), you should have gotten all of the Nuclide packages, including `nuclide-type-hint`.

**Comment by nmn** [comment]
@nmote I did use APM to install all packages of Nuclide while trying to make those things work. But it didn't seem to work. I'll try to install everything from source and report back.

**Comment by cbosuna** [comment]
@nmn Did this start working for you?

**Comment by nmn** [comment]
@cbosuna Nope... just tried installing from source but no luck. I've tried two separate macs. any of the hover/click things in Flow don't work for me. (type definition tooltips and click to definition)

That said, Hyperclick with the demo package DOES work. Also, IDE-FLOW has type tool tips that also generally work.

**Comment by nmn** [comment]
@cbosuna *GOOD NEWS*, I built from source again, and now type hints and click to source are both working. Sadly, autocomplete seems to be broken now, which was working before I did this update.

So as of now, everything is working great (at least in flow) except autocomplete.

**Comment by nmote** [comment]
Nuclide v0.31 fixed Flow autocomoplete. I think we're all set here.

**Comment by raould** [comment]
Mac OS X 10.10.5
flow 0.22.1
atom 1.6.0 installed today
used apm to install nucleide today, apparently 0.125.0

I do not see any flow error markers in Nuclide. I do get errors when I run flow from the command line. Is there some setting I am supposed to turn on via an Atom menu or something? Thanks! I'm very excited to get something going, it is e.g. lame that WebStorm doesn't have tight integration like this. :-)

(P.s. BTW the Nuclide-Flow docs only say you have to use "/* @flow */" when the Flow docs say "// @flow" is OK.)

**Comment by nmote** [comment]
Hey, this is a pretty old issue -- could you open a new one? CC me so the response is quicker.

It's hard to say what's going wrong here without more details. The most likely thing I can think of is that Nuclide isn't finding the Flow binary. You can go to the `nuclide-flow` section in the `nuclide` settings and specify the path to the Flow binary. See if that helps. If not there are some other things we can try.

I have some work planned to make it more obvious why results aren't appearing in various cases. We have to balance making clear why Flow isn't working against not annoying people who don't want to use it. Right now I think we are too far towards the latter.
