### ISSUE TITLE
Multiple cursor (cmd + click) action disabled by Nuclide

### ISSUE THREAD

**Issue by oldo** [facebook/nuclide#1159]
### Issue and Steps to Reproduce
After updating Nuclide the cmd + click function for multiple cursors is no longer working. Have confirmed that disabling Nuclide reverts to expected behaviour.

### Expected Behavior
cmd + click should allow multiple cursors or selection of multiple elements

### Actual Behavior
cmd + click does nothing.

### Versions
* Atom: 1.17.0
* Nuclide: 0.228.0
* Client OS: MacOS Sierra 10.12.4
* Server OS (optional): null

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (20) /Users/oldo/.atom/packages
├── Sublime-Style-Column-Selection@1.7.4
├── atom-panda-syntax@0.18.0
├── atom-wrap-in-tag@0.6.0
├── autocomplete-modules@1.6.10
├── busy-signal@1.4.1
├── file-icons@2.1.5
├── intentions@1.1.2
├── linter@2.1.4
├── linter-eslint@8.1.7
├── linter-php@1.3.2
├── linter-ui-default@1.4.0
├── nuclide@0.228.0
├── oceanic-next@1.0.0
├── pigments@0.39.1
├── project-manager@3.3.4
├── react@0.16.2
├── remote-atom@1.3.10
├── sync-settings@0.8.1
├── tab-foldername-index@2.0.3
└── toggle-quotes@1.0.1
```

**Comment by IanVS** [comment]
Try `alt+cmd+click`.  By default, `cmd+click` will use flow to take you to a definition.

**Comment by oldo** [comment]
Thank @IanVS 👌
