### ISSUE TITLE
Nuclide-Quick-Open on Windows, Mac keys displayed

### ISSUE THREAD

**Issue by Johann-S** [facebook/nuclide#116]
Hi,

When I use ``ctrl + t`` I have this modal which is open : 

![touchfaker js - dwampwwwtouchfaker - atom](https://cloud.githubusercontent.com/assets/1689750/8427075/fe257024-1f14-11e5-98ab-7bdc6113e560.jpg)

But I'm on Windows so I think it's a bit strange to have mac keys displayed next to "All results", "Filenames" and "Open files".

I think it's maybe at this line : https://github.com/facebook/nuclide/blob/master/pkg/nuclide/quick-open/lib/QuickSelectionComponent.js#L140

**Comment by jssln** [comment]
Thanks for the report!

**Comment by ssorallen** [comment]
This was fixed in commit bbbddd2da3546fbe00ea1a4ecbbc0eebe382d4f6.
