### ISSUE TITLE
hyperclick is Invalid on .vue file

### ISSUE THREAD

**Issue by Southhill** [facebook/nuclide#1165]
### Issue and Steps to Reproduce
I add .vue on extensions but hyperclick is Invalid on .vue file

### Expected Behavior
hyperclick on vue file is invalid

### Actual Behavior
click functionName,var is No response

### Versions
* Atom:1.17.2
* Nuclide:0.229.0
* Client OS:windows 10
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-beautify@0.29.24
├── atom-clock@0.1.8
├── atom-html-preview@0.1.22
├── atom-material-syntax@1.0.6
├── atom-material-syntax-dark@1.0.0
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.0.4
├── atom-nodejs-snippets@1.5.0
├── atom-ternjs@0.18.3
├── autocomplete-paths@1.0.5
├── autoprefixer@3.7.0
├── busy-signal@1.4.1
├── compare-files@0.8.0
├── css-snippets@1.1.0
├── csscomb@0.3.1
├── docblockr@0.10.3
├── editorconfig@2.2.2
├── emmet@2.4.3
├── file-icons@2.1.6
├── highlight-selected@0.13.1
├── hyperclick@0.0.40
├── intentions@1.1.2
├── javascript-snippets@1.2.1
├── js-hyperclick@1.11.0
├── language-babel@2.63.0
├── language-generic-config@1.3.0
├── language-javascript-jsx@0.3.7
├── language-rust@0.4.10
├── language-vue@0.22.0
├── linter@2.1.4
├── linter-csslint@1.3.4
├── linter-eslint@8.2.1
├── linter-ui-default@1.6.0
├── merge-conflicts@1.4.5
├── my-theme-syntax@0.0.0
├── nuclide@0.229.0
├── nuclide-format-js@0.0.36
├── open-in-browsers@0.0.19
├── platformio-ide-terminal@2.5.1
├── script@3.15.0
├── sync-settings@0.8.1
├── toggler@0.3.0
└── tree-view-git-status@1.4.0

**Comment by zhiquan-yu** [comment]
You need [vue-hyperclick](https://atom.io/packages/vue-hyperclick).

Your issue is about [js-hyperclick](https://github.com/AsaAyers/js-hyperclick), not nuclide, you should close this issue.

**Comment by Southhill** [comment]
yes, for atom editor i installed js-hyperclick has solve problem. but the effect is not very good。 then i installed vue-hyperclick on atom editor.
