### ISSUE TITLE
[Regression bug] Outline pane always closed upon opening Atom

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#1181]
### Issue and Steps to Reproduce
Run `atom .` in a folder where Atom was previously run and the Outline pane was open.

### Expected Behavior
Outline pane should be open (last saved state since Atom was closed).

### Actual Behavior
Outline pane is always closed.

### Versions
* Atom: 1.17.2
* Nuclide: 0.231.0
* Client OS: macOS 10.12.5

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (33) /Users/samh/.atom/packages
├── MagicPython@1.0.10
├── autocomplete-elixir@1.5.14
├── autocomplete-modules@1.6.10
├── color-picker@2.2.5
├── dash@1.7.1
├── expose@0.14.0
├── file-icons@2.1.7
├── git-time-machine@1.5.9
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── js-refactor@0.7.5
├── language-babel@2.65.1
├── language-elixir@0.18.0
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.10
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.1.4
├── linter-eslint@8.2.1
├── merge-conflicts@1.4.5
├── minimap@4.28.2
├── nuclide@0.231.0
├── nuclide-format-js@0.0.36
├── pigments@0.39.1
├── prettier-atom@0.32.0
├── refactor@0.11.4
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── todo-show@1.11.0
└── tool-bar@1.1.0
```

**Comment by matthewwithanm** [comment]
Does this happen multiple times for the same project? We changed the serializer name and accidentally didn't also keep the old one (for the transition) 😞 so it should happen just once per project.

**Comment by ffxsam** [comment]
Yep, I can type `atom .`, open the Outline view, quit Atom, then run `atom .` again and the Outline view is closed.

**Comment by matthewwithanm** [comment]
Aw sorry. We missed some locations 😢

**Comment by matthewwithanm** [comment]
@ffxsam Thanks for reporting btw!

**Comment by ffxsam** [comment]
No worries! Minor thing, really. 😄
