### ISSUE TITLE
index.html missing html code and looks incomplete

### ISSUE THREAD

**Issue by KrishMunot** [facebook/nuclide#1185]
### Issue and Steps to Reproduce
I'm curious to understand the purpose of this directory - https://github.com/facebook/nuclide/tree/master/docs/docs

### Expected Behavior
The index.html in that directory was supposed to have HTML code, it looks like it isn't complete perhaps, does it need to be developed further?

### Actual Behavior
It looks like a templated text in a HTML file

### Versions
* Atom:
* Nuclide:
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by captbaritone** [comment]
Question answered in #1186
