### ISSUE TITLE
nuclide-client will fail to create local client when opened via symlink

### ISSUE THREAD

**Issue by SiebelsTim** [facebook/nuclide#119]
Imagine you have a symlink in your home directory to your working directory. When opening Atom, it will consider `/home/symlink/www` different from `/var/www`.  
So `atom.projects.getPaths()` will return `/home/symlink/www` while any `TextEditor.getBuffer().getUri()`  will return `/var/www/...`. 
This results in this if clause returning true.
https://github.com/facebook/nuclide/blob/d1a32ba004b02bbd7cd62dfe4a80b0a5a8417108/pkg/nuclide/client/lib/main.js#L31

It boils down to a call to `containsPath("/home/symlink/www", "/var/www/file.php")` which yields false. The result is that nothing of nuclide-hack works. (nuclide-flow might be affected too).

**Comment by scv119** [comment]
Thanks for reporting this!

**Comment by mostafaeweda** [comment]
that was fixed a while ago
