### ISSUE TITLE
Changes required due to TextBuffer.save becoming async in Atom 1.19

### ISSUE THREAD

**Issue by maxbrunsfeld** [facebook/nuclide#1198]
Hey Nuclide team!

As I've mentioned to some of you, in Atom v1.19, we will release a [major change](https://github.com/atom/atom/pull/14435) to Atom's core text buffer data structure. As part of this change, we have made `TextBuffer.save` asynchronous; rather than blocking until the save is complete, it now immediately returns a `Promise` that *resolves* when the save is complete. Because of this, a few other Atom APIs that *use* `save` have similarly become async:

* `Pane.close`
* `TextBuffer.save`
* `TextEditor.save`
* `Pane.saveItem`
* `Pane.saveItemAs`
* `Pane.saveActiveItem`
* `Pane.saveActiveItemAs`
* `Pane.saveItems`
* `Workspace.saveActivePaneItem`
* `Workspace.saveActivePaneItemAs`

#### Effects on this package

We think this package could be impacted by this upgrade because it calls the changed methods in the following places:

* `TextBuffer.save`
  * [here](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-remote-connection/lib/remote-text-buffer.js#L93)
  * [here](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-remote-connection/lib/remote-text-buffer.js#L95)
* `TextEditor.save`
  * [here](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-patch-editor/lib/main.js#L127)
  * [here](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-patch-editor/lib/main.js#L180)
  * [here](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-patch-editor/lib/main.js#L191)
  * [here](https://github.com/facebook/nuclide/tree/master/resources/benchmarker/benchmarks/archived/open-edit-save-by-package.js#L76)
  * [here](https://github.com/facebook/nuclide/tree/master/resources/benchmarker/benchmarks/open-edit-save-by-size.js#L60)

We found these calls using a regex search, so this list might be incomplete, and it might contain some false positives.

#### What to do about the change

It should be pretty easy to adjust your package code and/or tests to work with the new async behavior, and to simultaneously keep it working with older versions of Atom. Here are some examples of pull requests we opened on our bundled packages to cope with the change:

* https://github.com/atom/autocomplete-plus/pull/852
* https://github.com/atom/whitespace/pull/155
* https://github.com/atom/symbols-view/pull/222
* https://github.com/atom/status-bar/pull/193
* https://github.com/atom/tabs/pull/448

Let me know if you have any questions. I'd be happy to help!

**Comment by hansonw** [comment]
Thanks @maxbrunsfeld! Our remote editors have always had a custom async save so this particular piece is pretty painless. We're now using the new APIs in 1.19 so hopefully this is good to go :)
