### ISSUE TITLE
Version Mismatch - Nuclide Server (233) and Atom Plugin (232)

### ISSUE THREAD

**Issue by guswelter** [facebook/nuclide#1201]
### Issue and Steps to Reproduce
Latest available Nuclide plugin version on Atom is 232. Latest available Nuclide-Server via npm is 233.

### Expected Behavior
Versions should match.

### Actual Behavior
Receive version mismatch error when trying to connect to Nuclide Server in Atom: "Version mismatch. Client at 232 while server at 233."

### Versions
* Atom: 1.18.0 x64 Mac (also verified on 1.18.0 on Windows 10)
* Nuclide: 232 on Client/Atom; 233 on Server
* Client OS: macOS Sierra
* Server OS (optional): Ubuntu

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by bottledwalter** [comment]
The client and server have to run the same version. The simple fix is to upgrade your client/Atom version of Nuclide to 233

**Comment by guswelter** [comment]
Nuclide v233 is not available in Atom. Atom is up-to-date, and latest Nuclide available is 232. Confirmed in Mac and Windows.

**Comment by guswelter** [comment]
@bottledwalter Could you please reopen? Your suggestion is not a fix. Thanks.

**Comment by maartendamen** [comment]
Same issue here, any way to manually install an earlier version to the server side?

**Comment by maartendamen** [comment]
This fixed it for me:

sudo npm remove nuclide -g
sudo npm install nuclide@0.232.0 -g

**Comment by guswelter** [comment]
@maartendamen Thank you, great workaround.

**Comment by achirkof** [comment]
Version mismatch. Client at 257 while server at 256.
server version:
```
→ sudo npm install nuclide -g
/usr/bin/nuclide-start-server -> /usr/lib/node_modules/nuclide/pkg/nuclide-server/nuclide-start-server
/usr/lib
└── nuclide@0.257.0
```
Atom version also 0.257.0, but anyway Atom complains.

`sudo npm remove nuclide -g` and reinstall didn't help
