### ISSUE TITLE
Zombie File Trees

### ISSUE THREAD

**Issue by crucialfelix** [facebook/nuclide#1210]
### Issue and Steps to Reproduce

I'm not sure what has caused it or where this state is stored, but there are now 11 zombie file tree tabs in the left side pane.

"close tab" doesn't work.

Restarting or reloading the project doesn't work.

![screen shot 2017-06-20 at 11 30 11](https://user-images.githubusercontent.com/218738/27327029-861fc4d6-55ad-11e7-8dbb-0ba6d14a9087.png)

(side pane is manually expanded to show all of the extra file trees)

### Expected Behavior

There should only ever be but one file tree.

### Actual Behavior

There be more than one.

### Versions
* Atom:
1.18.0
* Nuclide:
 nuclide@0.232.0
* Client OS:
OS X
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

Built-in Atom Packages (91)
├── atom-dark-syntax@0.28.0
├── atom-dark-ui@0.53.0
├── atom-light-syntax@0.29.0
├── atom-light-ui@0.46.0
├── base16-tomorrow-dark-theme@1.5.0
├── base16-tomorrow-light-theme@1.5.0
├── one-dark-ui@1.10.4
├── one-light-ui@1.10.4
├── one-dark-syntax@1.7.1
├── one-light-syntax@1.7.1
├── solarized-dark-syntax@1.1.2
├── solarized-light-syntax@1.1.2
├── about@1.7.6
├── archive-view@0.63.2
├── autocomplete-atom-api@0.10.1
├── autocomplete-css@0.16.2
├── autocomplete-html@0.8.0
├── autocomplete-plus@2.35.4
├── autocomplete-snippets@1.11.0
├── autoflow@0.29.0
├── autosave@0.24.3
├── background-tips@0.27.0
├── bookmarks@0.44.4
├── bracket-matcher@0.85.5
├── command-palette@0.40.4
├── dalek@0.2.1
├── deprecation-cop@0.56.7
├── dev-live-reload@0.47.1
├── encoding-selector@0.23.4
├── exception-reporting@0.41.4
├── find-and-replace@0.208.3
├── fuzzy-finder@1.5.8
├── github@0.3.3
├── git-diff@1.3.6
├── go-to-line@0.32.1
├── grammar-selector@0.49.5
├── image-view@0.61.2
├── incompatible-packages@0.27.3
├── keybinding-resolver@0.38.0
├── line-ending-selector@0.7.1
├── link@0.31.3
├── markdown-preview@0.159.12
├── metrics@1.2.5
├── notifications@0.67.2
├── open-on-github@1.2.1
├── package-generator@1.1.1
├── settings-view@0.249.4
├── snippets@1.1.4
├── spell-check@0.71.4
├── status-bar@1.8.11
├── styleguide@0.49.6
├── symbols-view@0.116.0
├── tabs@0.106.2
├── timecop@0.36.0
├── tree-view@0.217.1
├── update-package-dependencies@0.12.0
├── welcome@0.36.4
├── whitespace@0.36.2
├── wrap-guide@0.40.2
├── language-c@0.58.0
├── language-clojure@0.22.2
├── language-coffee-script@0.48.7
├── language-csharp@0.14.2
├── language-css@0.42.2
├── language-gfm@0.89.0
├── language-git@0.19.1
├── language-go@0.44.0
├── language-html@0.47.2
├── language-hyperlink@0.16.1
├── language-java@0.27.1
├── language-javascript@0.126.1
├── language-json@0.19.1
├── language-less@0.32.0
├── language-make@0.22.3
├── language-mustache@0.14.1
├── language-objective-c@0.15.1
├── language-perl@0.37.0
├── language-php@0.38.0
├── language-property-list@0.9.1
├── language-python@0.45.2
├── language-ruby@0.71.0
├── language-ruby-on-rails@0.25.2
├── language-sass@0.59.0
├── language-shellscript@0.25.0
├── language-source@0.9.0
├── language-sql@0.25.5
├── language-text@0.7.2
├── language-todo@0.29.1
├── language-toml@0.18.1
├── language-xml@0.35.0
└── language-yaml@0.29.0

Community Packages (127) /Users/crucial/.atom/packages
├── MagicPython@1.0.10
├── Zen@0.18.0
├── advanced-open-file@0.16.6
├── afterglow-monokai-syntax@1.3.5
├── archiver@0.0.0
├── atom-beautify@0.30.2
├── atom-ctags@5.1.0
├── atom-dark-fusion-syntax@2.2.0
├── atom-django@0.3.2
├── atom-easy-jsdoc@4.12.1
├── atom-fuzzy-grep@0.16.0
├── atom-material-syntax@1.0.6
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.0.4
├── atom-terminal@0.8.0
├── atom-ternjs@0.18.3
├── auto-update-packages@1.0.1
├── autocomplete-paths@1.0.5
├── browser-plus@0.0.96
├── busy@0.7.0
├── clipboard-plus@0.5.1
├── color-picker@2.2.5
├── copy-as-rtf@0.9.3
├── cursor-history@0.11.1
├── custom-title@1.0.1
├── dash@1.7.1
├── devdocs@0.2.1
├── django-templates@0.5.0
├── docblockr@0.10.3
├── editorconfig@2.2.2
├── emmet@2.4.3
├── envy-theme@0.1.1
├── find-and-replace-under-cursor@0.3.0
├── find-selection@0.16.0
├── fizzy@0.21.0
├── focus-dark@1.2.0
├── focus-light@1.2.0
├── fold-navigator@0.0.618
├── freshcut-theme@0.3.0
├── git-plus@7.9.3
├── git-time-machine@1.5.9
├── graphite-ui@0.15.1
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── hip-light-ui-theme@1.1.1
├── isotope-ui@2.8.5
├── jumpy@3.1.3
├── keybinding-cheatsheet@0.1.1
├── language-babel@2.66.0
├── language-cmake@0.3.0
├── language-crontab@1.0.0
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-jade@0.7.2
├── language-lua@0.9.11
├── language-markdown@0.23.0
├── language-nginx@0.8.0
├── language-ocaml@1.9.5
├── language-restructuredtext@1.1.0
├── language-rust@0.4.10
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── lines@0.13.1
├── linter@2.2.0
├── linter-csslint@1.3.4
├── linter-eslint@8.2.1
├── linter-flake8@2.2.1
├── linter-htmlhint@1.3.3
├── linter-json-lint@0.1.2
├── linter-pylama@0.9.3
├── linter-sass-lint@1.7.4
├── markdown-folder@0.5.0
├── markdown-preview-enhanced@0.13.0
├── markdown-preview-plus@2.4.9
├── markdown-themeable-pdf@1.2.0
├── markdown-writer@2.6.5
├── maximize-panes@0.2.0
├── merge-conflicts@1.4.5
├── move-panes@0.2.0
├── navigate@0.1.17
├── npm@2.0.0
├── npm-docs@0.2.0
├── nucleus-dark-ui@0.12.3
├── nuclide@0.232.0
├── nuclide-format-js@0.0.36
├── octocat-syntax@1.3.1
├── open-in@4.0.0
├── open-in-sourcetree@0.1.8
├── open-terminal-here@2.3.0
├── open-this@0.4.0
├── package-cop@0.2.10
├── pain-split@1.4.0
├── pandoc-convert@1.1.0
├── pane-layout-plus@0.7.3
├── pdf-view@0.59.0
├── pigments@0.39.1
├── postcss-sorting@2.10.0
├── prettier-atom@0.33.0
├── preview@0.17.0
├── processing-language@0.2.0
├── project-manager@3.3.5
├── python-tools@0.6.9
├── quick-file-actions@0.2.0
├── quote-words@0.2.0
├── railscast-theme@0.3.0
├── react-es6-snippets@0.3.0
├── react-snippets@0.8.0
├── recent-files-fuzzy-finder@0.3.2
├── regex-railroad-diagram@0.17.0
├── release-notes@0.53.0
├── schelp-syntax@0.6.3
├── script@3.15.0
├── set-syntax@0.3.2
├── show-in-system@0.4.0
├── sort-lines@0.14.0
├── string-case@0.1.0
├── supercollider@0.8.2
├── symbol-gen@1.3.1
├── tab-control@0.6.10
├── tab-switcher@1.5.4
├── toggle-quotes@1.0.1
├── tomorrow@1.0.0
├── tool-bar@1.1.0
├── unity-ui@2.1.11
├── vim-mode@0.66.0
├── vim-mode-plus@0.93.0
└── zentabs@0.8.8

**Comment by crucialfelix** [comment]
Disabling nuclide and then re-enabling managed to clear them out. It was a serious performance drag.

**Comment by jgebhardt** [comment]
👍  @crucialfelix note that Nuclide didn't fully support Atom 1.18 at the time, which was likely the cause here.
