### ISSUE TITLE
Where are 0.233.0 0.234.0 and 0.236.0 -- no updates in Atom

### ISSUE THREAD

**Issue by hmeerlo** [facebook/nuclide#1221]
### Issue and Steps to Reproduce
Running the check for updates in Atom reports that my 0.232.0 is the latest version. 

```
$ apm install nuclide@0.236.0
Installing nuclide@0.236.0 to /Users/hermanmeerlo/.atom/packages ✗
Package version: 0.236.0 not found
```

The same for 0.233.0 and 0.234.0 which according to the releases page have been released. So there seems to be a problem with the repository?

### Expected Behavior
Upgrade to latest and greatest so I'm not reporting old bugs.

### Actual Behavior
0.232.0 is reported as latest

### Versions
* Atom: 1.18.0
* Nuclide: 0.232.0 :-(
* Client OS: macos 10.12.5
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (22) /Users/hermanmeerlo/.atom/packages
├── MagicPython@1.0.10
├── file-icons@2.1.8
├── git-blame@1.1.1
├── git-plus@7.9.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.66.0
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.10
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── local-history@4.3.0
├── merge-conflicts@1.4.5
├── nuclide@0.232.0
├── nuclide-format-js@0.0.36
├── prettier-atom@0.34.0
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.1.0

**Comment by mostafaeweda** [comment]
I'm sorry we missed publishing the `apm` pieces of the release (we're getting that fixed now).
We just published the 0.236.0 and you should be good to go.
