### ISSUE TITLE
can't use react native debug in latest Nuclide 0.236.0

### ISSUE THREAD

**Issue by davidtan2008** [facebook/nuclide#1223]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
when I update Nuclide version to the latest 0.236.0, the Start Debugging option in Atom->Nuclide-> React Native disappear. 

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom: 1.18.0 X64
* Nuclide:  0.236.0
* Client OS: OS X El Capitan 10.11.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── js-hyperclick@1.11.0
└── nuclide@0.236.0

**Comment by davidtan2008** [comment]
React Native debugger support was dropped by fccd95d
We intend to bring a better one back in the future

**Comment by trinode** [comment]
Hi, I'm new to nuclide but I just spent hours trying to figure out why I couldn't get this working (having seen the feature on blogs etc), eventually came across this closed issue, is there any chance a note could be added to the readme or something to say it's removed? (lack of mentions didn't really help me find it was temporarily gone, all my googling just took me to pages showing how to use it, so I ended up trying to find out why the debug item was missing from the menu, started looking for missing packages etc...)
