### ISSUE TITLE
Reveal File on Switch should allow to 1 click to collapse folder

### ISSUE THREAD

**Issue by jepezi** [facebook/nuclide#1227]
### Issue and Steps to Reproduce
Reveal File on Switch should allow to 1 click to collapse folder.

On Nuclide 0.236.0 mac with this setting.
<img width="540" alt="screen shot 2560-07-07 at 9 22 01 am" src="https://user-images.githubusercontent.com/172099/27940623-f0109c76-62f5-11e7-9e0d-9a7e301102f3.png">

On next screenshot, `PostList.js` is currently active. Now when I click on `web` folder to collapse, it doesn't collapse the folder. Instead, the focus moves back to `PostList.js` again. It does collapse when I click `web` again the 2nd time.

![jump](https://user-images.githubusercontent.com/172099/27940762-eae733f8-62f6-11e7-8717-d39dda7459cf.gif)

### Expected Behavior
It should let me collapse the folder the first time I click `web`. Actually it I click to expand other folder, it also jumps back to `PostList.js` while expanding the folder. 

### Actual Behavior
Mentioned above, the focus in file tree moves back to active file when collapsing/ expanding folder.

### Versions
* Atom: 1.18.0 x64
* Nuclide: 0.236.0
* Client OS: mac

### Additional Details
* Installed packages (`apm ls --installed`):

```
$ apm ls --installed
Community Packages (32) /Users/jirat.a/.atom/packages
├── MagicPython@1.0.10
├── atom-jest-snippets@1.1.1
├── atom-react-snippets@0.2.2
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── duplicate-line-or-selection@0.9.0
├── emmet@2.4.3
├── fonts@3.0.2
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── intentions@1.1.2
├── language-babel@2.66.1
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.11
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── lint@0.0.1
├── linter@2.2.0
├── linter-eslint@8.2.1
├── linter-ui-default@1.6.2
├── merge-conflicts@1.4.5
├── nuclide@0.236.0
├── nuclide-format-js@0.0.36
├── pigments@0.39.1
├── prettier-atom@0.36.0
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── tool-bar@1.1.0
└── vim-mode-plus@0.93.0
```

**Comment by shushz** [comment]
Yes, it's a regression. It's fixed already by https://github.com/facebook/nuclide/commit/53a3fb815a5abcad964e3bc049e058e12c433085
and will be available in the next week's release.

Thanks for reporting!

**Comment by shushz** [comment]
BTW. A single click on a directory will select that directory, but a single click on the arrow left of it will collapse it.
