### ISSUE TITLE
Unable to use nuclide debugger for nodejs 

### ISSUE THREAD

**Issue by lorixx** [facebook/nuclide#1229]
### Issue and Steps to Reproduce

I wanted to use the default debugger to debug nodejs app since the UI and UX from Nuclide is much better and easier to use. However, I did try the following steps:

1/ Run command "node --debug=5858 server.js" to start my nodejs app.
2/ Go to my Atom editor and open the debugger view on Nuclide, click "Attach debugger" and select the 'node' application from the list.
3/ It saids "Successfully attached process. Debugger paused at thread(701916) because of: signal SIGSTOP".
4/ I added a few breakpoints in my nodejs app, and refresh the related website, but those breakpoints are never got triggered.

I was looking at the https://nuclide.io/docs/features/debugger/ and the image shows that javascript debugging works for Nuclide: https://nuclide.io/static/images/docs/feature-debugger-evaluation-ex.png

### Expected Behavior
The breakpoints should be triggered and functional for debugging.

### Actual Behavior
Nothing is triggered and the nodejs app seems to continue running.

### Versions
* Atom: 1.18.0
* Nuclide: 0.236
* Client OS: mac OS High Sierra
* Server OS (optional):

**Comment by rightparen** [comment]
@lorixx thanks for reporting!  I suspect that when you attached to the process, Nuclide was debugging native code rather than Javascript.

Because usage of the Javascript debugger was so low relative to support costs, Javascript debugger support was removed from Nuclide.  The picture you mention is a documentation bug.

Sorry I don't have a more helpful answer here.

**Comment by jasonmevans** [comment]
I'm running into the same problem, and I'd love to be able to have Node debugging in Atom using Nuclide. :(

**Comment by alflennik** [comment]
The popularity of VS Code (which provides debugging support as its killer feature) suggests that the lack of use may be due to difficulty with setup, not a lack of demand. It saddens me that so many languages are supported this super popular language is not.

**Comment by pelmers** [comment]
Actually we have a Node debugger now (and have for several months)! It looks like the docs aren't updated but it supports both Launch and Attach entry points. Just use the 'start debugging' button and select the Node tab.
