### ISSUE TITLE
Humongous tooltips in nuclide-type-hint-overlay

### ISSUE THREAD

**Issue by phorust** [facebook/nuclide#123]
Not sure if this is Nuclide specific or Atom related, but when I hover over large JSON, Nuclide will make a `<div class="nuclide-type-hint-overlay" />` with my Object's keys and the values as their types, like Flow type annotations. The problem with this is that it does it for any and all Objects, regardless of size, so editing large static JSON files is a pain.

I tried reproducing this locally but it seems to only work when I'm using my remote development server.

Is there an option to turn this off, or maybe limit tooltips to Objects that have reasonable size for display on the screen?

**Comment by nmote** [comment]
There is an option in the `nuclide-flow` package to disable typehints.

Admittedly, the typehints UI could also use some work, but hopefully that option is enough to keep you productive for now.

**Comment by phorust** [comment]
I've taken to hiding my large static JSON as inactive tabs, as I'd rather not disable typehints entirely. Agreed, there must be a nicer way of achieving this. Maybe `...` if the tooltip becomes too long, and allow the user to hover over `...` to see the rest of the tooltip?

**Comment by nmn** [comment]
Could either of you tell me if you did anything special when installing Nuclide to get tool-tips working? Any dependencies? I have not been able get tooltips working at all.

**Comment by phorust** [comment]
Unfortunately I didn't do anything special to get type hints working. I
think it depends on flow - check if your flow is installed and working?

On Thursday, July 9, 2015, Naman Goel <notifications@github.com> wrote:

> Could either of you tell me if you did anything special when installing
> Nuclide to get tool-tips working? Any dependencies? I have not been able
> get tooltips working at all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/nuclide/issues/123#issuecomment-120087308>.
>


-- 

Kevin Lee
UC Berkeley | Class of 2016
(650)804-1866

kevinmlee.io

**Comment by nmn** [comment]
@phorust Flow works just fine for me. I get linting errors and autocomplete, but not typehints. Just wanted to make sure there wasn't a dependency I was missing.

**Comment by nmote** [comment]
Just to update you on this -- we are planning to display type hints as trees. If you are interested you can check out dd74d1830767a5e9be55d7a01243c2d0004149f0, where I added the ability for Flow type hints to be structured as a tree. @jgebhardt is planning to do the UI to make these trees navigable when he gets a chance.

Once we have this done, large type hints will start out small, but you will be able to navigate through them if you like. I think this will provide the level of detail we want without getting in the way.

**Comment by phorust** [comment]
Cool - I actually ceased using nuclide due to issue #84, but definitely still a fan of the project. I'll take another look at it when it works again for me.

**Comment by nmote** [comment]
Addressed by some recent UI work
