### ISSUE TITLE
Nuclide settings not visible

### ISSUE THREAD

**Issue by SimerdeepSinghPopli** [facebook/nuclide#1230]
I recently installed nuclide package in atom ,but I am not able to see any nuclide tab in toolbar or able to see settings in package settings .  What I am missing ? 

Atom version : 1.18
OS - Windows 10
![screenshot 3](https://user-images.githubusercontent.com/30016720/27992003-c2b63814-64a6-11e7-80a7-ac39851ea5ba.png)
![screenshot 4](https://user-images.githubusercontent.com/30016720/27992007-dce6253c-64a6-11e7-8339-dfe77062d97a.png)
![screenshot 5](https://user-images.githubusercontent.com/30016720/27992008-dce63ed2-64a6-11e7-8f8a-ea61e68926d0.png)

**Comment by arufian** [comment]
I got this too. Is this something wrong with the Atom editor or Nuclide installation ?

**Comment by shushz** [comment]
Could you please list the installed packages? The output of `apm list`. The `apm` is Atom's package management command that should have been installed automatically when you've installed Atom.

And if possible, attach Nuclide client log file - it should be at <system temp dir>\nuclide-%USER%-logs\nuclide.log

**Comment by matthewwithanm** [comment]
This has been reported by other Windows users but we haven't had time to look at it yet. I'm going to try to download a VM and take a look.

**Comment by matthewwithanm** [comment]
@SimerdeepSinghPopli @arufian Also, do you see anything in the Dev Tools console? (View > Developer > Toggle Developer Tools)

**Comment by arufian** [comment]
@matthewwithanm @SimerdeepSinghPopli @shushz 
I have solved this issue, I think it's a bug on Atom side.

![bug-atom](https://user-images.githubusercontent.com/480889/28063637-f5aaaf78-665b-11e7-9bb8-97e353bb120c.png)

See the red bug on the down left side of the screen, I clicked this and rebuild my Atom.
Then nuclide will be work as expected.
Cheers.

**Comment by SimerdeepSinghPopli** [comment]
Thanks It worked
