### ISSUE TITLE
Tab switching with Ctrl+PageUp / Ctrl+PageDown does not work in 0.236

### ISSUE THREAD

**Issue by fsi** [facebook/nuclide#1231]
### Issue and Steps to Reproduce
I am used to switching to the next/previous tab in the editor with Ctrl+PageUp and Ctrl+PageDown combinations, which is a usual combination in browsers and editors alike. It used to work in atom editor with nuclide until I upgraded to nuclide 0.236.0

In it, coming from this particular commit, these keybindings are overriden to do the same as Ctrl+Home and Ctrl+End: https://github.com/facebook/nuclide/commit/b79fb35952386ee7b7f0933639e93fd6b5c81a44 

Steps to reproduce:
1. open a few files in different editor tabs
2. press ctrl+pagedown or ctrl+pageup

### Expected Behavior
Editor should switch to the next/previous tab

### Actual Behavior
Editor goes to the beginning/end of currently open tab

### Versions
* Atom: 1.18.0
* Nuclide: 0.236.0
* Client OS: linux
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── busy-signal@1.4.3
├── highlight-selected@0.13.1
├── intentions@1.1.2
├── language-babel@2.66.1
├── language-graphql@0.9.0
├── linter@2.2.0 (disabled)
├── linter-eslint@8.2.1
├── linter-ui-default@1.6.2
├── nuclide@0.236.0
├── nuclide-format-js@0.0.36
├── prettier-atom@0.36.1
├── set-syntax@0.3.2
└── tool-bar@1.1.0
```

To mitigate this I had to add this to my keymap.cson file:
```
$ cat ~/.atom/keymap.cson 
'.platform-win32 atom-workspace, .platform-linux atom-workspace':
  'ctrl-pageup': 'pane:show-previous-item'
  'ctrl-pagedown': 'pane:show-next-item'
```

**Comment by ebluestein** [comment]
@fsi thank you for the detailed report. This change was made to mimic the keybindings of the file tree in Windows Explorer, but I see that this conflicts with what people are used to in Chrome and other browsers.

We're going revert that change, look for this to be fixed in next week's release.
