### ISSUE TITLE
Nuclide doesn't support Git workspace change detection for remote projects

### ISSUE THREAD

**Issue by ZacharyEspiritu** [facebook/nuclide#1233]
### Issue and Steps to Reproduce
Nuclide doesn't seem to support Git well for remote projects. It doesn't update the "Uncommitted Changes" dropdown in the File Tree nor does it seem to be able to detect that the current remote project folder is a git repository in the Git or GitHub tab.

### Expected Behavior
The "Uncommitted Changes" dropdown in the File Tree and the Git/GitHub tab should detect and display Git workspace changes as if it was a local project folder.

### Actual Behavior
See above.

### Versions
* Atom: 1.18.0
* Nuclide: 0.236.0
* Client OS: macOS Sierra 10.12.5
* Server OS: Ubuntu 16.04.2 LTS

### Installed Packages
```
Community Packages (4) 
├── minimap@4.28.2
├── monokai-tweaked-syntax@0.3.0
├── nuclide@0.236.0
└── pigments@0.39.1
```

**Comment by aadisriram** [comment]
I just started hacking around this, i'll hopefully have it up and running soon. Will update once it gets going :)

**Comment by ArmandGrillet** [comment]
Hi @aadisriram, is there any updates regarding that issue?

**Comment by LLisa717** [comment]
Would love to see it coming :)

**Comment by matthiasludwig** [comment]
Is there any progress on this? I found #158 and #8207 and several other Open issues that relate to the general topic of better git integration.
Does anyone know if this is planned?

**Comment by ramachandranj** [comment]
any updates on this ?

**Comment by hiraksarkar** [comment]
Any update on this ?

**Comment by cspeidel** [comment]
@aadisriram same here. any status?

**Comment by LaCocoRoco** [comment]
Any update on this?

**Comment by aadisriram** [comment]
I am extremely sorry for the lack of responses and updates here, this is unfortunately not on our roadmap, I did try to put in some effort into this but was unable to prioritize this.
