### ISSUE TITLE
Tree view panel is not resizable

### ISSUE THREAD

**Issue by daveysigma** [facebook/nuclide#1234]
Tree view is not resizable on macOS (unless first tab is not a code window! if the first tab i.e. adjacent to the tree view in the next tab group is settings then you can resize)

### Expected Behavior
you should always be able to resize the tree view

### Actual Behavior
the sideways-move cursor is shown but the tree view tab cannot be resized.

### Versions
* Atom: 1.18
* Nuclide: 0.236
* Client OS: macOS 10.12.5
* Server OS (optional):

### Additional Details
├── MagicPython@1.0.10
├── aligner@1.2.3
├── aligner-javascript@1.2.0
├── atom-beautify@0.30.3
├── atom-html-preview@0.1.22
├── atom-ternjs@0.18.3
├── autocomplete-modules@1.6.10
├── browser-plus@0.0.97
├── busy-signal@1.4.3
├── color-picker@2.2.5
├── docblockr@0.10.5
├── expose@0.14.0
├── file-icons@2.1.8
├── fonts@3.0.2
├── git-diff-details@1.4.0
├── goto@1.8.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── intentions@1.1.2
├── language-babel@2.66.1
├── language-docker@1.1.8
├── language-elm@1.5.0
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.11
├── language-spacebars@0.2.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0
├── linter-docker@0.2.0
├── linter-eslint@8.2.1
├── linter-js-yaml@1.2.7
├── linter-stylelint@3.10.0
├── linter-ui-default@1.6.2
├── markdown-toc@0.4.2
├── minimap@4.28.2
├── minimap-autohide@0.10.1
├── minimap-pigments@0.2.2
├── monokai-seti@0.9.0
├── nuclide@0.236.0
├── nuclide-format-js@0.0.36
├── open-recent@5.0.0
├── open-terminal-here@2.3.0
├── pigments@0.39.1
├── platformio-ide-terminal@2.5.3
├── printer-paper-syntax@1.0.2
├── react@0.16.2
├── release-notes@0.53.0
├── remote-sync@4.1.5
├── set-syntax@0.3.2
├── sort-lines@0.14.0
├── sync-settings@0.8.2
├── tabs-to-spaces@1.0.3
├── tidy-tabs@0.4.0
├── toggle-quotes@1.0.1
├── tool-bar@1.1.0
└── zebra-stripes@1.2.1

**Comment by matthewwithanm** [comment]
Hey @daveysigma! Any chance you can make a video showing this? I can't repro.

**Comment by daveysigma** [comment]
it seems to have resolved itself.  probably another plugin breaking something
