### ISSUE TITLE
Make flow-language-server an open-source project and support atom-languageclient

### ISSUE THREAD

**Issue by zaaack** [facebook/nuclide#1236]
Nuclide is a little heavy for people not working at Facebook, and atom-languageclient +atom-ide-ui is a more hackable and lightweight way for IDE support in Atom, if flow-language-server can support atom-languageclient, then we get a lightweight and full-featured flow support immediately!

**Comment by wbinnssmith** [comment]
Your timing is pretty coincidental! We just open-sourced both [`flow-language-server`](https://github.com/flowtype/flow-language-server) and [`ide-flow`](https://github.com/flowtype/ide-flow) (not yet in the atom package installer, but you can apm install it).

We'd love contributions or ideas if you've got them!
