### ISSUE TITLE
nuclide server on windows server speciefied path ont found

### ISSUE THREAD

**Issue by fugitifx** [facebook/nuclide#1239]
### Issue and Steps to Reproduce
i install nodejs on windows servser 2012 r2, and install innpm -g nuclide and have an atom with nuclide install on my pc. When i try to connect to a remote project, i always have an error command nuclide-start-server not found. We use Cygwin for the ssh access cause i could'nt find SSH Daemon for windows

### Expected Behavior
can connect to my remote server

### Actual Behavior
can't connect to the server because of that command

### Versions
* Atom:1.18.0
* Nuclide:0.239
* Client OS:Windows 10
* Server OS (optional):Windows server 2012 r2

**Comment by ebluestein** [comment]
Sorry @fugitifx , Nuclide server is not supported on Windows at this time. The startup scripts and server itself have many dependencies on *nix that have not been ported over to Windows yet.
