### ISSUE TITLE
Provide feedback during installation

### ISSUE THREAD

**Issue by Adam-Meisen** [facebook/nuclide#125]
Platform: Windows 8.1

I installed nuclide yesterday, first through the atom gui, restarted atom, and left it running for an afternoon. Since node was using an abnormally high amount of CPU, I assumed it was downloading and transpiling nuclide packages. However, after restarting atom again and filtering packages by "nuclide", I only saw nuclide-installer, nuclide-hack, and nuclide-type-hint. I've uninstalled, then reinstalled it from command line today with apm. Node is currently using a high amount of CPU again, but I have no way of knowing what it's doing, or if it's encountering any errors.

**Comment by nmn** [comment]
There are packages in Nuclide that don't work on Windows. Flow for example only works on OS X and Linux systems. That may be causing some issues.

Further, did you install the packages using the atom UI or with apm ?

Use APM to install all Nuclide-* packages before you open up atom and you should see better results. Atom itself has some serious issues when you open up the settings screen.

**Comment by ssorallen** [comment]
As of yesterday's release of v0.111.0, Nuclide is a single package and has the same installation process as other Atom packages. Please try `apm install nuclide`.

http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
