### ISSUE TITLE
Latest version 0.242 break react native support

### ISSUE THREAD

**Issue by nicodmf** [facebook/nuclide#1252]
### Issue and Steps to Reproduce
Install nuclide 0.230.0 -> react inspector works
Install nuclide latest 0.242 -> react inspector don't work

### Expected Behavior
react inspector works

- the react native debugger could works too. Now the only correct debugger is in visual studio, when i see microsoft and his history, would prefer a nuclide support.

**Comment by ebluestein** [comment]
Sorry, this is by design. There were significant issues with the Nuclide react debugger and we decided to remove it for now since it was broken and not actively supported. We will look into re-adding this functionality in the future.
