### ISSUE TITLE
File tree visual defect with scrollbars on 1.19

### ISSUE THREAD

**Issue by awilkins** [facebook/nuclide#1253]
### Issue and Steps to Reproduce

Start Atom 1.19.x with Nuclide installed and the file tree showing.

### Expected Behavior

Should fit with the actual Atom style.

### Actual Behavior

Looks like this : 

![image](https://user-images.githubusercontent.com/368399/28768405-6748f45a-75cf-11e7-9d49-395667509a83.png)

### Versions

* Atom: 1.19.0-beta5
* Nuclide: 0.242.0
* Client OS: Ubuntu

### Additional Details

* If you fold and then unfold the "Folders" node it fixes the appearance.

**Comment by shushz** [comment]
Sadly, I don't think it's Atom 1.19 to blame. This was the issue with scroll bars for quite some time. In my experience it shows when you're moving from just using a laptop screen to an external monitor and reload (Cmd-Opt-Ctrl-L) usually fixes this.

Anyway, it's not Nuclide specific, more likely Atom-wide.

**Comment by awilkins** [comment]
Doesn't seem to be Atom-wide - doesn't happen with the core File Tree plugin, not seen it in any other panel.

If you start Atom with `--clear-window-state` it doesn't happen.

Also only happens in the "Folders" expansion, not in "Uncommitted Changes" or "Open Files".

If it's an Atom bug, something about the "Folders" region is triggering a real edge case.

**Comment by ali-master** [comment]
Hi @awilkins 
For resolving this problem, you should _Disable\Enable_ the **tree view** atom native package.then resolved this problem.

**Comment by awilkins** [comment]
That doesn't seem to work - Nuclide disables the native tree view anyway.

You can get it to resolve the issue temporarily by enabling the native tree view, then switching to that tab, and then back again, for the same reason I presume that folding / unfolding the "Folders" region in the Nuclide tree works - it redraws that element and the styles are actually applied.

**Comment by shushz** [comment]
@hansonw has fixed this in 0a860a29acfa7ee4294907b92c658aa88b3be92e! The fix should be available in the next release.

**Comment by awilkins** [comment]
@hansonw Nice detective work there ; props to you for knowing how to fix it as well.
