### ISSUE TITLE
Nuclide won't starts after installing the package in Atom

### ISSUE THREAD

**Issue by jtz-ar** [facebook/nuclide#1258]
### Issue and Steps to Reproduce
Nuclide won't start.

### Expected Behavior
The install instructions of Nuclide says that after installing the package, if I start Atom, Nuclide will open.
The expected behavior is that when I open Atom, nuclide will start. 

### Actual Behavior
Package nuclide is installed. Package is enabled. When I start Atom, the welcome screen is Atom, not Nuclide

### Versions
* Atom: 1.18.0 x64
* Nuclide: 0.243.0
* Client OS: windows 10
* Server OS (optional): not installed

### Additional Details
* Installed packages (`apm ls --installed`):

C:\Users\Jorge>apm ls --installed
Community Packages (1) C:\Users\Jorge\.atom\packages
└── nuclide@0.243.0

thank you very much!

**Comment by Rebsos** [comment]
Same Problem. Log:
```
Failed to require the main module of 'nuclide' because it requires one or more incompatible native modules (ctags, ctags, ctags, ctags, ctags, ctags, ctags, ctags, ctags, ctags, ctags, ctags, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, fuzzy-native, pty, pty, pty, pty, pty, pty, pty, pty, pty, pty, pty, pty).
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

**Comment by tommynsong** [comment]
same problem here as well, everything there's a new update, i have to rebuild the package.
already went through reset Atom to known good state.

**Comment by lewisl9029** [comment]
I started getting the same error in the console as @Rebsos after upgrading from 0.243.0 to 0.245.0. I also tried installing 0.244.0 manually and that didn't work either. Reverted back to 0.243.0 for now, which seems to be working fine here. I'm on Atom 1.19.2.

**Comment by ernanielyjr** [comment]
This works for me:
- In status bar (right bottom), click on "bug" icon
- Click in button "rebuild"
- Reload Atom.

**Comment by jtz-ar** [comment]
Thank you ernanielyjr!! It worked.

**Comment by tommynsong** [comment]
the "rebuild" works, however, if one of the package got updated, we have to rebuild it again after reload. is that the expected behavior?

**Comment by ajeets1978** [comment]
Ctr + Shift + H in Mac worked for me
