### ISSUE TITLE
How to format code?

### ISSUE THREAD

**Issue by michaellee8** [facebook/nuclide#1263]
How to format code?

**Comment by hansonw** [comment]
The shortcut for code formatting is cmd-shift-C (or find it in the command palette, cmd-shift-P, under "format code"). You need to have a suitable provider installed, though - we'll use clang-format for C++ files or yapf for Python files, for example.

**Comment by michaellee8** [comment]
I have saw a nuclide-format-js package in nuclide that seems can be used for formatting jsx. I tried it by pressing ctrl+shift+i,  a dialog telling the formatting completed, but there are no actual effect to my code except there a require react added. How should it be configured to format?

**Comment by hansonw** [comment]
Oh dear - that package will be renamed soon - it actually only formats your requires.
If you want general JS formatting please check out https://atom.io/packages/prettier-atom! :)
