### ISSUE TITLE
Unknown directive "connection"

### ISSUE THREAD

**Issue by steida** [facebook/nuclide#1268]
`@connection(key: "Posts_allPosts") {` invokes error "Unknown directive "connection""

```jsx
export default createFragmentContainer(
  Posts,
  graphql`
    fragment Posts_viewer on Viewer {
      allPosts(first: $first, orderBy: createdAt_DESC)
        @connection(key: "Posts_allPosts") {
        edges {
          node {
            id
            ...Post_post
          }
        }
      }
      # To understand what's happening here:
      # Post_viewer fragment will be attached to viewer.__fragments for Post.js
      ...Post_viewer
    }
  `,
);
```

**Comment by steida** [comment]
https://github.com/rmosolgo/language-graphql/issues/15#issuecomment-323230261

**Comment by steida** [comment]
@kassens any idea please?

**Comment by kassens** [comment]
Passing this to @asiandrummer, what's the recommendation to make language server recognize the Relay or other custom directives?

**Comment by asiandrummer** [comment]
@kassens @steida my official recommendation for now is to include them in the `.graphqlconfig` file:
```
{
  "extensions": {
    "customDirectives": [
      "directive @connection(key: String!, filters: [String]) on FIELD",
      // ...
    ]
  }
}
```
Although I think the language service should just hard-code them in the implementation...

**Comment by steida** [comment]
@asiandrummer It seems like a workaround. ETA for fix pls?

**Comment by asiandrummer** [comment]
@steida I'd say using `.graphqlconfig` to specify the custom directive is a valid fix as of now. We're discussing the possibility to embed the custom directives used in Relay in the language server, but it won't be anytime soon I presume.

**Comment by steida** [comment]
Thank you. It works.

https://github.com/este/este/blob/3d475cd38a2cb507f1fdb0f3439a9e17d4d2efe4/.graphqlconfig
