### ISSUE TITLE
Python version mismatch 

### ISSUE THREAD

**Issue by Venkat5694** [facebook/nuclide#1273]
### Issue and Steps to Reproduce
Documentation specifies that python 2.6 or higher is required to run nuclide-server but the file `nuclide-start-server` has `python2.7` in it.

### Expected Behaviour
Python version should be updated to `python 2.6` from `python 2.7` or the docs should be updated accordingly.

### Actual Behavior
The server does not start when the installed python version is 2.6

### Versions
* Atom: 1.17.2
* Nuclide: 0.236.0
* Client OS: OSX Sierra
* Server OS (optional): Linux

**Comment by ebluestein** [comment]
Thanks for the report! This will be fixed in the documentation in next week's release.
