### ISSUE TITLE
Does nuclide have a good autoComplete plugin?

### ISSUE THREAD

**Issue by xclidongbo** [facebook/nuclide#1287]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

For example, When I use 'Scrollview', the `showsHorizontalScrollIndicator` property name is too long and inconvenient

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom: 1.19.0
* Nuclide: 0.245.0
* Client OS: macOS
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by wbinnssmith** [comment]
Hi @xclidongbo -- based on the context it looks like you're using Nuclide for Objective-C or Swift development.

Nuclide integrates with clang to offer autocomplete suggestions for Objective C, and does the same with the Swift compiler.

If you're using Objective-C, make sure you have clang installed and Nuclide should offer completions.

**Comment by xclidongbo** [comment]
@wbinnssmith   I'm a  developer for iOS. But, I want to develop a app with React Native. Atom+nuclide. Code hints are too crude.React native's API does not prompt.

**Comment by wbinnssmith** [comment]
@xclidongbo if that's the case, you should definitely check out our [page on React Native features in Nuclide](https://nuclide.io/docs/platforms/react-native/).

As you might know, JavaScript is a dynamically typed language and it's difficult to build tools that offer accurate insight without explicit type structures and annotations. 

Nuclide has fantastic integration with [Flow](https://nuclide.io/docs/languages/flow/), which will give you suggestions, diagnostics, and other Nuclide features right in the editor.

If you don't want to use flow, there are plenty of [react native](https://atom.io/packages/search?utf8=%E2%9C%93&q=keyword:react-native) and [JavaScript](https://atom.io/packages/search?utf8=%E2%9C%93&q=javascript&commit=Search) packages for Atom that you'll find useful.

I'm going to close this for now, but if you have questions not addressed on the Nuclide documentation, let me know!

**Comment by xclidongbo** [comment]
Thx
