### ISSUE TITLE
[Feature] Highlighting linked files in the file tree

### ISSUE THREAD

**Issue by awilkins** [facebook/nuclide#1307]
Use case ;

As a developer, when I edit a tree node that is a softlink, I would like the tree to also highlight the file that the link targets, in order to promote awareness of the code I am editing.

As a developer, when a tree node is highlighted that is the target of softlinks that are also represented by tree nodes, I would like the tree to highlight these nodes in order to promote awareness of the code I may be affecting.

**Comment by shushz** [comment]
The file-tree's backing data structure is pretty complex and large (Nuclide is built and targeted to support huge repositories of tenths and hundreds of thousands of files).
I'm reluctant adding more properties to it if it will not be used in a significant percentage of cases.

I don't think softlinks within a repo is a case common enough to justify the extra cost.
Sorry.
