### ISSUE TITLE
Nuclide opens hundreds of `ocamlmerlin-server` processes while typing

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [facebook/nuclide#1314]
Typed up this entire Issue, then got a kernel-panic. Gonna keep it brief.

<img width="845" alt="screen shot 2017-09-29 at 11 05 46" src="https://user-images.githubusercontent.com/200/31025733-525b6e7e-a509-11e7-9176-3f6eee89c2d4.png">

Brand-new installation of Atom, Nuclide, OCaml, and Merlin (I'm a new user of all of the above.)

### Versions
* Atom: **1.20.1**
* Nuclide: **0.245.0**
* Client OS: macOS **10.13 High Sierra** Beta (17B25c)

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (17) /Users/ec/.atom/packages
├── MagicPython@1.0.12
├── file-icons@2.1.12
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.74.4
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.245.0
├── nuclide-format-js@0.0.41
├── set-syntax@0.4.0
├── sort-lines@0.15.0
└── tool-bar@1.1.0
```

**Comment by jgebhardt** [comment]
Nuclide v0.245 is about 12 releases / 10 weeks behind; does this still repro for you after upgrading to the current version?

**Comment by ELLIOTTCABLE** [comment]
Strange, @jgebhardt — I seem to be unable to upgrade Nuclide. Atom dies, without an error, when updating should ‘complete’ — then I get #271 upon manually re-launching it. (Maybe this is related to my other issue, #1315?)

Having done so, however, *does* fix this issue!

Thanks for the note — I hadn't even noticed that it was out-of-date (and I can't fathom why `apm` installed an out-of-date version — as said above, I'd installed it for the first time shortly before opening this Issue.)
