### ISSUE TITLE
nuclide/quick-open standalone

### ISSUE THREAD

**Issue by SavePointSam** [facebook/nuclide#1333]
I've seen reference to Nuclide's packages being available individually in the past, but everything was brought together for very good reasons. I'm curious with the new atom-ide project, could quick-open be made available as a stand along package. It's my favorite feature of nuclide, but there is also a bunch of things I don't need / use in Nuclide.

It would be wonderful to install it by itself. I expect this won't be possible, nor will it be supported, given Nuclide's past. Given that outcome, is there any plans to add it to atom-ide soon?

**Comment by Goom11** [comment]
We like the idea. Stay tuned.
