### ISSUE TITLE
no lint errors on a fresh install

### ISSUE THREAD

**Issue by naartjie** [facebook/nuclide#134]
I just installed `nuclide-installer` on a vanilla atom `1.0.0`. I couldn't see any flow errors until I installed `linter`. If this is needed to get flow messages showing can we add it to the README somewhere?

Also, I am confused about whether I should install `linter` or `linter-plus`? #106 #97

**Comment by ssorallen** [comment]
The optional "linter" package is called out in the docs under [Building from Source](http://nuclide.io/docs/setup/#building-from-source), but it is admittedly difficult to parse. The visibility of could be improved on that page, and it makes sense to add the package to the README as well.

The "linter-plus" package has been superseded by the "linter" package, the former is now defunct.

**Comment by naartjie** [comment]
Thanks @ssorallen. Should I do a PR for the docs, or do you guys have plans for this already?

**Comment by ssorallen** [comment]
There's no immediate plan to add improve the docs concerning "linter". A PR would be great and much appreciated. :+1:

**Comment by naartjie** [comment]
Thanks, here's the PR #135.
