### ISSUE TITLE
Outline view: focus search and keyboard navigation

### ISSUE THREAD

**Issue by ericbiewener** [facebook/nuclide#1342]
The outline view generally needs more keyboard support so that it can be used quickly without a mouse. I see two main things that are needed:

1. Focus the search field automatically when opening the outline view, and add a keyboard shortcut for focusing it when already open.
2. Add the ability to navigate the outline with arrow keys, and select one of the items with Enter.

**Comment by Goom11** [comment]
Thanks for the suggestions, stay tuned!
