### ISSUE TITLE
Setting up a simple Cmake C++ project with Nuclide

### ISSUE THREAD

**Issue by sonicdebris** [facebook/nuclide#1353]
Hello, I am testing Nuclide for c++ development with Cmake on Linux. 
I created a simple project, just a hello world cpp file with a simple `CmakeLists.txt`:
```
cmake_minimum_required (VERSION 3.9.1)
project (HELLO)
add_executable (hello-cmake hello.cpp)
```
The project builds and runs fine from command line:

```
-- The C compiler identification is Clang 4.0.1
-- The CXX compiler identification is Clang 4.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sd/hello-cmake
```
I also generate `compile_commands.json` using cmake, as needed by Nuclide:
```
[{
  "directory": "/home/sd/hello-cmake",
  "command": "/usr/bin/c++      -o CMakeFiles/hello-cmake.dir/hello.cpp.o -c /home/sd/hello-cmake/hello.cpp",
  "file": "/home/sd/hello-cmake/hello.cpp"
}]
```
Then I open the project in Nuclide clicking on Add project folder.

When I try to build the project (clicking on the "Play" button in the toolbar), I get this error: 

`No task runner available for the current working root selected in file tree`,

and code completion doesn't work. What am I missing?

I am on Ubuntu 17.10, Atom 1.21.1, Nuclide 0.262.0, Cmake 3.9.1. 
I installed all the recommended packages for Nuclide.

**Comment by sonicdebris** [comment]
I symlinked `/usr/lib/llvm-4.0.0/lib/libclang.so.1` to `/usr/lib/libclang.so` and now code navigation and code completion work. 

Debugging still doesn't (`lldb` can't be found, even though it's installed). And I didn't understand how to build and run the executable from within the ide yet, clicking on the Play button won't work, with the message I indicated in my previous post. Is building and running of cmake projects from within Nuclide even possible?

**Comment by sunjay** [comment]
> I symlinked /usr/lib/llvm-4.0.0/lib/libclang.so.1 to /usr/lib/libclang.so and now code navigation and code completion work.

This was extremely helpful! Thank you!

**Comment by pelmers** [comment]
For c++ projects the task runner only supports Buck at the moment: https://nuclide.io/docs/features/task-runner/

However it exposes a simple Atom service that would be simple to extend! See the sample at https://github.com/facebook/nuclide/tree/master/pkg/sample-task-runner if you have interest in making a CMake task runner.

Closing because it seems the original issue is resolved.

**Comment by matanster** [comment]
I figured I'd comment here as it is more or less the same scenario. I'm lost on how to install buck for Nuclide's C++ support. Its mentioned it is a prerequisite, but the buck download page only mentions how to include it in development projects. I'll fetch my answer on the nuclide github repo ― thanks for all your support so far!

**Comment by matanster** [comment]
I do feel idiotic for asking this, but how on earth should I download buck such that nuclide can find it? [the installation page](https://jitpack.io/p/facebook/buck/buck-v2018.03.26.01.pex) shows how to get buck into a development project, whereas for nuclide I tend to think it is a different scenario ― having a global installation that nuclide would find. 

Or I'm not reading it right, especially this part near the bottom is incomprehensible to me:

> fetch https://jitpack.io/com/github/ /buck/ /buck- .pex

Could you please advice? Installing buck from source may seem at the moment broken...

**Comment by pelmers** [comment]
@matanster if you're on macos it looks like there's a package available. Otherwise I think you need to build buck from source. https://buckbuild.com/setup/getting_started.html

If you're looking to have C++ language feature support, then all you need is a compile_commands.json at the root of your project. If you use cmake then you can symlink it from your build folder.

Having buck is only necessary if you want to use the task runner toolbar (i.e. buttons to run, debug, test, etc.). With other build systems you'll have to trigger from a command line.

**Comment by matanster** [comment]
@pelmers thanks, but Ubuntu linux, and
https://github.com/facebook/buck/issues/1812#issuecomment-376053025 :(

**Comment by matanster** [comment]
Well managed to install buck finally. But I'm not sure how to make Nuclide actually use it. E.g. here's a project that builds with plain `make`: https://github.com/JohnLangford/vowpal_wabbit#compiling. When I open it in Atom with nuclide (and buck) installed, it doesn't seem to be able to find the declarations of symbols. While implying I should build the project with buck, I've no idea how to do that. Could you please advise?

**Comment by matanster** [comment]
Okay, I guess a project building with `make` cannot be fully used with nuclide, unless converted to a buck build. Am I right? is there any straightforward conversion script?

**Comment by sunjay** [comment]
I have had success with using [Bear](https://github.com/rizsotto/Bear) to generate the files that nuclide wants for projects built with make.

**Comment by matanster** [comment]
@sunjay this is very helpful. Any specific `bear` command, or is it enough to just have it generate the `compile_commands.json` file?

**Comment by sunjay** [comment]
I usually just run `bear make`. You can also do it with specific targets (e.g. `bear make foo`) if you need it to add more to the compile commands file.
