### ISSUE TITLE
Outline, Hyperclick and other features stop working

### ISSUE THREAD

**Issue by ssandler** [facebook/nuclide#1358]
### Issue and Steps to Reproduce
I'm trying out Nuclide for Hacklang development. The issue is that almost all of the features stop working shortly after startup. Hyperclick just becomes a spinning wheel, the same for the outline, and mousing over objects does not reveal their structure. This happens reliably, and restarting always fixes it for a bit. I checked the Nuclide console and the Atom console, and saw no log entries at all.

This does *not* impact type checker errors. Those always work.

### Expected Behavior
Hack support will either not fail, or will clean itself up quickly if it does.

### Actual Behavior
Once this error occurs, these features never work until a restart of Atom.

### Versions
* Atom: 1.21.1
* Nuclide: 0.262.0
* Client OS: macOS Sierra 10.12.6
* Server OS (optional): n/a

### Additional Details
* hhvm version info is below (I don't want to update this since I'm pinning it to the version used on our servers)
```
HipHop VM 3.21.0 (rel)
Compiler: remotes/origin/3.21.0-slack-0-g56483773e2edd9e61782f1901ce40e47959e71b8
Repo schema: 1381c379b9e7d8cd9efa2ce49aeb6f699919dc3a
```

**Comment by ljw1004** [comment]
@ssandler Thanks for reporting. What you've describe is actually just a small tip of the iceberg where the connection between Hack and Nuclide is inadequate. I've spent the past six months rewriting all of this connection code (inside both the Hack project and the Nuclide project). The resulting work is currently in beta-testing with a small group of users, and I'm expecting it to go out in the 3.23 hhvm release (Nov17).

* The new code has much better "connection health monitoring". If hh_server isn't responding to Nuclide for any reason, then it shows why.
* The new connection code is based on the standard "Language Server Protocol". That theoretically makes it easy to also do Hack development from other clients as well (such as VSCode, and plain vanilla Atom without the Nuclide package) although I haven't yet got around to writing extensions for them to support this.

So sorry to say that I don't think it's worth pursuing this issue in the current legacy hack/nuclide.


How to unblock you? Hmm... I'm not actually sure. I'm kind of hoping you can live with this unacceptable behavior for a few weeks longer...

**Comment by ssandler** [comment]
Thanks for the speedy response @ljw1004 ! That's great to hear, and yes I can wait a few weeks 😄 

Since you mentioned VScode... I was using VScode before trying this out, and wanted to switch over because the Nuclide toolset seems excellent. Pranay at Slack made a plugin for VSCode that works nicely and quite a few of us have been using it for Hack development for months. https://marketplace.visualstudio.com/items?itemName=pranayagarwal.vscode-hack. I'd be happy to put you in touch with him.

**Comment by ljw1004** [comment]
Thanks for the pointer. Actually we're going for a slightly different approach. The way Pranay's plugin works is when VSCode asks for something e.g. "please show me hover at line 15 column 23" then it invokes a command-line utility `hh_client --type-at-pos 15:23`.

What we're doing is making `hh_client lsp` itself a native speaker of LSP. This means we have the ability to report stuff out-of-band (i.e. not solely in response to a request from VSCode). So for instance when hh_server stops, or is restarted, or is busy doing a typecheck, then the editor will show that straight away and can offer a "[Restart]" button when needed.

It also means that our LSP adapter has much easier access to the internals of hh_server. I'll be working to get Hack doc-comments into hover and autocomplete next month.

**Comment by rightparen** [comment]
Closing issue at @ljw1004 's request.

**Comment by fredemmott** [comment]
@ssandler: you can experiment with this by:

```
brew unlink hhvm
brew install hhvm/hhvm-preview
```

Then change `getUseLspConnection()` in `~/.atom/packages/nuclide/pkg/nuclide-hack/lib/HackLanguage.js` to always return true (or Promise(true) depending on what version of nuclide you have)

We now have homebrew binaries for high sierra, but not sierra, so if you've not upgraded that'll be a slow build-from-source. I'll try to get sierra binaries/bottles up later today or tomorrow.

**Comment by fredemmott** [comment]
`disable_optional_and_unknown_shape_fields` in `experimental_options` will get you this - however, this is likely to give you other problems - e.g. dependencies that target 3.23+ may not be usable with this set.

**Comment by ssandler** [comment]
Thank you!! That worked. I'll switch over to 3.23 full time so I can try out the LSP changes.

I did have to `git update-index --assume-unchanged .hhconfig` so that my changes to .hhconfig wouldn't propagate to coworkers laptops who have not upgraded to 3.23 (otherwise they'd get `Failure("invalid experimental feature disable_optional_and_unknown_shape_fields")`).
