### ISSUE TITLE
Can't start debug mode

### ISSUE THREAD

**Issue by vanvanj** [facebook/nuclide#1359]
### Issue and Steps to Reproduce
I have already run the "npm start", and the iOS simulator is running my react native project correctly. Then I click the "Nuclide" button at the top tool bar, then slide to "React Native", then I saw three options which are "Start Packager", "Stop Packager", "Restart Packager". But no "debug"

### Expected Behavior
I expect to see the debug option to start the debug mode. And also when I click the "Attach debugger", a new view pops up with only  one tab called "Native", I expect to see another tab called "React native" 

### Versions
* Atom:1.21.1
* Nuclide:0.263
* Client OS:masOS10.13
* Server OS (optional):

### Additional Details
├── MagicPython@1.0.12
├── autocomplete-modules@1.7.3
├── css-snippets@1.1.0
├── file-icons@2.1.13
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── hyperclick@0.1.5
├── language-babel@2.76.1
├── language-graphql@0.9.0
├── language-haskell@1.14.3
├── language-ini@1.19.0
├── language-javascript-jsx@0.3.7
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.5
├── nuclide@0.263.0
├── nuclide-format-js@0.0.41
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.0

**Comment by vanvanj** [comment]
I have already run the "npm start", and the iOS simulator is running my react native project correctly

**Comment by leotao2014** [comment]
Nuclide has dropped Node.js and React Native support of debugging in Release v0.236.0 on June 29, 2017

**Comment by vanvanj** [comment]
Then how can I debug React Native Project, any suggestion? @leotao2014

**Comment by mostafaeweda** [comment]
We've added new (& more stable) Node and RN debugger integrations in the latest release.
You can trigger `Launch` or `Attach` from the menu or command palette.
