### ISSUE TITLE
New diagnostics view doesn't show line number when in 'current file only' mode

### ISSUE THREAD

**Issue by fredemmott** [facebook/nuclide#1361]
### Issue and Steps to Reproduce

1. make multiple errors in a file
2. switch diagnostics view to current file only

### Expected Behavior

Should still see line numbers

### Actual Behavior

No line numbers, just type/source/description

![screen shot 2017-10-27 at 2 08 54 pm](https://user-images.githubusercontent.com/360927/32125362-64fbf36e-bb20-11e7-8d89-38313e675595.png)

### Versions
* Atom: 1.21.1
* Nuclide:0.262.0
* Client OS: MacOS High Sierra
* Server OS (optional): n/a

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (3) /Users/fredemmott/.atom/packages
├── ex-mode@0.18.0
├── nuclide@0.262.0
└── vim-mode-plus@1.11.2
```

**Comment by fredemmott** [comment]
@matthewwithanm 👋

**Comment by matthewwithanm** [comment]
hi @fredemmott 😊

we've already got an issue for this at facebook-atom/atom-ide-ui/issues/101. better yet, i'm about to ship the fix! should be in next week's release.

thanks for the issue ❤️
