### ISSUE TITLE
Buck build not working with .buckversion file: not found

### ISSUE THREAD

**Issue by kockok** [facebook/nuclide#1365]
### Issue and Steps to Reproduce
buck installed via brew
create a fresh app through react-native init
nuclide "run" button disabled
![one](https://user-images.githubusercontent.com/232541/32155283-657fd1c2-bd71-11e7-9ba6-ea16a9161289.png)
![two](https://user-images.githubusercontent.com/232541/32155301-838067b8-bd71-11e7-9db9-e4aff7317649.png)

### Expected Behavior
build and run the app

### Actual Behavior
Run button disable and ".buckversion file: not found" error shown

### Versions
* Atom: latest
* Nuclide: latest
* Client OS: latest macOS
* Server OS (optional):

**Comment by stepanhruda** [comment]
The button is disabled because you need to put the target name from your BUCK file into the combobox (text field, right of the buttons).

`.buckversion file: not found` is only an informative field about the versioning mechanism you are using, it is not blocking for any other flows.

**Comment by kockok** [comment]
@stepanhruda What should be put in the combobox?

**Comment by stepanhruda** [comment]
It depends on:

1. where your `.buckconfig` is
2. where the `BUCK` file for your target is relative to the `.buckconfig`
3. the target name in your `BUCK` file

If you have a simple project with `BUCK` next to `.buckconfig`, and defined a target called `foo` in `BUCK`, you'd put in `//:foo`
