### ISSUE TITLE
Scope highlighting - how to disable

### ISSUE THREAD

**Issue by fzymek** [facebook/nuclide#1366]
Is there a way to disable this "scope highlighting" ?? I cannot find any option controlling it. It only happens when nuclide plugin is enabled in Atom.

<img width="287" alt="screen shot 2017-10-30 at 15 50 49" src="https://user-images.githubusercontent.com/1157689/32181437-43281eca-bd8c-11e7-9392-5506c15bf2f4.png">

For some reason, it seems to be related to `Nuclide-flow -> Use the Flow binary included in each project's flow-bin` options. Highlighting happens when it is enabled. When I disable it it's gone.

**Comment by nmote** [comment]
What version of `flow-bin` do you have listed in your `package.json`? I thought I fixed this in v0.55.0 but this isn't the only report of people with more recent Flow versions having some trouble with this. I can't reproduce with this code snippet and Flow v0.57.3

**Comment by fzymek** [comment]
I am using quite old version `0.38`. This has started happening after nuclide update few days ago.

**Comment by nmote** [comment]
Yes, I recently enabled it by default in Nuclide, since I fixed it in Flow. This week's Nuclide release will have a setting so that people using old versions of Flow (or who just don't like the feature) will be able to disable it.

**Comment by fzymek** [comment]
@nmote 👍

**Comment by TheBox193** [comment]
@nmote Silly question, where do I find the setting? This block scope highlighting is up there on the list of the most distracting things possible list since it moves around all the time while coding. 😛
