### ISSUE TITLE
cannot update hyperclick

### ISSUE THREAD

**Issue by despairblue** [facebook/nuclide#137]
```
Unable to download https://www.atom.io/api/packages/hyperclick/versions/0.1.0/tarball: 404 Not Found Not found
```

Shouldn't the latest version be 0.24.0?

**Comment by despairblue** [comment]
seems to be unpublished again

**Comment by bolinfest** [comment]
@despairblue No, the latest version is 0.0.24. We removed v0.1.0. Unfortunately, hyperclick was originally on a different numbering scheme than the rest of Nuclide.

**Comment by despairblue** [comment]
yeah 0.0.24 was what I meant :)
