### ISSUE TITLE
An unexpected error occurred while running the React Native Packager process

### ISSUE THREAD

**Issue by wellyshen** [facebook/nuclide#1372]
### Issue and Steps to Reproduce
1. Open RN project with atom.
2. **Start packger** from **cmd + shift + P**.
3. Error occurs as following image screenshot.

<img width="465" alt="2017-11-09 2 08 02" src="https://user-images.githubusercontent.com/21308003/32590931-9441e61c-c4e2-11e7-80b7-507abc2a0a93.png">

### Expected Behavior
Running **Start packager** without error

### Actual Behavior
Error occurs as following image screenshot.

<img width="465" alt="2017-11-09 2 08 02" src="https://user-images.githubusercontent.com/21308003/32590931-9441e61c-c4e2-11e7-80b7-507abc2a0a93.png">

### Versions
* Atom: v1.22.0 x64
* Nuclide: v0.266.0
* RN: 0.50.3
* Client OS: MacOS v10.12.6
* Server OS (optional):

**Comment by hansonw** [comment]
Uh oh, this is caused by https://github.com/facebook/nuclide/commit/c9e138f55062497d62a40d7599658b9022a4df9d.
I'd manually revert to 0.264 while we get this fixed - apologies!

**Comment by Liuhuan247** [comment]
So I have to wait for your update to finish ?

**Comment by hansonw** [comment]
Yes, but you can manually downgrade in the meantime. Just run

```
apm install nuclide@0.264.0
```

**Comment by Liuhuan247** [comment]
Thank U. @hansonw

**Comment by hansonw** [comment]
v0.267 has the fix: https://github.com/facebook/nuclide/releases/tag/v0.267.0
Sorry, and thank you guys for the reports!
