### ISSUE TITLE
nuclide-server-start  Address family not supported by protocol

### ISSUE THREAD

**Issue by shuokay** [facebook/nuclide#1375]
### Issue and Steps to Reproduce
start nuclide-server-start from command line or client

### Expected Behavior
 nuclide server started

### Actual Behavior
Address family not supported by protocol

### Versions
* Atom: 1.19.3
* Nuclide: 0.256.0
* Client OS: MacOS 10.12.6
* Server OS (optional): CentOS 7 

### Additional Details
* Installed packages (`apm ls --installed`):
├── MagicPython@1.0.12
├── atomic-emacs@0.12.1
├── file-icons@2.1.13
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.78.0
├── language-graphql@0.9.0
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.5
├── nuclide@0.256.0
├── nuclide-format-js@0.0.41
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.0
```bash
$ nuclide-start-server
Traceback (most recent call last):
  File "scripts/nuclide_server_manager.py", line 395, in <module>
    server_start_result = manager.start_nuclide()
  File "scripts/nuclide_server_manager.py", line 211, in start_nuclide
    port = self._obtain_nuclide_server_port()
  File "scripts/nuclide_server_manager.py", line 199, in _obtain_nuclide_server_port
    port = self._find_open_port()
  File "scripts/nuclide_server_manager.py", line 85, in _find_open_port
    if self._is_port_open(port):
  File "scripts/nuclide_server_manager.py", line 81, in _is_port_open
    self._check_port_family(port, socket.AF_INET6)
  File "scripts/nuclide_server_manager.py", line 67, in _check_port_family
    s = socket.socket(family, socket.SOCK_STREAM)
  File "/usr/lib64/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 97] Address family not supported by protocol
```

**Comment by ccie6747** [comment]
Ran into this same message/issue after disabling v6 in ubuntu 16.04 LTS.   Reenabled v6 and ran fine.

**Comment by hansonw** [comment]
Yup you will want to make sure that both IPv4 and IPv6 are enabled (the Nuclide client prefers IPv6).
