### ISSUE TITLE
Make Nuclide server memory usage configurable

### ISSUE THREAD

**Issue by SuperCipher** [facebook/nuclide#1377]
### Issue and Steps to Reproduce
I have been using Nuclide Remote Development server with rpi3 without a problem until I upgraded both Nuclide client and server to version 0.266.0 or 0.267.0. Once trying to connect, from client to server after the upgrade, the error arises point to a log file state below.

> Important note.
- Rpi3 have 1 Gb of physical memory.
- Connection with Nuclide version lower than 0.266.0 can be done successfully with 876M of 
- memory available.
- Files size in a directory attempting to access is 42.4 MB combined.

 Remote machine (where Nuclide server reside)
- nodeJS version: v8.9.1
- npm version: 5.5.1
- nvm version: 0.33.0

 Client machine (where Nuclide client reside)
- nodeJS version: v8.9.1
- npm version: 5.5.1
- nvm version: 0.33.1

### Expected Behavior
Connected to server normally.

### Actual Behavior
error log file.
```
<--- Last few GCs --->

[14328:0x21206e8] 46289312 ms: Mark-sweep 0.5 (4.0) -> 0.5 (3.0) MB, 4.3 / 0.0 ms  allocation failure GC in old space requested
[14328:0x21206e8] 46289315 ms: Mark-sweep 0.5 (3.0) -> 0.5 (3.0) MB, 3.5 / 0.0 ms  last resort
[14328:0x21206e8] 46289319 ms: Mark-sweep 0.5 (3.0) -> 0.5 (3.0) MB, 3.7 / 0.0 ms  last resort


<--- JS stacktrace --->


#
# Fatal javascript OOM in CALL_AND_RETRY_LAST
#
```

### Versions
* Atom: 1.22.0
* Nuclide: 0.266.0
* Client OS: macOS High Sierra
* Server OS (optional): Raspbian GNU/Linux 8 (jessie)

### Additional Details
* Installed packages (`apm ls --installed`):
├── Hydrogen@2.0.1
├── MagicPython@1.0.12 (disabled)
├── Sublime-Style-Column-Selection@1.7.4
├── api-docs@0.0.6
├── atom-jade@0.3.0
├── atom-material-ui@2.0.6
├── atom-terminal@0.8.0 (disabled)
├── atom-terminal-panel@4.4.4 (disabled)
├── atom-ternjs@0.18.3 (disabled)
├── autocomplete-modules@1.8.0
├── block-comment@0.4.3
├── busy-signal@1.4.3
├── file-icons@2.1.13
├── haskell-grammar@0.4.0 (disabled)
├── highlight-selected@0.13.1
├── hyperclick@0.1.5
├── intentions@1.1.5
├── javascript-snippets@1.2.1 (disabled)
├── js-hyperclick@1.12.2 (disabled)
├── language-babel@2.78.0
├── language-graphql@0.9.0 (disabled)
├── language-haskell@1.14.3
├── language-ini@1.19.0
├── language-lua@0.9.11 (disabled)
├── language-ocaml@1.9.5 (disabled)
├── language-pug@0.0.21
├── language-rust@0.4.12 (disabled)
├── language-swift@0.5.0 (disabled)
├── language-thrift@1.0.2 (disabled)
├── linter@2.2.0 (disabled)
├── linter-ui-default@1.6.10 (disabled)
├── merge-conflicts@1.4.5
├── minimap@4.29.7
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-split-diff@0.3.7
├── nuclide@0.264.0
├── nuclide-format-js@0.0.41
├── remote-edit@1.9.0
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── split-diff@1.5.1
├── sync-settings@0.8.3
├── todo-show@2.1.0
├── tool-bar@1.1.0
└── tree-view-copy-relative-path@1.2.0

**Comment by hansonw** [comment]
Ah, https://github.com/facebook/nuclide/commit/bb1b7c4c15e4699ae0b9b9be645b064986bd57fd made it so that the server process has 4GB of memory allocated to it. I'll see if I can make this a configurable flag.

**Comment by hansonw** [comment]
In the meantime I guess you can stick with 0.266 (or modify the source locally to edit the 4GB limit)

**Comment by SuperCipher** [comment]
Thank @hansonw.
