### ISSUE TITLE
File Tree Broken With Gnome HiDPI Scaling 200%

### ISSUE THREAD

**Issue by smacleod** [facebook/nuclide#1379]
### Issue and Steps to Reproduce
Some elements of the File Tree are broken when used under gnome-shell with 200% scaling on a HiDPI display.
* The "Add Project Folder" and "Add Remote Project Folder" buttons are twice as wide as they should be.
* Scrolling will not work unless the size of the shown file tree is twice as long as the file tree pane itself.

![screenshot from 2017-11-14 18-32-36](https://user-images.githubusercontent.com/1317296/32811426-932ec436-c96d-11e7-90e1-5b5308a1bd59.png)

STR:

1. Have an XPS 13 (9360) with 3200x1800 display
1. Install Ubuntu 17.10, Atom, and Nuclide
1. Configure gnome to use Displays -> Scale: 200%
1. Observe that "Add Project Folder" and "Add Remote Project Folder" are too wide.
1. Add a project folder and expand file tree until it is longer than the file tree pane but less than twice as long
1. Observe that scrolling is not possible.
1. expand file tree further until it is over twice the length of the file tree pane
1. Observe scrolling works again

### Expected Behavior
Buttons to add project folders should be the correct size. Scrolling should always be possible when the file tree is taller than the file tree pane.

### Actual Behavior
Buttons to add project folders are too big. Scrolling breaks when the file tree is longer than the file tree pane but less than double the height.

### Versions
* Atom: 1.22.0
* Nuclide: 0.267.0
* Client OS: Ubuntu 17.10
* gnome-shell: 3.26.1-0ubuntu5
* Electron: 1.6.15
* Chrome: 56.0.2924.87
* Node: 7.4.0

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (17) /home/smacleod/.atom/packages
├── MagicPython@1.0.12
├── file-icons@2.1.13
├── highlight-selected@0.13.1
├── language-babel@2.78.0
├── language-graphql@0.9.0
├── language-haskell@1.14.3
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.267.0
├── nuclide-format-js@0.0.41
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.0
```

**Comment by shushz** [comment]
Unfortunately we don't use Linux machines on our team. I suspect that this may be somewhat similar to the issue fixed in 147837fd00c3d55021a66cd05c8e70385a5f30be for Windows, but without a linux box it's hard to test.

It may just an issue of turning the custom remeasuring logic at https://github.com/facebook/nuclide/blob/master/modules/nuclide-commons-ui/observable-dom.js#L272  for linux as well. Or it maybe something more complex, i.e. a Chrome bug.

If you feel like poking at it I can review a PR.

**Comment by smacleod** [comment]
I might have some time coming up to poke at this, I'll touch base when I get started.

**Comment by mkaminsky** [comment]
I'm seeing a similar problem on Linux with a HiDPI screen.  The fix mentioned above for Windows seems also to work for Linux.  I did a quick test and changed:
```javascript
    if (_os.default.platform() === 'win32') {
```
to
```javascript
    if (_os.default.platform() === 'win32' || _os.default.platform() === 'linux') {
```
and both the scrolling and extra wide button issues went away.

**Comment by captbaritone** [comment]
Resolved by https://github.com/facebook/nuclide/pull/1501
