### ISSUE TITLE
Slack team/channel

### ISSUE THREAD

**Issue by edvinerikson** [facebook/nuclide#138]
What about creating a Slack team/channel? Currently there is no chat for Nuclide, only Github issues and a Facebook group. 
I think it would be a good idea to have something that people could use to ask questions/discuss things that doesn't really fit into a Facebook post or a issue.

And I would love to have a direct chat with you guys.

Is this something that would be possible?

**Comment by aewing** [comment]
I think #nuclide on freenode (irc) would be a good medium, since Facebook is already using it for other projects.

**Comment by ssorallen** [comment]
Since the Atom team hangs out in Slack on atomio.slack.com, we could potentially create a #nuclide channel there. @bolinfest, what do you think?

**Comment by nmn** [comment]
There is also the reactiflux slack team that may make sense.

**Comment by edvinerikson** [comment]
Any updates?
I find @ssorallen proposal most natural/logic as Nuclide is only a set of packages to Atom.

**Comment by ssorallen** [comment]
@edvinerikson I am notified when "nuclide" (case-insensitive) is mentioned in the Atom Slack channels. I am `rossallen` in slack. I believe other Nuclide team members have watches in the Atom Slack channels as well. If you have Nuclide questions, mention the word and we will appear.

**Comment by edvinerikson** [comment]
Ahh, thanks for the update @ssorallen. :+1:
