### ISSUE TITLE
Nuclide debugger keeps pausing (no breakpoints set)

### ISSUE THREAD

**Issue by imdadahad** [facebook/nuclide#1382]
### Issue and Steps to Reproduce

Install atom and latest version of nuclide
Run the react native packager 
Run android app on emulator
Attach nuclide debugger to running packager

### Expected Behavior

It should not keep pausing at random/bizarre points in the application. 

### Actual Behavior

As soon as the debugger is attached, it triggers the debugger right away without any breakpoints being set. After hitting continue to move on, it triggers the debugger again and this continues. Refer to the image below which depicts one of the aforementioned occurences.

![32926106-40e0a682-cb3d-11e7-89ec-b43dd4d82f4b](https://user-images.githubusercontent.com/5855115/32926533-af073e26-cb3f-11e7-8d42-a878300e1d1a.png)

### Versions
* Atom: Latest
* Nuclide: Latest
* Client OS: Mac High Sierra
* Server OS (optional):

**Comment by mostafaeweda** [comment]
It seems you've connected a Native debugger (C++), not the React Native one.
A better RN debugger was recently added to Nuclide -- please update and let us know if that's still broken.

**Comment by imdadahad** [comment]
Thanks for the response @mostafaeweda , but is there a guide for this. The main docs page doesn't outlline how to set it up for RN.

**Comment by mostafaeweda** [comment]
That only came last week in 0f47df4 — you can either build Nuclide from source or wait for next week’s release. You'd be able to Launch / Attach from the Nuclide menu, Command Palette or the `Launch/Attach` buttons.

**Comment by imdadahad** [comment]
Oh, so currently the `Launch / Attach` connects the native debugger by default and in next week's release it will instead connect the RN one?
