### ISSUE TITLE
Unclear how to setup the RN debugger using Nuclide

### ISSUE THREAD

**Issue by imdadahad** [facebook/nuclide#1389]
Re-opening from here: https://github.com/facebook/nuclide/issues/1382

The Nuclide Docs do not provide clear instructions on how to Attach the debugger to the running RN application. It doesn't go into detail on how to prevent the Chrome debugger from launching automatically and which running process to attach the debugger to. 

### Issue and Steps to Reproduce

Build and Run Nuclide from source
Run the RN application inside an Android Emulator
Select to `Debug Remotely`, it breaks at this point as unable to prevent chrome from automatically launching the chrome debugger. Is it possible to have Nuclide auto attach instead of chrome by setting `REACT_DEBUGGER` to some value?

### Expected Behavior

Should be able to attach the debugger to a currently running RN application

**Comment by pelmers** [comment]
Hi @imdadahad, I will update the react native instruction docs on the next release to illustrate how to launch/attach the debugger.

**Comment by kdenz** [comment]
+1 @pelmers

**Comment by pelmers** [comment]
it should be either later today or early tomorrow

**Comment by pelmers** [comment]
update: the release 0.270 went out yesterday which includes the react native debugger, however a [little typo](https://github.com/facebook/nuclide/blob/0d4d20962e769ab848dcefc61b70a3aba0cc1966/pkg/nuclide-debugger-vsp/lib/main.js#L67) prevents it from being active in the menu and it will not be visible until the next release.

But if you're itching to try it out then you can manually edit the line in `~/.atom/packages/nuclide/pkg/nuclide-debugger-vsp/lib/main.js` and set `isOpenSource = true`.

**Comment by imdadahad** [comment]
That's great @pelmers! Have the docs been updated to describe how to connect the debugger to a running RN app on the emulator?

**Comment by pelmers** [comment]
@imdadahad  not yet, I wanted to sync the docs update with the working release.

But if you make the change I suggested you should be able to choose 'react native' from the 'attach debugger' menu and debug apps spawned by a running packager (aka metro bundler) as long as there is no debugger already attached

**Comment by imdadahad** [comment]
@pelmers that seems to work, sort of...

However, on selecting 'Debug JS Remotely' on the Android emulator it automatically connects to the Chrome debugger. Maybe I need to override `REACT_DEBUGGER` with some value to force it to attach from Nuclide?

**Comment by pelmers** [comment]
The debugger included here is a direct port of [vscode-react-native@0.4.4](https://github.com/pelmers/vscode-react-native/blob/0.4.4-vscode-stub) with some vscode-specific parts removed. It looks like you're running into [issue 581](https://github.com/Microsoft/vscode-react-native/issues/581) which seems to have been fixed in their 0.5.2 release, but we haven't updated our port to match.
For now could you try downgrading to react native < 0.50? I have tested with 0.49.

**Comment by imdadahad** [comment]
Ah I see. Our app needs 0.50 as that version introduced some notable bug fixes. I'll stick to sublime+chrome for now but will eagerly await for the update. Appreciate all the work so far 👍

**Comment by pelmers** [comment]
https://nuclide.io/docs/platforms/react-native/#debugging

**Comment by dulguuned** [comment]
Hello,
I can't make Nuclide debugger instead of chrome debugger. When i try to attach debugger it says "Debugger is not attached" , 
i have set /Users/developer/Dropbox/DotnoTuslahApp/package.json for Workspace (required). What is the issue?
