### ISSUE TITLE
unable to locate lldb-server-4.0.1 on Ubuntu

### ISSUE THREAD

**Issue by yagop** [facebook/nuclide#1391]
### Issue and Steps to Reproduce
I'm using Ubuntu 17.10, I installed `lldb` (which resolves to `1:4.0-37~exp3ubuntu1`) and `python-lldb-4.0` after trying to use the native debugger I got the following error:

```
process launch failed: unable to locate lldb-server-4.0.1 LLDB 19:37:16
Failed to start debugger process: debugger server exits with code: 1 Atom 19:37:16
```

I realised `lldb-server-4.0.1`is __not__ in the path but `/usr/bin/lldb-server`, `/usr/bin/lldb-server-4.0` and `/usr/bin/lldb-server-4.0.1-4.0` __are__.

I created the symbolic link `/usr/local/bin/lldb-server-4.0.1` but still didn't work. I created the same symlink in `/usr/bin/lldb-server-4.0.1` and it works!

I don't know if this is a nuclide bug or python-lldb-4.0 but it seems it should lookup `/usr/bin/lldb-server-4.0` or `/usr/bin/lldb-server-4.0.1-4.0` rather than `lldb-server-4.0.1` and use `/usr/local/bin` as PATH too.

### Expected Behavior
Lauch debugger server.

### Actual Behavior
```
process launch failed: unable to locate lldb-server-4.0.1 LLDB 19:37:16
Failed to start debugger process: debugger server exits with code: 1 Atom 19:37:16
```

### Versions
* Atom: 1.22.1
* Nuclide: 0.269.0
* Client OS: Ubuntu 17.10

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (4) /home/yago/.atom/packages
├── editorconfig@2.2.2
├── file-icons@2.1.14
├── language-cmake@0.3.0
└── nuclide@0.269.0
```

**Comment by ebluestein** [comment]
lldb-server is no longer used. 

Remaining LLDB launch issue is being tracked here: https://github.com/facebook/nuclide/issues/1531
