### ISSUE TITLE
React-Native metro won't start process

### ISSUE THREAD

**Issue by wellyshen** [facebook/nuclide#1395]
### Issue and Steps to Reproduce
<img width="1279" alt="2017-11-29 7 56 32" src="https://user-images.githubusercontent.com/21308003/33374119-c65fe104-d53f-11e7-8fb6-756befdb7572.png">

### Expected Behavior
Start metro process and console show the information of the process.

### Actual Behavior
Nothing happened and no any console log.

### Versions
* Atom: 1.22.1
* Nuclide: 0.270.0
* Client OS: MacOS 10.13.1

**Comment by pelmers** [comment]
thanks for the report, I was able to reproduce as well.

**Comment by stepanhruda** [comment]
Sorry about that. I will fix this in `0.271` next week.

To unblock yourself, you can run `atom.config.set('nuclide.nuclide-react-native.pathToNode', 'node')` from the Dev Tools console. To toggle the console hit Cmd-Option-I, or find it as "Window: Toggle Dev Tools" in the command palette (Cmd-Shift-P). Metro should start as expected then.
