### ISSUE TITLE
Remote Hack development - no linting or autocompletion

### ISSUE THREAD

**Issue by kalch** [facebook/nuclide#140]
I have just performed a fresh install of Nuclide on a fresh install of Atom 1.0.2, with nuclide packages. I have a vagrant box with a fresh install of Ubuntu 14.04 and HHVM 3.7.3.

I successfully remoted in to the vagrant box using nuclide-server on port 9090 and created an empty folder with only two files: an empty .hhconfig, and a index.php that looks like this:

<?hh

function f(): int {
  return 'not an int';
}

The editor displays No issues index in the status bar.

When running hh_client, I get:

/home/matt/index.php:4:10,21: Invalid return type (Typing[4110])
  /home/matt/index.php:3:15,17: This is an int
  /home/matt/index.php:4:10,21: It is incompatible with a string

Linter 1.2.0 and nuclide-hack 0.0.24 are installed in Atom in OS X.

I cannot get any linting, auto complete, click to definition (cmd-click) or type hints on mouse hover when editing in Atom?

**Comment by nmn** [comment]
@kalch Could you try https://atom.io/packages/linter-flow-plus and see if that works? (be sure to start a flow server before you open up atom)

**Comment by mostafaeweda** [comment]
@nmn this is not a `flow` issue.
@kalch do you see any errors in the console? `CMD+ALT+i` or in the log on your server: `~/nuclide.nohup.out` and `/tmp/nuclide-$USER-logs/nuclide.log*` ?
The file should have `HACK` grammar enabled at the bottom right of the editor, isn't this the case?

**Comment by mostafaeweda** [comment]
Also, make sure you have the .hhconfig file in your remote project root directory.
I just tried the latest released Nuclide and I see, 3 of those are coming from the hack worker linter and 3 coming from hh_client call:

![screenshot 2015-07-09 12 58 31](https://cloud.githubusercontent.com/assets/264320/8605455/49a8a102-263a-11e5-82c5-3d0fac9eec25.png)

So, just to be sure, even if you don't have `.hhconfig` and just edit a hack grammar file, you should be getting hack lint errors and autocompletions from the local hack worker.

I'm also suspecting an installer issue. so, does this happen when you build Nuclide from source?

**Comment by machee** [comment]
> you should be getting hack lint errors and autocompletions from the local hack worker

@mostafaeweda Does that require HHVM to be installed on the client running Atom?

**Comment by mostafaeweda** [comment]
@machee No

**Comment by kalch** [comment]
I get the local hack worker when I build from source.  I also now get the local hack worker using `apm install nuclide-installer` as well.   I'm getting this now when I try to remote into ubuntu 14.04 on vagrant - "Failed to connect to Nuclide server on 192.168.33.12: Version mismatch. Client at 57 while server at 56."  I had .hhconfig in the root before as well.  I'll keep working on it.

**Comment by jazzdan** [comment]
Hey @kalch I think that means you're running a different version of nuclide on the server (a newer version) than you are on the client. Maybe try following the [Build from Source](https://github.com/facebook/nuclide#building-from-source) to build your client from source and bring it up to the newest version?

**Comment by mostafaeweda** [comment]
@jazzdan that's accurate - but it seems that was an installer issue.
