### ISSUE TITLE
Nuclide Metro: Start doesn't work

### ISSUE THREAD

**Issue by suhabaobaid** [facebook/nuclide#1408]
### Issue and Steps to Reproduce
I am developing in react native, following the documentation from nuclide, I tried to start run from the command palette Nuclide Metro : Start but nothing shows up in the console as expected.

atom config file
"*":
  core:
    customFileTypes:
      "source.ini": [
        ".buckconfig"
        ".flowconfig"
        ".hgrc"
      ]
      "source.json": [
        "BUCK.autodeps"
      ]
      "source.python": [
        "BUCK"
      ]
    disabledPackages: [
      "linter"
      "tree-view"
    ]
    telemetryConsent: "limited"
  editor:
    preferredLineLength: 180
    showIndentGuide: true
    tabLength: 4
    tabType: "soft"
    zoomFontWhenCtrlScrolling: true
  "exception-reporting":
  "linter-ui-default":
    panelHeight: 222
  nuclide:
    "atom-ide-diagnostics-ui":
      autoVisibility: true
      showDiagnosticTraces: true
    "nuclide-flow":
      warnOnNotInstalled: false
    use:
      "nuclide-flow": false
".reason.source":
  editor:
    preferredLineLength: 110

while having react-native: start packager in the command palette, it was working. But this option doesn't exist anymore.

### Expected Behavior
console should print the state of the metro bundling 

### Actual Behavior
Nothing shows up in the consol

### Versions
* Atom: 1.18.11
* Nuclide: 0.270.0
* OS: MAC

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (8) 
├── busy-signal@1.4.3
├── hey-pane@1.1.0
├── intentions@1.1.5
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.0
├── linter-ui-default@1.6.10
├── nuclide@0.270.0
└── prettier-atom@0.43.1

**Comment by stepanhruda** [comment]
React Native Packager has been renamed to Metro (https://facebook.github.io/metro/) so you're definitely using the right command. This has been fixed in Nuclide 0.271 coming out this week, if you want to quickly unblock yourself, run `atom.config.set('nuclide.nuclide-react-native.pathToNode', 'node')` in the Atom's Dev Tools.

**Comment by suhabaobaid** [comment]
@stepanhruda Working perfectly. Thanks!
