### ISSUE TITLE
Flow +  Atom editor + JSX

### ISSUE THREAD

**Issue by ccorcos** [facebook/nuclide#141]
Is it possible to use Flow with JSX with the atom editor package?

**Comment by nmote** [comment]
Is this what you mean?

https://github.com/facebook/nuclide/commit/9648b729a676ae803ae2718befcd76617bec8fb4

**Comment by nmote** [comment]
See also https://github.com/facebook/nuclide/issues/92#issuecomment-116875416

**Comment by ccorcos** [comment]
@nmote I am using ES6 Babel syntax highlighting...

But even when I set the syntax to Javascript (JSX), I don't get any of the flow or hack bells and whistles...

**Comment by nmote** [comment]
Flow from the command line doesn't warn me about that either. If you think that's incorrect then file an issue against https://github.com/facebook/flow. If jump to definition works then it's a good indicator that our Flow integration is working.

**Comment by ccorcos** [comment]
I'm confused, look the first example:

http://flowtype.org

I have an empty `.flowconfig` and a file `text.jsx` all in the same folder. text.jsx has this:

```
/* @flow */
function foo(x) {
  return x * 10;
}
foo('Hello, world!');
```

I don't get any warnings for type hints. And cmd+click does multiple cursors instead of jump to definition...

I have nuclide-flow package installed... idk what else to do. its not working... :(

**Comment by nmote** [comment]
It appears that files with a `jsx` extension don't get labeled as JavaScript files by Nuclide (something that should get fixed), but I tried this example and once I selected JavaScript as the language, Flow features started working for me.

**Comment by nmote** [comment]
It looks like https://github.com/atom/language-javascript is the package that provides JavaScript syntax highlighting, perhaps filing an issue with them to add "jsx" to the list of extensions would be worthwhile.

**Comment by ccorcos** [comment]
Hmm. I see. I'm using babel syntax highlighting... would be nice to be able to use flow with other syntax highlighters...

**Comment by ccorcos** [comment]
So looking at the package: https://atom.io/packages/nuclide-flow

> - Shows Flow errors inline
> - Provides Flow-drive inline autocomplete
> - cmd-click on a symbol jumps to its definition
> - Hovering over an expression exposes its type

So I'm not getting the cmd-click jump to definition, and I'm not getting the hover... But they autocomplete has function signatures (pretty cool!!)

**Comment by nmote** [comment]
You could create a pull request to add other grammars here:

https://github.com/facebook/nuclide/blob/master/pkg/nuclide/flow/lib/constants.js#L13

So if you do have a package installed that provides syntax highlighting for `jsx` files, but uses a different scope name, adding it there should enable `nuclide-flow` to work.

**Comment by ccorcos** [comment]
sweet! Thanks for the help @nmote

**Comment by istarkov** [comment]
For me cmd-click still not works on JSX imports (just updated to nuclide 0.111)

**Comment by zertosh** [comment]
@istarkov, try cloning this repo, then opening the nuclide source directory in Atom, and going to `pkg/nuclide/arcanist/lib/main.js`. Then try cmd+click over `'../../busy-signal-provider-base'` or over `'../../busy-signal-interfaces';`. I just tried on that file using flow 0.20.1 and it works.

**Comment by istarkov** [comment]
@zertosh my fault looks like the problem not in `jsx` but in default params.
please look https://github.com/istarkov/nuclide-flow-error

inside [main.js](https://github.com/istarkov/nuclide-flow-error/blob/master/main.js) 
`import itWorks from './itWorks';` is cmd-clickable 
`import itNot from './itNot';` is not cmd-clickable

because inside [isNot](https://github.com/istarkov/nuclide-flow-error/blob/master/itNot.jsx) where is a `const y = ({x = 10}) => x;`

**Comment by nmote** [comment]
You need `/* @flow */` at the top of your files for Flow to understand them. If you don't have that, some Flow features will work on a best-effort basis but it will not be reliable.

**Comment by nmote** [comment]
And I'm not sure whether Flow will look for `.jsx` files, also.

**Comment by nmote** [comment]
I just tried your example and Flow does in fact support `.jsx` files. The problem is that you have a syntax error in `itNot.js`, so Flow cannot find that module. However, it's not getting reported because you don't have `/* @flow */` at the top.

**Comment by istarkov** [comment]
Here I wrote that problem not in jsx https://github.com/facebook/nuclide/issues/141#issuecomment-171564908

But why it is a syntax error?  It is valid es6 syntax.

**Comment by nmote** [comment]
I see. I'm not familiar with that syntax but Flow does not recognize it. I suggest you file an issue with [Flow](https://github.com/facebook/flow) regarding that.

**Comment by istarkov** [comment]
There is already such issue ;-) https://github.com/facebook/flow/issues/183

**Comment by flockonus** [comment]
For those landing in this issue from Atom JSX javascript support, the answer is in this comment:  https://github.com/atom/language-javascript/pull/313#issuecomment-174715761
