### ISSUE TITLE
BreakPoints turn into Unresolved(?) after launching debugger for react native in Windows.

### ISSUE THREAD

**Issue by HessiPard** [facebook/nuclide#1411]
### Issue and Steps to Reproduce
Start emulator and launch the react native debugger. everything works fine and debugger logs the output except setting breakpoints. they will turn into unresolved everywhere in project directory files. 
i tried everythings like reload the app and stop and start the debugger again.

### Expected Behavior
after launching the debugger, the breakpoints in the project directory files must be hitted .

### Versions
* Atom: 1.23.1
* Nuclide: 0.271.0
* Client OS: windows 10 x64

### Additional Details
├── file-icons@2.1.15
├── highlight-selected@0.13.1
├── language-babel@2.81.0
├── language-graphql@0.9.0
├── language-haskell@1.16.2
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.271.0
├── nuclide-format-js@0.0.42
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.0

**Comment by HessiPard** [comment]
for additional info, At the start if project directory doesnt have `.vscode` folder then attaching or launching the debugger cause below error:

`Could not debug. ENOENT: no such file or directory, mkdir '\PROJECT\.vscode\.react'`
<img width="730" alt="capture" src="https://user-images.githubusercontent.com/23122664/34071069-ac4f4874-e285-11e7-87a9-38a2e01013df.PNG">

and `.vscode/.react` must manually created first in the project directory.
I think it has something common with below issue and its commit that checking happens before creating directory:
[https://github.com/DonJayamanne/pythonVSCode/issues/1064](url)

and one more fact: becuase nuclide react native debugger uses vscode-chrome-debug, the breakpoints issue must be related to sourcemaps that didnt set correctly in build time according to this link:
[https://github.com/Microsoft/vscode-chrome-debug#my-breakpoints-arent-hit-whats-wrong](url)
but i dont know how to set them correctly in atom.
thanks

**Comment by pelmers** [comment]
@HessiPard  thanks for the detailed info, unfortunately I don't develop on windows but I can look into adding the sourcemap override to the available launch options.

re: path not existing, the line which should be creating the directory is here: https://github.com/pelmers/vscode-react-native/blob/68a10569859a8ee0f958e63200de4d1f8f0e4bf9/src/debugger/scriptImporter.ts#L74
however looking at the source again it appears it does not use mkdir recursively so it can only make the trailing portion of the path.

**Comment by lilin666** [comment]
@HessiPard @pelmers  I had encountered the same issue on macOS

**Comment by pelmers** [comment]
@lilin666 thanks, does your program also use source mapping?

**Comment by HessiPard** [comment]
thanks @pelmers for this commit! Good Job! 😉
I hope you add a way for modifying source maps too.

**Comment by pelmers** [comment]
@HessiPard yes my plan is to add the source mapping fields to the launch/attach dialogs very soon by porting from launch.json configuration of vscode! (probably by next release)

**Comment by pelmers** [comment]
closing by bfd730b9c219bd8258fcc30ec6fcb18cf9255226 , see updated documentation at https://nuclide.io/docs/platforms/react-native/#debugging

the new launch window looks like this:
![screen shot 2018-01-04 at 10 35 05 am](https://user-images.githubusercontent.com/2406051/34634265-2c7b9f6e-f237-11e7-8279-6971f82d07aa.png)
