### ISSUE TITLE
tunneling socket could not be established, statusCode=407

### ISSUE THREAD

**Issue by jagatsingh** [facebook/nuclide#1424]
### Issue and Steps to Reproduce

I am behind the corporate proxy. When I try to establish the remote connection, I get this error.

tunneling socket could not be established, statusCode=407

I have tried password and private key authentication in the connection profile.

From the command line, I can install both apm or npm packages.

But, from the Atom UI while creating a new Remote connection, I get the above error.

I am using cntlm as my proxy handler in mac which is configured to talk to corporate proxy.

Thanks in advance.

### Expected Behavior

The connection should be set up.

### Actual Behavior

I get a proxy error.

### Versions

* Atom    : 1.22.1
* Electron: 1.6.15
* Chrome  : 56.0.2924.87
* Node    : 7.4.0
* Nuclide: 0.271.0 (from the apm config below)
* Client OS: Mac
* Server OS Ubuntu 16.04

### Additional Details
* Installed packages (`apm ls --installed`):

Community Packages (38) /Users/myusername/.atom/packages
├── Hydrogen@2.2.0
├── MagicPython@1.0.12
├── Sublime-Style-Column-Selection@1.7.4
├── atom-ide-ui@0.7.0
├── atom-mypy@0.2.4
├── atom-nikola@1.0.0
├── busy-signal@1.4.3
├── compare-files@0.8.1
├── dash@1.7.1
├── emmet@2.4.3
├── file-icons@2.1.15
├── highlight-selected@0.13.1
├── imdone-atom@2.3.23
├── intentions@1.1.5
├── language-babel@2.81.1
├── language-graphql@0.9.0
├── language-haskell@1.16.2
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-matlab-octave@0.1.2
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── language-yaml@0.31.1
├── linter@2.2.0
├── linter-js-yaml@1.2.8
├── linter-ui-default@1.6.10
├── markdown-writer@2.7.3
├── minimap@4.29.7
├── nuclide@0.271.0
├── nuclide-format-js@0.0.42
├── python-indent@1.1.4
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── split-diff@1.5.1
└── tool-bar@1.1.0

* apm config

x00000i11312230:~ myusername$ apm config list
; cli configs
globalconfig = "/Users/myusername/.atom/.apm/.apmrc"
user-agent = "npm/3.10.10 node/v6.9.5 darwin x64"
userconfig = "/Users/myusername/.atom/.apmrc"

; environment configs
node-gyp = "/Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp"
python = "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"

; project config /Users/myusername/.npmrc
ca = null
http-proxy = "http://127.0.0.1:3128"
https-proxy = "http://127.0.0.1:3128/"
proxy = "http://127.0.0.1:3128/"
registry = "http://registry.npmjs.org/"
strict-ssl = false

; userconfig /Users/myusername/.atom/.apmrc
http-proxy = "http://127.0.0.1:3128"
https-proxy = "http://127.0.0.1:3128/"
proxy = "http://127.0.0.1:3128/"
strict-ssl = false

; globalconfig /Users/myusername/.atom/.apm/.apmrc
cache = "/Users/myusername/.atom/.apm"
progress = false

; node bin location = /Applications/Atom.app/Contents/Resources/app/apm/bin/node
; cwd = /Users/myusername
; HOME = /Users/myusername/.atom/.node-gyp
; "npm config ls -l" to show all defaults.

x00000i11312230:~ myusername$

**Comment by ebluestein** [comment]
The credentials Nuclide prompts you for are credentials for SSH'ing into the remote server. From the error code you're receiving (407) it appears your proxy requires authentication to establish a connection. I do not believe there is any way to do this from Nuclide unfortunately.
