### ISSUE TITLE
Adding the option to support extension in "Nuclide-js-imports-client"

### ISSUE THREAD

**Issue by oriSomething** [facebook/nuclide#1438]
### Issue and Steps to Reproduce

Try to use autocomplete with any import. The complete adds path without `.js` and lack the ability to force to add the extension so it will import like: `import {···} from "./my-file.js"`

### Expected Behavior

It would be nice if there will be an option for autocomplete with file extension

### Actual Behavior

-- (described above)

### Versions
* Atom: - (doesn't matter)
* Nuclide: 0.277.0
* Client OS: - (doesn't matter)
* Server OS (optional): - (doesn't matter)

**Comment by jgebhardt** [comment]
Hi, thank you for the suggestion! We don't currently have bandwidth to tackle this, but if anyone is interested in building this, we'd be open to a PR. Thanks!
