### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by svipben** [facebook/nuclide#1444]
### Issue and Steps to Reproduce
1. Open Terminal
2. Switch to another open file
3. Go back to the terminal

![image](https://user-images.githubusercontent.com/10441177/35329970-5cef8cd2-010a-11e8-8320-679f76e4d9c9.png)

### Versions
* Atom: 1.23.3
* Nuclide: 0.278.0
* OS: macOS

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (20) /Users/bsvipas/.atom/packages
├── MagicPython@1.0.12
├── file-icons@2.1.16
├── highlight-selected@0.13.1
├── language-babel@2.81.1
├── language-graphql@0.9.0
├── language-haskell@1.17.3
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter-eslint@8.4.0
├── nuclide@0.278.0
├── nuclide-format-js@0.0.43
├── prettier-atom@0.48.0
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.4
```

**Comment by rightparen** [comment]
Thanks for reporting! This is fixed in 21305c3bec0fe177c146cae472124b93075e6076, which should be in next week's release.
