### ISSUE TITLE
Undo one cursor in multi-cursor mode

### ISSUE THREAD

**Issue by DavidDionise** [facebook/nuclide#1447]
### Issue and Steps to Reproduce
In (pre-nuclide) atom, when I had several cursors with Cmd + Click, I could drop one cursor with Cmd + U. I know that I can use Cmd + Alt + Click for multiple cursors, but I can't find a way to drop just one cursor

### Expected Behavior
Cmd + Alt + U drops one cursor

### Actual Behavior
Nothing

### Versions
* Atom: 1.23.3
* Nuclide: 0.278.0
* Client OS: mac 10.13.3
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by drmathochist** [comment]
It's a little fidgety, but ⌘⌥-click on a multi-cursor will remove that particular cursor.
