### ISSUE TITLE
Debugger does not allow anything but the full path

### ISSUE THREAD

**Issue by rajivshah3** [facebook/nuclide#1452]
### Issue and Steps to Reproduce
1. Make a React Native project
2. In Atom (with Nuclide), open the folder containing the package.json and all related JS files
3. Show the Debugger tab from the Command Palette
4. Attempt to attach the debugger

### Expected Behavior
"Workspace path" field should accept relative paths

### Actual Behavior
Only the full path works.

Setting the path to `./` gives this error when the debugger starts:
```
Could not debug. EACCES: permission denied, mkdir '/.vscode'
```

Setting the path to `~/app` gives this error when the debugger starts:
```
Could not debug. EACCES: permission denied, mkdir '/~'
```

The only path that works is `/Users/rajiv/app`

### Versions
* Atom: 1.23.3
* Nuclide: 0.280.0
* Client OS: macOS High Sierra 10.13.2

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (3) /Users/rajiv/.atom/packages
├── nuclide@0.280.0
├── tool-bar@1.1.4
└── zentabs@0.8.9
```

**Comment by pelmers** [comment]
@rajivshah3 thanks for the feedback, as a quick fix for now I'll change the wording to make it clear it should be an absolute path. A bit later I can look into making the path relative to the workspace. 

remark to anyone who wants to make a PR, that would probably mean adding a bit of logic to this part: https://github.com/facebook/nuclide/blob/master/pkg/nuclide-debugger-vsp/lib/ReactNativeCommonUiComponent.js#L76-L86 as well as passing the workspace path into the component (or fetching from atom's [api](https://atom.io/docs/api/v1.23.3/Project#instance-getPaths))

**Comment by rajivshah3** [comment]
@pelmers hi, I think I might have a fix but I can't test it because the debugger won't open if I run Atom in dev mode using the instructions [here](https://nuclide.io/docs/advanced-topics/building-from-source/#development-mode). I commented out my changes and the debugger still won't open in dev mode, and it doesn't show up in the Command Palette either. Is there something I'm doing wrong?

**Comment by pelmers** [comment]
@rajivshah3 have you tried running it with the chrome devtools open? (cmd-shift-i on macos) There might be an error message or stack trace that could help find the issue.

Since the launch/attach portion is UI code (i.e. runs in electron process) you can have console.logs and they will appear in the chrome console.

**Comment by rajivshah3** [comment]
This is what I saw but I don't think there's anything related to the debugger
```
/Applications/Atom.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDOM.js:71 Download the React DevTools and use an HTTP server (instead of a file: URL) for a better development experience: https://fb.me/react-devtools

/Users/rajiv/nuclide/node_modules/react-dom/cjs/react-dom.development.js:15374 Download the React DevTools for a better development experience: https://fb.me/react-devtools

You might need to use a local HTTP server (instead of file://): https://fb.me/react-devtools-faq

installDevTools.js [sm]:54 Unable to load extension fmkadmapgofadopljbjfkapdkoienihi. Make sure it is installed in one of your Chrome profiles.

/Users/rajiv/nuclide/lib/internal/track-nuclide-ready.js:80 Nuclide ready time: 2847ms (expand for requires by root)

consoleAppender.js [sm]:53 [2018-02-16T05:04:42.543Z] [ERROR] [default] - Failed to listen to remote debug commands - You could be running locally with two Atom windows. IsLocal: true
﻿
```

**Comment by pelmers** [comment]
Hmm you're right, these messages aren't related to the debugger. If you're editing Nuclide from source, make sure you've `apm link` the correct location, see https://nuclide.io/docs/advanced-topics/building-from-source/

**Comment by pelmers** [comment]
merging to #1576
