### ISSUE TITLE
Treeview - back to old alignment

### ISSUE THREAD

**Issue by kikoseijo** [facebook/nuclide#1459]
### Issue and Steps to Reproduce

Please, get that back as what it was, visually now its hard to see if im looking onside a folder or not.

### Expected Behavior

Things that are inside a folder should be padded accord, provide images.

### Actual Behavior

things inside folders are on same padding than the parent.

### Versions
Pure atom + nuclide, latest at today.

### Additional Details
Community Packages (29) /Users/smac/.atom/packages
├── MagicPython@1.0.12
├── artisan@0.3.1
├── atom-autocomplete-php@0.25.6
├── auto-detect-indentation@1.3.0
├── autocomplete-flow@1.6.0 (disabled)
├── bootstrap-3-snippets-for-atom@2.14.2
├── emmet@2.4.3
├── file-icons@2.1.16
├── highlight-selected@0.13.1
├── javascript-snippets@1.2.1
├── language-babel@2.83.1
├── language-blade@0.38.0
├── language-graphql@0.9.0
├── language-haskell@1.17.3
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.282.0
├── nuclide-format-js@0.0.44
├── php-fmt@0.1.2
├── prettier-atom@0.50.0
├── remote-ftp@2.1.4
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.5

### Check this pictures

Except components, all other folders are open, but now I have to look the arrow to appreciate it.
as them in the same level-

![screen shot 2018-02-09 at 09 58 06](https://user-images.githubusercontent.com/1528668/36062300-f237213a-0e69-11e8-961e-d52095848a09.png)

### This is what used to be:

![screen shot 2018-02-09 at 09 57 58](https://user-images.githubusercontent.com/1528668/36062304-15140c72-0e6a-11e8-8a9f-28e84b4a9238.png)

**Comment by kikoseijo** [comment]
Moving it to the atom/tree-view

**Comment by kikoseijo** [comment]
FIX:

```css
.tree-view {
  li.file.entry.list-item {
    margin-left: 1.4rem !important;

  }
}
```

Why is the `!important` necessary?
Something else its messing around.

**Comment by IanVS** [comment]
I think this should be re-opened.  The workaround is great, but the view should be fixed for everyone.  It's so hard to tell what files are inside folders now.

**Comment by kikoseijo** [comment]
Im getting this with a clean atom + nuclide install.

**Comment by IanVS** [comment]
It looks like this may be fixed by https://github.com/facebook/nuclide/commit/3704e5b1bb409f120e241b74272e2f6472e808a2.

**Comment by alamothe** [comment]
This works with Atom's default tree view, but it is messed up in Nuclide. 

Thanks so much for the workaround, as it's really irksome to use file tree with the broken alignment

**Comment by kikoseijo** [comment]
Excellent!
Ill close now its been corrected, should be available on next releases.
