### ISSUE TITLE
nuclide-file-tree shows hidden files despite configuration

### ISSUE THREAD

**Issue by bobrock** [facebook/nuclide#146]
I am stuck with nuclide-file-tree configuration. Plugin shows "*.pyc" files inside tree view despite configuration.

"*.pyc" has been listed inside "Ignored names" and core tree-view is configured to hide ignored names and to hide VCS ignored files.

<img width="306" alt="screen shot 2015-07-18 at 16 11 15" src="https://cloud.githubusercontent.com/assets/997430/8761921/82d7a956-2d69-11e5-8097-d9ad31d9451d.png">
<img width="324" alt="screen shot 2015-07-18 at 16 10 20" src="https://cloud.githubusercontent.com/assets/997430/8761922/85a23de0-2d69-11e5-9191-1f895ad74fd5.png">
<img width="545" alt="screen shot 2015-07-18 at 16 10 53" src="https://cloud.githubusercontent.com/assets/997430/8761923/8806de7e-2d69-11e5-9ce3-9d032caa088e.png">

Versions:
nuclide-file-tree v0.0.24
Atom v1.0.2
os: osx 10.10.4

If needed i can provide any additional informations and logs.

TIA and best regards

**Comment by bobrock** [comment]
This is duplicated issue, sorry for that :-(

**Comment by ssorallen** [comment]
Thanks for the issue. Linking as duplicate of #76 so we see it later.
