### ISSUE TITLE
Debugger is gone

### ISSUE THREAD

**Issue by irlabs** [facebook/nuclide#1461]
### Issue and Steps to Reproduce

The debugger is gone, and won't show or launch when the option is chosen.

1. enable the setting 'Show debugger on breakpoint set'
2. try to set a breakpoint in the gutter
3. nothing happens: no breakpoint appears in the gutter and the debugger pane is not shown.

### Expected Behavior

It is expected that a breakpoint appears in the gutter and shows in the debugger pane.

### Actual Behavior

nothing

### Versions
* Atom: 1.24.0
* Nuclide: 0.283.0
* Client OS: Mac OS X
* Server OS (optional): Metro Bundler

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── MagicPython@1.0.12
├── atom-beautify@0.30.9
├── autocomplete@0.47.0
├── autocomplete-flow@1.6.0
├── autocomplete-json@5.5.2
├── autocomplete-modules@1.10.0
├── autocomplete-python@1.10.5
├── busy-signal@1.4.3
├── dash@1.7.1
├── file-icons@2.1.16
├── highlight-selected@0.13.1
├── ide-flowtype@0.19.0
├── intentions@1.1.5
├── language-babel@2.83.4
├── language-graphql@0.9.0
├── language-haskell@1.17.3
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── linter-flow@5.6.1
├── linter-pycodestyle@2.1.3
├── linter-ui-default@1.6.10
├── nuclide@0.283.0
├── nuclide-format-js@0.0.44
├── python-tools@0.6.9
├── script@3.17.3
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.6
```

**Comment by mostafaeweda** [comment]
Sorry, that regressed (in the nuclide-debugger rewrite) due to that line change: https://github.com/facebook/nuclide/blob/master/pkg/nuclide-debugger/package.json#L82 -- if you remove it from your nuclide installation, it'll bring back the debugger.

In the meantime, I'll work on a proper fix.

**Comment by mostafaeweda** [comment]
That was fixed in https://github.com/facebook/nuclide/commit/0a2f7b1ffcdc29f3322e3c64980ab342827cbee9, you can either build from source or wait for next week's release.
