### ISSUE TITLE
[nuclide-terminal] custom shell support

### ISSUE THREAD

**Issue by kbrgl** [facebook/nuclide#1462]
### Issue
nuclide-terminal runs the bash shell by default, with no way to configure shells like zsh and fish.

### Expected Behavior
nuclide-terminal should have the ability to configure shell commands

### Versions
* Atom: 1.24.0
* Nuclide: 0.283.0
* Client OS: macOS High Sierra 10.13.2

**Comment by kbrgl** [comment]
I'd like to work on this issue as it doesn't seem too complicated, where should I start?

**Comment by pelmers** [comment]
actually we already have custom shell support! The documentation just hasn't been published yet but will be very soon. cc @rightparen

**Comment by rightparen** [comment]
Nuclide's terminal does try to discover your default shell (as set by `chsh` on the target machine), but it is also possible to control explicitly. I just landed the documentation, so in case there is a delay in syncing to nuclide.io, here is the relevant section:

# Custom Shell

By default, Nuclide terminal starts a new shell by running `/bin/bash --login -i`.  You can customize this behavior by adding a file `$HOME/.nuclide-terminal.json` **on the machine where the shell process runs**.  Here is an example you can use on OSX to start the version of bash from MacPorts:

```
{
  "command": [
    "/opt/local/bin/bash",
    "--login",
  ]
}
```
