### ISSUE TITLE
Autocomplete is very slow in .jsx files

### ISSUE THREAD

**Issue by allenylzhou** [facebook/nuclide#1463]
### Issue and Steps to Reproduce
When .flowconfig exists in your project, autocomplete is very slow in .jsx files (still works perfectly in .js files)

### Expected Behavior
Typing in `tim` should immediately trigger the autocomplete dropdown with the setTimeout function as an option

### Actual Behavior
After typing in `tim`, the dropdown does not appear until 3-5 seconds later.

### Versions
* Atom: 1.24.0
* Nuclide: 0.283.0
* Client OS: macOS High Sierra (10.13.1)
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── language-babel@2.83.4
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── merge-conflicts@1.4.5
├── nuclide@0.283.0
├── sync-settings@0.8.3
└── team-snippets

**Comment by matthewwithanm** [comment]
thanks for the report, @allenylzhou! @wanderley's out but i'll ask him to take a look at this next week.

**Comment by wanderley** [comment]
Now, `nuclide-autocomplete` imposes a time limit for providers. It should fix this problem.
