### ISSUE TITLE
Cannot find Nuclide React Native: Start Packager

### ISSUE THREAD

**Issue by subarashii** [facebook/nuclide#1467]
### Issue and Steps to Reproduce
step to run a project
1.install atom
2.install nuclide packages
3.config the nuclide packages(Install Recommended Packages On Startup )
4.init the demo project

### Expected Behavior
command+shift+p, there is no Start Packager option.

### Actual Behavior
I can run the project whit react-native run-ios.

### Versions
* Atom:1.24.0
* Nuclide:0.283.0
* Client OS:Mac OS
* Server OS (optional):

**Comment by arturstaszczyk** [comment]
Try command + shift + p and run 'Nuclide Metro: Start'
See: https://github.com/facebook/nuclide/issues/1392

**Comment by subarashii** [comment]
@arturstaszczyk thank you !

**Comment by subarashii** [comment]
too many rn guidelines docs should be update in Chinese website
