### ISSUE TITLE
Unable to remap Hyperclick to a keyboard shortcut

### ISSUE THREAD

**Issue by k** [facebook/nuclide#1468]
### Issue and Steps to Reproduce
I can't remap hyperclick to a keyboard shortcut.

### Expected Behavior
Hyperclick should show in the command palette so I can remap it to a keyboard shortcut

### Actual Behavior
Hyperclick does not show in the command pallete and does not appear to be able to be mapped.

### Versions
* Atom: 1.24.0
* Nuclide: 0.283.0
* Client OS: Mac osx 10.13.3
* Server OS (optional): N/A

### Additional Details
* Installed packages (`apm ls --installed`):
```
[36mCommunity Packages (18)[39m /Users/kenny/.atom/packages
├── atom-easy-jsdoc@4.12.5
├── autocomplete-js-import@1.4.0
├── busy-signal@1.4.3
├── ex-mode@0.18.0 (disabled)
├── graphql-autocomplete@1.1.1
├── intentions@1.1.5
├── language-babel@2.84.0
├── language-graphql@0.9.0
├── language-javascript-jsx@0.3.7
├── language-markdown@0.25.1
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── linter-stylelint@4.2.0
├── linter-ui-default@1.6.10 (disabled)
├── markdown-preview-plus@2.5.1
├── nuclide@0.283.0
├── prettier-atom@0.51.0
└── vim-mode-plus@1.28.1
```

**Comment by matthewwithanm** [comment]
thanks for the issue @k! are you looking for a mouseless keyboard shortcut or a different +click modifier?

**Comment by k** [comment]
I’m a vim’er so keyboard haha. Thanks for the response.

**Comment by matthewwithanm** [comment]
cool (:

we do have a command for this, but it's kinda weirdly named: "Hyperclick: Confirm Cursor", and it has a default keybinding of `⌘⌥⏎`. is that not showing up for you?

**Comment by k** [comment]
Ah thanks! Yes that showed up. I must have gotten stuck on looking for 'goto' and 'jump to definition' type searches. Thank you!

**Comment by matthewwithanm** [comment]
@wbinnssmith maybe we should add some aliases for this one?
