### ISSUE TITLE
Disable JS Auto-imports messages

### ISSUE THREAD

**Issue by penx** [facebook/nuclide#1469]
### Issue and Steps to Reproduce

`nuclide-js-imports-server`/`nuclide-js-imports-client` are raising unnecessary warnings. These messages should not be shown and/or be easy to disable. I can't find any clear instructions on how to disable this without uninstalling nuclide.

<img width="349" alt="screen shot 2018-02-20 at 11 35 11" src="https://user-images.githubusercontent.com/1027024/36421896-2398efa4-1632-11e8-894c-3b43bd2fbf46.png">

### Expected Behaviour

- Should not warn about variables such as 'module' or 'console' being missing imports
- Should be easy to find instructions in documentation on how to disable this

### Versions
* Atom: 1.24.0 x64
* Nuclide: 0.283.0
* Client OS: Mac OS X 10.13.3

**Comment by mostafaeweda** [comment]
You may disable JS Auto-Imports from Atom's settings page:
`Packages -> nuclide` -- scroll to the bottom, and expand the `Enabled Features` section.
![screenshot 2018-02-21 15 21 31](https://user-images.githubusercontent.com/264320/36511341-252cde04-171b-11e8-8285-1818ac3934e3.png)
There, you can uncheck `Enable the "nuclide-js-imports-client" feature` to disable it
![screenshot 2018-02-21 15 20 53](https://user-images.githubusercontent.com/264320/36511351-2c7bf37a-171b-11e8-944d-9191f174c327.png)

**Comment by followbl** [comment]
hi @mostafaeweda thanks for this...I do believe there could be a bug here related to turning this feature off (which after some reading through your documentation, I don't believe I want to do, but still logging this here nonetheless)...not sure if it's expected that a feature like OmniSearch isn't supposed to work.

@penx after reading through the docs on this [feature](https://github.com/facebook/nuclide/tree/master/pkg/nuclide-js-imports-server) I believe a solution that you're looking for is enabling a project configuration of sorts to be set. For me, it's set in my .eslintrc.js file and looks like so. hope this helps, I know this one was bothering me for a few days

```
module.exports = {
  extends: 'react-app',
  env: {
    browser: true,
    node: true,
  },
  rules: {
    'no-undef': 0,
    radix: 0,
    'import/first': 0,
  },
};
```

[Enter steps to reproduce:]

1. Disable using steps above from @mostafaeweda 
2. cmd+P: to open OmniSearch

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.5
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.303.0


### Stack Trace

Uncaught Error: Provider JSImportsService is not registered with quick-open.

```
At /Users/brad/.atom/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:310

Error: Provider JSImportsService is not registered with quick-open.
    at SearchResultManager._getProviderByName (/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:458:31)
    at SearchResultManager.getProviderSpecByName (/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:571:36)
    at SearchResultManager._getResultsForProvider (/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:477:31)
    at Object.keys.map.providerName (/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:535:40)
    at Array.map (native)
    at SearchResultManager.getResults (/packages/nuclide/pkg/nuclide-quick-open/lib/SearchResultManager.js:534:7)
    at QuickSelectionComponent._updateResults (/packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:710:350)
    at /packages/nuclide/pkg/nuclide-quick-open/lib/QuickSelectionComponent.js:360:12)
    at a.__tryOrUnsub (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:71:208)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:70:63)
    at a._next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:68:217)
    at a.next (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:67:406)
    at a.debouncedNext (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:172:293)
    at a.Md (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:44:281)
    at a._execute (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:118:206)
    at a.execute (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:118:27)
    at a.flush (/packages/nuclide/node_modules/rxjs/bundles/Rx.min.js:310:133)
```

### Commands

```
     -7:48.9.0 core:close (input.hidden-input)
     -6:03.5.0 core:save (input.hidden-input)
  2x -5:52.9.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -5:52.4.0 core:backspace (input.hidden-input)
     -5:52.1.0 core:save (input.hidden-input)
     -3:36.4.0 core:undo (input.hidden-input)
     -3:35.4.0 core:save (input.hidden-input)
     -1:54.9.0 core:confirm (input.hidden-input)
     -1:06.9.0 core:close (select#nuclide.use.nuclide-js-imports-client.form-control)
     -1:06.0 core:save (input.hidden-input)
     -1:00.7.0 nuclide-quick-open:find-anything-via-omni-search (input.hidden-input)
     -0:59.8.0 editor:consolidate-selections (input.hidden-input)
     -0:59.8.0 core:cancel (input.hidden-input)
     -0:15.7.0 core:close (select#nuclide.use.nuclide-js-imports-client.form-control)
     -0:14.8.0 core:save (input.hidden-input)
     -0:13.3.0 nuclide-quick-open:find-anything-via-omni-search (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.4 
atom-panda-syntax 0.18.0 
autoclose-html 0.23.0 
autocomplete-modules 2.0.0 
busy-signal 1.4.3 
custom-title 1.0.1 
file-icons 2.1.21 
fold-search-results 1.0.5 
git-blame 1.6.0 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.85.0 
language-graphql 0.10.1 
language-haskell 1.17.7 
language-ini 1.20.0 
language-kotlin 0.5.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-eslint 8.4.1 
MagicPython 1.0.12 
material-syntax 0.6.1 
merge-conflicts 1.4.5 
nuclide 0.303.0 
nuclide-format-js 0.0.45 
pigments 0.40.2 
prettier-atom 0.53.0 
pretty-json 2.0.0 
react 0.18.0 
recent-files-fuzzy-finder 0.6.1 
set-syntax 0.4.0 
sort-lines 0.18.0 
Sublime-Style-Column-Selection 1.7.4 
tabs-to-spaces 1.0.5 
tool-bar 1.1.7 
xml-formatter 0.11.0 
zentabs 0.8.9 
```

**Comment by mostafaeweda** [comment]
After disabling, please restart Atom/Nuclide as that could be a bug in the deactivation flow - cc @hansonw

**Comment by cappslock** [comment]
Is there any way to fix/ignore these particular cases without disabling auto-imports completely?
