### ISSUE TITLE
"Add remote project folder" dialog doesn't save deleted value.

### ISSUE THREAD

**Issue by kartagis** [facebook/nuclide#1470]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
I am trying to add remote project folder, so I open up the dialog and fill in my details. I delete `nuclide-start-server` in the remote server command box, and save it (please see the below screenshot). 
![screenshot 2018-02-22 16 18 33](https://user-images.githubusercontent.com/1607518/36540661-4ed39910-17ec-11e8-8cd3-fb0f567f65f7.png)

To my surprise, it is not deleted because I get the below error:

![screenshot 2018-02-22 16 18 05](https://user-images.githubusercontent.com/1607518/36540626-29231db2-17ec-11e8-9c76-572696c11f52.png)

### Expected Behavior
The save button should properly save.

### Actual Behavior
The save button does not save.

### Versions
* Atom: 1.23.3
* Nuclide: 0.278.0
* Client OS: macOS 10.12.6
* Server OS (optional): Ubuntu 16.04

### Additional Details
* Installed packages (`apm ls --installed`):
apm ls --installed
Community Packages (9) /Users/tolga/.atom/packages
├── Remote-FTP@0.10.7
├── alias-command@1.0.1
├── atom-beautify@0.29.17
├── atom-jshint@2.0.0
├── drupal@1.9.0
├── emmet@2.4.3
├── nuclide@0.278.0
├── react-native-snippets@0.3.0
└── vim-mode@0.66.0

**Comment by mostafaeweda** [comment]
I see you already have a saved profile: `magnec` (doesn't that profile have the remote command saved with it) - if that didn't save the command, could you try deleting it and creating it again?

I see you have an error here of `nuclide-start-server` -- that should be something like: 
`~/nuclide-server/pkg/nuclide-server/nuclide-start-server` (a path to your nuclide server installation)

**Comment by kartagis** [comment]
Do I need to have that installation?

Best regards,
Tolga

**Comment by mostafaeweda** [comment]
Yes, you must have it as Nuclide would need these server pices to achieve things like: code editing, language services, debugging

**Comment by kartagis** [comment]
I need it on the client, right?

Best regards,
Tolga

**Comment by mostafaeweda** [comment]
You need both: client and server setup, find documentation at: https://nuclide.io/docs/editor/setup/#installing-nuclide-server
