### ISSUE TITLE
Section of unselectable text on website

### ISSUE THREAD

**Issue by 1j01** [facebook/nuclide#1472]
I can't select text in the section near the top of the website.
This displeases me. [Relevant XKCD.](https://xkcd.com/1271/)

![no selection zone](https://user-images.githubusercontent.com/3630663/36648684-9ab058bc-1a64-11e8-9885-6b2a129c40c7.gif)

You could fix this by adding `pointer-events: none;` to `.projectLogo` (and `pointer-events: all` on the `img`) or fixing the area `.projectLogo` takes up (changing how the `#home_wrap` layout works)

![selection disabled nuclide](https://user-images.githubusercontent.com/3630663/36648783-bed4dd2a-1a65-11e8-9683-c66d20aa125f.png)

**Comment by 1j01** [comment]
@captbaritone  Oh, I was actually looking at this project because of you. :P hi 👋

**Comment by captbaritone** [comment]
Haha! 

Well, your gripe was resolved in https://github.com/facebook/nuclide/commit/d87747863755233e38b2424653bc852c8a20680b You should now be able to highlight to your heart's content.
