### ISSUE TITLE
Support Linters like ESlint on Remote Projects

### ISSUE THREAD

**Issue by tim-soft** [facebook/nuclide#1475]
### Issue and Steps to Reproduce
A lot of linting plugins, but more specifically ESlint, do not work on remote projects.

![capture](https://user-images.githubusercontent.com/10257939/36877993-39aa8fd8-1d7a-11e8-97f8-8223dc7964f9.PNG)

### Expected Behavior
Linting integration on a project level when working on files remotely via nuclide + watchman

### Actual Behavior
Linters like ESlint aren't very useful operating on only the currently opened file, which are evidently all linter plugins in atom have access to when the filesystem is remote.

Here's a follow up discussion about why linter-eslint specifically doesn't work on remote projects https://github.com/AtomLinter/linter-eslint/pull/1017

Can this sort of issue be remedied in some trivial way, given the SSH connection and all of the Nuclide/flow capabilities?

### Versions
* Atom: 1.24.0
* Nuclide: 0.268.0
* Client OS: Win10/MacOS
* Server OS (optional): Ubuntu 16.04

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (21) C:\Users\timel\.atom\packages
├── file-icons@2.1.17
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── language-babel@2.84.0
├── language-graphql@0.9.0
├── language-haskell@1.17.3
├── language-ini@1.19.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter-eslint@8.4.1
├── MagicPython@1.0.12
├── nuclide@0.286.0
├── nuclide-format-js@0.0.44
├── prettier-atom@0.51.0
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.6
```

**Comment by hansonw** [comment]
Unfortunately, there is no straightforward remedy short of bundling an ESLint server into the Nuclide server. @wanderley is currently working on it - we should hopefully be able to open source this at some point :)

**Comment by tim-soft** [comment]
Knowing that something is in the works is very good to know! ESlint is sorely missed in these remote projects, maybe this is a good architecture question for the atom crowd.

**Comment by SavePointSam** [comment]
I'm not sure why this was closed. This is still an issue. Having a solution in the works isn't the same as having a solution. This problem still pains me on a daily basis. :(

**Comment by tim-soft** [comment]
I totally feel your pain. I closed the issue because ESlint is its own organization, it's ultimately up to them or create their own ide language server like Facebook has with flow. 

I don't know of a more universal solution that Nuclide could facilitate. Running any linter on the remote box and reporting back the results via atom UI doesn't feel very vender agnostic
