### ISSUE TITLE
fs.watch may provide null filenames

### ISSUE THREAD

**Issue by ritchiedw** [facebook/nuclide#1491]
I'm not exactly sure what was happening when the error arose, I was on another screen looking at code.  I had been copying code from another git repo into the file as part of a tutorial.  
It may be connected to Watchman (from the stack trace below) which isn't supported on Windows anyway.

The content of the only file I had open in Atom is:

import React from 'react';
import { StackNavigator } from 'react-navigation';
import routes from './config/routes';
import { initApi } from './services/api';

const AppNavigator = StackNavigator(routes);

export default class extends React.Component {
  componentWillMount() {
    initApi();
  }

  render() {
    return (
      <AppNavigator />
    )
  }
}

**Atom**: 1.25.0 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Home
**Thrown From**: [nuclide](https://github.com/facebook/nuclide) package 0.291.0

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of null

```
At C:\Users\ritch\.atom\packages\nuclide\node_modules\nuclide-commons\nuclideUri.js:655

TypeError: Cannot read property 'indexOf' of null
    at _archiveEncode (/packages/nuclide/node_modules/nuclide-commons/nuclideUri.js:655:10)
    at array.forEach (/packages/nuclide/node_modules/nuclide-commons/nuclideUri.js:648:39)
    at Array.forEach (native)
    at _archiveEncodeArrayInPlace (/packages/nuclide/node_modules/nuclide-commons/nuclideUri.js:648:9)
    at Object.join (/packages/nuclide/node_modules/nuclide-commons/nuclideUri.js:199:5)
    at FSWatcher._fs.default.watch (/packages/nuclide/pkg/nuclide-filewatcher-rpc/lib/FileWatcherService.js:115:78)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:194:7)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1392:12)
```

### Commands

```
     -9:45.2.0 core:paste (input.hidden-input)
     -9:42.7.0 core:save (input.hidden-input)
     -5:38.7.0 editor:newline (input.hidden-input)
     -5:32.1.0 core:paste (input.hidden-input)
     -4:57.6.0 core:save (ul.list-inline.tab-bar.inset-panel)
     -2:33.7.0 core:paste (input.hidden-input)
     -2:29.5.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
file-icons 2.1.18 
highlight-selected 0.13.1 
hyperclick 0.1.5 
language-babel 2.84.0 
language-graphql 0.9.0 
language-haskell 1.17.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-scala 1.1.9 
language-swift 0.5.0 
language-thrift 1.0.2 
MagicPython 1.0.12 
nuclide 0.291.0 
nuclide-format-js 0.0.45 
set-syntax 0.4.0 
sort-lines 0.18.0 
tool-bar 1.1.7 
tool-bar-main 0.0.11 
```

**Comment by hansonw** [comment]
Ah... not Watchman, but just Node's `fs.watch` may sometimes be providing a null filename. Thanks for flagging, will fix!

**Comment by hansonw** [comment]
Addressed in https://github.com/facebook/nuclide/commit/8d94af2676d8baa65ac4fadff20e20f94d5594f5 - will be pushed next week.
