### ISSUE TITLE
Error: BABEL issue with nuclide-hack

### ISSUE THREAD

**Issue by tcyrus** [facebook/nuclide#150]
When I upgraded nuclide-hack from 0.0.22 to 0.0.24, I received this message on update:
```
Installing nuclide-hack@0.0.24 to /Users/username/.atom/packages [BABEL] Note: The code generator has deoptimised the styling of "/Users/username/.atom/packages/nuclide-hack/static/hh_ide.js" as it exceeds the max of "100KB".
✓
```

**Comment by mostafaeweda** [comment]
this should no longer be an issue with the UP release: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
