### ISSUE TITLE
nuclide-tree-view : cannot select file one above currently selected file

### ISSUE THREAD

**Issue by awilkins** [facebook/nuclide#1503]
### Issue and Steps to Reproduce

* Open a project with three files in a folder (e.g. `[a.js, b.js, c.js]`)
* Click `b.js` : file is highlighted and editor pane opens for b.js
* Click `a.js` : nothing happens
* Click `c.js` : highlighted and opened
* Click `b.js` : nothing happens
* Click `a.js` : highlighted and opened

### Expected Behavior

* All files clicked should be highlighted and an editor should open

### Actual Behavior

* Cannot select file above currently selected file
* Does not apply to folders ; these work normally
* No output in developer console

### Versions
* Atom: 1.27.0-beta0
* Nuclide: 0.297.0
* Client OS: Ubuntu 16.04

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (51) /home/awilkins/.atom/packages
├── MagicPython@1.0.12
├── atom-beautify@0.32.2
├── autocomplete-modules@2.0.0
├── busy-signal@1.4.3
├── ex-mode@0.18.0
├── file-icons@2.1.18
├── go-debug@1.6.1
├── go-plus@5.8.3
├── go-signature-statusbar@1.2.3
├── graphviz-preview-plus@1.5.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.13.1
├── ide-go@0.7.0
├── intentions@1.1.5
├── language-babel@2.84.0
├── language-dot@1.7.0
├── language-graphql@0.10.1
├── language-haskell@1.17.6
├── language-ini@1.19.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-markdown@0.25.1
├── language-nginx@0.8.0
├── language-nunjucks@4.2.1
├── language-ocaml@1.9.5
├── language-plantuml@0.2.0
├── language-r@0.4.2
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-terraform@0.8.1
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── linter-json-lint@0.1.3
├── linter-terraform-semantics@0.2.0
├── linter-terraform-syntax@1.2.2
├── linter-ui-default@1.7.1
├── minimap@4.29.8
├── minimap-highlight-selected@4.6.1
├── narrow@0.65.0
├── nuclide@0.297.0
├── nuclide-format-js@0.0.45
├── plantuml-viewer@0.7.2
├── regex-railroad-diagram@0.19.4
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── teletype@0.13.0
├── tool-bar@1.1.7
├── vim-mode-plus@1.32.0
└── vim-mode-plus-keymaps-for-surround@0.2.1
```

**Comment by awilkins** [comment]
Further detail

* This also applies if a folder is above the selected file
* If you close the editor for the selected file, and click the file or folder above it, the editor opens again - this seems to indicate that the click event is going to the same file element again

**Comment by matthewwithanm** [comment]
weird! i can't seem to repro this. do you have any errors in your devtools console? also, does this repro when nuclide is the only package enabled?

**Comment by awilkins** [comment]
No console output. 

Have reproduced on all three of my machines

* Ubuntu 16.04, Intel GPU
* Ubuntu 16.04. nvidia GPU
* Ubuntu 18.04. HiDPI screen, Intel GPU

Also reproduces when nuclide@0.299.0 is only non-core package installed (moved .atom and installed just Nuclide). 0.300.0 won't load right now.

Here you can see the displayed box model highlight for the `<li>` element for the `.python-version` file - covering the `.node-version` file above. That seems to be the issue - it's catching the clicks intended for `.node-version`, which explains why it re-opens the file if you close it's editor and try to click on `.node-version` 

![image](https://user-images.githubusercontent.com/368399/39337566-9b7b8ca0-49b5-11e8-8d51-7004d31d2d0b.png)

**Comment by awilkins** [comment]
This seems to be a manifestation of a bug in [one-dark-ui : #257](https://github.com/atom/one-dark-ui/issues/257).

Workaround : go to `one-dark-ui` settings and disable "Make tree-view project headers sticky".

This also gets rid of an annoying horizontal scrollbar at the base of the treeview.

![image](https://user-images.githubusercontent.com/368399/39338044-53119966-49b8-11e8-99b5-2880843004f2.png)

**Comment by matthewwithanm** [comment]
Thanks for the follow-up, @awilkins! Gonna close this since it seems to have been addressed there (:
