### ISSUE TITLE
Font not displaying correctly when using powerline fonts and zsh themes

### ISSUE THREAD

**Issue by ggeldenhuis** [facebook/nuclide#1506]
### Issue and Steps to Reproduce
I am using the agnoster zsh theme with powerlines fonts. When opening up a console in atom it does not correctly display.
Display I am getting:
![screenshot from 2018-04-24 08-29-11](https://user-images.githubusercontent.com/192423/39172495-d7c6233c-4799-11e8-8b09-1d2082f7f927.png)
Display I am expecting:
![screenshot from 2018-04-24 08-29-54](https://user-images.githubusercontent.com/192423/39172514-e15dab2c-4799-11e8-84a9-107a98173af9.png)

### Versions
* Atom: 1.26.0
* Nuclide: Don't know
* Client OS: Ubuntu 17.10
* Server OS (optional):

**Comment by jgebhardt** [comment]
@ggeldenhuis the console font is a separate setting from the Atom editor font. Try setting it via Atom's settings > Packages > Nuclide > Terminal > Font Family. Let us know if that doesn't work. Thanks!
