### ISSUE TITLE
Nuclide is not load in atom

### ISSUE THREAD

**Issue by Binman1** [facebook/nuclide#1511]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:
* Nuclide:
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by ebluestein** [comment]
We'd need more information to be able to help you troubleshoot this. Please let us know how you installed Nuclide, what OS and Atom version you are running, and what happens when you load Atom (are there any errors, for example?)
