### ISSUE TITLE
C++ Wrong diagnostics clang

### ISSUE THREAD

**Issue by BigfootN** [facebook/nuclide#1516]
Hello,

I am trying to use nuclide with a project using a third party library (like poco for example). Auto completion works fine. The only problem I have is with diagnostics.

Here is an example:

![Imgur](https://i.imgur.com/JdQjMDz.png)

A `compile_commands.json` is present at the root of my project. What is weird is that autocompletion works very well, `Poco` is recognized but not with diagnostics. Also the included headers are recognized.

#### Versions

Atom: `1.26.1`
Electron: `1.7.11`
Nuclide: `0.301.1`
OS: `Archlinux`
Clang version: `6.0.0`
cmake: `3.11.1`

#### Installed packages:

```
Community Packages (30)
├── atom-beautify@0.32.2
├── atom-material-ui@2.1.3
├── autocomplete-paths@2.12.2
├── busy-signal@1.4.3
├── file-icons@2.1.19
├── gruvbox-plus-syntax@1.3.1
├── highlight-selected@0.13.1
├── hyperclick@0.1.5
├── intentions@1.1.5
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.6
├── language-ini@1.19.0
├── language-kotlin@0.5.0
├── language-latex@1.1.1
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-clang@4.1.2 (disabled)
├── linter-ui-default@1.7.1 (disabled)
├── nuclide@0.301.1
├── nuclide-format-js@0.0.45
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── tool-bar@1.1.7
└── you-complete-me@0.8.0 (disabled)
```

Thank you very much in advance.

**Comment by pelmers** [comment]
Hi, if this is still a problem -- how did you generate the compile_commands.json? Do you have a reproducing example?
