### ISSUE TITLE
nuclide-server dying with uncaughtException: Unexpected token p in JSON at position 0 SyntaxError: Unexpected token p in JSON at position 0

### ISSUE THREAD

**Issue by jjh42** [facebook/nuclide#1517]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

Start nuclide remote (persisted for a few versions, currently on 0.299.0).

### Expected Behavior

Server is stable.

### Actual Behavior

Every few hours remote server dies (and remote log shows)

[2018-05-06T07:24:51.750Z] [FATAL] nuclide-server - uncaughtException: Unexpected token p in JSON at position 0
SyntaxError: Unexpected token p in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.req.on (/usr/lib/node_modules/nuclide/modules/atom-ide-debugger-python/RemoteDebuggerCommandService.js:116:34)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 1: node::Abort() [node]
 2: 0x11e8359 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0xb7a9ac [node]
 5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 6: 0x2a03fe3042fd

### Versions
* Atom: 1.26.1
* Nuclide: 0.299.0
* Client OS: Mac
* Server OS (optional): Ubuntu

### Additional Details
* Installed packages (`apm ls --installed`):
├── advanced-open-file@0.16.8
├── atom-ctags@5.1.2
├── atom-material-syntax@1.0.8
├── atom-material-syntax-light@0.4.6
├── busy-signal@1.4.3
├── clang-format@1.30.0
├── clipboard-plus@0.5.1
├── file-watcher@1.2.6
├── highlight-selected@0.13.1
├── hugofy@2.0.0
├── intentions@1.1.5
├── language-bazel@0.3.4
├── language-gcl@0.0.2
├── language-hugo@0.5.1
├── language-latex@1.1.1
├── language-lua@0.9.11
├── latexer@0.3.0
├── line-ending-converter@1.3.2
├── linter-glint@0.2.0
├── merge-conflicts@1.4.5
├── minimap-find-and-replace@4.5.2
├── minimap-highlight-selected@4.6.1
├── nuclide@0.299.0
├── pane-info@1.0.0
├── pdf-view@0.69.0
├── release-notes@0.53.0
├── revert-buffer@0.6.0
├── ssh-config@0.13.0
└── sync-settings@0.8.6

**Comment by Blake1985** [comment]
Ok I was just runnin it threw there I bout it off let go. Com an it was giving me problems with pushing the buttons an I read where u could get the old messages out an all

**Comment by Blake1985** [comment]
It seem like whatever y’all did the buttons will push I’m a country boy I don’t even speak y’all language

**Comment by jjh42** [comment]
It may be this crash occurs when I have  poor network connectivity / like the dropped connection results in an incomplete message or something? I'm not sure.

**Comment by mostafaeweda** [comment]
Please update to the latest nuclide and re-open with reproduce steps as this stack trace doesn't yield code on the line.

I'm also wondering if you have something that sends text/non-json to `localhost:9615` as that port is taken by nuclide to enable python auto-attach debugging: https://github.com/facebook/nuclide/blob/master/modules/atom-ide-debugger-python/RemoteDebuggerCommandService.js#L39

**Comment by jjh42** [comment]
thanks. is there an easy way to disable the python debugger so that port
never gets opened/ to eliminate that possibility.

jj

**Comment by mostafaeweda** [comment]
Yes, in nuclide's atom's package settings, expand the last section `Enabled Features` to find the option to do so:
<img width="797" alt="screenshot 2018-05-31 17 38 22" src="https://user-images.githubusercontent.com/264320/40815200-97a43a82-64f9-11e8-9499-8e796f6d7245.png">

Change that to `Never` and it'd disable that sub-package.
