### ISSUE TITLE
Flow annotations break some syntax highlighting

### ISSUE THREAD

**Issue by bradencanderson** [facebook/nuclide#152]
Flow annotations can occasionally break Atom's built-in JS syntax highlighting:

![syntax_hl_ss](https://cloud.githubusercontent.com/assets/5060341/8832042/54573e9e-305b-11e5-8d14-129fddbf3377.png)

Seems weird.

**Comment by cbosuna** [comment]
You might try using something like https://atom.io/packages/language-babel.  Let me know if ti works better for you.

**Comment by bradencanderson** [comment]
It does, thanks a bunch!
