### ISSUE TITLE
UnhandledPromiseRejectionWarning cannot find module pty-v0.1.4-node-v57-linux-x64/pty.node

### ISSUE THREAD

**Issue by braxtons12** [facebook/nuclide#1527]
### Issue and Steps to Reproduce

1. install atom-ide-ui, atom-ide-debugger-native-gdb
2. try to launch a debugger for an application
(node:8037) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module '/home/braxton/.atom/packages/atom-ide-debugger-native-gdb/node_modules/nuclide-prebuilt-libs/pty/build/pty-v0.1.4-node-v57-linux-x64/pty.node'

I've tried un-installing/reinstalling, rebuilding, etc. Nothing has solved the problem.

### Versions
* Atom: 1.26.1 x64
* Atom-IDE: atom-ide-ui 0.11.1
* Client OS: Manjaro KDE x64

### Additional Details
* Installed packages (`apm ls --installed`):
├── Warm-Dark-syntax@0.1.0
├── atom-clock@0.1.16
├── atom-ide-dark-syntax@0.1.2
├── atom-ide-debugger-native-gdb@0.7.2
├── atom-ide-debugger-node@0.7.1
├── atom-ide-debugger-ocaml@0.7.1
├── atom-ide-debugger-python@0.7.1
├── atom-ide-debugger-react-native@0.7.1
├── atom-ide-ui@0.11.1
├── autocomplete-cmake@0.3.1
├── autocomplete-glsl@0.2.3
├── autocomplete-java@1.2.7
├── autocomplete-json@5.5.2
├── build@0.70.0
├── build-cmake@0.11.0
├── busy-signal@1.4.3
├── color-picker@2.3.0
├── dark-flat-ui@1.2.4
├── dark-syntax@0.0.2
├── darker-one-dark-syntax@1.0.4
├── highlight-selected@0.13.1
├── ide-cquery@0.11.1
├── ide-css@0.3.0
├── ide-go@0.7.0
├── ide-html@0.4.2
├── ide-json@0.2.1
├── ide-standardjs@0.0.1
├── ide-vala@0.2.0
├── intentions@1.1.5
├── language-cmake@1.1.0
├── language-glsl@2.0.4
├── language-hlsl@1.2.0
├── minimap@4.29.8
├── minimap-bookmarks@0.4.2
├── minimap-codeglance@0.4.7
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── minimap-pigments@0.2.2
├── minimap-selection@4.5.0
├── neutron-dark-syntax@1.0.5
├── neutron-dark-ui@2.1.4
├── one-dark-dim-syntax@0.1.0
├── project-viewer@1.3.1
├── slim-dark-ui@0.12.0
├── snow-dark-syntax@0.1.1
├── two-dark-ui@1.0.2
├── vs-like-dark-syntax@1.0.0
└── zhk-dark-syntax@0.3.1

**Comment by pelmers** [comment]
The cause is a node version mismatch, we only distribute the prebuilt binary for node v7. for a fix see facebook/nuclide#1431
