### ISSUE TITLE
Not able to run debugger for c++ (lldb)

### ISSUE THREAD

**Issue by shanky061** [facebook/nuclide#1531]
### Issue and Steps to Reproduce
Not able to launch debugger for Native - LLDB (C/C++).

* open a c++ source file
* then try to launch debugger
* provide provide full path of program and cwd
* click launch
* check console error in developer tools

### Expected Behaviour
Debugger should be started with given arguments

### Actual Behaviour
Nothing. It throws error in console.

![screen shot 2018-05-12 at 9 30 14 pm](https://user-images.githubusercontent.com/6399773/39959270-e5a2daf8-562c-11e8-8f6b-fdb00a2c0cc9.png)

### Versions
* Atom: 1.26.1 x64
* Nuclide: 0.302.0
* Client OS: macOS 10.13.4

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (32) /Users/shanky061/.atom/packages
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── autocomplete-modules@2.0.0
├── build@0.70.0
├── busy@0.7.0
├── busy-signal@1.4.3
├── duotone-dark-sea-syntax@2.1.0
├── duotone-light-syntax@2.1.0
├── file-icons@2.1.20
├── go-plus@5.8.3
├── go-signature-statusbar@1.2.3
├── highlight-selected@0.13.1
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.7
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter-eslint@8.4.1
├── native-ui@0.26.1
├── nuclide@0.302.0
├── oceanic-next@1.0.0
├── set-syntax@0.4.0
├── seti-syntax@1.1.3
├── seti-ui@1.10.0
├── sort-lines@0.18.0
└── tool-bar@1.1.7

**Comment by ebluestein** [comment]
Do you have LLDB installed and in your PATH?

**Comment by shanky061** [comment]
yes, it is. Let me know if need more information. Is it working for you ?

**Comment by dragostis** [comment]
I'm having the exact same issue. `lldb` is definitely in the `PATH`.

**Comment by dragostis** [comment]
I don't really understand how it can fail launching `lldb-vscode` command. Am I supposed to have this binary installed?

**Comment by dragostis** [comment]
I `ln -s`ed `lldb` to `lldb-vscode` and it does seem to make a difference. Now I'm getting that it 'Failed to configure debugger'.

**Comment by velocityboy** [comment]
Can you run the gdb native debugger?

**Comment by dragostis** [comment]
I haven't set it up yet, but gdb seems to at least fail because of permissions. My use case, however, requires LLDB.

**Comment by dragostis** [comment]
Reading [this](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-debugger-vsp/package.json), it seems like it's trying to run VSCode's LLDB debugger, which is fine, but I'm not sure whether it comes packaged with Nuclide or not.

**Comment by ebluestein** [comment]
Unfortunately, it is not possible to launch LLDB debugging with the open source version of Nuclide at this time. This functionality requires the lldb-vscode module, which is not available yet. 

A PR is pending to open source lldb-vscode here: https://reviews.llvm.org/D50365

**Comment by dragostis** [comment]
@ebluestein Does this just work right now or do I need to install lldb-vscode separately?

**Comment by ebluestein** [comment]
You'll need to build and install lldb-vscode.  Instructions for building LLDB can be found here:
https://lldb.llvm.org/build.html

You can then build lldb-vscode using `ninja lldb-vscode`.  The resulting binary must be available in your $PATH for Nuclide to find it.

**Comment by dragostis** [comment]
@ebluestein, does lldb-vscode support running `rust-lldb` instead of `lldb`? This is just a thing wrapped on top of `lldb` for pretty-printing Rust-specific types.

**Comment by ebluestein** [comment]
@dragostis Rust support is not something we've looked into (yet) but might in the near future. Rust-lldb actually just sets up some type formatters for LLDB and then starts debugging. You can probably import those type formatters after starting debugging in Nuclide.  The Nuclide console allows you to run LLDB commands directly by prefixing them with a backtick ( ` ).

It runs 3 commands like this:

```
script_import="command script import \"$RUSTC_SYSROOT/lib/rustlib/etc/lldb_rust_formatters.py\""
category_definition="type summary add --no-value --python-function lldb_rust_formatters.print_val -x \".*\" --category Rust"
category_enable="type category enable Rust"
```

**Comment by dpo** [comment]
@ebluestein FWIW, the current Homebrew formula for `llvm` builds `lldb-vscode` with
```
brew install llvm --HEAD --with-lldb
```
However, on macOS, the resulting lldb isn't linked to a standard search path because it conflicts with the one shipped with Xcode. It would be great if there were a way to indicate where the debugger is located in Nuclide (I didn't find any such option).
