### ISSUE TITLE
No scrolling in directory tree

### ISSUE THREAD

**Issue by heyakyra** [facebook/nuclide#1532]
### Issue and Steps to Reproduce
Scrolling is not possible in the directory tree. The "add project..." and "add remote..." buttons are also cut off (only half of them show, and expanding the tree view only expands the buttons as well). This is a file tree bug #27 

### Expected Behavior
Being able to scroll

### Actual Behavior
Can't scroll

### Versions
* Atom: 1.21, 1.22, 1.23
* Nuclide: 0.273
* Client OS: Fedora 28

### Additional Details
* Installed packages (`apm ls --installed`): all community package are disabled

**Comment by matthewwithanm** [comment]
Hey @heyakyra! Sorry we let this slip through the cracks 😞

We've made a lot of File Tree improvements since you opened the issue (and haven't had any other reports) so I'm going to close it. Let us know if it's still an issue on the latest version.
