### ISSUE TITLE
Where is the React Native Compile & Simulator Toolbar

### ISSUE THREAD

**Issue by AdamBrodzinski** [facebook/nuclide#154]
After watching the F8 talk on tooling and Nuclide I wanted to try it out to consider ditching Vim... However I can't find the plugin for React Native toolbar... is this hidden or not released? I couldn't find any documentation on it either.

**Comment by simonwelsh** [comment]
See #31.

**Comment by AdamBrodzinski** [comment]
Ah, thanks @simonwelsh ! I'm closing as this is a dupe
