### ISSUE TITLE
Can't scroll issues in diagnostics. 

### ISSUE THREAD

**Issue by rostislav-simonik** [facebook/nuclide#1540]
### Issue and Steps to Reproduce
After upgrading nuclide to 0.305 scrolling in diagnostics is not possible. 

### Versions
* Atom: 1.27.1 x64
* Nuclide: 0.305.0
* Client OS: Mac HighSiera
* Server OS (optional):

**Comment by aparedes** [comment]
Can't scroll in 0.307.0 either

**Comment by matthewwithanm** [comment]
alright, tracked it down to 3689ab2273f06dea07bd427670a48b4e21f45ecf! @rholinshead's gonna get a fix together.

**Comment by rholinshead** [comment]
A fix for this was made in f6f0d1d9f4e9ab64178a5512117bb5dda10c1725 and released in v0.311.0

Thanks for reporting it!
