### ISSUE TITLE
error on node-gyp rebuild

### ISSUE THREAD

**Issue by RyanSalih** [facebook/nuclide#1545]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

> fsevents@1.2.4 install /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents
> node install

Failed to execute '/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/node /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp configure --fallback-to-build --module=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64/fse.node --module_name=fse --module_path=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64 --node_abi_napi=electron-v1.7 --python=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh' (1)

> runas@3.1.1 install /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/runas
> node-gyp rebuild

/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9
└── (empty)

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-electron-v1.7-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and electron@1.7.15 (electron-v1.7 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "configure" "--fallback-to-build" "--module=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64/fse.node" "--module_name=fse" "--module_path=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64" "--node_abi_napi=electron-v1.7" "--python=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh"
gyp ERR! cwd /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/node /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp configure --fallback-to-build --module=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64/fse.node --module_name=fse --module_path=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64 --node_abi_napi=electron-v1.7 --python=/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/fsevents
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/node_modules/nuclide/node_modules/runas
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/package.json'
npm WARN graphql-language-service-utils@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service@1.1.2 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN relay-runtime@1.6.0 requires a peer of relay-compiler@1.6.0 but none was installed.
npm WARN graphql-language-service-interface@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service-server@1.1.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN graphql-language-service-types@1.1.0 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none was installed.
npm WARN apm-install-dir-11852-10512-1uzeea.0ex6m0lik9 No description
npm WARN apm-install-dir-11852-10512-1uzeea.0ex6m0lik9 No repository field.
npm WARN apm-install-dir-11852-10512-1uzeea.0ex6m0lik9 No README data
npm WARN apm-install-dir-11852-10512-1uzeea.0ex6m0lik9 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/nuclide/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! Darwin 17.3.0
npm ERR! argv "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/AppTranslocation/69A20EF7-0EFA-4D06-AFCE-D25543317D64/d/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/ryansaleh/.atom/.apm/.apmrc" "--userconfig" "/Users/ryansaleh/.atom/.apmrc" "install" "/private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/d-11852-10512-pinz7v.2hz146lxr/package.tgz" "--runtime=electron" "--target=1.7.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs runas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/85/8q_b6snx3xqgb5kzp4rq9gs40000gn/T/apm-install-dir-11852-10512-1uzeea.0ex6m0lik9/npm-debug.log
npm ERR! code 1

### Versions
* Atom: 1.27.2
* Nuclide: 0.307.0
* Client OS: 10.13.2
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by theGhostJW** [comment]
same issue for me:
OS:           win 10.0.17134 Build 17134
Atom:       1.27.2
Nuclide:   0.305.0 => Updating to “nuclide@0.307.0” failed.

**Comment by hansonw** [comment]
see #1541 - you'll need to downgrade to v303 for now.

**Comment by dnmnkdsj** [comment]
Pyg is only support python version from 2.5.0 to 3.0.0, so if you have the wrong version of python, you will meet this problem.
And if you have different versions of python, you will also meet this problem, which is because of node-gyp's stupid setup way: ** node-gyp use a file called python-interceptor.sh to call your python program, and the command is static written in the sh file **.
You may use python2.7 by command python2 in your shell, then you can use python2 in gyp too, by change "python" to "python2" in line37 and line40 in python-interceptor.sh(which can be found in your apm log), then problem solved.
See also https://github.com/danielgtaylor/atom-api-blueprint-preview/issues/38#issuecomment-430852308
