### ISSUE TITLE
Attaching a debugger to a node server port: 8080

### ISSUE THREAD

**Issue by adtm** [facebook/nuclide#1549]
### Issue and Steps to Reproduce
I am running a koa.js server with node on port 8080 (the URL looks like: `localhost:8080/random/api` ). And I cannot attach a debugger instance to the specified port.

### Expected Behavior
I should be able to attach a debugger to node process instance on port 8080.

### Actual Behavior
I get an error: `sudo: no tty present and no askpass program specified`. 
Also, in my terminal console, I see that nuclide tried to access `/json` endpoint and got 404.

### Versions
* Atom: 1.27.2
* Nuclide: 0.3111.0
* Client OS: macOS High Sierra

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-beautify@0.32.5
├── atom-clock@0.1.16
├── atom-jest-snippets@2.1.0 (disabled)
├── autocomplete-modules@2.0.0
├── browser-plus@0.0.98
├── build-npm-apm@0.12.0
├── busy-signal@1.4.3
├── carbon-now-sh@2.0.3
├── color-picker@2.3.0
├── docblockr@0.13.7
├── emmet@2.4.3
├── file-icons@2.1.21
├── git-blame@1.7.0
├── git-history@3.3.0
├── highlight-selected@0.13.1
├── hyperclick@0.1.5
├── intentions@1.1.5
├── js-hyperclick@1.13.0
├── language-babel@2.85.0
├── language-ethereum@0.3.9
├── language-graphql@0.10.1
├── language-haskell@1.17.7
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── linter-solidity@0.5.0
├── linter-tslint@1.9.1
├── linter-ui-default@1.7.1
├── nuclide@0.311.0
├── nuclide-format-js@0.0.46
├── open-in-browser@0.5.2
├── platformio-ide-terminal@2.8.1
├── prettier-atom@0.54.0
├── react@0.18.0 (disabled)
├── react-snippets@1.1.1
├── readme@2.0.0
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── tool-bar@1.1.7
└── tree-view-copy-relative-path@1.2.0

**Comment by pelmers** [comment]
Hi, are you trying to debug the node process? I'm not familiar with koa.js but in general you need to launch node with `--inspect=<debug port>`, then that debug port is where you point the debugger. Make sure you're not trying to debug the port for the HTTP endpoint.

**Comment by adtm** [comment]
Everything is now working, after trying and trying, the debugger attached. Thank You very much!
