### ISSUE TITLE
atom-ide-debugger-java Not Installing on Windows

### ISSUE THREAD

**Issue by collinarnett** [facebook/nuclide#1551]
### Issue and Steps to Reproduce
I'm trying to get the atom-ide-debugger-java module installed on my windows machine (yes I know windows is not officially supported); however I am running into a few issues before I expect to:

Things I've tried:

1. As listed on the README.md I've run `apm install` atom-ide-debugger-java folder in the  with the following error message:

![image](https://user-images.githubusercontent.com/38230482/41378623-9c957a72-6f2d-11e8-8567-3cd705c0c612.png)

2. I tried `apm link`, which put the package in atom but did not seem to do anything since the package had not been built.

Has anyone had any success getting this package installed on windows?
### Expected Behavior
installed atom-ide-debugger java

### Actual Behavior
error as shown above

### Versions
* Atom: 1.27.2
* Nuclide: 0.315.0
* Client OS: Windows 10 Pro
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (26) C:\Users\Collin\.atom\packages
├── atom-beautify@0.32.5
├── atom-ide-debugger-java@0.7.1-dev
├── atom-ide-ui@0.12.0 (disabled)
├── atom-section-divider@1.0.3
├── file-icons@2.1.21
├── highlight-selected@0.13.1
├── Hydrogen@2.5.0
├── ide-java@0.8.3
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.7
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.315.0
├── nuclide-format-js@0.0.45
├── script@3.18.1
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── tone-syntax@0.2.2
└── tool-bar@1.1.7

**Comment by ebluestein** [comment]
Sorry, unfortunately installing this package standalone from source is not supported yet. You'll need to install Nuclide if you want to use the Java debugger at this time.
