### ISSUE TITLE
Diff View not working

### ISSUE THREAD

**Issue by marekcirkos** [facebook/nuclide#1556]
### Issue and Steps to Reproduce
I am using mercurial with nuclide, when I edit any file and then try to trigger "Diff View" from Tree File nuclide:
- Opens new files tap with name "atom:/nuclide/diff-view?file=[full_file_path]&onlyDiff=true"
- ask for password without any reason
- regardless if enter a password, it fails due to "Unable to save file: Permission denied '/atom:'"

Note:
Blame, changed file list, and gutter notes work fine.

### Expected Behavior
Tab with proper diff view should be open

### Actual Behavior
Tab with empty content is opened

### Versions
* Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

* Nuclide: 0.315.0
* Client OS: OSX
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (2) /Users/marko/.atom/packages
├── file-icons@2.1.21
└── nuclide@0.315.0

**Comment by kevwil** [comment]
I'm having the same problem, has this been fixed? What was the cause?
