### ISSUE TITLE
macOS + User with relocated home directory throws dscl error

### ISSUE THREAD

**Issue by michaelrommel** [facebook/nuclide#1561]
### Issue and Steps to Reproduce
In the Atom Nuclide IDE, when a Terminal is opened, it throws an error, because my home directory is not /Users/username, but instead in /Volumes/Othervolume/username.

This is because the dscl command in line 149 in `.atom/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/pty-service/PtyService.js` uses `homedir`. By using the official directory `/Users/username` it correctly provides the shell.

### Expected Behavior
$ dscl . -read /Users/username/ UserShell
UserShell: /bin/bash

### Actual Behavior
$ dscl . -read /Volumes/Datapartition/Users/username UserShell
read: Invalid Path
<dscl_cmd> DS Error: -14009 (eDSUnknownNodeName)

### Versions
* Atom: 1.28.0. x64
* Nuclide: 0.317.0
* Client OS: Mac OS X El Capitan

I fixed it for me with
```
    const output = await (0, (_process || _load_process()).runCommand)('dscl', ['.', '-read', '/Users/'+username, 'UserShell']).toPromise();
```

It is a cosmetic issue, no priority in fixing.

**Comment by pelmers** [comment]
If you write ~/.nuclide-terminal.json file with your preferred default shell then it should skip us calling dscl to derive it: https://nuclide.io/docs/features/terminal/#custom-shell

**Comment by michaelrommel** [comment]
OK, thanks for the hint! I added this to my environment, it works okay for me. I am closing this issue, maybe you will find a universal way to autodetect the shell in those edge cases like mine on a Mac.
