### ISSUE TITLE
nuclide terminal enter a multi-line display question

### ISSUE THREAD

**Issue by Lwenli1224** [facebook/nuclide#1567]
###  nuclide terminal usage issue
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

### Expected Behavior
I hope the command line experience will be better

### Actual Behavior
Enter a command

### Versions
* Atom: v1.28.0
* Nuclide: 0.319.0
* Client OS: macOS V10.13.5

### Additional Details
The first line of commands entered when using terminal cannot be put down to the second line. the first line of commands cannot be seen.
``
First Line command

![first](https://user-images.githubusercontent.com/16096724/42092966-5c3d904c-7bdd-11e8-8cf0-abb3da65fbf9.png)

The first line disappeared when input to the second line

![second](https://user-images.githubusercontent.com/16096724/42093032-911f8360-7bdd-11e8-8424-603bd4af5171.png)

**Comment by pelmers** [comment]
I can't reproduce this issue, can you check your shell's wraparound mode setting?

refer to https://github.com/xtermjs/xterm.js/issues/1359 for detail
