### ISSUE TITLE
Error getting default shell on clicking "New Terminal Button"

### ISSUE THREAD

**Issue by manavdahra** [facebook/nuclide#1568]
Hi,
I just recently updated my nuclide package in atom and I am getting this issue.

### Issue and Steps to Reproduce
1. Click on "New Terminal Button" on top left
2. Terminal opens in a new tab
3. Check the message it prints on terminal screen

### Expected Behavior
Shouldn't get this error message

### Actual Behavior
Got this error in terminal tab
```
Error getting default shell:
ProcessExitError: "dscl" failed with exit code 56

                                                 <dscl_cmd> DS Error: -14136 (eDSRecordNotFound)


                                                                                                dscl . -read /Users/manav UserShell
```

### Versions
* Atom: 1.28.0
* Nuclide: 0.319.0
* Client OS: Mac OS High Sierra 10.13.1
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (21) /Users/manav/.atom/packages
├── MagicPython@1.0.12
├── atom-beautify@0.32.5
├── file-icons@2.1.21
├── highlight-selected@0.13.1
├── ide-typescript@0.7.6
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.319.0
├── nuclide-format-js@0.0.46
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.7 

Additional info:
I use iTerm + zsh on my system. Could that be the source of issue ?

**Comment by pelmers** [comment]
Looks similar to #1561, a workaround is to write a ~/.nuclide-terminal.json config to specify a shell which would avoid the call to `dscl`.
Documentation: https://nuclide.io/docs/features/terminal/#custom-shell
