### ISSUE TITLE
Nuclide-remote Permission change on save v0.0.25

### ISSUE THREAD

**Issue by arsenx** [facebook/nuclide#157]
After updating both the server side and client side nuclide packages, save permissions are being altered upon save.

What was once a `-rw-r--r--` file becomes `-rw-------`

Some more data I can provide would be that I use nuclide-server-start -k because of issue #130

**Comment by bolinfest** [comment]
Are you still the owner of the file? Are you running the server as yourself or root?

**Comment by arsenx** [comment]
The ownership of the file remains the same but permissions pass from 644 to 600
And to answer the question the server is running on the same user as the file owner which are me and not root.

**Comment by bolinfest** [comment]
@arsenx Thanks for the detailed bug report! I suspect this was introduced by https://github.com/facebook/nuclide/commit/32bdf743e423b3643b464a43080954a91542f7d1. I'll get a fix out ASAP.

What Linux distro are you running the server on? I'm curious if there's anything special about your temp directory.

**Comment by arsenx** [comment]
Thank you very much @bolinfest 
I'm running this on clean Debian 8 installation.

**Comment by bolinfest** [comment]
@arsenx I believe that https://github.com/facebook/nuclide/commit/b16f67a0216d6f7483a25c585a5a17d7470569ba should fix your issue if you're willing to build `nuclide-server` from source.

**Comment by bolinfest** [comment]
@arsenx I'm pushing v0.0.26 out right now.

**Comment by bolinfest** [comment]
v0.0.26 is out. Closing. Feel free to reopen if you still see an issue.

**Comment by arsenx** [comment]
I am confirming that v0.0.26 fixes the issue.

Thank you for addressing to the issue so quickly @bolinfest
