### ISSUE TITLE
Search for commands is hardly usable

### ISSUE THREAD

**Issue by Maaartinus** [facebook/nuclide#1573]
### Issue and Steps to Reproduce
Press `Ctrl+Shift+P` and enter `sort` in the search box.

### Expected Behavior
Expecting to be able find commands like "sort lines" and similar (used from Emacs: `M-x sort <tab>`).

### Actual Behavior
Getting a big list of things like
- Nuclide Js Imports Toggle Provider
- Nuclide Ios Simulator Logs: Start

### Comment
I do understand how the search works, but this make it unusable. I'm proposing to either
- add a toggle between this smart search and a standard one
- or sort the exact matches first
- or make Ctrl-F search in the list

### Versions

* Atom: Version number atom 1.26.1
* Nuclide: Version number nuclide@0.303.0 
* Client OS: Ubuntu 18.04

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (7) /home/maaartinus/.atom/packages
├── busy-signal@1.4.3
├── expand-region@0.4.2
├── intentions@1.1.5
├── language-babel@2.85.0
├── linter@2.2.0 (disabled)
├── linter-ui-default@1.7.1 (disabled)
└── nuclide@0.303.0

**Comment by hansonw** [comment]
Ctrl+Shift+P isn't something that Nuclide provides - that's https://github.com/atom/command-palette.
