### ISSUE TITLE
code diagnostics reporting valid syntax as invalid, and expecting invalid syntax

### ISSUE THREAD

**Issue by kaleidoc0de** [facebook/nuclide#1577]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

when attempting array destructuring with the list function on an associative array code diagnostics reports an error

example code
`$a_array = array("foo" => "foo", "bar" => "bar");
list("foo" => $foo, "bar" => $bar) = $a_array;`

### Expected Behavior
no error message to be reported

### Actual Behavior
error message reported:
syntax error, unexpected T_DOUBLE_ARROW, expecting T_DOUBLE_COLON

### Versions
* Atom: 1.28.2
* Nuclide: 0.323.0
* Client OS: Ubuntu 18.04 LTS 

### Additional Details
HipHop VM 3.21.0 (rel)
php-linter 1.5.1

**Comment by mostafaeweda** [comment]
Nuclide is only surfacing the linter results.
I see you're using `php-linter` which looks non-happy with that syntax.
cc @ljw1004 @arxanas

**Comment by arxanas** [comment]
If php-linter just relays the syntax errors from HHVM, then this will happen because HHVM doesn't support the double-arrow syntax in `list` expressions. I don't believe there are any plans to add it to HHVM, so you'll have to either not use this syntax or not use HHVM.
