### ISSUE TITLE
Failed to start debugger process: Transport unexpectedly closed

### ISSUE THREAD

**Issue by BlueSkyInwind** [facebook/nuclide#1578]
### Issue and Steps to Reproduce

 Q1: When I wanted to debug, the console reported an error ： Failed to start debugger process: Transport unexpectedly closed
 Q2:  When I entered metro start at CMD + shift + p, there was no response

### Expected Behavior

I expect to debug my RN project in my ide

### Actual Behavior

I have been studying RN for a week, but I have been unable to debug since atom + nuclide was installed automatically

### Versions
* Atom:  1.28.2
* Nuclide:  0.324.0
* Client OS:  macOS 10.13.6
* Server OS (optional):

### Additional Details
├── atom-ctags@5.1.2
├── atom-react-autocomplete@0.1.10
├── atom-react-native-style@0.2.0
├── autocomplete-js-import@1.4.0
├── autocomplete-json@5.5.2
├── autocomplete-modules@2.1.0
├── autocomplete-paths@2.12.2 (disabled)
├── busy-signal@1.4.3
├── color-picker@2.3.0
├── emmet@2.4.3
├── emmet-jsx-css-modules@1.0.0
├── es6-javascript@1.0.0
├── file-icons@2.1.22
├── highlight-selected@0.14.0
├── intentions@1.1.5
├── javascript-snippets@1.2.1
├── js-hyperclick@1.13.0
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-javascript-jsx@0.3.7
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-jshint@3.1.8
├── linter-ui-default@1.7.1
├── minimap@4.29.8
├── nuclide@0.324.0
├── nuclide-format-js@0.0.46
├── pigments@0.40.2
├── react@0.18.0 (disabled)
├── react-es6-snippets@0.3.0
├── react-native-snippets@0.3.0
├── react-snippets@1.1.1
├── set-syntax@0.4.0
├── simplified-chinese-menu@5.3.5
├── sort-lines@0.18.0
└── tool-bar@1.1.7

**Comment by pelmers** [comment]
thanks for report @BlueSkyInwind. could you share your react native version as well?

It's probably time to update https://github.com/pelmers/vscode-react-native/tree/nuclide again...

**Comment by BlueSkyInwind** [comment]
"dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0"
  },

**Comment by pelmers** [comment]
thanks for the info, I'll go ahead and merge this one with a duplicate: #1576
