### ISSUE TITLE
FileTree will steal focus from text editor

### ISSUE THREAD

**Issue by samuel-ye** [facebook/nuclide#1579]
### Issue and Steps to Reproduce
Enable nuclide file tree feature, the text editor will not get focus to input text, which means unusable at all. Disable nuclide file tree feature, use atom default file tree instead, the text editor pane will behave normally.

### Expected Behavior
Enable nuclide file tree should allow normal text editing functionality

### Actual Behavior
Nuclide file tree prevents the focus in text editor pane

### Versions
* Atom: 1.28.2
* Nuclide: 0.324.0 (0.316.0)
* Client OS: Mac 10.13.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

├── atom-beautify@0.32.5
├── atom-jade@0.3.0 (disabled)
├── atom-material-syntax@1.0.8
├── atom-material-ui@2.1.3
├── atom-ternjs@0.18.3
├── autocomplete-python@1.10.5
├── build@0.70.0
├── build-grunt@0.4.0
├── build-gulp@0.11.0
├── build-xcodebuild@0.2.0
├── busy@0.7.0
├── busy-signal@1.4.3
├── coverage-gutter@0.19.0
├── cucumber@0.6.0
├── dash@1.7.1
├── docblockr@0.13.7
├── escape-utils@0.5.3
├── file-icons@2.1.22
├── file-types@0.5.5
├── gherkin-autocomplete@2.0.0
├── git-plus@8.0.0
├── go-debug@1.6.2
├── go-outline@0.6.7
├── go-plus@5.8.4
├── go-signature-statusbar@1.2.3
├── goto-definition@1.3.4
├── highlight-selected@0.14.0
├── hyperclick@0.1.5
├── intentions@1.1.5
├── javascript-snippets@1.2.1
├── js-hyperclick@1.13.0
├── js-refactor@0.8.1
├── kite@0.99.0 (disabled)
├── language-babel@2.85.0
├── language-docker@1.1.8
├── language-gherkin@1.0.4
├── language-gherkin-i18n@1.3.4
├── language-matlab@0.2.1
├── language-pug@0.0.22
├── language-vue@0.23.1
├── less-than-slash@0.18.0
├── linter@2.2.0
├── linter-clang@4.1.2
├── linter-coffee-variables@0.8.2
├── linter-coffeelint@2.0.0
├── linter-csslint@2.0.1
├── linter-eslint@8.4.1
├── linter-flake8@2.3.0 (disabled)
├── linter-golinter@1.2.2
├── linter-jshint@3.1.8
├── linter-json-lint@0.1.3
├── linter-jsxhint@0.1.2
├── linter-matlab@1.1.0
├── linter-pug@2.0.3
├── linter-pylint@2.1.1 (disabled)
├── linter-shellcheck@1.4.7
├── linter-swagger@0.4.2
├── linter-ui-default@1.7.1
├── markdown-preview-plus@3.3.3
├── markdown-writer@2.7.4
├── minimap@4.29.8
├── minimap-find-and-replace@4.5.2
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.6.1
├── node-debugger@1.10.1
├── nuclide@0.324.0
├── one-dark-vivid-syntax@1.8.1
├── open-in-browser@0.5.2
├── pigments@0.40.2
├── pinegrow-atom@0.3.1
├── project-manager@3.3.6
├── react@0.18.0 (disabled)
├── refactor@0.11.5
├── sonarlint@1.1.0
├── stacktrace@0.0.2
├── symbols-list@2.5.1 (disabled)
├── symbols-tree-view@0.14.0 (disabled)
├── synced-sidebar@0.4.3
├── tool-bar@1.1.7 (disabled)
└── wakatime@7.0.4

**Comment by pelmers** [comment]
@samuel-ye what Atom theme are you currently using? Does the same issue happen with using defaults such as Atom Light/Dark? Also do you have any custom styles defined in .atom/styles.less?

**Comment by samuel-ye** [comment]
@pelmers  Using the Atom Dark still has the focus issue, while previously same problem with the One Dark theme.  And seems no custom styles in the styles.less:

```
/*

 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed and saved.
 *
 * Add your own CSS or Less to fully customize Atom.
 * If you are unfamiliar with Less, you can read more about it here:
 * http://lesscss.org
 */


/*
 * Examples
 * (To see them, uncomment and save)
 */

// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// To style other content in the text editor's shadow DOM, use the ::shadow expression
atom-text-editor::shadow .cursor {
  // border-color: red;
}
```

**Comment by matthewwithanm** [comment]
@samuel-ye Sorry but we haven't been able to repro this or heard any other reports. We're going to close it out, but if you can repro with the latest versions of Atom and Nuclide (and other third party packages disabled), please let us know!
