### ISSUE TITLE
MacBook Pro Touchbar virtual buttons blank

### ISSUE THREAD

**Issue by w-hc** [facebook/nuclide#1582]
### Issue and Steps to Reproduce
If I toggle the tool bar off and then quit atom, the next time atom starts up, the virtual buttons on the Macbook Pro touch bar will be there but appear blank. This is a minor issue.

### Expected Behavior
Even with the tool bar toggled off, the touch bar buttons should still load as per normal.

### Versions
* Atom: 1.28.1
* Nuclide: 0.324.0
* Client OS: Mac OS High Sierra
* Server OS (optional):

**Comment by brianchenlee** [comment]
@w-hc Thanks for filing this! Unfortunately, nobody on the team has the bandwidth to work on this right now. You can file this issue to the provider here: https://github.com/suda/tool-bar
