### ISSUE TITLE
Index.js files hidden as if a part of VCS ignored

### ISSUE THREAD

**Issue by jHwls** [facebook/nuclide#1583]
### Issue and Steps to Reproduce
All files titled `index.js` in `app/web` folders hidden in file tree as if they were included in `.gitignore`—which they are not. Had to untick 'Hide VCS Ignored Paths' under Nuclide Settings > File Tree in order to reveal these files in the file tree.

### Expected Behavior
File tree should show all app files!

### Actual Behavior
File tree hiding/marking as ignored anything named `index.js`.

### Versions
* Atom: 1.28.2
* Nuclide: 0.327.0
* Client OS: High Sierra 10.13.5
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-pair@2.0.13
├── atom-transpose@0.3.5
├── busy-signal@1.4.3
├── change-case@0.6.5
├── file-icons@2.1.22
├── highlight-selected@0.14.0
├── intentions@1.1.5
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haml@0.31.1
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-latex@1.1.1 (disabled)
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── latex@0.50.0 (disabled)
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1 (disabled)
├── linter-rubocop@2.2.3 (disabled)
├── linter-ui-default@1.7.1 (disabled)
├── nord-atom-syntax@0.9.1
├── nord-atom-ui@0.11.0
├── nuclide@0.327.0
├── nuclide-format-js@0.0.47
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── tablr@1.8.3
├── tool-bar@1.1.7
└── wordcount@2.10.4 (disabled)

**Comment by brianchenlee** [comment]
Hey @jHwls can you share your gitignore? cc: @matthewwithanm

**Comment by jHwls** [comment]
Sure, sorry, that would have made sense:

`# App artifacts
/api/_build
/api/db
/api/deps
/api/*.ez

# Generated on crash by the VM
/api/npm-debug.log

# Static artifacts
/api/assets/node_modules

# Since we are building assets from assets/,
# we ignore priv/static. You may want to comment
# this depending on your deployment strategy.
/api/priv/static/

# Files matching config/*.secret.exs pattern contain sensitive
# data and you should not commit them into version control.
#
# Alternatively, you may comment the line below and commit the
# secrets files as long as you replace their contents by environment
# variables.
/api/config/*.secret.exs

# front_end node_modules
/web/node_modules
`

**Comment by matthewwithanm** [comment]
sorry, i can't seem to get this to repro. if you can figure out a repro or could share your global gitignore, please feel free to reopen!
