### ISSUE TITLE
Disabled Nuclide on Windows 10 - Nuclide Menu Item Still exists

### ISSUE THREAD

**Issue by theGhostJW** [facebook/nuclide#1584]
### Issue and Steps to Reproduce
I have disabled the Nuclide package but the Nuclide menu is still there.
It only has the Refactorizer sub menu item.

### Expected Behavior
Expected the menu item to disappear 

### Actual Behavior
As above

### Versions
* Atom: 1.29.0
* Nuclide: 0.328.0
* Client OS: Windows 10
* Server OS (optional):

### Additional Details
├── atom-beautify@0.32.5
├── atom-haskell@0.4.0 (disabled)
├── atom-ide-ui@0.13.0
├── atom-js-console@1.2.2 (disabled)
├── atom-save-all@0.4.1
├── atom-ternjs@0.18.3 (disabled)
├── auto-detect-indentation@1.3.0
├── autocomplete-haskell@1.0.1 (disabled)
├── autocomplete-modules@2.1.0
├── autoprefixer@3.7.1

Is there another package I need to disable?
├── ava@0.11.0
├── browser-plus@0.0.98
├── browser-plus-zoom@0.0.2
├── busy-signal@1.4.3
├── clipboard-plus@0.5.1
├── color-picker@2.3.0
├── copy-find-results@0.1.0
├── docblockr@0.13.7
├── drag-drop-text@0.1.4 (disabled)
├── editorconfig@2.2.2
├── emmet@2.4.3
├── file-icons@2.1.22
├── git-time-machine@2.1.0
├── haskell-ghc-mod@2.2.4 (disabled)
├── haskell-pointfree@0.2.0
├── haskell-scry@1.0.8
├── hasklig@0.4.0
├── hey-pane@1.1.0
├── highlight-selected@0.14.0
├── hyperclick@0.1.5
├── ide-flowtype@0.23.1 (disabled)
├── ide-flowtype-coverage@1.9.2 (disabled)
├── ide-haskell@2.3.1 (disabled)
├── ide-haskell-cabal@2.2.0 (disabled)
├── ide-haskell-hasktags@0.0.15
├── ide-haskell-hie@0.10.1
├── ide-haskell-hoogle@0.1.2
├── ide-haskell-repl@0.8.1
├── ide-purescript@0.24.0 (disabled)
├── intentions@1.1.5
├── language-ansi@1.1.1
├── language-babel@2.85.0
├── language-graphql@0.10.1
├── language-haskell@1.17.8
├── language-haskell-scoped@0.1.1
├── language-ini@1.20.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5 (disabled)
├── language-purescript@0.8.3 (disabled)
├── language-rust@0.4.12
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@2.2.0 (disabled)
├── linter-eslint@8.4.1
├── linter-flow@5.6.1 (disabled)
├── linter-ui-default@1.7.1
├── MagicPython@1.0.12
├── markdown-scroll-sync@2.1.2
├── merge-conflicts@1.4.5
├── minimap@4.29.8 (disabled)
├── minimap-autohide@0.10.1 (disabled)
├── minimap-bookmarks@0.4.2 (disabled)
├── minimap-codeglance@0.4.7 (disabled)
├── minimap-highlight-selected@4.6.1 (disabled)
├── minimap-selection@4.5.0 (disabled)
├── minimap-split-diff@0.3.7 (disabled)
├── navigate@0.1.20 (disabled)
├── navigation-history@0.1.8
├── npm@2.0.0
├── nuclide@0.328.0 (disabled)
├── nuclide-format-js@0.0.47 (disabled)
├── nuclide-test-runner-mocha@0.1.1 (disabled)
├── open-recent@5.0.0
├── path-copy@0.14.0
├── pigments@0.40.2
├── platformio-ide-terminal@2.8.3
├── print-atom@0.1.1
├── quick-step@1.4.0
├── script@3.18.1
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── split-diff@1.5.2
├── Sublime-Style-Column-Selection@1.7.4
├── tablr@1.8.3
├── teletype@0.13.3
├── todo-show@2.3.0
├── tomatimer@1.2.3
├── tool-bar@1.1.7
├── vertical-tabs@1.0.7 (disabled)
└── zentabs@0.8.9

**Comment by ebluestein** [comment]
This is probably coming from atom-ide-ui

Tracked by https://github.com/facebook-atom/atom-ide-ui/issues/287
