### ISSUE TITLE
tree view is slow

### ISSUE THREAD

**Issue by despairblue** [facebook/nuclide#159]
The tree view takes about half a second to handle events, be it mouse clicks or keyboard events.

The screenshot below shows 9 key presses, one even took 1 second.
![screen shot 2015-08-04 at 23 53 44](https://cloud.githubusercontent.com/assets/927609/9073765/176c621c-3b04-11e5-9f83-3f360d5476ec.png)

I also have the whole cpu profile, I'm just not sure where to upload it to.

## Command History

```
  3x -7:17.4 blur (atom-text-editor.editor)
  2x -7:04.7 click (span.nuclide-tree-component-item-arrow)
  2x -7:01.0 blur (div.nuclide-file-tree)
  3x -3:04.4 click (span.icon.name.icon-file-directory)
  2x -2:59.4 blur (div.nuclide-file-tree)
     -2:02.6 core:move-up (div.nuclide-file-tree)
     -2:01.4 core:move-down (div.nuclide-file-tree)
  4x -1:59.6 blur (div.nuclide-file-tree)
 10x -1:53.0 core:move-up (div.nuclide-file-tree)
  2x -1:47.6 blur (div.nuclide-file-tree)
     -0:02.0 command-palette:toggle (div.nuclide-file-tree)
     -0:01.8 blur (div.nuclide-file-tree)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:00.0 bug-report:open (div.nuclide-file-tree)
```

## Versions

* **Atom:**       1.0.3
* **Atom-Shell:** 0.22.3
* **OS:**         Mac OS X 10.10.4
* **Misc**
    * apm  1.0.1
    * npm  2.5.1
    * node 0.10.35
    * python 2.7.6
    * git 2.3.2

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by jssln** [comment]
Hey @despairblue, we are actively working on performance improvements to the file tree. Look out for updates in the next few weeks!

**Comment by despairblue** [comment]
:rocket: Sounds great, I'm looking forward to it :smiley:

**Comment by andrewnester** [comment]
So guys, any updates on tree view perfomance? Looks like issue still there for large projects with lots of files :(

**Comment by bolinfest** [comment]
Yes! We haven't made it part of a public release yet, but if you build from source, try `nuclide-file-tree-deux`: it is much, much faster.

It lacks VCS integration at the moment, but we're working on it.

**Comment by andrewnester** [comment]
@bolinfest great! Sounds cool 😀 Are you planning to add it to public releases? If yes, then when?

**Comment by bolinfest** [comment]
Probably when we have Git support since we don't want to regress folks.
I've posted About this on some of the other issues, but given how atom
package installation works today, it's honestly faster and takes up much
less disk to build Nuclide from source than to do an official install.
We're working to make that better, though.

**Comment by ssorallen** [comment]
The 'nuclide-file-tree' rewrite landed in master a few weeks ago, and the performance is significantly improved. We had seen similar flame charts as @despairblue, but those are no more.

Closing this out. Let me know if you see problems with the new tree.
