### ISSUE TITLE
Nuclide tree-view doesn't support copy/paste across different windows

### ISSUE THREAD

**Issue by stomvi** [facebook/nuclide#1593]
### Issue and Steps to Reproduce
Currently not supporting to copy a file from a window and paste it to a different one.

#440 
I think add a local folder and do the copy/paste is a workaround. But usually it's much easier to work with different folders in separate windows.

**Comment by Dayjo** [comment]
Is this fixed in the latest release (0.345.0) ?

**Comment by captbaritone** [comment]
I don't think we expect to implement this. Sorry for the any frustration this is causing.
