### ISSUE TITLE
Atom failing to apply fix in gutter

### ISSUE THREAD

**Issue by albeanth** [facebook/nuclide#1595]
### Issue
I am testing nuclide as a more developed c++ IDE within atom (which seems pretty sweet by the way 👏 ), and have run into a minor bug. See the screenshot below. To test the gutter/fix feature in Atom, I took off a semicolon on a line in my c++ code. 
![screen shot 2018-08-20 at 4 37 01 pm](https://user-images.githubusercontent.com/18561046/44372221-c52edd80-a497-11e8-9eec-eba49e69621b.png)

### Expected Behavior
I expected that by hitting the fix button, the semicolon would have been added. 

### Actual Behavior
Hitting the fix button and following the message (saving to get fresh results and trying again) didn't do anything.

### Versions
* Atom    : 1.29.0
* Electron: 2.0.5
* Chrome  : 61.0.3163.100
* Node    : 8.9.3
* Nuclide: 0.337.0
* Client OS: MacOS 10.13.6

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (19) /path/to/.atom/packages
├── autocomplete-moose@0.23.1 (disabled)
├── busy-signal@1.4.3 (disabled)
├── intentions@1.1.5
├── language-latex@1.1.1 (disabled)
├── language-matlab@0.2.1
├── language-moose@0.26.2 (disabled)
├── latex@0.50.0 (disabled)
├── latex-autocomplete@1.1.1 (disabled)
├── latextools@0.8.5 (disabled)
├── linter@2.2.0 (disabled)
├── linter-markdown@5.2.2 (disabled)
├── linter-moose@0.4.0 (disabled)
├── linter-pylint@2.1.1 (disabled)
├── linter-ui-default@1.7.1
├── make-runner@1.1.15
├── nuclide@0.337.0
├── pdf-view@0.71.0 (disabled)
├── platformio-ide-terminal@2.8.4 (disabled)
└── switch-header-source@0.32.0 (disabled)

```

**Comment by pelmers** [comment]
Fixed by https://github.com/facebook/nuclide/commit/f625549e6102e6d3eaa1a20f4f57ab40f204fae7
