### ISSUE TITLE
Wrong log file path in Wiki

### ISSUE THREAD

**Issue by martinraison** [facebook/nuclide#1599]
### Issue and Steps to Reproduce
The log file path in the  wiki's "Logging" page is wrong. I would have made a pull request but apparently it's not supported by Github wiki.

### Expected Behavior
The actual log file path can be found with
```
ls `node -p 'require("os").tmpdir()'`/nuclide-${USER}-logs/nuclide.log
```

### Actual Behavior
The wiki says the log file path is
```
ls `node -p 'require("os").tmpdir()'`/nuclide-${USER}-logs/nuclide.log-`date "+%Y-%m-%d"`
```
When I try this, I get a "no such file or directory" error (because the path is incorrect).

### Versions
* Atom: all
* Nuclide: all
* Client OS: all
* Server OS (optional): all

### Additional Details
* Installed packages (`apm ls --installed`):
N/A

**Comment by pelmers** [comment]
updated, thanks!
