### ISSUE TITLE
Terminal coloring scheme no effect?

### ISSUE THREAD

**Issue by w-hc** [facebook/nuclide#1608]
### Issue and Steps to Reproduce
I try to select different coloring in settings and there seems to be no effect at all on terminal appearance. I wonder whether these buttons are just dummies for now, or it is rather the case that I am using them incorrectly. 

### Expected Behavior
Terminal bg and fg colors should change based on different selections?
My major grievance is that, when using Atom Materials UI, the terminal is reduced to a pale white-greyish blob and I cannot see the command line displayed. That's why I must at least change the bg color to provide contrast for the text.
![screen shot 2018-09-04 at 21 15 45](https://user-images.githubusercontent.com/17956191/45067213-bfd0b600-b087-11e8-8577-b69ff6351cde.png)

### Versions
* Atom: 1.30.0
* Nuclide: 0.345.0
* Client OS: MacOS High Sierra 10.13.6
* Server OS (optional): CentOS

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (31) /Users/redacted/.atom/packages
├── MagicPython@1.0.12
├── atom-clock@0.1.16
├── atom-material-syntax@1.0.8
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.1.3
├── busy-signal@1.4.3 (disabled)
├── city-lights-ui@1.5.3
├── file-icons@2.1.24
├── flatwhite-syntax@0.8.1
├── fonts@3.1.0
├── highlight-selected@0.14.0
├── intentions@1.1.5 (disabled)
├── language-babel@2.85.0
├── language-graphql@0.10.1 (disabled)
├── language-ini@1.20.0
├── language-rust@0.4.12 (disabled)
├── language-scala@1.1.9 (disabled)
├── language-swift@0.5.0 (disabled)
├── linter@2.2.0 (disabled)
├── linter-js-yaml@1.3.0
├── linter-jsonlint@1.3.0
├── linter-pylint@2.1.1 (disabled)
├── linter-swiftc@2.0.0 (disabled)
├── nbviewer@1.0.2 (disabled)
├── nuclide@0.345.0
├── nuclide-format-js@0.0.47
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── tablr@1.8.3 (disabled)
├── tool-bar@1.1.10
└── vim-mode-plus@1.34.0 (disabled)

**Comment by pelmers** [comment]
The color settings in the menu only affect colored output from tools such as `ls`.

You can currently only change the foreground/background with custom CSS. See details at https://github.com/facebook-atom/atom-ide-ui/issues/300.

**Comment by w-hc** [comment]
Hi thank you so much for the help. Is it possible to change the font color as well? The referenced issue only discusses bg color.

**Comment by pelmers** [comment]
Not sure about why it doesn't work on the material ui, the terminal does just pull the 'color' CSS from the terminal-pane div: https://github.com/facebook/nuclide/blob/c77ce65ea50f95e797190a695570de6ed8fb24f0/modules/atom-ide-ui/pkg/atom-ide-terminal/lib/terminal-view.js#L772-L775

**Comment by pelmers** [comment]
Ah, I just tried it and the issue is that the theme uses transparency, which must be enabled separately for the terminal as well.

Go to the nuclide settings (cmd-alt-comma) and find the Allow Transparency option under the Terminal section. Then make sure it's checked.
You can also find this in regular Atom settings under packages > nuclide, but it's a bit harder to find there.

**Comment by w-hc** [comment]
I have enabled this terminal transparency option. But still things are not changed.
My syntax theme is Flatwhite. But I've tried other syntaxes and it goes the same. So I suspect it must be the UI.

<img width="801" alt="screen shot 2018-09-05 at 10 34 15" src="https://user-images.githubusercontent.com/17956191/45104309-6ef8a600-b0f7-11e8-8234-e146a95ee73d.png">

I've restarted Atom several times to make sure the settings are in effect.

**Comment by pelmers** [comment]
I wasn't able to reproduce this case, here's how it looks for me using Material UI + Flatwhite syntax and no custom CSS styles.
![screen shot 2018-09-05 at 4 14 43 pm](https://user-images.githubusercontent.com/2406051/45126170-de39be80-b126-11e8-971f-e61094378cfb.png)

**Comment by w-hc** [comment]
How curious.
You know that by default, ~/.atom/style.less is populated with a few dummy examples like 
```css
// style the background color of the tree view
.tree-view {
  // background-color: whitesmoke;
}

// style the background and foreground colors on the atom-text-editor-element itself
atom-text-editor {
  // color: white;
  // background-color: hsl(180, 24%, 12%);
}

// style UI elements inside atom-text-editor
atom-text-editor .cursor {
  // border-color: red;
}
```
If I comment them out completely, then everything is working.

**Comment by pelmers** [comment]
@w-hc do you have a workaround for the issue?

is there a chance it's related to this bug I filed on vertical split dock items to Atom? https://github.com/atom/atom/issues/17963

**Comment by w-hc** [comment]
Hi, I think there is some relationship. 
I cannot reproduce the bug you reported. 
After poking around, now when I open new terminal, it opens up __not__ as a new bottom pane, but as a new pane just like when I open up a new code pane. 
<img width="594" alt="screen shot 2018-09-07 at 13 58 16" src="https://user-images.githubusercontent.com/17956191/45238054-187d9a00-b2a6-11e8-89f2-4caf9ae203af.png">

I do not know how this actually happened. I just drag them around trying to reproduce your bug.
Under this setup, the command line prompt is displayed correctly.

The trouble is I don't know how to go back. Even the console comes up as a new pane. I miss the bottom pop-up. hahah

**Comment by pelmers** [comment]
The terminal should be serializing the last known location and opening new ones there. If you put a last-opened terminal at the bottom pane and reload Atom, the new ones should go there too.
