### ISSUE TITLE
Autocomplete should respect lint rules.  

### ISSUE THREAD

**Issue by rostislav-simonik** [facebook/nuclide#1611]
I'm not sure whether it is related to nuclide. Point me to right direction in case I'm wrong. 

Currently autocomplete feature doesn't follow eslint rules. E.g. I have rule that all brackets must include space before and after. 

i.e. 
`import { something } from 'package';`

but autocomplete fills:
` import {something} from 'package';`

Thanks.

**Comment by wanderley** [comment]
Unfortunately, `nuclide-js-imports` doesn't know about eslint formating rules, what generates this issue.  It is not in your plans to include this type of option, but I think you can accomplish it with `prettier` and auto-formatting your file when saving it.
