### ISSUE TITLE
Highlight in file tree does not highlight whole filename

### ISSUE THREAD

**Issue by Lixire** [facebook/nuclide#1612]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

Open a workspace with nested folders and long filenames (such that you'd need to side-scroll to read the names). Also happens if you make the component smaller.
### Expected Behavior
Tell us what should happen.

When focused/clicked on a filename, the whole row should be highlighted.

### Actual Behavior
Tell us what happens instead.

The highlight ends at the component window size so when you side-scroll, the rest is not highlighted
![image](https://user-images.githubusercontent.com/13241824/45234669-4b666480-b28b-11e8-9585-cdcf3cc9da83.png)

### Versions
* Atom: 1.28.0
* Nuclide: 0.345.123134661
* Client OS: MacOS High Sierra
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by matthewwithanm** [comment]
Thanks for the report! This should be fixed in the current release (:
