### ISSUE TITLE
Version parity between client and server is overtly strict.

### ISSUE THREAD

**Issue by bdowling** [facebook/nuclide#1613]
### Issue and Steps to Reproduce

Upgrading the client and server when you may have multiple users/locations involved can be extremely challenging with the current 1to1 version parity. 

Are there any plans to adapt the versioning so that the client and server can work within "ranges" and/or only have truly incompatible changes prevent the client from connecting to the server?  I know the current approach may be easier to define/code with the rapid release cycles, but it is not easy on the consumers.
 
### Expected Behavior

A more flexible approach on this would be beneficial.

**Comment by Dayjo** [comment]
Really agree with this. 

Any minor change requires full uninstall and re-install on the server which is quite jarring when there's lots of developers using it.

**Comment by semmypurewal** [comment]
Yeah, we definitely feel your pain. This is, in part, due to our stateful RPC framework.

We've talked a lot about approaches to making this work, but they all involve migrating away from our current approach to RPC. That's a long-term project, though, and won't be finished soon. :(
