### ISSUE TITLE
How can I instal atom-ide-ui?

### ISSUE THREAD

**Issue by Iakubovich** [facebook/nuclide#1614]
I cannot find in atom search "atom-ide-ui". If I type "ide" then there are a lot of results (ide-python; ide-haskell, ect), but there is nothing if I type "atom-ide-ui". What am l doing wrong?

### Versions
* Atom: 1.30.0
* Client OS: WIN10

**Comment by velocityboy** [comment]
Are you searching from the Install tab of settings and it's not showing up?

If it's not there, try doing 'apm install atom-ide-ui' from the command
prompt.

**Comment by Iakubovich** [comment]
Thank you,  'apm install atom-ide-ui' works fine!
