### ISSUE TITLE
CMD+F keyboard functionality defaulting to Find in Project instead of Buffer

### ISSUE THREAD

**Issue by Dayjo** [facebook/nuclide#1622]
### Issue
The functionality of CMD+F has changed in a recent version (not the last, maybe the version before this). The context / top menu works as expected but the keyboard functionality is incorrect.

When opening a file, CMD+F is now opening "Find in Project" the first time you press it, pressing the menu item under `Find > Find in Buffer` works as expected. 

### Steps to Reproduce

![](http://c.dayjo.me/6ca26e7dc6b7/Screen%20Recording%202018-09-27%20at%2004.03%20pm.gif)

1. Click file1 in the file tree
2. Press CMD+F
3. Sometimes this first time it will show correctly the Find in Buffer panel.
4. Click file2 in the file tree (You can precede or follow this with closing the panel pressing ESC).
5. Press CMD+F

### Expected Behavior
Find in Buffer panel is open.

### Actual Behavior
Find in Project panel is open.

### Versions
```
MacOSX High Sierra 10.13.6

Atom    : 1.31.0
Electron: 2.0.7
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.1
npm  6.2.0
node 8.9.3 x64
atom 1.31.0
python 2.7.10
git 2.15.2
```

### Additional Details
One thing I have noticed, that if I select the file from the "Open Files" panel in the tree, it works as expected. Disabling nuclide and reverting to the default tree-view works as expected.

**Comment by pelmers** [comment]
If the active node (i.e. selected DOM node) is in the file tree, then cmd-f opens find in project. That's implemented in https://github.com/facebook/nuclide/blob/d28fa2933206132c4ad691bee7cac535c46130ef/pkg/nuclide-file-tree/lib/registerCommands.js#L244-L247

When you click file in file tree, the active element is still the file tree. Once you click a file, then cmd-f will search in buffer.

**Comment by pelmers** [comment]
and the opened file isn't focused because you have pending panes enabled:
see https://github.com/facebook/nuclide/blob/d28fa2933206132c4ad691bee7cac535c46130ef/pkg/nuclide-file-tree/lib/redux/Epics.js#L92-L99

**Comment by Dayjo** [comment]
Thanks @pelmers! Very useful response, this can be resolved by enabling the `Focus editor on file selection` option;

![](http://c.dayjo.me/3827a2b8f066/Image%202018-10-02%20at%209.53.32%20am.png)

I feel like this functionality has definitely changed as it's just something I noticed started happening with my normal workflow. I believe the default atom file-tree works as my original issue expected.

Happy to close this if this isn't actually changed default functionality.

**Comment by pelmers** [comment]
Good to hear that works, the focus editor option has been in the settings for a while now -- I don't think its behavior changed recently.
