### ISSUE TITLE
Cannot open symlink folders

### ISSUE THREAD

**Issue by w-hc** [facebook/nuclide#1624]
### Issue and Steps to Reproduce
It used to be the case that folders which are symbolic links can be opened just like a regular folder. However, in a few recent updates, symbolic linked folders cannot be opened anymore.

### Expected Behavior
It would be nice if sym-linked folders can just be opened.

### Versions
* Atom: 1.30.0
* Nuclide: 0.353.0
* Client OS: Mac OS Mojave 10.14 (18A391)
* Server OS (optional): CentOS

### Additional Details
* Installed packages (`apm ls --installed`):
```bash
Community Packages (34) /Users/redacted_user_name/.atom/packages
├── MagicPython@1.0.12
├── atom-clock@0.1.16
├── atom-material-syntax@1.0.8
├── atom-material-syntax-light@0.4.6
├── atom-material-ui@2.1.3
├── busy-signal@1.4.3 (disabled)
├── city-lights-ui@1.5.3
├── file-icons@2.1.25
├── flatwhite-syntax@0.8.1
├── fonts@3.1.0
├── gl-light-syntax@3.0.0
├── highlight-selected@0.14.0
├── intentions@1.1.5 (disabled)
├── language-babel@2.85.0
├── language-graphql@0.11.0 (disabled)
├── language-ini@1.20.0
├── language-rust@0.4.12 (disabled)
├── language-scala@1.1.9 (disabled)
├── language-swift@0.5.0 (disabled)
├── linter@2.2.0 (disabled)
├── linter-js-yaml@1.3.0
├── linter-jsonlint@1.3.0
├── linter-pylint@2.1.1 (disabled)
├── linter-swiftc@2.0.0 (disabled)
├── nbviewer@1.0.2 (disabled)
├── nuclide@0.353.0
├── nuclide-format-js@0.0.47
├── pretty-json@2.0.3
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── styri-syntax@0.2.0
├── tablr@1.8.3 (disabled)
├── tool-bar@1.1.10
└── vim-mode-plus@1.34.0 (disabled)
```

**Comment by cs01** [comment]
Thanks for reporting this. It has been fixed in master (https://github.com/facebook/nuclide/commit/a169e082a49d0f59478dd2efd8ffe5bc9e9a42f3), but did not make it into the latest release (v0.354.0). It will be in the next release.
