### ISSUE TITLE
git-diff is disabled, no diff gutters

### ISSUE THREAD

**Issue by IanVS** [facebook/nuclide#1627]
### Issue and Steps to Reproduce
It seems that nuclide [disables](https://github.com/facebook/nuclide/blob/b6cf1b77edfeb0b383e7c443f9b308c04cce8c7b/pkg/nuclide-diff-gutters/lib/main.js#L53) `git-diff`, and so I no longer am getting diff gutters, which I find to be really useful.

### Expected Behavior
I should see colors in the gutter indicating whether a line is removed, added, or changed.

### Actual Behavior
I get no indications.

### Versions
* Atom: 1.32.0-beta1
* Nuclide: 0.354.0
* Client OS: macOS

**Comment by IanVS** [comment]
@tjfryan it looks like you reviewed https://github.com/facebook/nuclide/commit/78255d804d81d7ccdfd213626a8cf35b36860355 which removed git-diff, and https://github.com/facebook/nuclide/commit/405805af1fc7733c2fac6e893709e074d2a6bc9b which seems to attempt to add new ones?  But it seems the new ones aren't working, is there something we have to do to turn them on?

**Comment by shanpls** [comment]
@IanVS This will be fixed in the next release

**Comment by IanVS** [comment]
This doesn't seem to be fixed in `0.362.0`, I still don't have git diff gutters.

**Comment by adrnlHP** [comment]
Yeah definitely still not fixed

**Comment by Boboss74** [comment]
I miss git diff gutters 😭

**Comment by Boboss74** [comment]
@shanpls still not fixed in 0.366.0 :/

**Comment by Boboss74** [comment]
@IanVS
You can see the gutters ? :o

**Comment by Boboss74** [comment]
It's working !

I removed the followed git-diff lines in my ~/.atom/config.cson

```cson
"*":
  core:
    disabledPackages: [
	  "git-diff"
	]
    packagesWithKeymapsDisabled: [
      "git-diff"
    ]
```

Shame on me T-T

**Comment by IanVS** [comment]
Yep, here's a fresh restart of atom, with nuclide enabled:

![image](https://user-images.githubusercontent.com/4616705/48004029-1ab17880-e0de-11e8-9859-6d49cdb12804.png)

Make sure you enable the `git-diff` package, and it seems that nuclide is no longer disabling it.  Can anyone else confirm?

**Comment by sintylapse** [comment]
thanks, @Boboss74 , it worked. Maybe after some nuclide updates this settings were persisted
