### ISSUE TITLE
Attach Debugger on Remote Server

### ISSUE THREAD

**Issue by LaCocoRoco** [facebook/nuclide#1629]
### Issue and Steps to Reproduce
Debugging node.js local works absolutly fine, so i tried to debug on my remote server.
In the attach debugger view @ "Attach debuger to" only localhost is available.
Is there some way to add my remote server for this? 

### Expected Behavior
-

### Actual Behavior
-

### Versions
* Atom: 1.31.2
* Nuclide: v10.11.0
* Client OS: Windows 10
* Server OS (optional): Debian 9

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-beautify@0.33.4
├── file-icons@2.1.25
├── goto-definition@1.3.4
├── highlight-selected@0.14.0
├── language-babel@2.85.0
├── language-graphql@0.11.0
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.354.0
├── nuclide-format-js@0.0.47
├── open-in-browser@0.5.2
├── set-syntax@0.4.0
├── sort-lines@0.18.0
├── sync-settings@0.8.6
├── tool-bar@1.1.10
└── tool-bar-main@0.0.11

**Comment by ebluestein** [comment]
You can add remote connections to Nuclide via the File Tree or the "Connect" button on the breadcrum bar.
