### ISSUE TITLE
Node debugger: breakpoints not working since updating to latest Nuclide version.

### ISSUE THREAD

**Issue by jp-apps** [facebook/nuclide#1634]
### Issue and Steps to Reproduce
Since updating to latest Nuclide version, every time the Debugger is attached to a node.js --inspect instance and you set a breakpoint on any line you get the following console message by the Node Debugger: 

`Error processing "setBreakpoints": Invalid parameters: condition: string value expected `

When you check the console in the Developer Tools you get the following stack trace:

\~/.atom/packages/nuclide/modules/nuclide-debugger-common/VsDebugSession.js:219 Uncaught (in promise) Error: [{_extensionName}] Error processing "{_requestType}": {_stack}

at send.then.errorResponse (~/.atom/packages/nuclide/modules/nuclide-debugger-common/VsDebugSession.js:219)

at \<anonymous\>

at process._tickCallback (internal/process/next_tick.js:188)

send.then.errorResponse @ \~/.atom/packages/nuclide/modules/nuclide-debugger-common/VsDebugSession.js:219

_tickCallback @ internal/process/next_tick.js:188

async function (async)

addUIBreakpoints @ \~/.atom/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/vsp/DebugService.js:1214

toggleSourceBreakpoint @ \~/.atom/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/vsp/DebugService.js:1258

_handleGutterClick @ \~/.atom/packages/nuclide/modules/atom-ide-ui/pkg/atom-ide-debugger/lib/BreakpointDisplayController.js:373

Was able to solve it by downgrading to the previous version I had which was 0.351.0

### Expected Behavior
Not have an error when setting a breakpoint, and have breakpoint working.

### Actual Behavior
Error when setting breakpoint, and breakpoint not working.

### Versions
* Atom: 1.31.2
* Nuclide: 0.357.0
* Client OS: macOS High Sierra 10.13.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── api-docs@0.0.6
├── atom-beautify@0.33.4
├── autocomplete-paths@2.12.2
├── busy-signal@1.4.3
├── emmet@2.4.3
├── intentions@1.1.5
├── linter@2.2.0 (disabled)
├── linter-csslint@2.0.1
├── linter-eslint@8.4.1
├── linter-htmlhint@1.5.1
├── linter-ui-default@1.7.1
└── nuclide@0.351.0

**Comment by LaCocoRoco** [comment]
Thank you my friend! I got the same problem.
Local debugging worked with error "setBreakpoints".
Remote debugging failed with the "forEach" error.
But downgrading on v0.351.0 solved the problem.

**Comment by ebluestein** [comment]
Thanks for reporting and sorry about that! We'll have a fix in for the next release cut
