### ISSUE TITLE
Suggestion: Add release notes in Github releases, CHANGELOG.md or README.md

### ISSUE THREAD

**Issue by blaiprat** [facebook/nuclide#164]
For the past two days Nuclide has been updated with four releases. I've tried to have a look to what's changed and what's fixed by checking Github releases, checking if a CHANGELOG.md exists, looking in the webpage if there's a blog, checking the Facebook group and finally googling if there's an official twitter account. 

The only way I've been able to glimpse a little bit is by checking the commit history, but it's not that clear. It would be great to have some sort of release notes to understand what changed.

**Comment by jssln** [comment]
@blaiprat good point! We'll do this in the next release.

**Comment by bolinfest** [comment]
I was thinking about this last night: thanks for calling us out on it. I'll backfill some notes for the flurry of releases in the last 48 hours.

**Comment by bolinfest** [comment]
It's live!

**Comment by jssln** [comment]
https://github.com/facebook/nuclide/blob/master/CHANGELOG.md

**Comment by blaiprat** [comment]
Awesome, thank you!
