### ISSUE TITLE
I have try to install nuclide package. after that i got this issue

### ISSUE THREAD

**Issue by alina-zubbb** [facebook/nuclide#1645]
### Issue and Steps to Reproduce
I have try to install nuclide package in atom. after that i got issue
http://prntscr.com/lads7l

### Expected Behavior
nuclide package success installed

### Actual Behavior
http://prntscr.com/lads7l

### Versions
* Atom:
* Nuclide:
* Hackintosh MacOS High Sierra:

**Comment by matthewwithanm** [comment]
Hey @alina-zubbb! Sorry for the delay, but this [should be fixed](https://github.com/facebook/nuclide/commit/709edc38194cdb2c41789af2a6a3102cc53cfc7a) 🙂
