### ISSUE TITLE
Output from Eslint missing

### ISSUE THREAD

**Issue by morloy** [facebook/nuclide#1648]
### Issue and Steps to Reproduce
Since a couple of days, all diagnostics output from eslint has disappeared from Nuclide.

No suspicious error messages in the console, so I don’t really know where to look.

### Versions
* Atom: 1.32.0
* Nuclide: 0.362.0
* Client OS: Mac OS X Mojave
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── file-icons@2.1.26
├── highlight-selected@0.14.0
├── language-babel@2.85.0
├── language-graphql@0.11.0
├── language-haskell@1.17.8
├── language-ini@1.20.0
├── language-kotlin@0.5.0
├── language-lua@0.9.11
├── language-ocaml@1.9.5
├── language-rust@0.4.12
├── language-scala@1.1.9
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── nuclide@0.362.0
├── nuclide-format-js@0.0.47
├── set-syntax@0.4.0
├── sort-lines@0.18.0
└── tool-bar@1.1.10
```

**Comment by wellyshen** [comment]
I have the same issue with react-native

**Comment by mostafaeweda** [comment]
We've root-caused this to these lines: https://github.com/facebook/nuclide/blob/228d32d6f4573c52e7c0c72df83583548e18c891/pkg/nuclide-js-imports-client/package.json#L76-L78 & a fix is on its way with the next release.

**Comment by morloy** [comment]
@mostafaeweda Thanks for addressing this issue!
I tried removing the lines manually in `~/.atom/packages/nuclide/pkg/…`, but at least for me this doesn’t have any effect.

**Comment by mostafaeweda** [comment]
I've just released https://github.com/facebook/nuclide/releases/tag/v0.366.0 which has this issue fixed - please update.

**Comment by morloy** [comment]
Just upgraded—still no diagnostics from eslint. Running `node_modules/.bin/eslint  .` on the console shows all the errors, Nuclide doesn’t.

**Comment by mostafaeweda** [comment]
What extension are you using to power the eslint diagnostics? can you help trace the issue down?

**Comment by morloy** [comment]
All right, I reset all Atom settings to try to find the source of this problem. Forgot to re-install the `linter-eslint` package after that 😁
Works fine now, thanks!
