### ISSUE TITLE
Code formatting not working for JavaScript on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by cmbrownfield** [facebook/nuclide#168]
I just removed atom and deleted the .atom directory and reinstalled atom.  I then installed the nuclide-installer package and the linter package.  I opened a JavaScript file and tried formatting it (nothing happened).  I hit ctrl-shift-i and see this message "No code format providers registered for scopeName".  Code formatting works for PHP and Hack files, but I've never gotten it to work for JavaScript.  The nuclide packages show as version 0.0.30.

**Comment by mostafaeweda** [comment]
Indeed, we are still behind on the javascript code format provider.
However, we have a new to-be-released package that cares about providing missed require statements, and formatting the javascipt code on a rule-based model that could be what you are looking for.

**Comment by mostafaeweda** [comment]
I'd close this now and please look for the next release's new package: `format-js`
