### ISSUE TITLE
Nuclide-Type-Hint is a performance killer

### ISSUE THREAD

**Issue by steelbrain** [facebook/nuclide#173]
Not just the editors, it also lagged the settings view for me. You guys need to be a bit efficient there.

**Comment by nmote** [comment]
I've never seen a problem with it. Could you provide a bit more context? Is it possible that you could narrow down the specific type hint provider that seems to be causing you trouble (e.g. hack if you are editing hack code).

**Comment by steelbrain** [comment]
I was using the hack one.

**Comment by nmote** [comment]
Could you explain what evidence you have that suggests nuclide-type-hints is to blame?

**Comment by steelbrain** [comment]
It was a rough guess, nothing too solid. I guessed it by disabling all the provider packages of nuclide and only enabled the core ones.

**Comment by nmote** [comment]
OK, I'm going to close this but if you can provide more details (like a CPU trace) feel free to re-open.

**Comment by steelbrain** [comment]
I am super-streched up between work, will provide more info once I am free.
