### ISSUE TITLE
Can't run nuclide-server-start from client

### ISSUE THREAD

**Issue by MordFustang21** [facebook/nuclide#174]
I can successfully run the command on the server but when it's ran from the connect window it fails.
[user@server ~]$ echo SYNSYN;./home/dlaird/node-v0.12.7-linux-x64/bin/node_modules/nuclide-ser ver/nuclide-start-server -t 60;echo SY NSYN SYNSYN -bash: ./home/dlaird/node-v0.12.7-linux-x64/bin/node_modules/nuclide-server/nuclide-start-server: No such file or directory SYNSYN [user@server ~]$ exit logout

This is the output from when the command is run. I'm not sure what's appending the SYNSYN

**Comment by nmote** [comment]
Have you tried running the entire path from the command line?

```
./home/dlaird/node-v0.12.7-linux-x64/bin/node_modules/nuclide-server/nuclide-start-server
```

The leading `.` looks suspicious to me. I would try removing that from the 'Connect' dialog box.

**Comment by MordFustang21** [comment]
That dot was the problem!
That was the command I was running on the server so I had pasted it into the connect assuming it would work.

Thanks really appreciate the help.
