### ISSUE TITLE
Missing attribution on 'file-watcher'

### ISSUE THREAD

**Issue by lwblackledge** [facebook/nuclide#179]
Hi,

It looks like [nuclide-file-watcher](https://github.com/facebook/nuclide/tree/master/pkg/nuclide/file-watcher/lib) was taken from [file-watcher](https://github.com/lwblackledge/file-watcher).

Could you please add an attribution to [nuclide-file-watcher](https://github.com/facebook/nuclide/tree/master/pkg/nuclide/file-watcher/lib) showing that the code was based on [file-watcher](https://github.com/lwblackledge/file-watcher)?

Thanks.

**Comment by ssorallen** [comment]
cc @mostafaeweda

**Comment by mostafaeweda** [comment]
working on it as of writing this

**Comment by lwblackledge** [comment]
Thanks a lot.

**Comment by mostafaeweda** [comment]
Added in d7e89d2
