### ISSUE TITLE
[format-js] React require should not be removed if JSX is used in file

### ISSUE THREAD

**Issue by Daniel15** [facebook/nuclide#180]
If JSX is used in the file, format-js shouldn't remove the `React` variable, even if React is not directly anywhere in the code.

Example:
```
var React = require('react');

exports.createStuff = function() {
  return <p>Stuff!</p>;
}
```

When format-js runs on this file, it removes the `var React = require('react')` line, which causes a "React is not defined"-type error at runtime as JSX compiles to a `React.createElement` call

**Comment by Daniel15** [comment]
cc @kyldvs

**Comment by kyldvs** [comment]
This is resolved. https://github.com/facebook/nuclide/commit/fdf65bc45d14ca75d84f03d26a4adc4ce6b4bc47

**Comment by Daniel15** [comment]
Hey look, a "Close Issue" button. :tada:
