### ISSUE TITLE
Consume package-deps in Nuclide Installer

### ISSUE THREAD

**Issue by steelbrain** [facebook/nuclide#184]
I've recently released a open source helper module on npm which allows atom packages to depend on each other. Unlike the currently implementation, it does not accept versions because in Atom they don't matter mostly. Packages export services, they export different versions of those services at once so end-users should always use the latest versions of all packages.
Some of the linter providers are already using it, others will use it very soon. Other popular IDE packages like `omnisharp-atom` and `atom-typescript` are using it as well. It's support has been confirmed on all major platforms.

From my own experience with nuclide-installer, I wasn't given any progress bar of any kind-of, nothing indicating what was installed or what was left to be installed. That package fixes that, it shows a notification with a progress bar along with the names of packages to be installed.

If you were to install the nuclide bundle with it, here's how it would look like
```coffee
// main.coffee
module.exports = 
  activate: ->
    require('atom-package-deps').install("nuclide-installer").then(() => { /* Do my thing */ })
```
```js
// package.json
{
  "name": "nuclide-installer",
  ...
  "package-deps": ["nuclide-hack", "linter", "nuclide-flow", "nuclide-tree-view"]
}
```

**Comment by ssorallen** [comment]
Is https://github.com/travs/atom-package-dependencies the helper module you mean?

**Comment by steelbrain** [comment]
No I mean [`atom-package-deps`](http://npmjs.org/package/atom-package-deps)

**Comment by ssorallen** [comment]
Aha great. Thanks for the link. @scv119, would this simplify Nuclide's installer at all?

**Comment by bolinfest** [comment]
Why does it depend on `atom-linter`?

https://github.com/steelbrain/package-deps/blob/master/package.json#L22-L24

**Comment by steelbrain** [comment]
@bolinfest `atom-linter` is our helper module in linter, `atom-package-deps` uses it for it's `exec` method, but it could be freed from it, not a big deal.

**Comment by bolinfest** [comment]
@steelbrain Moving it out sounds like a good idea.

Also, if the user has the package installed, but has chosen to disable it, do you force them to re-enable it? I ask because:

https://github.com/steelbrain/package-deps/blob/master/lib/main.js#L20-L23

Also, since you're using Babel, you could use async/await to avoid those `then()` calls.

**Comment by bolinfest** [comment]
Also, I'm not sure that you need a `class` when you only have static methods in `main.js`.

**Comment by steelbrain** [comment]
@bolinfest `class` makes things look simpler but that's not the reason it's there, while I was developing that module, I had some non-static methods on it. It can all be just replaced with exports now.

and Thanks for the tip about async/await. I use non-transpiled ES6 in some of my projects so use Pure ES6 even when using babel, You're right, I should be taking advantage of ES7.

Yes, we're forcing a re-enable because packages that depend on each other can't work properly unless all of them are active. For example `linter-ruby` can't work if `linter` is deactivated, so to properly deactivate, the user should deactivate them both. But I get the idea that with nuclide, people would want to disable some and use others, I'll add a second argument to install method for that.

**Comment by k2b6s9j** [comment]
:+1:

**Comment by steelbrain** [comment]
@bolinfest all the changes/features you proposed have been implemented and are there in the latest version. We are adding some test cases but that shouldn't be a blocker.

**Comment by bolinfest** [comment]
We decided to go in a different direction here. https://github.com/facebook/nuclide/commit/dbe5b5fb8fd7f2bee134e954fe9a2c2a8e53309e explains how and why.

Further, I suspect that we're going to need to do some more work with our custom installation to address https://github.com/atom/atom/issues/8217.

**Comment by steelbrain** [comment]
@bolinfest the implementation seems nice, except that you are spawning a process per dependency, where `package-deps` spawns just one process for all the deps.
