### ISSUE TITLE
Nuclide very slow to install/startup through Atom's GUI installer.

### ISSUE THREAD

**Issue by admmasters** [facebook/nuclide#189]
When installing Atom through Nuclide's installer - it takes a very long time and makes the CPU run incredibly hot on OSX Yosemite/El Capitan. However when running the dev install script, we have none of these issues and Atom starts up normally with the packages loading instantly.

**Comment by bolinfest** [comment]
Yes, this is a serious issue. I think the problem needs to be fixed in Atom rather than Nuclide. I filed an issue to track this at https://github.com/atom/atom/issues/8217.

**Comment by admmasters** [comment]
No problem thanks for the update.

**Comment by admmasters** [comment]
Going to close as not related to Nuclide.

**Comment by bolinfest** [comment]
Until https://github.com/atom/atom/issues/8217 is fixed, it's honestly much more efficient to build and install from source than it is via `apm`.

**Comment by michaeljcalkins** [comment]
@bolinfest Is this related?
![screen shot 2016-02-22 at 1 17 20 pm](https://cloud.githubusercontent.com/assets/8272012/13233048/c68ac260-d966-11e5-9ba8-611067df37af.png)

**Comment by ssorallen** [comment]
@michaeljcalkins The 'nuclide-installer' package no longer exists. The exceptions you're seeing look unrelated. Can you expand the stack traces and paste them into a new issue?

**Comment by michaeljcalkins** [comment]
@ssorallen Sorry it was unrelated to this issue.
Just needed to install some other programs: https://github.com/facebook/nuclide/issues/371
