### ISSUE TITLE
Nuclide 0.31 and ESlint

### ISSUE THREAD

**Issue by admmasters** [facebook/nuclide#190]
As we can no longer run Linter and Nuclide Diagnostics UI together - a user can no longer run both concurrently. Is there a way for Nuclide to consume the current errors/warnings from ESLint?

**Comment by bolinfest** [comment]
What package were you using to see ESLint errors? This should just work with the Nuclide package.

**Comment by admmasters** [comment]
I was using linter-eslint.

**Comment by admmasters** [comment]
In fact - that seems to be the only ESLint package that you can install. As a side note I'm using babel-eslint if that helps?

**Comment by nmote** [comment]
As @bolinfest says, this should just work. What do you mean by "that seems to be the only ESLint package that you can install?"

I will see if I can repro using `linter-eslint`.

**Comment by bolinfest** [comment]
@admmasters We have docs on this in a couple of places now:

https://github.com/facebook/nuclide/tree/master/pkg/nuclide/diagnostics#readme
https://github.com/facebook/nuclide/tree/master/pkg/nuclide/diagnostics/store#readme

**Comment by admmasters** [comment]
Hi @bolinfest yes I've read them - however linter-eslint throws an exception if linter is not installed.

**Comment by admmasters** [comment]
@nmote I was talking about trying other packages such as: https://atom.io/packages/eslint

**Comment by nmote** [comment]
Unfortunately it looks like `linter-eslint` simply does not start if the `linter` package is not there. We can't control the behavior of other packages, but I've filed an [issue](https://github.com/AtomLinter/linter-eslint/issues/212) against the `linter-eslint` package asking them to reconsider this requirement.

**Comment by admmasters** [comment]
Understood. Thanks for the update.

**Comment by nmote** [comment]
@admmasters Note that in the mean time, you can actually enable the `linter` package, ignore our warning, and have both UIs displaying messages. You can even go to the settings for `nuclide-diagnostics-store` and tell it not to consume diagnostics from packages using the `linter` API. That way you won't see duplicate diagnostic messages. The ones using our API (Flow, Hack) will still show up in our UI, and everything else will still show up in the `linter` UI.

This isn't ideal but it might be better than missing out on ESLint issues entirely.

**Comment by admmasters** [comment]
Thanks - will look at playing around with the config.

**Comment by LegNeato** [comment]
I think this is still an issue even though they appear to have "fiedx" it on their side? Using latest of everything I can only see `eslint` errors when disabling legacy linters in `nuclide-diagnostics` and enabling linter.

**Comment by LegNeato** [comment]
I put up https://github.com/facebook/nuclide/pull/213 that fixes the issue for me.

**Comment by nmote** [comment]
Should be fixed in ff151885b2569032f315ab93a441e78bd855dc1a
