### ISSUE TITLE
Nuclide-hack package is broken in version 0.0.32

### ISSUE THREAD

**Issue by cmbrownfield** [facebook/nuclide#198]
There are at least 2 undefined methods being used in the latest release of nuclide-hack:

I'm using atom version 1.0.11 and nuclide 0.0.32.

First issue is in the NuclideHackService.js file produced by the build:
~/.atom/packages/nuclide-hack/node_modules/nuclide-client/node_modules/nuclide-server/lib/services/NuclideHackService.js line 34:
The method in "stderr.contains" is undefined.  The proper require statement needs to be added to the source code (or stderr.includes should be used).

Second issue is in the HackDiagnosticsProvider.js file produced by the build:
~/.atom/packages/nuclide-hack/lib/HackDiagnosticsProvider.js line 166:
The method in "this.invalidatePathsForHackLanguage" is an undefined method.  I see no other reference to this method in the source code.

The second issue is also causing an "undefined promise rejection" error.

**Comment by mostafaeweda** [comment]
The second issue has been fixed and will be pushed soon.
The first issue, that wasn't the case because we are developing with the hack service remotely with node 0.12.x with --harmony flag - which has the `contains` method --> will replace with `indexOf` to work everywhere

**Comment by mostafaeweda** [comment]
the first issue has been fixed and will be pushed as well, thanks for the detailed report.
