### ISSUE TITLE
100%+ CPU usage in Nuclide 0.0.32

### ISSUE THREAD

**Issue by torifat** [facebook/nuclide#199]
<img width="1440" alt="screenshot 2015-09-17 19 45 27" src="https://cloud.githubusercontent.com/assets/208544/9934718/d51e3172-5d74-11e5-905b-f6f40de4a282.png">

I have removed `Atom` along with all it's settings from `~/Library/Application Support` & `~/.atom`. And, did a fresh install. But, still it's taking more than 100% CPU. I have waited for more than 30mins to see if it finishes but no luck.

```
OS: OS X 10.10.5 (14F27)
Atom: 1.0.11
Xcode: No
Processor: 2.5 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
```

```
apm  1.0.4
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.2
```

```
/Users/rifat/.atom/packages (41)
├── Stylus@1.2.1
├── chester-atom-syntax@0.1.1
├── emmet@2.3.10
├── file-icons@1.6.9
├── hyperclick@0.0.32
├── language-babel@0.15.0
├── nuclide-arcanist@0.0.32
├── nuclide-blame@0.0.32
├── nuclide-blame-provider-hg@0.0.32
├── nuclide-blame-ui@0.0.32
├── nuclide-buck-files@0.0.32
├── nuclide-clang-atom@0.0.32
├── nuclide-code-format@0.0.32
├── nuclide-debugger-atom@0.0.32
├── nuclide-debugger-hhvm@0.0.32
├── nuclide-debugger-lldb@0.0.32
├── nuclide-diagnostics-store@0.0.32
├── nuclide-diagnostics-ui@0.0.32
├── nuclide-diff-view@0.0.32
├── nuclide-file-tree@0.0.32
├── nuclide-file-tree-deux@0.0.32
├── nuclide-file-watcher@0.0.32
├── nuclide-find-references@0.0.32
├── nuclide-flow@0.0.32
├── nuclide-format-js@0.0.32
├── nuclide-fuzzy-filename-provider@0.0.32
├── nuclide-hack@0.0.32
├── nuclide-hack-symbol-provider@0.0.32
├── nuclide-hg-repository@0.0.32
├── nuclide-installer@0.0.32
├── nuclide-language-hack@0.0.32
├── nuclide-move-pane@0.0.32
├── nuclide-objc@0.0.32
├── nuclide-ocaml@0.0.32
├── nuclide-open-filenames-provider@0.0.32
├── nuclide-quick-open@0.0.32
├── nuclide-remote-projects@0.0.32
├── nuclide-test-runner@0.0.32
├── nuclide-toolbar@0.0.32
├── nuclide-type-hint@0.0.32
└── pigments@0.15.0
```

**Comment by thoradam** [comment]
Same here.

```
atom 1.0.15
apm  1.0.5
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.5.3
```

```
/Users/thoradam/.atom/packages (39)
├── build@0.46.0
├── hyperclick@0.0.32
├── language-javascript-jsx@0.3.7
├── nuclide-arcanist@0.0.32
├── nuclide-blame@0.0.32
├── nuclide-blame-provider-hg@0.0.32
├── nuclide-blame-ui@0.0.32
├── nuclide-buck-files@0.0.32
├── nuclide-clang-atom@0.0.32
├── nuclide-code-format@0.0.32
├── nuclide-debugger-atom@0.0.32
├── nuclide-debugger-hhvm@0.0.32
├── nuclide-debugger-lldb@0.0.32
├── nuclide-diagnostics-store@0.0.32
├── nuclide-diagnostics-ui@0.0.32
├── nuclide-diff-view@0.0.32
├── nuclide-file-tree@0.0.32
├── nuclide-file-tree-deux@0.0.32
├── nuclide-file-watcher@0.0.32
├── nuclide-find-references@0.0.32
├── nuclide-flow@0.0.32
├── nuclide-format-js@0.0.32
├── nuclide-fuzzy-filename-provider@0.0.32
├── nuclide-hack@0.0.32
├── nuclide-hack-symbol-provider@0.0.32
├── nuclide-hg-repository@0.0.32
├── nuclide-installer@0.0.32
├── nuclide-language-hack@0.0.32
├── nuclide-move-pane@0.0.32
├── nuclide-objc@0.0.32
├── nuclide-ocaml@0.0.32
├── nuclide-open-filenames-provider@0.0.32
├── nuclide-quick-open@0.0.32
├── nuclide-remote-projects@0.0.32
├── nuclide-test-runner@0.0.32
├── nuclide-toolbar@0.0.32
├── nuclide-type-hint@0.0.32
└── vim-mode@0.60.0
```

**Comment by domluna** [comment]
I also had the issue. Uninstalled all the Nuclide stuff and now Atom runs super smooth.

**Comment by coogleyao** [comment]
Same here. Like @domluna says.

**Comment by mkarklins** [comment]
I also have identical issue.

**Comment by soulfly** [comment]
The same for me..this is annoying 

OS X 10.10.5, Atom 1.0.18,

**Comment by dzannotti** [comment]
same for me, sadly never been able to test nuclide properly because of this issue

**Comment by torifat** [comment]
Instead of using the `nuclide-installer`, I built it from source using `./scripts/dev/setup`. And, it's working fine now.

**Comment by devlesedi** [comment]
Having same issue. I will try @torifat's solution.

**Comment by dzannotti** [comment]
i tried @torifat solution, same problem sadly

**Comment by arnarthor** [comment]
Same for me. Crashing a 15" Retina 2015 model. I've tried uninstalling only the flow pack based on #201 but no help. Also tried to build for source but that doesn't install more than 5 packages for me.

**Comment by arnarthor** [comment]
Not sure if it's related but this got fixed for me when I updated to El Capitan

**Comment by ultragtx** [comment]
I tried `./scripts/dev/setup` and seems no 100% cpu usage anymore. (10.11.0, atom 1.0.19).

It takes less than 10 minutes to initialize and cache some files when I restart atom after the installation. After that, everything goes fine.

You should take a look at the outputs of script, there may be some errors, a complete reinstall by removing ~/.atom may help.

**Comment by DjebbZ** [comment]
Same for me after running the installer. Atom was just unusable for me.

I just upgraded to OS X 10.11 (was on 10.8 before) then run the installer. Same results.
Then I uninstalled all `nuclide-*` packages with apm and run the `./scripts/dev/setup` script. No more CPU problem, but nothing different in Atom since there are only 5 packages installed.

I want nuclide for Flow, not interested into remote stuff, Hack or OCaml. So I installed nuclide-flow and configured the path to Flow. Nothing happens.

What packages are needed for local Flow support ?

**Comment by ultragtx** [comment]
@DjebbZ like you said `there are only 5 packages installed`, which means the setup script didn't complete successfully, you should make sure there's no error in the output of the script.

uninstall all `nuclide-*` packages is not enough, the package `hyperclick` also belongs to nuclide.

**Comment by DjebbZ** [comment]
Indeed I had forgotten `hyperclick`.

Now I clean installed it with the scripts, and same problem. Even worse, Atom refuses to display any file. Just an empty window, then 100% CPU and not responding.

**Comment by UnsungHero97** [comment]
+1 Atom is completely unusable.

Atom v1.1.0
Mac 10.10.5

**Comment by Keno** [comment]
I think at this point this is pretty well known, but I'll add my +1 here

**Comment by mr-max** [comment]
+1 (Mac OS X 10.11.1)

**Comment by anguskwan** [comment]
![image](https://cloud.githubusercontent.com/assets/1006912/11836628/e26534b4-a416-11e5-9862-f8c1384ad254.png)

will try build from sources.

**Comment by soulfly** [comment]
It's already 3 months since the issue was reported and still we don't have a fix..
It's a mess

**Comment by ssorallen** [comment]
We have major redesigning going on that replaces the many nuclide-* packages with a single 'nuclide' package that primarily aims to fix this issue and several others open on this repo currently. You can install 'nuclide' from source right now the same way any other Atom package is: clone the repo, `npm install`, `apm link`. Instructions are in the README (https://github.com/facebook/nuclide#nuclide) and will be updated there.

There was no small fix to make the many-package approach work, which is why we haven't addressed this particular GitHub issue yet. One of the people on the team will close many of these issues once there's a full release of the 'nuclide' package ready to try.

**Comment by UnsungHero97** [comment]
@ssorallen thanks for the update! is there an ETA on when the full release will happen? ... 1 month? ... 1 quarter? ... 1 year?

**Comment by ssorallen** [comment]
@UnsungHero97 No promises or dates yet, but we are aiming for a 1-month scale. It's usable from master as a single package already.

**Comment by nmote** [comment]
Fixed by the unified package: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
