### ISSUE TITLE
Hack: Clicking on errorcount in statusbar jumps on line above

### ISSUE THREAD

**Issue by SiebelsTim** [facebook/nuclide#2]
I guess it's supposed to jump on the line with the error, displaying the error. But the cursor is on the line above when clicking on it.

To be clear what I am meaning with errorcount in statusbar:
![nucl4](https://cloud.githubusercontent.com/assets/1153003/7788503/e4ca272c-023c-11e5-9e21-9622d04e363b.png)

Not sure if this is Atom Linter related.

**Comment by ssorallen** [comment]
Closing this since Nuclide now uses its own [nuclide-diagnostics-ui](https://atom.io/packages/nuclide-diagnostics-ui) and this issue was for the AtomLinter.
