### ISSUE TITLE
setup fails in ubuntu 14.04 and windows 8.1

### ISSUE THREAD

**Issue by ceram1** [facebook/nuclide#204]
Window 8.1 64bit
-----
 - nodejs: ```v4.0.1```
 - atom: ```1.0.15```
 - python: ```2.7.10```

git is installed with msys-git and I have installed [TDM-GCC](http://tdm-gcc.tdragon.net/).

When I run ```git clean -fxd && git checkout . && ./scripts/dev/setup```, (from github desktop git shell)
It says ``` [mklink, /J, /D, dest, src]``` failed because file already exists.
Also, ```git clean -fxd && git checkout . && python ./scripts/dev/setup``` from windows batch didn't work.

Ubuntu 14.04 LTS 64bit
-----
 - kernel: ```3.16.0-49-generic```
 - nodejs: ```v0.12.7```
 - atom: ```1.0.11```
 - python: ```2.7.6```

When I run ```git clean -fxd && git checkout . && ./scripts/dev/setup```,
```bash
Installing dependencies for Node package nuclide-ui-checkbox...
Done installing dependencies for nuclide-panel
Installing dependencies for Atom package nuclide-installer...
Linking /home/ceram1/.atom/packages/hyperclick to /home/ceram1/src/nuclide/pkg/nuclide/hyperclick failed: EEXIST, file already exists '/home/ceram1/src/nuclide/pkg/nuclide/hyperclick'
Error running ['apm', 'link', '/home/ceram1/src/nuclide/pkg/nuclide/hyperclick'] in /home/ceram1/src/nuclide
Process Process-32:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./scripts/dev/../lib/topological_installer.py", line 167, in install_dependencies
    fs.cross_platform_check_output(cmd_args)
  File "./scripts/dev/../lib/fs.py", line 89, in cross_platform_check_output
    raise subprocess.CalledProcessError(returncode, cmd_args, output=stdout)
CalledProcessError: Command '['apm', 'link', '/home/ceram1/src/nuclide/pkg/nuclide/hyperclick']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./scripts/dev/setup", line 50, in <module>
    exclude_windows_incompatible_packages=is_windows())
  File "./scripts/dev/../lib/package_manager.py", line 34, in install_dependencies
    installer.install()
  File "./scripts/dev/../lib/topological_installer.py", line 53, in install
    self._do_multiprocess_install()
  File "./scripts/dev/../lib/topological_installer.py", line 100, in _do_multiprocess_install
    (config['name'], exitcode))
Exception: Installing package hyperclick failed with exit code 1
```

**Comment by ceram1** [comment]
Additional note:
nuclide-installer worked on both side, but it was too slow.
And when I link ~/.atom/compile-cache to ramdisk, it works much faster.

After linking, showing package list works without problem.
I didn't test package list before linking to ramdisk.

**Comment by ssorallen** [comment]
The setup script has been removed as of yesterday's release, v0.111.0 of 'nuclide'. Building from source now only requires cloning, `npm install`, and `apm link`.

http://nuclide.io/docs/setup/#building-from-source
