### ISSUE TITLE
nuclide-quick-open show no results

### ISSUE THREAD

**Issue by eyalw** [facebook/nuclide#210]
I'm opening nuclide-quick-open with Cmd+T and no results show up.
using OS X El-Capitan. Latest Atom version (1.0.19)

![screen shot 2015-10-04 at 9 05 27 pm](https://cloud.githubusercontent.com/assets/608669/10269305/ad9d8ef8-6adb-11e5-8c6d-b37c016894f9.png)

**Comment by eyalw** [comment]
I didn't install nuclide-fuzzy-filename-provider...
after I did, it worked fine :+1:

**Comment by dideler** [comment]
I have nuclide-quick-open and nuclide-fuzzy-filename-provider installed, but still nothing. Just says "Loading..." when I search.

The nuclide-fuzzy-filename-provider package did add an extra tab for filenames to the search panel.

Is there anything else I need to install? Both READMEs at https://github.com/facebooknuclideapm/nuclide-quick-open#readme https://github.com/facebook/nuclide/tree/master/pkg/nuclide/quick-open#readme don't mention much about installation.

My guess is I need to install the whole nuclide ecosystem to get it to work. Is not possible to install specific nuclide packages the way you usually install Atom packages?

**Comment by rkit** [comment]
Try to install [watchman](https://github.com/facebook/watchman)
```
brew install watchman
```
