### ISSUE TITLE
Sucks

### ISSUE THREAD

**Issue by say2joe** [facebook/nuclide#216]
This package hangs Atom.IO... so much for QA. I had to manually uninstall every nuclide-* package via a bash shell script so that I could go back to coding (apm remove doesn't support wildcards).

**Comment by iamdustan** [comment]
This type of issue title is not okay. I apologize on behalf of the Nuclide team that it’s caused such an inconvenience for you.

**Comment by ged15** [comment]
@say2joe I am sorry to say, but this issue seems useless. Please try to be more constructive as venting frustration does not help anyone.

**Comment by ssorallen** [comment]
It sounds like you may have hit the issue solved in https://github.com/atom/settings-view/pull/674 It will be fixed with a new release of Atom.

If you have other problems, we can try to track down the problem if you add more details.
