### ISSUE TITLE
Collaborate with us

### ISSUE THREAD

**Issue by steelbrain** [facebook/nuclide#217]
We're thinking of writing a base debugging interface provider. Your experience from nuclide debugger package will be very helpful. Would you mind sharing your ideas about how that base provider's API should look like and about it's UI?

**Comment by peterhal** [comment]
Currently the Nuclide debugger is built on the chrome dev tools UI and uses their protocol for new providers. This has worked well for getting the debugger off the ground. The chrome dev tools protocol has some JS specific aspects to its design which we are starting to bump up against. We will start building our own UI (replacing parts of the chrome UI in pieces) and extending the chrome protocol going forwards.

Would love to hear about your plans.

**Comment by iamdustan** [comment]
Could either of these projects take anything from [Valence](https://developer.mozilla.org/en-US/docs/Tools/Valence) which allows Firefox DevTools to inspect and debug remote targets such as Chrome and Safari for iOS?

**Comment by joefitzgerald** [comment]
@peterhal could you elaborate on what "specific aspects to its design" that you are starting to bump against?

**Comment by mostafaeweda** [comment]
https://github.com/atom/atom/issues/9841#issuecomment-345393394

**Comment by steelbrain** [comment]
Thank You @mostafaeweda
