### ISSUE TITLE
Installation fails if notifications package is disabled

### ISSUE THREAD

**Issue by lyptt** [facebook/nuclide#219]
I disable notifications in my Atom configuration to avoid distractions, it seems that the nuclide-installer package doesn't expect this and ends up throwing an error as a result.

Enabling notifications so that the installer can show installation progress allows the installation to proceed.

**Comment by ssorallen** [comment]
Can you paste the error you were seeing or a screenshot of it?

**Comment by mostafaeweda** [comment]
All installation issues should have been fixed with out UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
