### ISSUE TITLE
Remote: Connection status

### ISSUE THREAD

**Issue by etcinit** [facebook/nuclide#22]
While trying out the remote feature in Nuclide, the only way I was able to check that a connection was successful was by looking at the console and waiting for the remote project to appear. I think that having a status icon for the connection and perhaps one for when the Hack tools are working would help out people trying to debug connectivity issues or server setup problems (like a slow coffee shop wifi or firewall issues on the server side). Here's a quick mockup:
![nuclidestatus](https://cloud.githubusercontent.com/assets/1160305/7953066/4dec63bc-098d-11e5-95c3-c12f595774cb.png)

**Comment by mostafaeweda** [comment]
wanted to let you know that I'm actively working on this now

**Comment by etcinit** [comment]
:+1:

**Comment by mostafaeweda** [comment]
added, will be updated with the next push
