### ISSUE TITLE
No inline error messages when strip_root enabled in .flowconfig

### ISSUE THREAD

**Issue by samwgoldman** [facebook/nuclide#230]
Steps to reproduce:
* Create a simple Flow project with the `strip_root` config option set to `true`
* Create any type error, like `var x: string = 0`
* See an error in the diagnostics pane, but no inline error message

Expectation: An inline error message should appear

Actual result: No inline error message is displayed

Workaround: Turn off `strip_root`

Flow version: 0.18.1
Atom: 1.1.0
Nuclide: master (d0f6758602e5d23f8be5d20210215db052f8ec86)

**Comment by nmote** [comment]
Am I correct in assuming that `strip_root` is just meant to increase readability for humans? If so, I think the right fix would be to have Flow print full paths when `--json` is passed, even if `strip_root` is set to `true`? What do you think?

**Comment by samwgoldman** [comment]
I can't confirm whether `strip_root` was intended only for humans, but if true, I think your solution is a good one.

**Comment by gabelevi** [comment]
Actually `strip_root` was invented for the tests. We wanted to record test output in a way that was portable. If the test output included the absolute file path then they'd always need to be run from the same path. I think the tests run with `--strip-root` by default.

Tests that run with `--json` might have trouble with your solution.

I'm not sure what the value of using `strip_root` as a human is nowadays. The new error format will use relative paths if they're shorter.

**Comment by samwgoldman** [comment]
> I'm not sure what the value of using strip_root as a human is nowadays. The new error format will use relative paths if they're shorter.

Then perhaps the workaround is the solution. :)

I had this setting enabled before the new format, and only started using nuclide recently.

**Comment by nmote** [comment]
Maybe the Flow docs should be updated to recommend against using `strip_root`? In any case, I don't think there is anything actionable here for Nuclide so I'm closing this out.
