### ISSUE TITLE
SLOOOOOW

### ISSUE THREAD

**Issue by sevki** [facebook/nuclide#232]
I don't know if this has been mentioned before but nuclide absolutely kills atom, completely, I'm wondering if I'm doing something wrong? am I doing something wrong, something somewhere in the manual I didn't read or something

![timecop_-_atom___config_-_atom](https://cloud.githubusercontent.com/assets/429977/10863172/2099f1fc-7fcd-11e5-9a6a-d0a9a141f463.png)

**Comment by bolinfest** [comment]
Is this Windows or something else?

**Comment by sevki** [comment]
![about_this_mac](https://cloud.githubusercontent.com/assets/429977/10868510/1ddc8854-8099-11e5-8df6-773c153b8b0c.png)
no other packages installed. 
only `nuclide-installer` installed after `rm -rf ~/.atom`

**Comment by guswelter** [comment]
@sevki, see #199 and #215 which may be what you're experiencing. If so, build from source may fix (instructions at https://github.com/facebook/nuclide/blob/master/README.md).

@bolinfest, any eta on the next release? Nuclide seems to be crippled on OS X unless you build from source at the moment.

**Comment by guswelter** [comment]
@bolinfest ping...

**Comment by KeKs0r** [comment]
Facing the same issue with nuclide 0.32

Has something relevant to this issue changed since 0.32?

**Comment by adamkdean** [comment]
Same issue with latest Nuclide, Atom 1.1.0, and OS X Yosemite (10.10.1). Reduced Atom to `sloooow`.

**Comment by sevki** [comment]
:+1: @adamkdean

**Comment by raelmiu** [comment]
Just installed on OS X. Still same issue, slow to load but impossibly slow to use. I type significantly faster than it renders, and scrolling is just impossible.

**Comment by silvestreh** [comment]
:+1: It's so slow that it absolutely kills Atom. I'll try to build it from source like @guswelter suggested, but still, this needs some serious work.

**Comment by dvcrn** [comment]
I chopped only a few packages out of nuclide and it increased the startup time to nearly 10s. `fuzzy-filename-provider` peaks with 3s.

**Comment by UnsungHero97** [comment]
+1

**Comment by nmote** [comment]
Fixed by the unified package: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
