### ISSUE TITLE
add syntax highlighting support Flow type annotations

### ISSUE THREAD

**Issue by UnsungHero97** [facebook/nuclide#236]
I incorrectly filed this issue in the wrong repository: https://github.com/atom/one-dark-syntax/issues/53

Syntax highlighting for TypeScript in Atom works really well, but it does not work in the case where I'm writing JavaScript with Flow type annotations. I have Nuclide built from source, but this is what I see:

Flow:
![2f060d54-8156-11e5-988d-9b68ecf271b0](https://cloud.githubusercontent.com/assets/440299/10921657/9f487eaa-822b-11e5-9e54-cb1bbba5fe15.png)

I expect to see the same syntax highlighting as with TypeScript:
![360127d8-8156-11e5-9e77-cd8c5a073849](https://cloud.githubusercontent.com/assets/440299/10921661/a52f60e0-822b-11e5-8a77-0a8d0c0965f9.png)

**Comment by ssorallen** [comment]
The [language-babel](https://atom.io/packages/language-babel) package supports Flow type annotations. We recommend installing that package and setting "Babel ES6 JavaScript" as the default language for '.js' files.

**Comment by UnsungHero97** [comment]
that seems to work. thanks!
