### ISSUE TITLE
hg-repository plugin not displaying line changes in gutter

### ISSUE THREAD

**Issue by sronsiek** [facebook/nuclide#237]
I'm using atom 1.1.0 (latest stable) on Linux.

I followed install instructions for nuclide-hg-repository as per:

https://atom.io/packages/nuclide-hg-repository 

I installed the entire nuclide package-set with nuclide-installer. When I open a project tree under mercurial version control, I correctly see file & folder highlighting for changed files in the directory tree panel. However I do not see the 'gutter' highlights indicating changed lines in the editor.

Due to  https://github.com/facebook/nuclide/issues/84 I had to remove most nuclide packages, without which atom was unusable.

I'm left with the following:

```
nuclide-file-tree
nuclide-hg-repository
nuclide-file-watcher
```

So the issue is: Is gutter highlighting broken, or is some additional config needed for this?

Are any nuclide packages in addition to the 3 I named required for this feature? Though note it did not work for me while all nuclide-packages were installed.

**Comment by jssln** [comment]
Hi @sronsiek, the gutter highlighting is actually provided by Atom's 'git-diff' package (https://github.com/atom/git-diff), which expects certain methods in the relevant "Repository" class to be synchronous. In Nuclide's implementation of HgRepositoryClient (the analogous class to Atom's GitRepository), we don't do this, so the gutter highlighting may not work as expected.

More detail here: https://github.com/facebook/nuclide/tree/master/pkg/nuclide/hg-repository#api-caveats

**Comment by batisteo** [comment]
I got this message from Atom:
`Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.`

Then I tried to rebuild the package and I got this for `nuclide-hg-repository 0.0.32`

```bash
In file included from ../node_modules/nan/nan_new.h:190:0,
                 from ../node_modules/nan/nan.h:74,
                 from ../src/bufferutil.cc:16:
../node_modules/nan/nan_implementation_12_inl.h: Dans la fonction membre statique ‘static NanIntern::FactoryBase<v8::Signature>::return_t NanIntern::Factory<v8::Signature>::New(NanIntern::Factory<v8::Signature>::FTH, int, NanIntern::Factory<v8::Signature>::FTH*)’:
../node_modules/nan/nan_implementation_12_inl.h:181:76: erreur: no matching function for call to ‘v8::Signature::New(v8::Isolate*, NanIntern::Factory<v8::Signature>::FTH&, int&, NanIntern::Factory<v8::Signature>::FTH*&)’
   return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
                                                                            ^
In file included from ../src/bufferutil.cc:7:0:
/home/batisteo/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:4515:27: note: candidate: static v8::Local<v8::Signature> v8::Signature::New(v8::Isolate*, v8::Handle<v8::FunctionTemplate>)
   static Local<Signature> New(
                           ^
/home/batisteo/.atom/.node-gyp/.node-gyp/0.30.7/deps/v8/include/v8.h:4515:27: note:   candidate expects 2 arguments, 4 provided
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 4.2.3-300.fc23.x86_64
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/batisteo/.atom/packages/nuclide-hg-repository/node_modules/nuclide-remote-connection/node_modules/nuclide-server/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 

npm ERR! Linux 4.2.3-300.fc23.x86_64
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/batisteo/.atom/.apm/.apmrc" "--userconfig" "/home/batisteo/.atom/.apmrc" "rebuild" "--target=0.30.7" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bufferutil@1.0.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/batisteo/.atom/packages/nuclide-hg-repository/npm-debug.log
```

On Fedora 23 and Atom 1.1.0
I hope it helps somehow.

**Comment by inkytonik** [comment]
I am seeing a similar problem when using Atom 1.3.0-beta0 on Mac OS X 10.11.1 with nuclide-hg-repository 0.0.35. No other nuclide packages are installed.

When I have a hg project open, add some lines to a file and save it, the standard (non-nuclide) tree view updates to highlight the file and its directory (and parents). Also, the small box with a dot in it appears at the right end of the status bar. I do't get any gutter lines nor any indication of "added or deleted" line counts in the status bar. All of this works fine with a git project.

I don't get any crash report nor can I see any messages that come from the nuclide-hg-repository package in the console, so I'm at a losses to how to investigate this further. Suggestions would be welcome.

**Comment by richarddewit** [comment]
+1

**Comment by inkytonik** [comment]
I did some more investigation and I found a fix for this problem that works for me when using the latest single package install of nuclide (version 0.115.1). It's an easy fix. See this pull request for more details: https://github.com/facebook/nuclide/pull/355.

**Comment by mostafaeweda** [comment]
this is now fixed - also, make sure you are using the latest `nuclide` / `watchman` / `mercurial`
