### ISSUE TITLE
Support running nuclide-server on solaris-sparc (enhancement)

### ISSUE THREAD

**Issue by pyhedgehog** [facebook/nuclide#249]
I'm afraid, that this will require removing dependency on node:
https://github.com/nodejs/node-v0.x-archive/issues/3322#issuecomment-9189343

**Comment by nmote** [comment]
It is highly unlikely that we will move away from Node. We also have native dependencies and I'm not optimistic that they will all compile properly for a different architecture. This is not going to happen, at least not in the near future.

**Comment by pyhedgehog** [comment]
:sob:
