### ISSUE TITLE
Add a CHANGELOG.md

### ISSUE THREAD

**Issue by BlaM** [facebook/nuclide#255]
Atom just updated "hyperclick", but there is no way to find out what changed.

(Can't say anything about the other "modules" because those don't work on Windows anyway)

**Comment by ssorallen** [comment]
Thanks for bringing this up, and I like the idea of adding a CHANGELOG. We have been writing internal release notes, and checking them in to a changelog seems reasonable as well.

**Comment by bolinfest** [comment]
We have a changelog.md in the uber Nuclide repo, no?

**Comment by ssorallen** [comment]
@bolinfest Oh yes, you're right.

@BlaM Where did you expect the change log to be? Nuclide updates all of its packages at the same time, and so the changes are aggregated in https://github.com/facebook/nuclide/blob/master/CHANGELOG.md.

**Comment by BlaM** [comment]
So there was an update, but no change? hyperclick isn't mentioned once in https://github.com/facebook/nuclide/blob/master/CHANGELOG.md

**Comment by ssorallen** [comment]
You can compare tags on GitHub, [v0.0.34...v0.0.35](https://github.com/facebook/nuclide/compare/v0.0.34...v0.0.35) is an example.

**Comment by ssorallen** [comment]
Going to close this because the changelog exists at the root and the impending refactor of Nuclide into far fewer Atom packages will make the current one-changelog approach make more sense.
