### ISSUE TITLE
Unable to add a project folder to nuclide-file-tree

### ISSUE THREAD

**Issue by MadDV** [facebook/nuclide#259]
I click add new project folder, select it, but nothing happens. There aren't any errors so I'm unsure of the issue.

https://streamable.com/62c2

**Comment by ssorallen** [comment]
Can you open the developer tools (View > Developer > Developer Tools) and see if there are any exceptions or logs there?

**Comment by MadDV** [comment]
http://i.imgur.com/gfdoNgp.png

Doesn't look like it, except for that one TypeError, which was wasn't from adding a project I believe.

**Comment by moonman22** [comment]
I have the same issue and in the  Developer Tools there is is this error but i dont know if its related or not 
```
Uncaught (in promise) Error: Command failed: C:\Windows\system32\cmd.exe /s /c "xprop -root _NET_CLIENT_LIST"
'xprop' is not recognized as an internal or external command,
operable program or batch file.



  at ChildProcess.exithandler (child_process.js:215:12)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:817:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)
```
hope to find a fix soon.

**Comment by marcpeterson** [comment]
I have the same problem.  I get this error:
```
Uncaught (in promise) Object {command: "which hh_client", errorMessage: "spawn which ENOENT", exitCode: "ENOENT", stderr: "", stdout: ""}

step @ C:\Users\USERNAME\.atom\packages\nuclide-quick-open\lib\SearchResultManager.js:17
_tickCallback @ node.js:368
```
But if I enable the `tree-view` package, I'll see the folder added there.

**Comment by ssorallen** [comment]
@marcpeterson It looks like your issue is Windows-related (it's trying to run `which hh_client` as a separate process, a command that doesn't exist on Windows). Nuclide needs to switch to something like the ['which' module](https://github.com/npm/node-which) to do cross-platform binary discovery.

**Comment by lucidlemon** [comment]
any updates on this? just wanted to use my windows machine for some developing but i cant work without a file tree..

**Comment by mostafaeweda** [comment]
closing this in favor for a general nuclide windows support, #321

**Comment by chrisahardie** [comment]
FYI - if you uncheck the **Enable the "nuclide-file-tree"** option, you get the stock Atom file tree back.
