### ISSUE TITLE
Initial open after install failed

### ISSUE THREAD

**Issue by fabean** [facebook/nuclide#26]
Everything installed fine when I ran `./scripts/dev/setup` no error or anything, but on first boot of Atom immediately this error popped up.

![screenshot 2015-06-03 07 32 16](https://cloud.githubusercontent.com/assets/3298524/7960054/4076c98a-09c3-11e5-89ba-81d5965d6d59.png)

After a reboot of Atom everything worked just fine.

I'm on a Mac model # A1398 Late 2013 rMBP
OSX 10.10.4
2.3GHz i7
16GB RAM

**Comment by ssorallen** [comment]
This looks like an installation problem with Atom from a much earlier version. Have you tried after updating to a newer version of Atom?

I'm going to close this because we can't do anything here. If you still have problems after updating, please comment and reopen the issue if relevant.
