### ISSUE TITLE
Nuclide file tree colorless on git repository

### ISSUE THREAD

**Issue by dvcrn** [facebook/nuclide#260]
![screen shot 2015-12-02 at 3 20 24 pm](https://cloud.githubusercontent.com/assets/688326/11523747/3d6bfdee-9908-11e5-8b51-d00a6ad02239.png)

I saw a lot of screenshots and reports from people saying that git diff colouring is supported as well but I couldn't make it work. Tried re-installing nuclide a few times but it still stays grey for everything while the normal atom file-tree is fully coloured. 

Is this a known problem?

**Comment by victor-borges** [comment]
+1

**Comment by victor-borges** [comment]
I'm facing the same problem. After installing Nuclide on Atom. when I change a local file in a Github repository the IDE doesn't add any class to tree view list.
When I remove all packages; clean the cache folders and reinstall Atom, it works again. If I install only nuclide, it stops.

I've already tried with both Atom versions 1.3.0 and 1.5.0, and I have the same problem.

**Comment by viatsko** [comment]
Discussion about the problem of implementing custom git repo is here https://github.com/atom/atom/issues/10423

I have a working git implementation in my fork of nuclide, but to work correctly it requires Atom patching because of that problem (repo detection firing up too early). :(

**Comment by ruler88** [comment]
Looks like nuclide disables Atom's default tree-view package. Even when I re-enable the tree-view the editor doesn't seem to be showing the old tree-view. Is there something in nuclide we can dis-able so we can use Atom's tree-view package?

**Comment by ssorallen** [comment]
@ruler88 You can deselect "Enable the 'nuclide-file-tree' feature" (and in the next release "Enable the 'nuclide-side-bar' feature" as well) in Settings > Packages > nuclide to disable Nuclide's file-tree. Doing so will re-enable Atom's bundled tree-view.

![screen shot 2016-02-12 at 3 19 34 pm](https://cloud.githubusercontent.com/assets/29612/13023271/479d4b5c-d19c-11e5-93be-0e97ce7f3759.png)
![screen shot 2016-02-12 at 3 19 21 pm](https://cloud.githubusercontent.com/assets/29612/13023273/47ddc51a-d19c-11e5-9800-88e46139e751.png)

Note that Atom's tree-view does not support remote file systems, which is the main reason Nuclide has its own. If you are planning on doing remote development, you'll need Nuclide's file-tree.

**Comment by Kaijun** [comment]
@ssorallen 

it will cause something like this:
![screen shot 2016-03-16 at 12 06 00](https://cloud.githubusercontent.com/assets/1693027/13810320/9070e374-eb6f-11e5-9ca7-c219d878d551.png)

A blank sidebar for the previous file-tree still remains...

how to toggle it off?

**Comment by lightning18** [comment]
You need to disable both nuclide-file-tree and nuclide-side-bar.

**Comment by Kaijun** [comment]
@lightning18

thanks, i thought nuclide-side-bar was the next release thing

**Comment by ssorallen** [comment]
In the next release you will only need to disable the 'nuclide-file-tree' feature. The side-bar will hide automatically when it has to consumers.

**Comment by BigMurry** [comment]
I have faced the same issue. But I really like the working set feature, so it's a complicated mood to have to choose side between colorful tree-view and working set. Hoping this will not be a problem soon.

**Comment by rentrop** [comment]
Somehow this does not work...
My file tree stays colorless during changes in files...
@ssorallen solution of disabling tree-view and side-bar helped...

Any Ideas?

### Versions
* Atom: 1.10.0
* Nuclide: 0.166.0
* OS: OS X El Capitan v. 10.11.6

**Comment by BornaP** [comment]
I too have the same problem with the exactly the same software/os x versions.

**Comment by pnakibar** [comment]
My nuclide-file-tree is also colorless.

Versions:
* Ubuntu 16.04
* Atom: 1.10.2
* Nuclide: 0.168.0

**Comment by KingScooty** [comment]
What was the reason for this being closed? I too am wondering why my file tree doesn't change colour depending on what files are changed within a git repo project.

**Comment by viatsko** [comment]
It works on a newer version of Atom + Nuclide (although, not for remote projects)

**Comment by KingScooty** [comment]
>It works on a newer version of Atom + Nuclide (although, not for remote projects) 

@viatsko Are you saying the nuclide file tree changes colour when files change? Since when? I'm on the latest version of Atom + Nuclide and my tree isn't changing colour.

**Comment by viatsko** [comment]
It works for git and mercurial repositories (currently use Nuclide on Atom stable + latest Nuclide). **.git** should be in the root of the project.

Alternatively, you can disable Nuclide file manager and enable default one.

**Comment by gustavopch** [comment]
@viatsko My nuclide-file-tree is also colorless for local project with .git folder in the root of the project.

- OS: Windows 8.1
- Atom: 1.17.2 ia32
- Nuclide: 0.232.0

**Comment by tjaklitsch** [comment]
Why was this closed?

**Comment by mlostek** [comment]
Same issue here.. Why was it closed?
