### ISSUE TITLE
How to uninstall nuclide from atom?

### ISSUE THREAD

**Issue by k0pernikus** [facebook/nuclide#266]
I am experiencing performance degradation by nuclide; after installation atom is very slow to start up and atom will freeze completely.

Which is why I want to uninstall nuclide, yet the docs don't state how and it seems that there lots of packages and uninstalling them manually is quite tedious as shortcuts like:

    $ apm remove nuclide-*

doesn't work.

How to uninstall nuclide from atom?

**Comment by iilei** [comment]
+1

**Comment by ssorallen** [comment]
`apm uninstall` for each package is the way to uninstall Nuclide completely. One way to one-line it is to find an Atom packages beginning with 'nuclide-' and piping them to `apm uninstall`:

    find ~/.atom/packages -name 'nuclide-*' -maxdepth 1 -type d | sed s/.*\\/// | xargs apm uninstall

**Comment by stevenla** [comment]
my command of choice was:

    apm list | grep -o "nuclide[^@]*" | xargs apm uninstall

**Comment by angexis** [comment]
Thanks! That was helpful! The tree-view has just disappeared after that... To re-enable it:
Edit ~/.atom/config.cson
Find
```
    disabledPackages: [
      "tree-view"
    ]
```
Remove the "tree-view" reference, save
=> you're done!

**Comment by ssorallen** [comment]
@angexis Thanks, I forgot to mention that. It's difficult to build a package that replaces a core Atom package while being a good citizen that re-enables the core package if it's disabled or removed. We chose to disable 'tree-view' permanently but need to document that in case you want to re-enable the core package.

**Comment by angexis** [comment]
@ssorallen You're very welcome! The goal was for me to document it ;-)

**Comment by ssorallen** [comment]
To be quite exact and not rely on the output of `apm list`, I created a list of the 'nuclide-' packages and put them into a single `apm uninstall`. The script should be straightforward and remove all Nuclide packages: https://gist.github.com/ssorallen/aff66a1c05d865fe4e83

**Comment by ssorallen** [comment]
There's now a doc on the site for uninstalling in upcoming single-package release and v0.0.35 and prior, which were shipped as many Atom packages.

http://nuclide.io/docs/uninstall/
