### ISSUE TITLE
Unexpected token P after install nuclide-hg-repository

### ISSUE THREAD

**Issue by mjs7231** [facebook/nuclide#267]
Getting this exception in the console after installing nuclide-hg-repository in Atom. I can't really get much more information as it wont let me click the exception to dig in.

    Uncaught SyntaxError: Unexpected token P     events.js:141

I'm on Ubuntu 15.04 x64 and running apm -v shows the following:

    apm  1.4.0
    npm  2.13.3
    node 0.10.40
    python 2.7.9
    git 2.1.4

**Comment by ssorallen** [comment]
Can you paste the output of `apm list --no-dev --installed` so we can see which packages you have installed?

**Comment by mostafaeweda** [comment]
Please try our latest Up release in http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/, and feel free to open if that's still the case.
