### ISSUE TITLE
nuclide-file-tree bugs

### ISSUE THREAD

**Issue by alicoding** [facebook/nuclide#27]
Hey guys! 

First of all, thanks for the invitation and I'm happy to contribute and will do as much as I can.
I thought it'd be nice to file a meta bug for Nuclide's specific feature and reference them to any known bug, and I'm not sure if that's a good thing to do but if isn't the right workflow please feel free to close this bug and I will file a new bug for my issue that I've found.

- Two file/directory tree on sidebar - https://github.com/facebook/nuclide/issues/3
- Clicked on the item on the tree does not open the file right away (needs to double click to do so).
- Clicked on the folder does not expand the item.

So I'm not sure if they are intentional there for the last two?

**Comment by ssorallen** [comment]
'nuclide-file-tree' now permanently disables Atom's 'tree-view' package. If you disable 'nuclide-file-tree' via Atom's Settings view, 'nuclide-file-tree' will re-enable 'tree-view' (https://github.com/facebook/nuclide/blob/master/pkg/nuclide/file-tree/lib/main.js#L153). If you run Atom in safe mode you will have to manually re-enable 'tree-view' or remove it from `disabledPackages` in ~/.atom/config.cson.
