### ISSUE TITLE
can not autocomplete 

### ISSUE THREAD

**Issue by MountainHill** [facebook/nuclide#272]
Hi,all.
OS:OS X EI Capitan(10.11.1)
I follow steps to install nuclide:
Step 1(https://github.com/atom/atom/blob/master/docs/build-instructions/os-x.md):
```
git clone https://github.com/atom/atom.git
cd atom
script/build
```
Step 2(https://github.com/facebook/nuclide):
```
$ git clone git@github.com:facebook/nuclide.git
$ cd nuclide
$ npm install
$ apm link
```
Now I can use,and I open a HelloWorld project create by 'react-native init HelloWorld'.
I edit the index.os.js file, I write code as follows
```
var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
});
```
The problem is atom can not autocomplete the property,as 'flex'/'justifyContent'/'alignItems'...,in _container_.All the properties are write by hand.
Does anyone know why?

**Comment by nmote** [comment]
I'm assuming you do in fact have Flow installed, and you get autocomplete elsewhere. What you describe does not sound like something that Flow autocomplete currently supports. You could open an issue on the Flow repository to request more autocomplete.

**Comment by MountainHill** [comment]
@nmote Thanks for your answering.I will try your advise"open an issue on the Flow repository".
