### ISSUE TITLE
infoService.getServerVersion is not a function

### ISSUE THREAD

**Issue by rune-ks** [facebook/nuclide#278]
```
Failed to connect to Nuclide server on xxxx:
infoService.getServerVersion is not a function.
```

I'm getting this error whenever I try to connect to my remote server. 

This is using a clean install of Nuclide locally and a clean install of Nuclide remotely (with ./scripts/dev/setup --no-atom). Watchman is installed and working as well.

I've tried searching, but can't find any information on this error whatsoever.

**Comment by outermeasure** [comment]
I'm also getting the same error. I am using Nuclide on Win 8.1 with a Debian Jessie remote.

**Comment by ThomasBS** [comment]
I'm also experiencing this error when I try to connect to the remote server. Ubuntu 15.04 with Debian Jessie remote.

**Comment by tugrul** [comment]
+1

**Comment by jorne** [comment]
Same here. Nuclide-server 0.0.35 (from npm) running on Raspbian Wheezy with Node 4.2.3.

**Comment by jamesbeedy** [comment]
Same here - trusty 14.04.3!

**Comment by aewing** [comment]
I'm experiencing this issue as well. Windows 10 x64, Ubuntu 14.04 remote. Both nuclide elements installed today.

**Comment by steblar** [comment]
Same Here. Mac osX 10.11

**Comment by mostafaeweda** [comment]
For windows support, refer to #321 - otherwise, I believe this should be fixed with our latest UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
