### ISSUE TITLE
Reveal in file-tree doesn't clearly 'reveal' the file

### ISSUE THREAD

**Issue by jimschubert** [facebook/nuclide#28]
*Problem*

Selecting 'Reveal in File Tree' doesn't consistently put focus on the current file in the file tree.

NOTE: this is with atom's default tree-view disabled

*Repro*

Atom 0.205.0
OS X Yosemite 10.10.3
nuclide HEAD as of dc7d1c5

* Cloned https://github.com/hhvm/hack-example-site to `~/temp/hack-example-site`
* Open a new instance of Atom
* Open `~/temp/hack-example-site`
* Use <kbd>CMD</kbd>+<kbd>T</kbd> to Fuzzy File Name Search for and open *GetController.php*
* Secondary click (you know, 'right-click') to pull up menu and select 'Reveal  in File Tree'

The result is folders are not expanded recursively and you'll need to select 'Reveal in File Tree' multiple times for files more than one directory deep. It looks like to me like `find` in the `revealActiveFile` function of [FileTreeController.js#L514](https://github.com/facebook/nuclide/blob/master/pkg/nuclide/file-tree/lib/FileTreeController.js#L514) is the problem, but I don't have a chance now to debug it.

**Comment by ssorallen** [comment]
This issue should be fixed in 'nuclide-file-tree' now. If you install from source and still see this problem, let me know.
