### ISSUE TITLE
Failed to connect to Nuclide server

### ISSUE THREAD

**Issue by tnwt7** [facebook/nuclide#280]
I keep getting an error: `[ERROR] nuclide - Cannot read property 'localImplementation' of undefined` log message when trying to connect to Nuclide server in my local vm.

I built Nuclide from source both in local and remote server using v0.0.35

**Comment by nmote** [comment]
I have seen this message only when the client and server versions are inconsistent. Are you sure that both are on the same version?

**Comment by tnwt7** [comment]
@nmote I have check out v0.0.35 before run `./scripts/dev/setup`. Then using `./pkg/nuclide/server/nuclide-start-server` to start a server. Is this guarantee that I have the same version on both?

**Comment by mostafaeweda** [comment]
This have been fixed with the UP release, see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
