### ISSUE TITLE
Seeing two file-tree-viewers

### ISSUE THREAD

**Issue by jjh42** [facebook/nuclide#287]
I installed Nuclide (from source 1 day ago) on Atom 1.3.2 (latest stable).

Now, whenever I open a new window I see two file-trees (the built-in one and Nuclide file tree). Is this normal? I presume that I should just use the nuclide one - I can hide the built-in one manually but it shows up again when I open a new window.

**Comment by ssorallen** [comment]
Can you paste the "disabledPackages" value from your ~/.atom/config.cson files? It might be the cause of incorrect disabling.

**Comment by marshallbu** [comment]
I found that another package (tree-view-git-status) forced the Atom tree view to be enabled.  I had to disable that and a couple others to ensure the default tree view wasn't also rendered.

**Comment by jjh42** [comment]
disabledPackages: [
      "symbols-view"
      "tree-view"
    ]

**Comment by jjh42** [comment]
@marshallbu I tried looking for packages that depend on tree-view but didn't find anything. How did you find the packages that were the problem. I've disabled most things now and its still a problem.

**Comment by marshallbu** [comment]
@jjh42 Nothing really scientific, I just disabled things that I knew were extending tree-view functionality and narrowed it down from there.  Do you have any other packages that do that?  Stuff like file-icons has been fine.

I also had to disable the symbols-view b/c it constantly gave errors with nuclide's hyperclick dependency.

**Comment by jjh42** [comment]
@marshallbu thanks for your help. By a process of elimination I figured out its the term3 package - not quite sure why but disabling it fixes this issue.

**Comment by marshallbu** [comment]
Nice, another to add to my watch out list.  Yay nuclide ;-)

**Comment by eyko** [comment]
I have the same issue - `rm -rf ~/.atom`, then opened Atom once to make sure it gets initialised, then installed nuclide. By default I get 2 tree views.

**Comment by viatsko** [comment]
@eyko, even after reloading Atom after first run with Nuclide?

**Comment by eyko** [comment]
@viatsko good call, ignore my previous comment. It wasn't _exactly_ that though: after reading your message I double checked my running processes and could still see two results from `pgrep -f Atom`. Not sure what made the process stick around, but after `pkill`ing them I'm getting one pane as expected (nuclide-file-tree). Thanks :)
