### ISSUE TITLE
command click on mac

### ISSUE THREAD

**Issue by istarkov** [facebook/nuclide#291]
Is it possible to move [this keybinding](https://github.com/facebook/nuclide/blob/master/pkg/nuclide/hyperclick/lib/HyperclickForTextEditor.js#L319) to other key not `meta`,
on OSX `meta` key in atom is already used for multiple selections.

**Comment by mostafaeweda** [comment]
The collision is avoided when hyperclick is used, and that will be fixed for you with the next release - keep tuned.

Thanks for reporting.
