### ISSUE TITLE
Could not uninstall nuclide-installer

### ISSUE THREAD

**Issue by colenhuttran** [facebook/nuclide#295]
I am using window for my PC. I have read guide to install nuclide in Atom in http://nuclide.io/docs/setup/
I installed nulcide from GUI Atom (nuclide-installer).
It took me about 4 hours to finish nuclide-installer package. Then, I restart atom, Atom become freeze and usually no-responding.
I look at .atom\packages folder. There are a lot package here. I try to browser to sub-folders. And there are huge folders in sub-folder, It even Window could not browser to final folder.
I use rm command in window to delete them, but system notice me the path could not found, because it is too long.
I also started window in safe mode, but folders in .atom\packages still could not be deleted
"C:\Users\cole\ATOM~1\packages\NUCLID~2\NODE_M~1\NUCLID~2\NODE_M~1\NUCLID~1\NODE_M~1\NUCLID~1\NODE_M~1\NU0AEE~1\NODE_M~1\BABEL-~1\NODE_M~1\REGENE~1\NODE_M~1\defs\NODE_M~1\yargs\NODE_M~1\cliui\NODE_M~1\CENTER~1\NODE_M~1\ALIGN-~1\NODE_M~1\kind-of\node_modules" => a path is too long to access in window

I tried to user apm uninstall and the result is attached picture.

![nuclide](https://cloud.githubusercontent.com/assets/16481719/12043342/0177adfa-aeb7-11e5-8ca2-890735e807e7.GIF)

I would like to uninstall nuclide and reinstall successfully, i like to study react and have a good ide to use.

Please help me resolve this issue.
Thanks a lot

**Comment by dsifford** [comment]
If you enter the following from a bash shell, it will uninstall all nuclide-related packages..

```sh
apm uninstall $(apm list -b | grep -P -o "^nuclide.*(?=@)")
```

**Comment by colenhuttran** [comment]
thanks dsi
I deleted all folder in /atom/packages/ manually by script.


I tried to use your script, and the result is:

![capture](https://cloud.githubusercontent.com/assets/16481719/12044547/d180615a-aec5-11e5-946f-53e1b9c4477b.GIF)

It is delete completely.??

**Comment by dsifford** [comment]
@colenhuttran I'm on linux so, unfortunately, I'm unable to offer much insight on cygwin.

To check to see if it's removed, enter `apm ls` in the console. You'll get a list of all installed packages. If it's not in that list, you're good to go.

If it is in the list, then the bash script probably didn't work properly on your cygwin installation. This can be checked by entering just the code in the parenthaces to see if just the names of the nuclide packages are listed... (eg. `apm list -b | grep -P -o "^nuclide.*(?=@)"`)

**Comment by colenhuttran** [comment]
Yes, it is empty now..Thanks dsi.
Which way do you install nuclide from atom or command line ??
I installed from atom and it take me 4 hours to finish, the my atom is slow, very slow. It is terrible.

**Comment by dsifford** [comment]
@colenhuttran I have not reinstalled. The nuclide team is [working on refactoring the current multi-package distribution](https://github.com/facebook/nuclide/blob/master/README.md) into a single-package version (which, will supposedly be much more reliable). I'm waiting for that to happen before I reinstall.

**Comment by efkan** [comment]
Yes. Paths are too long and there are tons of folders because of using `nodejs` modules. Therefore, installing and removing Nuclide is too slow and have problems.

**Comment by ssorallen** [comment]
I added an page about uninstalling Nuclide (nuclide-installer included) on nuclide.io: http://nuclide.io/docs/uninstall/

It lists all published packages and so requires only `apm`.

**Comment by efkan** [comment]
Yeah! Thanks to your page I had overcome the uninstall issue :+1:
I'm looking forward to the new Nuclide package and more good windows support. (watchman, mercurial etc.)

**Comment by mostafaeweda** [comment]
For windows support, refer to: #321
But all installation issues should have been fixed with our UP release see: http://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/
