### ISSUE TITLE
Opening a folder?

### ISSUE THREAD

**Issue by aaandrew** [facebook/nuclide#3]
![screen shot 2015-05-25 at 2 02 53 am](https://cloud.githubusercontent.com/assets/5565596/7807834/8d833a78-0343-11e5-9b8e-232bfe6649a2.png)

This seems like a pretty basic issue but it seems that opening a folder with Nuclide opens a duplicate of the same project? I tried opening the same folder (i.e. 'atom [foldername]') with and without the nuclide packages. Had expected behavior with vanilla atom (one folder opened), but got the results above after installing the Nuclide packages.

On a side note, I think this issue also affects horizontally resizing the project pane sidebar. If you slightly adjust the sidebar when you have this problem, then the adjustments are very glitchy.

**Comment by oclbdk** [comment]
Fixed with https://github.com/facebook/nuclide/commit/0942e4d0022644a6280565b9a5c5b75c5ac0dcc3

**Comment by pgnd** [comment]
Could someone bump the version so that Atom updates will pick up this fix?
