### ISSUE TITLE
Installing, Working and Uninstalling are Painful on Windows

### ISSUE THREAD

**Issue by efkan** [facebook/nuclide#302]
I've tried install `nuclide-installer` in Atom. 

**Installing** and **uninstalling**/deleting (and even working with) Nuclide is too slow and have problems. The installing has taken more than 5 hours for me. Actually, I have never run the Atom. And removing manually is painful. 

The reason should be that the file paths are too long and ***there are tons of files and folders*** because of using NodeJS and modules; Which are created by using NodeJS.

I think, the file structure of Nuclide should be changed. I don't know how. Because there are thousands file dependent on others. And **most likely the creators of Nuclide have already thought this issue**.

I wanted to inform, nevertheless.

Probably these are not problem on Linux or Mac OS X. However I have to use Windows..

A sample file path that is shortened by Windows (258 character);
```
C:\Users\Efkan\ATOM~1\packages\NU6AA0~1\NODE_M~1\NUCLID~1\NODE_M~1\NUCLID~1\NODE_M~1\NUCLID~2\NODE_M~1\NUA6F7~1\NODE_M~1\BABEL-~1\NODE_M~1\REGENE~1\NODE_M~1\defs\NODE_M~1\yargs\NODE_M~1\cliui\NODE_M~1\CENTER~1\NODE_M~1\ALIGN-~1\NODE_M~1\kind-of\node_modules
```

Actually there is one more folder after the latest `node_modules` named `is-buffer`. However Windows cannot open the folder because the maximum path length limitation (260 characters) :smiley: <br> And I don't know how much folder and file exist in the `is-buffer` folder. 

Original path should be like the below (bigger than 383 characters);
```
C:\Users\Efkan\.atom\packages\nuclide-debugger-hhvm\node_modules\nuclide-client\node_modules\nuclide-remote-connection\node_modules\nuclide-server\node_modules\nuclide-node-transpiler\node_modules\babel-core\node_modules\regenrator\node_modules\defs\node_modules\yargs\node_modules\cliui\node_modules\center-align\node_modules\align-text\node_modules\kind-of\node_modules\is-buffer\...
```

**Comment by nmote** [comment]
We have actually already done the file restructuring you hint at. It's briefly explained in the [README](https://github.com/facebook/nuclide/blob/master/README.md). Basically it is now only a single package. The individual `nuclide-*` packages, including `nuclide-installer`, will be shortly deprecated. We are working out the final kinks and we expect to have a release out soon. In the mean time you can install from source if you wish.

The problems are the same on Mac OS X and Linux, but I believe they are exacerbated in Windows.

**Comment by efkan** [comment]
Thank you.
