### ISSUE TITLE
Mistake in doc about keybindings

### ISSUE THREAD

**Issue by viatsko** [facebook/nuclide#309]
http://nuclide.io/docs/shortcuts/

"To open a file in Nuclide, hit ⌘-p, which will open a file finder dialog that does fuzzy matching on your input against file paths. This basically acts as an autocomplete for what you type, though it has some tolerance for misspellings."

Suppose that should be ⌘-t (or even Alt + ⌘ + t), because there's no override of Atom's keybinding by default and ⌘-p in pure Atom + Nuclide is showing default file finder dialog not backed up by watchman.

**Comment by viatsko** [comment]
Or maybe even suggest to assign Cmd+T's file search on Cmd+P:

```
'.platform-darwin atom-workspace':
  'cmd-p': 'nuclide-fuzzy-filename-provider:toggle-provider'
```

**Comment by nmote** [comment]
Weird, cmd+P actually works fine for me. CC @jgebhardt

**Comment by viatsko** [comment]
Is it correct then? (default Cmd+P)
<img src="http://i.imgur.com/DNzZhvt.png" />

Or omnisearch one is correct?

**Comment by nmote** [comment]
I just looked and for Facebook-internal users we override cmd+P to trigger quick-open. We didn't do that for external users, presumably so that we don't mess with existing workflows too much. So the docs should be updated.

**Comment by dsifford** [comment]
On the topic of keybindings, to your knowledge @nmote , are we going to ever be able to disable all nuclide keybindings in the future (some packages allow this).

I'm having an extremely hard time overriding `ctrl-alt-o`

**Comment by JoelMarcey** [comment]
We have a new page of keyboard shortcuts now. I hope that resolves this issue:

http://nuclide.io/docs/editor/keyboard-shortcuts/
