### ISSUE TITLE
Stand-alone version of Nuclide?

### ISSUE THREAD

**Issue by rauschma** [facebook/nuclide#312]
I don’t want to turn my Atom into an IDE. Have you considered creating a separate, stand-alone version of Nuclide? Basically, it would be Atom with custom name + icon and the Nuclide package installed.

**Comment by nmote** [comment]
The current consensus among the team is that we don't want to do this. Even if we did, it would probably be nontrivial and it would be hard to justify the effort right now.

You can always disable and enable the Nuclide package when you want to switch back and forth.

**Comment by LegNeato** [comment]
FWIW Nuclide actually started this way and there were a bunch of downsides...
