### ISSUE TITLE
Project Panes seems to bug

### ISSUE THREAD

**Issue by tychota** [facebook/nuclide#314]
Plateforms
=======

- windows 10 (uptodate)
- atom 1.4.0
- nuclide 0.111.0

**Disclaimer** : just updated to new-world atom ! Got some problem removing old version ! Ending up `rimraf .atom` in my user directory so normally it is brand new Atom.

Reproduction steps
===============

- click on `Add Project Folder` in Left-side toolbar
- select any directory
- validate

Expected
------------
See the project content replacing the left side nav

Actual
--------
Nothing happen user side, the side nav remains with the two button `Add Project Folder` and `Add Remote Project Folder`

Logs
=====

Actually never got far in atom debuging !
Opening the console get me 

```
Uncaught (in promise) Error: Failed to populate FileSearch for C:\redacted\path\to\my\dir
    at C:\Users\Salas\.atom\packages\nuclide\pkg\nuclide\path-search\lib\PathSetFactory.js:23:11
    at process._tickCallback (node.js:368:9)
```

this happened in file `FuzzyFileSearchService.js`, last line:
```javascript
export async function isFuzzySearchAvailableFor(
    rootDirectory: NuclideUri
): Promise<boolean> {
  return await fsPromise.exists(rootDirectory);
}
```

End
===

Sorry for this bad FR-english !!
Hope it helps !
Not tested in Linux (to know if it is windows specific): my arch linux crashing was actually my reason to use windows to code :)

I'm available for more info, if that isn't enough !

**Comment by tychota** [comment]
I received other uncaught error in promise wich return me an object !

```javascript
{command: "ps -e -o pid,comm",
errorMessage: "spawn ps ENOENT",
exitCode: "ENOENT",
stderr: "",
stdout: ""}
```

```javascript
{command: "which hh_client",
errorMessage: "spawn which ENOENT",
exitCode: "ENOENT",
stderr: "",
stdout: ""}
```

While they are absolutly not related to this issue (I should open a other one !), it seems that Nuclide use some POSIX specific command ! I don't went far to investigate.

**Comment by tychota** [comment]
Wrong button ("github please")

**Comment by tychota** [comment]
https://github.com/facebook/nuclide/issues/27#issuecomment-109071798 may be the root cause
I think the log attach isn't related  to the tree issue !

**Comment by nmote** [comment]
Thanks for the detailed bug report, but we don't currently support Windows. We are hoping to work out the kinks in the near future but for now you'll be best off returning to Arch if you want to use Nuclide.

**Comment by tychota** [comment]
Do you want us to still report bug on windows, even if they are put on hold ? Or just wait till a propice time !

For those we are gonna find this issue : you can go in nuclide settings and deactivate the file-tree, then edit config.json to reactivate the default atome tree.

**Comment by tychota** [comment]
@nmote : maybe it is better to tackle some easy issue (like https://github.com/facebook/nuclide/issues/314#issuecomment-171600229) than having yet another :+1: thre à la https://github.com/facebook/flow/issues/6 !

I completly understand the priority but would you accept contribution from community (which and ps can easily have a powershell equivalent as far as I know) !

**Comment by nmote** [comment]
For now I don't think it's useful to get bug reports on Windows since we won't act on them at the moment, and obvious things like this problem will be one of the first things solved when we do start working on Windows support.

However we would be thrilled to accept contributions to improve Windows support. It's definitely something we want to do, we just haven't prioritized it yet.
