### ISSUE TITLE
Can not view the file-tree 

### ISSUE THREAD

**Issue by nlitterat** [facebook/nuclide#315]
I installed the Atom editor and install the package for nuclide (not the installer)
all seems to work but I can not see the file-tree panel.
all I see is two buttons
Add project folder 
and 
Add remote project folder

I can see that the original Atom file-tree package is disabled

Any ideas

**Comment by viatsko** [comment]
OS? Screenshot? Nothing is happening when you're pressing buttons?

**Comment by nlitterat** [comment]
Screen shot:
![image](https://cloud.githubusercontent.com/assets/6443319/12327848/4e1f9e16-bae1-11e5-83b2-bd04fa3ccf8e.png)


Os : windows 7
When pressing them everything seems to work (I tried just the add project folder) but nothing is added to the panel

Many thanks for the fast response

**Comment by viatsko** [comment]
Something's wrong for sure on Windows with file-tree:
http://i.imgur.com/cAgOptd.png (context menu is still working, but for example if you'll add file in folder - it won't update right away = slightly unresponsive)

Also notice about ctags:
http://i.imgur.com/Eb2sqUE.png

Also
```
C:\Users\viatsko\AppData\Local\atom\app-1.5.0-beta0\resources\app.asar\src\package.js:713 Failed to require the main module of 'nuclide' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.
```

Also thrift compilation problem here in the log file:
http://paste.fedoraproject.org/310789/45278783/

**Comment by nmote** [comment]
We don't currently support Windows. The unified package was a step forward but we still have some kinks to work out. Dup of #314
