### ISSUE TITLE
Option to disable cmd + hovering of hyperclick

### ISSUE THREAD

**Issue by chenglou** [facebook/nuclide#319]
Hyperclick uses the meta key + click, without the option to opt out of it. This clashes with atom's multicursor click which also uses meta.

**Comment by jgebhardt** [comment]
cc @mostafaeweda

**Comment by mostafaeweda** [comment]
This fixes it by consuming the event only if it's a hyperclick event (a definition is already highlighted/underlined): https://github.com/facebook/nuclide/commit/7419c1d6987914d5da56a09bd25a9defe59d8d89

**Comment by chenglou** [comment]
I'm using the latest version of Nuclide and the problem still persists.
