### ISSUE TITLE
Gutter has extra div.custom-decorations -- Resulting in large gutter size

### ISSUE THREAD

**Issue by dsifford** [facebook/nuclide#323]
Hello,

I downloaded the new nuclide package today for the purpose of using the flow features... and only the flow features.

I disabled all packages that are unrelated to flow and, for whatever reason, my gutter is extra-wide. 

![image](https://cloud.githubusercontent.com/assets/5240018/12344791/39b8d9b4-bb0f-11e5-818b-3139d52a853d.png)

Happy to help troubleshoot / provide any details for you if you need it. Thanks for the help!

**Comment by nmote** [comment]
The width of the gutter isn't ideal, but I'm not extremely surprised by this. The line numbers alone take up a constant width throughout the file, so if you have a file with three digit (or even four digit) line numbers, the gutter will look more compact once you scroll down. That's pretty much unavoidable. 

However it looks like `nuclide-debugger` may not be removing its gutter space when it's disabled. Could you confirm that you have disabled the `nuclide-debugger-atom` feature?

Could you use the dev tools to see which gutter elements you have, and their widths? There should be a div with the class `gutter-container`. For each child, could you include its `gutter-name` and its width?
