### ISSUE TITLE
Re-Enable "tree-view" when uninstalling

### ISSUE THREAD

**Issue by BlaM** [facebook/nuclide#326]
Nuclide seems to disable the default "tree-view" plugin when installing. It soes not reenable it however when being uninstalled - leaving the user with a window with no tree view and no explanation how to get it back.

**Comment by ssorallen** [comment]
Thanks for bringing this up; we need to document this, likely on the [Uninstalling Nuclide](http://nuclide.io/docs/uninstall/) page.

Atom packages don't get a chance to respond to being uninstalled. If, for example, you close Atom and then `apm uninstall nuclide`, the Nuclide package doesn't have an opportunity to clean up.
