### ISSUE TITLE
A few flow settings seem to be ignored

### ISSUE THREAD

**Issue by chenglou** [facebook/nuclide#330]
Notably: 

- the `[options]` section of flowconfig where I defined e.g. $FlowFixMe, doesn't suppress the gutter's warning:
![screenshot 2016-01-17 00 50 29](https://cloud.githubusercontent.com/assets/1909539/12376164/5b4b2da6-bcb4-11e5-9a43-5f1e9dbaf546.png)

- `@noflow` comment on top of files is ignored, and nuclide flow keeps showing errors.

When I run flow directly from the command line everything is respected. I've also started my own server in the foreground and the results are good too.

If it helps, the path [here](https://github.com/facebook/nuclide/blob/d0404ccedb10dee6515644af1bbb1d39fc861824/pkg/nuclide/flow-base/lib/FlowRoot.js#L34) outputs the right value (root of my project).

**Comment by zertosh** [comment]
cc: @nmote

**Comment by nmote** [comment]
We use these features extensively while developing Nuclide itself and I haven't encountered anything like this. Could you paste your `~/.atom/config.cson`? I'm thinking you might have "Diagnostics as you type" enabled, which is currently labeled experimental because it has some quirks like this.

**Comment by chenglou** [comment]
Ah yes I did have it enabled. Didn't think it'd affect this. It works with that turned off. Thanks!

**Comment by nmote** [comment]
No problem. Getting this to work properly is yet another item on my long to do list :smile:
