### ISSUE TITLE
SSH into remote server in case of a jump-server !

### ISSUE THREAD

**Issue by collegeimprovements** [facebook/nuclide#332]
In oreder to ssh into the  ` Target remote server` (say server `T : Target Server`), I have to first ssh into a `jump server` (say server `J : Jump Server`) and from  that Jump server, I can ssh into my target server.

Is it possible to edit files of `Target server` with the help of `nuclide` ?

**Comment by matthewwithanm** [comment]
Hi @collegeimprovements! Sorry, but that's not a feature that's currently on our roadmap. Depending on the details of your situation, you might be able to get something working with SSH tunnels but right now the only supported usage is connecting directly to a machine running the nuclide server. (Of course, you could always mount the remote drive and edit it that way.)

**Comment by jjh42** [comment]
I have made this work by ssh port forwarding.

Something like:

`ssh $J -L T:22 -L T:9090 -L T:9091 -L T:9092 T:9093`
then have nuclide connect to the 127.0.0.

Although as this isn't supported and is kinda hairy it can take a bit of messing around to make it work.
