### ISSUE TITLE
Mercurial repos detected as Non-Mercurial Repository

### ISSUE THREAD

**Issue by julienmarie** [facebook/nuclide#345]
All my mercurial repositories are detected as non mercurial.
`Diff view only supports Mercurial repository but found no repository`

Is there something I missed?

**Comment by ssorallen** [comment]
Do you see an exception or any other information?

**Comment by shushz** [comment]
This might be fixed with the upcoming release by https://github.com/facebook/nuclide/commit/13305bd2222e13c479091eb2fcd3b012cfddda35

**Comment by bolinfest** [comment]
Agree with @shushz that 13305bd2222e13c479091eb2fcd3b012cfddda35 was likely the fix. Closing, but feel free to reopen if this does not address the issue.
