### ISSUE TITLE
How to open default file-tree?

### ISSUE THREAD

**Issue by ilearnio** [facebook/nuclide#346]
I just installed nuclide, and I noticed that it has replaced the default Atom's sidebar (or maybe just file tree). But I like the default one because it highlights files and folders that was modified. So I disabled the `nuclide-file-tree` package and now I can't open the default sidebar. The keybinding cmd+\ (or cmd+k+b) is no longer working :(

How can I return back the default sidebar?

Thanks

**Comment by ssorallen** [comment]
Re-enable the package named 'tree-view' either from within Atom Settings page (search for 'tree-view' in the _Packages_ tab) or by editing your '~/.atom/config.cson' and removing `'tree-view'` from the `disabledPackages` array.

Note: Atom's tree-view does not support remote development and does not integrate with Mercurial. You will have to use Nuclide's file-tree if you'd like to use those features.

**Comment by ilearnio** [comment]
Thanks, it helped! I'm not using remote development or Mercurial, so it's OK for me. Thank you again!
