### ISSUE TITLE
buck toolbar cannot be hidden

### ISSUE THREAD

**Issue by despairblue** [facebook/nuclide#360]
I think [this](https://github.com/facebook/nuclide/blob/68ae91213e1b55cc309910995d87110b3104ef4f/pkg/nuclide/buck/toolbar/lib/BuckToolbar.js#L112) line of code is not really doing what it's supposed to do. Not exactly sure if `hidden` should work. If it should, that might be a bug in atom 1.6 beta.

![screen shot 2016-02-11 at 00 25 59](https://cloud.githubusercontent.com/assets/927609/12965404/35d5514a-d056-11e5-944d-7802d7481e0b.png)

## Command History

```
  4x -4:03.3 nuclide-buck-toolbar:toggle (div.buck-toolbar.padded.tool-panel)
     -0:11.2 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:04.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:04.2 core:cancel (atom-text-editor.editor.mini)
     -0:03.1 fuzzy-finder:toggle-file-finder (atom-text-editor.editor)
     -0:02.4 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:02.4 core:cancel (atom-text-editor.editor.mini)
     -0:02.2 editor:consolidate-selections (atom-text-editor.editor)
     -0:02.2 core:cancel (atom-text-editor.editor)
     -0:01.9 command-palette:toggle (atom-text-editor.editor)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.0 bug-report:open (atom-text-editor.editor)
```

## Versions

* **Atom:**       1.6.0-beta0
* **Atom-Shell:** 
* **OS:**         Mac OS X 10.10.5
* **Misc**
    * apm  1.5.0
    * npm  2.13.3
    * node 0.10.40
    * python 2.7.10
    * git 2.5.4

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.7.1.</small>

**Comment by ssorallen** [comment]
`.tool-panel` got a `display: block;` in 1.6; `[hidden]` used to be the only style modifying `display` here.
