### ISSUE TITLE
Jump To Definition

### ISSUE THREAD

**Issue by ccoffey** [facebook/nuclide#362]
I am considering using Nuclide because of the "Jump To Definition" feature mentioned [here](http://nuclide.io/docs/languages/flow/#feature-examples). 

Can I use this feature without annotating my code with flow types? I may someday integrate flow into my application but for now I would really like to be able to jump to definitions by clicking on functions, variables, etc.

I just ran a test and unless I am missing something it doesn't work. With regards to the call to foo() at line 100 below, I tried clicking, double clicking, cmd + click, alt+click but nothing will cause my editor to jump to the definition at line 1.

```
1 function foo() {
2   return 'foo';
3 }
.
.
.
100 console.log(foo());
```

**Comment by ssorallen** [comment]
I believe you minimally need a `/* @flow */` annotation at the top of the file in order for Flow to analyze it. Without that annotation, Flow will skip the file.

**Comment by ccoffey** [comment]
Adding ```/* @flow */``` to the top of the source file doesn't seem to have had any effect. Is there a getting started tutorial anywhere? I have 2 questions at this point

1. Do I need to run flow manually or does Nuclide do that automatically for me in the background?
2. Do I just click on a function or is there also a key that I need to hold down?

**Comment by ssorallen** [comment]
You also need a '.flowconfig' file in the root of your project in order for Flow to start.

1. Nuclide will start a Flow server for you if it finds a '.flowconfig'
2. You need to hold Command (on Mac) or Ctrl (on Linux/Windows)

**Comment by ccoffey** [comment]
Thank you @ssorallen, this is working now! Correct me if I am wrong but I have to add ```/* @flow */``` to the top of each file I want "Jump To Definition" to work with? This will likely mean that we won't be moving to Nuclide anytime soon because we have not made the decision to use Flow yet.

**Comment by nmote** [comment]
I *think* that as long as you have a `.flowconfig`, then Flow's jump to definition will work on a best-effort basis even for files without `/* @flow */`. Without type annotations, of course, it's not always possible to resolve the definition for a symbol but for simple cases like your example it should work.

That's not really a supported use-case, though. We are primarily interested in supporting JavaScript projects that do use Flow.

**Comment by artivilla** [comment]
It would be nice if i can use these JS features jump to definition/autocomplete without having to use Flow. Are there other packages in atom that provide us with an inbuilt node debugger and these features without installing Nuclide?

**Comment by JohnyDays** [comment]
@artivilla Due to the dynamic nature of javascript, this is a momentuous task that really has only been taken on by the flow and typescript teams. There are also some other tools that only give you in-file goto definition, and basic autocomplete (function/variable names).
