### ISSUE TITLE
connect ETIMEOUT

### ISSUE THREAD

**Issue by tominkozhimala** [facebook/nuclide#366]
When attempting to connect for remote development, `nuclider-server-start` is executed with necessary parameters and the NuclideServer starts on port 9090. But my local machine fails to complete the connection and displays the following [I removed my IP address]:
![timeout](https://cloud.githubusercontent.com/assets/1771815/13079239/d4cfacb0-d488-11e5-81bd-fb5bffbb807d.PNG)

Attempted uninstall and clean install of nuclide, Atom, and nuclide server but issue still reproduces. 

When debugging Atom, exception is caught at SshHandshake.js:417:
`Error: connect ETIMEDOUT <ServerIP>:9090`
`  at Object.exports._errnoException (util.js:837:11)`
`  at exports._exceptionWithHostPort (util.js:860:20)`
`  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)`

### nuclide.nohup.out [INFO]
`[2016-02-16 14:56:53.718] [INFO] nuclide - NuclideServer started on port 9090.`
`[2016-02-16 14:56:53.726] [INFO] nuclide - NuclideServer event loop blocked for 2016ms`

### System Details (Server):
Ubuntu 14.04.3 LTS
Nuclide: `nuclide@0.116.0`

`node -v`
`v5.6.0`

`npm -v`
`3.6.0`

`watchman -v`
`4.4.0` 

`python --version`
`Python 2.7.6`

`netstat -lnt`
`Proto Recv-Q Send-Q Local Address           Foreign Address         State`
`tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN`
`tcp6       0      0 :::22                   :::*                    LISTEN`
`tcp6       0      0 :::9090                 :::*                    LISTEN`

### System Details (Client):
Windows 8.1
Nuclide: 0.116.0
Atom: 1.5.3

`apm -v`
`apm 1.6.0`
`npm 2.13.3`
`node 0.10.40`
`python`
`git`
`visual studio 2013`

**Comment by shushz** [comment]
@tominkozhimala the error message mentions different client and the server versions. Could you please update the server 0.116 and see whether the problem persists?

**Comment by tominkozhimala** [comment]
@shushz both my server and client versions are updated to 0.116.0 (see above in system details)

**Comment by shushz** [comment]
Right. I'm able to reproduce the error when the authentication is not made fast enough. Fast enough is in about under 10 sec.

**Comment by tominkozhimala** [comment]
I attempted to make the connection and set the timeout to be both 60 and 180 seconds.
`nuclide-start-server -t 60`
`nuclide-start-server -t 180`

But both of these still caused the `connect ETIMEOUT` after about 25 seconds. 

Is there another approach that I can take?

**Comment by shushz** [comment]
Yes, the server does start, I guess it's something in the client. Looking into this and will update.

**Comment by shushz** [comment]
Current status:
This error is consistently reproduced when something like a firewall is preventing the connectivity to the Nuclide server. I no longer can reproduce it in other cases. Moreover, I suspect that when I did observe it initially I might have mistakenly chosen a firewalled port.

If your server is not using SSL, could you please try running something like `curl -X POST http://<YourServerIP>:9090/heartbeat` and see whether you're receiving the version string (116) back?

If curl timeouts - it's a connectivity issue.

**Comment by tominkozhimala** [comment]
Since my server is an AWS EC2 instance, I can't use the same `curl` command you provided, but my attempt to use `curl --cacert .ssh/ubuntu.pem -X POST http://52.36.12.86:9090/heartbeat --connect-timeout 30 -m 60` timed out with `curl: (28) Connection timed out after 30000 milliseconds`

Other routes that I tried with the same result:
- Turned on logging for my local machine firewall and did not see any dropped/blocked connections. 
- Turned my local machine firewall off and attempted to make the connection to the server
- Updated both my server and client versions to 0.117.0
- Attempted to connect from another local machine on another network with firewall turned off (Windows 8.1, Atom 1.5.3, Nuclide 0.117.0)
- Spun up a new AWS EC2 instance with default settings and followed install instructions for nuclide server and got the same `connect ETIMEOUT` error

Since my server is an Amazon EC2 instance, I checked my security groups to verify my connection permissions (these are the default settings):
### Inbound	
Type: SSH
Protocol: TCP
Port Range: 22
Source: 0.0.0.0/0

### Outbound
Type: All traffic
Protocol: All
Port Range: All
Destination:0.0.0.0/0

I'm beginning to think that the issue is server-side, but my server outbound settings allows all traffic.

**Comment by shushz** [comment]
OK. So, it seems you need to open the port 9090 in your inbound configuration. Otherwise, the SSH passes through and the server is started, but it can't be connected to later on.

**Comment by tominkozhimala** [comment]
Looks like that worked! Thanks for the help @shushz

**Comment by shushz** [comment]
Awesome :-)
