### ISSUE TITLE
windows10 nuclide 0.118 on atom treeview don't show the tree,please fix

### ISSUE THREAD

**Issue by tonytbl** [facebook/nuclide#369]
### Issue and Steps to Reproduce
windows10 nuclide 0.118 on atom treeview don't show the tree,please fix

 

### Versions
* Atom:1.5.3
* Nuclide:0.118
* Client OS:win10
* Server OS (optional):

**Comment by viatsko** [comment]
Nuclide is incompatible with Windows at the moment. :(

Please follow this issue for updates https://github.com/facebook/nuclide/issues/321

**Comment by shushz** [comment]
Yes, unfortunately Windows is not yet fully supported.
Closing as duplicate of https://github.com/facebook/nuclide/issues/321

**Comment by ssorallen** [comment]
@tonytbl Did it work in previous versions?
