### ISSUE TITLE
Doesn't search for files when cm+t is pressed due to promise error

### ISSUE THREAD

**Issue by michaeljcalkins** [facebook/nuclide#371]
### Issue and Steps to Reproduce
I just installed nuclide
Opened a project
Pressed cmd+t
Stuck on Loading... and doesn't search for any files

### Expected Behavior
When I type a file I know exists it should be listed and ready to open.

### Actual Behavior
It gets stuck on Loading...

### Versions
* Atom: 1.5.3
* Nuclide: 0.118.0
* Client OS: Mac El Capitan
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── file-icons@1.6.15
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.15.4
├── language-ini@1.14.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── nuclide@0.118.0
├── sort-lines@0.14.0
└── tool-bar@0.2.1

![screen shot 2016-02-22 at 1 17 20 pm](https://cloud.githubusercontent.com/assets/8272012/13263016/a263664c-da1c-11e5-9b72-b1a29d268e11.png)

![screen shot 2016-02-23 at 11 01 08 am](https://cloud.githubusercontent.com/assets/8272012/13263043/c7a52fd0-da1c-11e5-8306-20f0d713f7ad.png)

**Comment by shushz** [comment]
@michaeljcalkins it looks like like a [Watchman](https://facebook.github.io/watchman/) error. Is it properly [installed](http://nuclide.io/docs/editor/setup/#post-installation__other-installations) and is on the PATH?
Do you see any other prints in the console or in the logs?

**Comment by michaeljcalkins** [comment]
![screen shot 2016-02-24 at 10 45 51 am](https://cloud.githubusercontent.com/assets/8272012/13296731/ce085524-dae3-11e5-8b9b-35cb0b305a2c.png)

Just got this guy.

**Comment by michaeljcalkins** [comment]
Fixed it! For future readers:

`brew update && brew install watchman`

https://facebook.github.io/watchman/docs/install.html

I just checked and no where did I find on Nuclide that I needed to install Watchman.

**Comment by nmote** [comment]
@JoelMarcey I think we should make this clearer in the docs.

@mostafaeweda Let's pop up a clear warning if watchman isn't installed, explaining the implications and how to install it.

**Comment by michaeljcalkins** [comment]
I doubt I would have had this issue if the **Other Installations** section to the top of http://nuclide.io/docs/quick-start/getting-started/ labeled as required programs/packages.

**Or** at least mention that nuclide has required packages and list links to them because I don't want/need mercurial.
