### ISSUE TITLE
`tree-view` disabled after uninstalling nuclide

### ISSUE THREAD

**Issue by janmonschke** [facebook/nuclide#372]
### Issue and Steps to Reproduce
- Uninstall the `nuclide` package

### Expected Behavior
- The normal Atom `tree-view` should show

### Actual Behavior
- `tree-view` is hidden

### Versions
* Atom: 1.5.3
* Nuclide: 0.118.0
* Client OS: OSX
* Server OS (optional):

### Additional Details
`config.cson` still contained these lines after uninstalling:

    disabledPackages: [
      "tree-view"
    ]

**Comment by nmote** [comment]
Dup of #331
