### ISSUE TITLE
Nuclide file tree removes current file tree and shows nothing

### ISSUE THREAD

**Issue by DaveyEdwards** [facebook/nuclide#375]
### Issue and Steps to Reproduce
Problem
Tree view breaks and can never get it to show files/folders.
Empty space with add project folder is shown

Solution: 
Went to nuclide settings and disable the following 2 settings:  

1. Enable the "nuclide-file-tree" feature
Can not find '' inside the View tab to even display it
Removes your current file tree

2. Enable the "nuclide-side-bar" feature
This creates a big blank area next to the file tree (if first is disabled, otherwise shows nothing), which is where Im sure the nuclide file tree would have been shown 

### Expected Behavior
Tree view should be shown

### Actual Behavior
Tree view does not show, and does not allow you to add any project folders

### Versions
* Atom: 0.119
* Nuclide: 0.119.0
* Client OS: Windows 10

### Edit: Pictures added

Both Disabled
![image](https://cloud.githubusercontent.com/assets/15203899/13361624/b0cf8be8-dc74-11e5-8476-863dadc97948.png)

Both Enabled
![image](https://cloud.githubusercontent.com/assets/15203899/13361566/5be78770-dc74-11e5-96b3-f2097f6a6947.png)
![image](https://cloud.githubusercontent.com/assets/15203899/13361573/64e7aeb8-dc74-11e5-8215-8db7d11cf0d4.png)

Tree disabled, but sidebar enabled
![image](https://cloud.githubusercontent.com/assets/15203899/13361590/862b19e8-dc74-11e5-842e-be2f035977ba.png)

File Tree enabled, sidebar disabled
![image](https://cloud.githubusercontent.com/assets/15203899/13361642/c99a6d46-dc74-11e5-99ce-a6fb6d6e4346.png)

**Comment by nmote** [comment]
Could you add a screenshot? I think it would help us understand what's going on.

**Comment by DaveyEdwards** [comment]
Absolutely, let me know if you need anything else.

**Comment by ZebraFlesh** [comment]
Windows isn't supported yet: https://github.com/facebook/nuclide/issues/321

**Comment by umamiMike** [comment]
uninstalling.

**Comment by Daniel15** [comment]
@ssorallen - Any ideas what's broken here? I'm seeing the same thing - Atom's built-in file tree works fine, but Nuclide's doesn't.  This must mean Nuclide is doing something differently.

Nuclide's one **does** work for remote projects, but not local projects.
