### ISSUE TITLE
React Native debugger doesn't work with React Native v0.21.0-rc

### ISSUE THREAD

**Issue by Nikamura** [facebook/nuclide#376]
### Issue and Steps to Reproduce
* Create project using RN v0.21.0-rc
* Start packager
* Start react native debugger in atom
* Enable "chrome debugging" in the application

### Expected Behavior
* Nuclide attaches automatically, and application loads normally so you can continue debugging.

### Actual Behavior
* Nuclide attaches automatically, but application is stuck at loading from localhost:8081...
![image](https://cloud.githubusercontent.com/assets/3459367/13351924/ed7aad9a-dc81-11e5-9bf0-e8ffe9f0b2ba.png)

### Versions
* Atom: 1.5.3
* Nuclide: 0.119.0
* Client OS: OS X 10.10

### Additional Details
/Users/*/.atom/packages (1)
└── nuclide@0.119.0

I know that 0.21.0-rc changed some stuff in the Chrome debugging https://github.com/facebook/react-native/commit/64d56f34b779de94f251f4b443463cbfe790912d so don't really know if this is atom bug or React Native

**Comment by matthewwithanm** [comment]
Hi @Nikamura! Two quick questions. Have you used the debugger successfully with a previous version of RN? Also, what version of node do you have installed?

**Comment by Nikamura** [comment]
@matthewwithanm Just tested with the latest stable version and it didn't work also. So no.
Node version is 5.7.0

**Comment by matthewwithanm** [comment]
Ah, I think I see. Sometimes the debugger gets stuck for some reason. Can you hit the Pause button (F8) and see if it resumes?

**Comment by Nikamura** [comment]
Tried on two different RN apps on two different simulators, got two different errors after clicking fn+f8 (osx)

<img width="466" alt="screen shot 2016-02-27 at 01 23 58" src="https://cloud.githubusercontent.com/assets/3459367/13369760/e2e008e8-dcf0-11e5-9d9e-f853e408e015.png">
<img width="387" alt="screen shot 2016-02-27 at 01 15 55" src="https://cloud.githubusercontent.com/assets/3459367/13369761/e2e5bb08-dcf0-11e5-8276-b4d680d7df8e.png">

**Comment by matthewwithanm** [comment]
Okay, those are RN issues 😢

I have commits in to fix it (bb3d8d535000ad78a95776f2de9282130f80d0bd and ecf6981093f7f9afe4a462eee9e7af864c6d9e70) that I'm hoping to get into [0.21][0].

[0]: https://github.com/facebook/react-native/issues/6087

**Comment by Nikamura** [comment]
Okay cheers, I will cherry pick them until then. Have a good weekend:)

**Comment by matthewwithanm** [comment]
You too! Thanks for helping me diagnose!

**Comment by Nikamura** [comment]
It works, but I don't know if the behaviour is intended https://gfycat.com/UnconsciousImaginativeEel it always come up paused or something cause after each reload I have to press FN+F8, should I be using hot reloading to be able to use the debugging?

**Comment by matthewwithanm** [comment]
The paused thing is a bug 😢. I'll try to figure it out ASAP.

**Comment by Nikamura** [comment]
@matthewwithanm the bug where debugger starts paused is still present. Do you need any help debugging it?

**Comment by matthewwithanm** [comment]
Sorry, I've been working on an overhaul of the debugger stuff that's taken longer than anticipated. I'll put in a quick fix for this today.

**Comment by Nikamura** [comment]
Okay, thanks. Waiting for it.

**Comment by matthewwithanm** [comment]
Hey all! I've pushed a bunch of updates. Here's the current story (as of bb3311c75092ad7d80a456b3be0b734c55398f72):

1. You don't have to unpause between reloads (yay!)
2. The debugger isn't paused when you attach it if you're running node 4 (yay!)
3. …but it is if you're running v5 (boo!)

I've opened a new issue (#402) for the remaining bug. Thanks for bearing with me!
