### ISSUE TITLE
React Native: Start Packager use of const in strict mode

### ISSUE THREAD

**Issue by micksabox** [facebook/nuclide#377]
### Issue and Steps to Reproduce
Execute 'Nuclide React Native: Start Packager'

### Expected Behavior
Packager starts and output is displayed

### Actual Behavior
Tell us what happens instead.
```
.../node_modules/react-native/local-cli/cli.js:74
  const setupEnvScript = /^win/.test(process.platform)
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```
### Versions
* Atom: 1.5.3
* Nuclide: 0.119.0
* Client OS: Mac OS X 10.10.5
* Server OS (optional):

### Additional Details
└── nuclide@0.119.0

Seems like the Node version that Nuclide uses to start the packager is not ES6 friendly.

**Comment by matthewwithanm** [comment]
Hey @micksabox! Nuclide actually uses your system node for this task (e.g. whichever is on `$PATH`). Sorry, I'll add a setting so that you can customize this. 😕

In the meantime, can you try opening Atom from the CLI in a terminal that has the right version of node on the PATH as a workaround?

**Comment by matthewwithanm** [comment]
Oops! The packager doesn't actually call out to node; it just calls [the `packager.sh` in react-native][1] which in turn uses the `node` on your path.

The workaround should still do the trick, but this illustrates a need for a better `$PATH` story in Nuclide.

[1]: https://github.com/facebook/react-native/blob/f99579adaa1d312ba0ee4a71badba84e57f197e6/packager/packager.sh

**Comment by micksabox** [comment]
@matthewwithanm opening Atom from the CLI did not work as well. Luckily, you put me on the right track and I realized I had another version of node installed in my `$PATH`. Once removed, the packager worked as expected.

**Comment by cco5566** [comment]
@micksabox I'm in the same condition as you but I still can't fix it.  😕
Would you plz show more detail about how you run React Native Server normally?

**Comment by micksabox** [comment]
@cco5566  what I ended up doing was symlinked the latest nvm version of node (mine is v5.0.0) to the path /usr/bin/node. I think that Nuclide looks for the node installed specifically at /usr/bin/node, so just by symlinking it to the right version this solved the problem.

**Comment by matthewwithanm** [comment]
Hey guys! The next release adds a setting for node path. Hope this helps!

**Comment by matthewwithanm** [comment]
To clarify what's going on here: Nuclide is executing the [packager script in react-native][0] which does the following:

    THIS_DIR=$(dirname "$0")
    node "$THIS_DIR/../local-cli/cli.js" start "$@"

So whichever node is in your `$PATH` is the one that's going to be used. Note, though, that Nuclide isn't going to get `$PATH` modifications made in your shell configurations (`.bash_profile`, `.zshrc`, etc) unless you launch it from a session that has those modifications.

There are a couple of things we could do to make this better: 1) give users more control over their `$PATH` within Nuclide and 2) allow alternate ways to specify the packager command. (We already have one alternative, which is a [`.buckconfig` with a `[react-native]` section][1].)

[0]: https://github.com/facebook/react-native/blob/f99579adaa1d312ba0ee4a71badba84e57f197e6/packager/packager.sh
[1]: https://github.com/facebook/nuclide/blob/43f30a52001a5e6fb4ec09be9655bdb8bb72caf9/pkg/nuclide/react-native/lib/packager/getCommandInfo.js#L86-L96

**Comment by Emilios1995** [comment]
@micksabox Would you please provide more details about how you made this symlink?

**Comment by micksabox** [comment]
@Emilios1995 As per my answer above, I removed the existing node binary in /usr/bin/ and made a new file called node there, and symlinked it to the v5.0.0 version of node. I followed instructions here: http://stackoverflow.com/questions/1951742/how-to-symlink-a-file-in-linux. Basically, symlink is like a file redirect, so whenever something is looking for the node in /usr/bin, it will get redirected to the v5.0.0 version. Good luck.

**Comment by matthewwithanm** [comment]
@Emilios1995 @micksabox With 2d735, Nuclide will use the `nuclide-react-native.pathToNode` setting to run the packager. ("Path to Node Executable" under "Nuclide-react-native" in the Nuclide settings.) This'll be in next week's release.

Also related, once atom/atom#4126 lands, Atom should automatically pick up your PATH settings!
