### ISSUE TITLE
Run button is missing for Node.JS project

### ISSUE THREAD

**Issue by mictadlo** [facebook/nuclide#380]
### Issue and Steps to Reproduce
I imported a Node.JS project (server and client side) to Nuclide, but the RUN button did not appear neither auto completion is working.

### Expected Behavior
I would expected that I would a RUN button and auto completion would work.

### Actual Behavior
I am not able to execute the project and the auto completion is not working.

### Versions
* Atom: 1.4.0
* Nuclide: 0.120.0
* Client OS: Linux mint 17.3

**Comment by jgebhardt** [comment]
@mictadlo can you clarify what you mean by Run button? Has this run button worked previously?

**Comment by mictadlo** [comment]
In this video https://youtu.be/X0VH78ye4yY?t=29m29s on the top there is a RUN button. Unfortunately, I have  never got this RUN button.

**Comment by jgebhardt** [comment]
Ah, what you see in the video is the Buck build bar, which only appears in Buck-based projects. There's not currently a "run" button button for node in Nuclide. I'm curious though– How would you expect it to behave, hypothetically speaking? Would we just try to read `package.json` and extract npm scripts and wrap them in UI?

**Comment by mictadlo** [comment]
I would have aspected to behave like shown here https://www.youtube.com/watch?v=54aol-U_1es&index=15&list=PL6gx4Cwl9DGBMdkKFn3HasZnnAqVjzHn_
