### ISSUE TITLE
Multiple select button on file tree needs styling fixes

### ISSUE THREAD

**Issue by michaeljcalkins** [facebook/nuclide#381]
### Issue and Steps to Reproduce
Multiple select button on file tree needs styling fixes

![screen shot 2016-03-02 at 9 23 51 am](https://cloud.githubusercontent.com/assets/8272012/13468701/c3d450b0-e058-11e5-8934-15567c4b8361.png)

![screen shot 2016-03-02 at 9 26 35 am](https://cloud.githubusercontent.com/assets/8272012/13468716/e0f86adc-e058-11e5-861d-cff254fe1361.png)

### Expected Behavior
The icon should appear in the middle of the button.

### Actual Behavior
The icon is off to the left.

### Versions
* Atom: 1.5.3
* Nuclide: 0.120.0
* Client OS: 10.11.3

**Comment by jamesgpearce** [comment]
This was fixed in https://github.com/facebook/nuclide/commit/87159ec695473b073d593edd276994960583e97e
