### ISSUE TITLE
Interfacing a new debugger

### ISSUE THREAD

**Issue by dpo** [facebook/nuclide#382]
This is just a question. I'm wondering if there are guidelines explaining how to interface a new debugger with Nuclide? I'm particularly interested in one of the Python debuggers. Where should one start looking?

Thanks!

**Comment by johnislarry** [comment]
Hey!  There are currently no written guidelines for interfacing debuggers.  I can point you to some examples that might help you -- they all have roughly the same structure.  Nuclide currently supports 3 debuggers:

1. LLDB -- works for local projects (and soon for remote projects).  Look in `pkg/nuclide/debugger/lldb-{client,server}`
2. HHVM -- works for remote projects only.  Look in `pkg/nuclide/debugger/hhvm` and `pkg/nuclide/debugger-hhvm-proxy`
3. Node and React Native -- works for local projects only.  Look in `pkg/nuclide/debugger/node`

Each of these debuggers shares common UI code in `pkg/debugger/atom`.  Hopefully this is enough for you to get started.  I'm going to close this issue but feel free to reopen with follow up questions, comments, etc.

**Comment by matthewwithanm** [comment]
I just wanted to jump in and say that this would be so awesome @dpo! Keep us/me in the loop!
