### ISSUE TITLE
Unable to focus between editor and side bar

### ISSUE THREAD

**Issue by codemonkey800** [facebook/nuclide#384]
### Issue and Steps to Reproduce
Previous versions of Nuclide allowed me to change focus between the side bar and editor. For some reason, it doesn't work in version 0.120.0. I haven't tried downgrading just yet, but I have a feeling it'll work fine on older versions.

I also have a Mac with Atom set up exactly the same way as I have it set up on my Linux laptop. Changing focus works fine on my Mac, so it's definitely something to do with Linux.

### Expected Behavior
Alt+/ should switch focus between the side bar and the editor.

### Actual Behavior
Focus isn't changed at all.

### Versions
* Atom:  1.6.0-beta7
* Nuclide: 0.120.0
* Client OS: Arch Linux x64
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
Sublime-Style-Column-Selection@1.5.1
atom-beautify@0.28.26
atom-jade@0.3.0
atom-material-syntax@0.4.3
atom-material-ui@1.2.0
autoclose-html@0.23.0
autocomplete-cmake@0.3.1
autocomplete-html-entities@0.1.0
autoprefixer@3.2.0
color-picker@2.1.1
csscomb@0.3.1
docblockr@0.7.3
editorconfig@1.2.4
haskell-grammar@0.4.0
highlight-line@0.11.1
highlight-selected@0.11.2
jade-beautify@0.1.4
language-babel@2.15.4
language-cmake@0.1.4
language-docker@1.1.6
language-fish-shell@1.0.3
language-groovy@0.5.0
language-ini@1.14.0
language-kotlin@0.4.0
language-latex@0.6.1
language-lua@0.9.4
language-mips@0.2.0
language-ocaml@1.1.2
language-swift@0.4.0
language-thrift@1.0.2
latex@0.30.0
latexer@0.3.0
linter@1.11.3
linter-chktex@1.2.5
linter-csslint@1.3.2
linter-docker@0.1.2
linter-eslint@7.0.0
linter-gcc@0.6.8
linter-jade@0.3.2
linter-kotlin@0.1.0
linter-lua@1.0.1
linter-swiftc@2.0.0
minimap@4.19.0
minimap-highlight-selected@4.3.1
nuclide@0.120.0
pdf-view@0.45.0
preview@0.16.6
release-notes@0.53.0
remote-edit@1.8.24
sort-lines@0.14.0
sync-settings@0.6.0
tool-bar@0.2.1
trailing-spaces@0.3.2
```

**Comment by jgebhardt** [comment]
1) By sidebar, do you mean the tree view?
2) By changing focus, do you mean toggling it? I don't think focus was ever affected by this.

**Comment by ssorallen** [comment]
Looks like this stopped working when the file-tree got wrapped in another container for working-sets. I'll take a look.

**Comment by codemonkey800** [comment]
@jgebhardt Yeah I mean the tree view. I assumed sidebar and tree view were interchangeable since it's referenced as the sidebar in command palette:

![atom](https://cloud.githubusercontent.com/assets/2176050/13541885/f920bb66-e213-11e5-9818-0e9b51fd1f2c.png)

Maybe a name change would be better? There are commands called `Nuclide Sidebar: Toggle` and `Nuclide File Tree: Toggle` that do the exact same thing but are mapped to different shortcuts.

And toggling it works fine. Both the commands I mentioned above work, but the `Nuclide Sidebar: Toggle Focus` does not.

@ssorallen That makes sense. Working sets just appeared with this version, so I suspected it had something to do with that.
