### ISSUE TITLE
I can not open a folder

### ISSUE THREAD

**Issue by cuitl** [facebook/nuclide#385]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

### Expected Behavior
Tell us what should happen.

### Actual Behavior
when I click add project folder' and select one folder ,nothing happened and the 'add project folder' is also there.

### Versions
* Atom:1.5.4
* Nuclide:lastest version
* Client OS:window
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by jgebhardt** [comment]
> Nuclide:lastest version

Can you be more specific? Which exact Nuclide version are you using? You can find the version in Settings > Packages > Nuclide.

**Comment by ssorallen** [comment]
Merging this into #375.
