### ISSUE TITLE
lintOnFly error - Need Help

### ISSUE THREAD

**Issue by Roadspill** [facebook/nuclide#387]
### Issue and Steps to Reproduce

Upon loading Atom, I get this error. I'm not sure what it means, nor can I seem to find anything about it on the internet. I would like to figure out how to fix this, and better understand what it means.

**_ERROR or ALERT MESSAGE (Not sure which, it's red)**_

> nuclide-diagnostics-store found problems with a linter. Diagnostic messages from that linter will be unavailable.
> - lintOnFly must be false for a linter with 'project' scope
### Expected Behavior

Load Atom cleanly with no errors.
### Actual Behavior

Same as above, loads Atom with an error.
### Versions
- Atom: 1.5.4
- Nuclide: v120
- Client OS: Mac OSX 10.11.3 (El Capitan)
### Additional Details

Everything is up to date as of this moment.

/Users/_home_directory_/.atom/packages (44)
├── Sublime-Style-Column-Selection@1.5.1
├── atom-beautify@0.28.26
├── atom-ternjs@0.13.2
├── auto-detect-indentation@1.0.0
├── autoclose-html@0.23.0
├── autocomplete-modules@1.4.1
├── autocomplete-plus@2.29.1
├── autoprefixer@3.2.0
├── color-picker@2.1.1
├── csscomb@0.3.1
├── docblockr@0.7.3
├── editorconfig@1.2.4
├── emmet@2.4.2
├── file-icons@1.6.17
├── haskell-grammar@0.4.0
├── highlight-line@0.11.1
├── highlight-selected@0.11.2
├── javascript-snippets@1.2.1
├── jshint@1.8.3
├── language-babel@2.15.5
├── language-ini@1.14.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.3
├── linter-csslint@1.3.2
├── linter-eslint@7.0.0
├── linter-flow@4.1.0
├── linter-htmlhint@1.0.3
├── linter-jshint@2.0.2
├── minimap@4.19.0
├── minimap-highlight-selected@4.3.1
├── minimap-pigments@0.1.7
├── monokai-seti@0.7.0
├── nuclide@0.120.0
├── open-recent@5.0.0
├── pigments@0.24.2
├── react@0.14.1
├── save-session@0.16.0
├── seti-ui@0.9.1
├── solarized-seti-ui@0.8.6
├── sort-lines@0.14.0
├── todo-show@1.3.0
├── tool-bar@0.3.0
└── uglify@1.2.5

**Comment by ssorallen** [comment]
Nuclide's diagnostics clashes with the community "linter" package. @nmote, what's the current recommendation for linter / diagnostics?

**Comment by nmote** [comment]
Sorry for the delay in responding. Basically, you have a package installed the the Nuclide diagnostics package is not compatible with. I should improve the error message here to include the name of the package.

This error, specifically, I think is just a case of diagnostics being overly conservative. When I implemented this validation I wasn't sure what it would mean to have a project-level linter that could lint as you type, so I disallowed it. We could probably relax this restriction, though.

Anyway, this will only effect results from the one package that is triggering this error. It's almost certainly one of the `linter-` packages. If you like you could also go in to the Nuclide settings and disable the `nuclide-diagnostics-*` features and just use the `linter` package to display issues. You won't get Flow issues through `nuclide-flow` anymore, but it looks like you're using the `linter-flow` package which is compatible with `linter`.

**Comment by jiangyuanhk** [comment]
`Linter-Eslint` works fine with diagnostics, but whenever `linter-flow` is enabled the error would appear.  Wonder what's the best configuration for now?

**Comment by export-mike** [comment]
@jiangyuanhk hey I'm getting this error as I'm using linter-flow and linter-eslint did you get anywhere with this?

**Comment by export-mike** [comment]
@jiangyuanhk got it! 
disable the linter, as mentioned here: https://github.com/AtomLinter/linter-eslint#installation
![image](https://cloud.githubusercontent.com/assets/2983327/15902686/1ffe7970-2da1-11e6-8b06-f622b893507f.png)

**Comment by joshburgess** [comment]
Disabling the linter isn't really a great option considering some of us likely have other linters for various languages we want to use that have nothing to do with Nuclide and depend on it. 

I've messed about with the settings in Nuclide multiple times and cannot seem to get rid of this "lintOnFly must be false for a linter with 'project' scope" error...

**Comment by joshburgess** [comment]
I'm pretty baffled by how to get rid of this error other than just completely disabling the nuclide-diagnostics-store...

**Comment by nmote** [comment]
I think the validation just has to be relaxed. Removing [this if block](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-diagnostics-store/lib/LinterAdapterFactory.js#L87) should do it. Anyone want to put up a PR?

**Comment by OvermindDL1** [comment]
I currently get this error on every load, and I've disabled every linter.  What is the proper fix for this?

**Comment by nmote** [comment]
I described what I think is the proper fix in my last comment. Feel free to put up a PR.

**Comment by OvermindDL1** [comment]
I did that locally as a test and it does resolve that specific issue, but some languages linter's functionality vanished.  I think they rely on the GUI system within linter...

**Comment by nmote** [comment]
That sounds like a separate issue. If they are doing something too weird we won't bend over backwards to support it but if there's an obvious incompatibility with the linter API that should be fixed. In any case we'll need a separate issue with more details.
