### ISSUE TITLE
Hack: XHP Single Quote Mismatch Issue

### ISSUE THREAD

**Issue by aewing** [facebook/nuclide#39]
Currently XHP support is having some issues with syntax highlighting stemming from "mismatched" single quotes. See below:
![nuclide-xhp-bug](https://cloud.githubusercontent.com/assets/5033161/7998887/d7fa06e8-0af7-11e5-8462-36871f98c8ce.png)

**Comment by fredemmott** [comment]
@mostafaeweda : any update on this? Can still reproduce on master.

**Comment by fredemmott** [comment]
Appears to be fixed, guessing c88465e2c107c5a58688d417fd255b808514f55e
