### ISSUE TITLE
Not able to make Flow work with Nuclide

### ISSUE THREAD

**Issue by pixelpunch** [facebook/nuclide#395]
### Issue and Steps to Reproduce
Flow works fine when I call it from the Terminal. I had installed it with - 

`$> mkdir -p get_started
$> cd get_started
$> echo '{"name": "get_started", "scripts": {"flow": "flow; [[ $?=0||$?=2 ]]"}}' > `package.json``

Throws the correct errors.

### Expected Behavior
How do I ensure that Flow is on the $PATH? I did this -

`export PATH=$PATH:~/flow
pixeld@Xb-nP-Pixel-D $ ~/flow 
$ echo $PATH
/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/Users/pixeld/flow`

### Actual Behavior
`~$  type flow
flow not found`

### Versions
* Atom:1.5.4
* Nuclide: 0.120.0
* Client OS: El Capitan
* Server OS (optional):

### Additional Details
* Installed packages (`complete Nuclide`):

**Comment by peterhal** [comment]
After the npm install step in the flow quick start, flow will be installed into: get_started/node_modules/.bin/flow

**Comment by pixelpunch** [comment]
Hi Peter

Thanks for the tip. I couldn't find the executable. Now I know.
All good now.

Alok

**Comment by romulof** [comment]
It would be very nice if Nuclide could automatically search for _flow_ executable first at `./node_modules/.bin/` then after at `$PATH`.
