### ISSUE TITLE
When I enable it in Windows, I can't open any project.

### ISSUE THREAD

**Issue by bosung90** [facebook/nuclide#397]
### Issue and Steps to Reproduce
When I enable nuclide in Windows, I get no folder structure on the left hand side even after opening a project.

### Expected Behavior
I should see a project folder structure on the left hand side (it works fine in Mac)

### Actual Behavior
I see "Add project folder" and "Add remote proejct folder" buttons but no project folder structure

### Versions
* Atom: 1.5.4
* Nuclide: 0.120.0
* Client OS: Windows 10
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`): 
├── language-babel@2.15.5
└── nuclide@0.120.0

**Comment by ssorallen** [comment]
Merging this into #385.

Windows support is minimal at the moment, but I'd like to at least ensure you get a file tree.
