### ISSUE TITLE
Preview tabs not working

### ISSUE THREAD

**Issue by Nikamura** [facebook/nuclide#407]
### Issue and Steps to Reproduce

Using latest nuclide (master) on `atom-beta` preview tabs do not work as the option  `usePreviewTabs` has been removed from `atom/tabs` https://github.com/atom/tabs/commit/873f88431343b79cf74e7fb79a0c03631a700ce3 (can't find exact commit where it was removed)
and now it's default behaviour.

### Expected Behavior
Single clicking on file it should open a Preview/Pending tab

### Actual Behavior
Single clicking doesn't do anything.

### Manual fix
Adding 
```cson
  nuclide:
      "nuclide-file-tree":
         usePreviewTabs: true
  tabs:
    usePreviewTabs: true
```
to your config.cson fixes this behaviour

**Comment by ssorallen** [comment]
I had my eye on this one in Atom Beta, thanks for reporting. We will get this fixed soon.
