### ISSUE TITLE
Inspector not running in Nuclide

### ISSUE THREAD

**Issue by tsvetann** [facebook/nuclide#408]
### Issue and Steps to Reproduce

Cannot start RN inspector in Nuclide
### Expected Behavior

Starting rninspector in Atom.
### Actual Behavior

Waiting for a connection from React Native

This should happen pretty quickly. If it hasn't, something's wrong. 😢

Troubleshooting Tips:

Make sure a React Native app is running and that it's in DEV mode.
Only one element inspector can be active at a time. Close any other open inspectors.
There may be a zombie element inspector instance running. Try reopening your Atom window or check port 8097.

localhost:8097 gives me: Upgrade Required
### Versions
- Atom: 1.5.4
- Nuclide: 0.124.0
- Client OS: OSX

Any ideas how to debug this further are welcome!

**Comment by matthewwithanm** [comment]
Hi @tsvetann! Have you gone through the troubleshooting tips yet? If you're seeing "Upgrade Required" in a browser, it probably means there's another inspector connected. Do you have another Atom window open with one? Have you tried restarting Atom yet?

You can check to see what's using the port by running `lsof -i :8097` in your terminal.

**Comment by tsvetann** [comment]
Thanks @matthewwithanm I have tried all steps mentioned.

`lsof -i :8097` returns nothing. I start rninspector and it returns: `Atom\x20H 13655 t.nikolov   32u  IPv4 0xb33f0b252baadc93      0t0  TCP *:sac (LISTEN)` but the inspector window suggests it cannot connect. Only one Atom instance opened! Even restarted my mac and the same thing. There must be something else but now sure how to dig deeper.

**Comment by matthewwithanm** [comment]
It's interesting that you're not seeing your React Native app in that list. It's running, right? What version of RN is it?

**Comment by tsvetann** [comment]
RN version: 0.21.0-rc

Thx

**Comment by NullPtrEx** [comment]
Also happens with RN 0.22.2 and a real Android device connected.

lsof -i :8097 returns Atom.

**Comment by danybony** [comment]
With RN 0.26.1 the inspector correctly works with iOS simulator, but it's displaying the same error (Waiting for a connection from React Native, check port 8097) with Android (both emulator or physical device).
`lsof -i :8097` returns just Atom here as well.

**Comment by benjy** [comment]
I have this same issue on Android.

Nuclide: 1.141.0
React Native: ^0.27.0-rc2

```
lsof -i :8097
COMMAND     PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
Atom\x20H 44388 benjy   31u  IPv4 0x381532cf3a414ba9      0t0  TCP *:sac (LISTEN)
```

**Comment by Jtango18** [comment]
Same issue here on Android. Glad I'm not going crazy.

**Comment by ColCh** [comment]
Guys, It's not a `nuclide` issue. It's `react-native` issue.

I've got it working on android simulator. 🎉 

Follow this comments: https://github.com/facebook/react-devtools/issues/229#issuecomment-225746736 and https://github.com/facebook/react-devtools/issues/229#issuecomment-226237564

However, MR by @kageurufu was merged about month ago, I don't see their changes 

And, by the way, big thanks @kageurufu

**Comment by Jtango18** [comment]
Working for me after upgrading to 0.30 too. Hooray!

**Comment by gpEscrivo** [comment]
For connecting the inspector to a real device typing:

`adb reverse tcp:8097 tcp:8097`

in the console worked for me.
