### ISSUE TITLE
process_info.py broken on Solaris

### ISSUE THREAD

**Issue by darrenkenny** [facebook/nuclide#412]
When I install nuclide on Solaris - server-side - it fails to start the nuclide-server process
due to errors in processing the process information in process_info.py. 

The ps command on Solaris behaves differently to that on Solaris, so the process_info.py
file needs some slight modification to work out of the box.

Attached is a diff of the changes that I had to make to get it to work, and successfully
start up the nuclide-server (and not start it, if it's already running).

[process_info.py.diff.txt](https://github.com/facebook/nuclide/files/176492/process_info.py.diff.txt)

**Comment by ssorallen** [comment]
Pasted comments of the author's diff:

```diff
--- ./pkg/nuclide/server/scripts/process_info.py.orig	Sun Jan 10 23:55:35 2016
+++ ./pkg/nuclide/server/scripts/process_info.py	Wed Mar 16 16:52:09 2016
@@ -12,9 +12,11 @@
 import subprocess
 import utils
 
-COLUMNS = ['pid', 'command']
+if os.uname()[0] == 'SunOS':
+    COLUMNS = ['pid', 'comm', 'args']
+else:
+    COLUMNS = ['pid', 'command']
 
-
 # TODO: Ideally, we want to use psutil, but it is not part of standard library.
 class ProcessInfo(object):
 
@@ -25,8 +27,14 @@
         tokens = line.strip().split()
         self._fields = {}
         for i in range(len(columns)):
+            if os.uname()[0] == 'SunOS' and columns[i] == 'args':
+                # Skip 'args'
+                continue
             self._fields[columns[i]] = tokens[i]
-        if columns[i] == 'command':
+
+        if os.uname()[0] == 'SunOS' and columns[i] == 'args':
+            self._fields['command'] = ' '.join(tokens[i:])
+        elif columns[i] == 'command':
             # In ps, 'comm' means the base command and 'command' is the full command.
             # So far only the first token in command is assigned to command field.
             # Assign that to 'comm' field.
@@ -82,8 +90,6 @@
         else:
             # Filter out comm and command column and then append it to the end
             # so that we can use space as delimiter.
-            new_columns = [column for column in columns if column not in ['comm', 'command']]
-            new_columns.append('command')
             args.append('-o')
             args.append(','.join(columns))
```

**Comment by mostafaeweda** [comment]
@darrenkenny we do accept PRs, please submit one and we shall put it in as soon as possible.

**Comment by darrenkenny** [comment]
A PR requires me to sign a contributor agreement, which I'm currently unable to do due to the approvals that I'd need from my employer to permit it... Is there no way you could apply the patch
for me?

**Comment by matthewwithanm** [comment]
Sorry, @darrenkenny but we can't accept code unless you sign the CLA. 😢

**Comment by jgebhardt** [comment]
I'm closing this issue since it's been quite a while. If anyone wants to file a PR, please feel free to do so!
