### ISSUE TITLE
Can not make autoComplete use flow shipped lib/react.

### ISSUE THREAD

**Issue by iamchenxin** [facebook/nuclide#413]
with `.flowconfig` 
```
[ignore]
.*/node_modules/.*
.*/node_modules/react/.*
```
with ignoring `.*/node_modules/react/.*` , the imported `React` is still `any` type.
Should the autoComplete be referred to [declare module react](https://github.com/facebook/flow/blob/master/lib/react.js#L148) in flow's `lib/react.js`?  did i miss something?(maybe im a bit confused with flow's module declaration)
![screenshot from 2016-03-17 06-22-07](https://cloud.githubusercontent.com/assets/8873545/13838272/8f182820-ec0a-11e5-9341-9511bc35b78b.png)

BTW: is there some something like typescript's d.ts to manage flow's type definitions for 3rd libs in nuclide community?
i google and stackoverflow this,find no information about how to get or share type definitions from somewhere.

Sorry for this useless issue,but i did not find the answer anywhere else.

### Versions
* Atom:1.5.4
* Nuclide:lastest
* Client OS:ubuntu 15.10

**Comment by nmote** [comment]
Hey, it would be better to file this issue on the [Flow repository](https://github.com/facebook/flow) as it's not specific to Nuclide and they know more about the intricacies involved.

I do know that they have plans to make it easy to manage 3rd party library type definitions but unfortunately it's not currently very simple.
