### ISSUE TITLE
[Documentation] div.projectLogo covers home page links

### ISSUE THREAD

**Issue by vtambourine** [facebook/nuclide#414]
Block `div.projectLogo` covers home page link, making them inaccessible.

![screen shot 2016-03-17 at 13 16 46](https://cloud.githubusercontent.com/assets/1044363/13843113/3c4d4ad0-ec4b-11e5-897a-93399f11085f.png)

**Comment by jamesgpearce** [comment]
fix coming! thanks

**Comment by jamesgpearce** [comment]
https://github.com/facebook/nuclide/commit/13c79356b0f175ed20b94785e3fd6f99e54f54cb
