### ISSUE TITLE
Nuclide install unable to find "relative-date" package

### ISSUE THREAD

**Issue by joetyson** [facebook/nuclide#422]
### Issue and Steps to Reproduce
Have tried installing from source, via apm install, and via atom's package install in settings.

### Expected Behavior
Expected nuclide to install.

### Actual Behavior
Receive this error: "Installing “nuclide@0.125.0” failed"

Expanded details:
npm WARN engine nuclide@0.125.0: wanted: {"atom":">=1.5.3","node":">=4.1.1"} (current: {"node":"0.10.40","npm":"2.13.3"})
npm ERR! Darwin 15.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/joe/.atom/.apm/.apmrc" "--userconfig" "/Users/joe/.atom/.apmrc" "install" "/private/var/folders/31/njc40rln41v0x3d6pfl0pvmc0000gn/T/d-116222-3030-5glias/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/relative-date
npm ERR! 404 
npm ERR! 404 'relative-date' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'nuclide'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/31/njc40rln41v0x3d6pfl0pvmc0000gn/T/apm-install-dir-116222-3030-1ilw9hw/npm-debug.log

### Versions
* Atom: 1.6.0
* Nuclide: 0.125.0
* Client OS: OS X 10.11.3
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
/Users/joe/.atom/packages (2)
├── merge-conflicts@1.3.7
└── monokai@0.18.0

**Comment by samwgoldman** [comment]
Yup—happening over here too. It looks like the `relative-date` package used to exist on NPM, but has since been removed from the registry. Replacing the version string with `"azer/relative-date"` in `package.json` is a hacky temporary workaround. The same thing is happening with `left-pad`, a library by the same author.

**Comment by samwgoldman** [comment]
See https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c#.y64upds2r

**Comment by jsg2021** [comment]
Its been republished as 1.1.3. New maintainer: https://github.com/n-johnson/relative-date

**Comment by HADB** [comment]
+1

**Comment by HADB** [comment]
@jsg2021 but nuclide seems to use version 1.1.2

**Comment by hansonw** [comment]
Solved by 0.126.0.
