### ISSUE TITLE
Question about remote connections

### ISSUE THREAD

**Issue by alanzanattadev** [facebook/nuclide#426]
Hi

I don't know if I have to open an issue for that but it's the only way I know to ask you something about nuclide.

How can I use the remote connection of nuclide to send ssh commands to remote server without creating my own connection, in my atom packages, is there any way ?

It's for git-commit and git-checkout packages.

Thank you

**Comment by jjh42** [comment]
This relates to my request for a nuclide api.
https://github.com/facebook/nuclide/issues/516 where you've provided an interim solution.

**Comment by nmote** [comment]
Closing in favor of that issue.
