### ISSUE TITLE
nuclide-file-tree won't stay disabled

### ISSUE THREAD

**Issue by courthead** [facebook/nuclide#430]
### Issue and Steps to Reproduce
I've added `nuclide-file-tree` to the list of `disabledPackages` in my config and reenabled `file-tree`, which works at first. However, after closing Atom and reopening it, things have reset.

### Expected Behavior
Disabling Nuclide's file tree should keep it disabled permanently + prevent it from disabling the default file tree.

### Actual Behavior
After restarting Atom, the Nuclide file tree is back and the normal file tree is gone. When I check my config, both show up under `disabledPackages`. To get things back how I want them, I have to remove `file-tree`, remove `nuclide-file-tree`, save, then add `nuclide-file-tree` back. Every single time I restart Atom.

### Versions
* Atom: 1.6.0
* Nuclide: 0.126.0
* Client OS: OSX

**Comment by courthead** [comment]
Figured it out, didn't see the box for `Enable the "nuclide-file-tree" feature` in the Nuclide settings!

**Comment by nahuelhds** [comment]
I'd like to do this action with Nuclide 0.239.0. How can I?

**Comment by nahuelhds** [comment]
I've did the same as @courthead mention but it auto-enables again after restart.
Plus, in Nuclide 0.239.0 I'm not seeing the option `Enable the "nuclide-file-tree" feature`, so I really don't know how to perform this so it persist even after Atom restart.

Any help would be apprettiated. Thanks!
