### ISSUE TITLE
No Preview Tabs in 1.6.0

### ISSUE THREAD

**Issue by yuwang17** [facebook/nuclide#431]
### Issue and Steps to Reproduce
Preview tabs not working. At Atom 1.6.0 usePreviewTabs was removed from "Tabs" and, under nuclide I have no way to preview tabs. 

### Expected Behavior
Single click on the file in tree view shows the preview tab instead opening new tabs.

### Actual Behavior
Every click on the new tree view file opens a new tab.

### Versions
* Atom: 1.6.0
* Nuclide: 0.126.0
* Client OS: Mac OS 10.11.3

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-beautify@0.28.27
├── atom-material-syntax@0.4.5
├── atom-material-ui@1.2.10
├── autoclose-html@0.23.0
├── autocomplete-clang@0.8.9
├── autocomplete-haskell@0.6.5
├── autocomplete-python@1.7.2
├── color-picker@2.1.1
├── ex-mode@0.8.0
├── git-plus@5.13.0
├── haskell-ghc-mod@1.11.4
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── ide-haskell@1.5.4
├── language-babel@2.16.0
├── language-haskell@1.7.6
├── language-ini@1.15.0
├── language-latex@0.6.1
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── latex@0.32.0
├── linter@1.11.4
├── linter-csslint@1.3.2
├── linter-eslint@7.1.3
├── linter-flake8@1.13.0
├── markdown-writer@2.3.2
├── merge-conflicts@1.3.7
├── minimap@4.21.0
├── monokai@0.18.0
├── nuclide@0.126.0
├── pdf-view@0.50.0
├── pigments@0.26.0
├── react@0.14.2
├── react-snippets@0.3.0
├── seti-syntax@0.4.2
├── seti-ui@0.9.2
├── sort-lines@0.14.0
├── tool-bar@0.4.0
├── vim-mode@0.65.0
└── vim-mode-plus@0.28.0

**Comment by yuwang17** [comment]
I don't think this issue has been fixed in 0.127 ...

**Comment by ssorallen** [comment]
@yuwang17 No it hasn't. I mentioned the issue in my commit, and so GitHub auto-closed it. I can leave this open and close it when the commit makes it into a release.

**Comment by yuwang17** [comment]
Alright. Cool! Hope you can fix this soon. Thanks!

**Comment by ssorallen** [comment]
This is out and fixed in v0.128.0.

@yuwang17, let me know if you still have problems after updating to the latest.
