### ISSUE TITLE
Outline View should support Function Expressions

### ISSUE THREAD

**Issue by DaleJefferson** [facebook/nuclide#437]
### Issue and Steps to Reproduce
![screen shot 2016-03-29 at 23 38 51](https://cloud.githubusercontent.com/assets/375005/14126236/6d1ab290-f607-11e5-9154-e9f912845d18.png)

```
/* @flow */

function functionDeclaration() {
}

var functionExpression = function () {
};
```

### Expected Behaviour
I would expect both types to show up in the Outline View

### Actual Behaviour
Only the function declarations is displayed

### Versions
* Atom: 1.6.0
* Nuclide: 0.127.0
* Client OS: Mac OS

### Additional Details
* Installed packages (`apm ls --installed`):

├── atom-typescript@8.4.0
├── autocomplete-modules@1.4.1
├── editorconfig@1.2.4
├── git-plus@5.13.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.16.0
├── language-ini@1.15.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.4
├── linter-eslint@7.1.3
├── nuclide@0.127.0
├── pigments@0.26.0
├── sort-lines@0.14.0
├── terminal-plus@0.14.5
└── tool-bar@0.4.0

**Comment by nmote** [comment]
Yep, there are a bunch of different things that I'm planning to support with outline view in the near future but I wanted to get an initial working version off the ground ASAP. I'll probably get to this in the next two weeks.

**Comment by nmote** [comment]
exports.foo =..., module.exports = { ... }, and maybe top-level constants are some of the others.

**Comment by DaleJefferson** [comment]
@nmote It looks like a really promising feature, it seems to do a really good job with ES6 classes. I eagerly await wider language support, thanks for adding this feature.
