### ISSUE TITLE
Python3 incompatibilities

### ISSUE THREAD

**Issue by Adonai** [facebook/nuclide#438]
### Issue and Steps to Reproduce
Clang server fails to start  (apparently due to incorrect python version)

* Install python
* Install atom
* Install nuclide
* Build your project with cmake
* Create symlink to compile_commands.json in your src tree
* Open this folder as a project in Nuclide

(tested on KWin)

### Expected Behavior
Clang server should pick up compile_commands.json and provide autocompletions and checks for Nuclide

### Actual Behavior
```
2016-03-29T23:19:38.125Z] [ERROR] nuclide - Error receiving data Traceback (most recent call last):
  File "/home/adonai/.atom/packages/nuclide/pkg/nuclide-clang/python/clang_server.py", line 12, in <module>
    from clang.cindex import *
  File "/home/adonai/.atom/packages/nuclide/pkg/nuclide-clang/pythonpath/clang/cindex.py", line 513
    raise ValueError,'CursorKind already loaded'
                    ^
SyntaxError: invalid syntax
```
In logs

### Versions
* Atom: 1.6.0
* Nuclide: 0.127.0
* Client OS: ArchLinux

**Comment by Adonai** [comment]
Note: I have both versions of python installed but python3 detected by `/usr/bin/env python`.

**Comment by hansonw** [comment]
This will be fixed by https://github.com/facebook/nuclide/pull/716. Thanks @jesseschalken!
