### ISSUE TITLE
Implement file/folder copy/paste functionality [nuclide-file-tree]

### ISSUE THREAD

**Issue by aiboy** [facebook/nuclide#440]
Plz add this functionality.

It's really necessary when you miss click and have file created in a wrong project folder.

Opening Finder just to move file is real pain because i need to copy it and then not to forget to remove. 

PS: Will you accept pull request?

**Comment by ssorallen** [comment]
We certainly accept pull requests. New features in the file-tree have not been a priority, but I would gladly review pull requests and get them in.

**Comment by mikaoelitiana** [comment]
I am also needing this feature. This was availaible in Atom when nuclide wasn't installed yet.

**Comment by shushz** [comment]
FWIW, recently a move by drag&drop was implemented in Nuclide's file-tree.

**Comment by mikaoelitiana** [comment]
Oh ok that's great. Thanks

**Comment by derwaldgeist** [comment]
+1

For me, this was the main reason why I returned to standard Atom. A file tree without file management operations does not make any sense to me. I read somewhere that this was a deliberate decision and that one should use the operating system instead. But I think such a file tree is way more comfortable than Mac's Finder.

**Comment by ajhool** [comment]
Can't believe that this isn't a standard feature and that it actually downgrades from Atom's native functionality. Will look into solutions to implement this and make a PR.

**Comment by bassment** [comment]
+ 1 
Don't think I can start using nuclide without this functionality implemented ;(

**Comment by darklrd** [comment]
+1

**Comment by francesco-carrella** [comment]
=1

**Comment by b2whats** [comment]
+1

**Comment by derwaldgeist** [comment]
Just saw that this has been implemented in the most recent Nuclide version. Yippie! 🎉

**Comment by shushz** [comment]
Yep, by John (presumably @drmathochist).

**Comment by buschettu** [comment]
+1
