### ISSUE TITLE
Nuclide can't see public methods in classes

### ISSUE THREAD

**Issue by srcspider** [facebook/nuclide#443]
### Issue and Steps to Reproduce
Nuclide (or hack) is unable to differentiate between methods and functions if `public` is not mentioned. The `public` keyword is not mandatory. The `hh_client` appears to be smart enough to tell that its actually a method since it whines about wanting a useless "public" there (not sure how to turn that off) so its most likely an issue with nuclide itself.

You can tell nuclide sees it wrong via the `Outline View`

Example,

```php
<?php namespace test;

class Example {

  function method1() {
    // ...
  } 

  public function method2() {
    // ...
  }

} # class
```

### Expected Behavior
Nuclide should see a class with 2 public methods (`method1`, `method2`).

### Actual Behavior
Nuclide sees a class with 1 method (`method2`) and a function `\test\method1`.

### Versions
* Atom: 1.6.1
* Nuclide: latest
* Client OS: Ubuntu
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.16.0
├── language-ini@1.15.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── nuclide@0.127.0
├── sort-lines@0.14.0
└── tool-bar@0.4.0
```

**Comment by nmote** [comment]
What is the output of `hh_client --outline`?

**Comment by srcspider** [comment]
Perhaps I don't understand the question but running that simply appears to either start a server or takes forever to run.

```
For more detailed logs, try `tail -f $(hh_client --monitor-logname) $(hh_client --logname)`
Server launched with the following command:
	'/usr/bin/hh_server' '-d' '/home/srcspider/*****************' '--waiting-client' '5'
Spawned typechecker (child pid=7906)
Logs will go to /tmp/hh_server/*******************.x.monitor_log
```

**Comment by nmote** [comment]
Ah sorry, yeah you need to pipe in the file contents. I'll look into this.

**Comment by nmote** [comment]
@peterhal I think you addressed this, right?

**Comment by peterhal** [comment]
In Hack, class members require an access modifier, so the example code given is a syntax error.

When there's a syntax error the outline view is best effort only.
