### ISSUE TITLE
https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz not find

### ISSUE THREAD

**Issue by zyu** [facebook/nuclide#449]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:
* Nuclide:
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by matthewwithanm** [comment]
Hey @zyu! Could you please describe your issue for us?

**Comment by zyu** [comment]
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/atom-shell/v0.34.5/node-v0.34.5.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1584:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.34.5" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/zyf/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by zyu** [comment]
i have try it many times

**Comment by matthewwithanm** [comment]
Sorry, @zyu, I'm having trouble understanding your issue. Please bear with me!

Are you saying that you're unable to install Nuclide? I see a very old version of node in the error you showed. Is your Atom up to date?

Can you answer these questions for me?

* What are you trying to do?
* What were you doing when you got the error?
* What was the expected result?
* What actually happened?
* What versions of the following are you using?
    * Atom
    * Nuclide
    * Operating system (for example, "Mac OSX 10.10.5")

**Comment by zyu** [comment]
install the Nuclide
press the button of install
atom -v  1.6.2
Nuclide -v 0.128.0
node -v 5.4.1

**Comment by zyu** [comment]
mac -v 10.11.4

**Comment by zyu** [comment]
nstalling “nuclide@0.128.0” failed.Hide output…

**Comment by matthewwithanm** [comment]
Sorry, @zyu, this looks like an [apm] issue, not Nuclide.

[apm]: https://github.com/atom/apm
