### ISSUE TITLE
nuclide-file-tree: add "search in directory"

### ISSUE THREAD

**Issue by tsunammis** [facebook/nuclide#45]
I suggest an improvement on ```nuclide-file-tree```

The feature "search in directory" as the native atom file tree.

Best,

**Comment by torifat** [comment]
Can you please list a few features which are not high priority according to you. So that, we can contribute those from community. There are things like, bring all the shortcuts in `nuclide-file-tree`.

**Comment by tsunammis** [comment]
@torifat Ensure compatibility with existing modules, for example, I get some troubles with Color Piker, and I think there are another issues with probably the other modules.

Then, a shortcut to search only on a specific directory (current directory selected) ?

**Comment by bolinfest** [comment]
This has been fixed!
