### ISSUE TITLE
Feature request: enable nested dev environment

### ISSUE THREAD

**Issue by HuaisiXu** [facebook/nuclide#453]
### Issue and Steps to Reproduce
Enable development on a virtual machine inside a remote host.

i.e.  I have a virtual machine at 192.168.1.101 on remote host HOST, then I would like to be able to put "HOST:22:192.168.1.101" in the server box when adding a remote project folder.

and even ".......host1:22:host2:22:host3:22:remote_host", so only the tip of this list requires a Nuclide server.

**Comment by zertosh** [comment]
That's not really a use case we're aiming to support. Sorry.
