### ISSUE TITLE
Edit working set not working

### ISSUE THREAD

**Issue by Pszek** [facebook/nuclide#454]
### Issue and Steps to Reproduce
I want to append some directories into current working set, instead I got procedure for defining them from scratch.

### Expected Behavior
I can add/remove folders/files to existing working set.

### Actual Behavior
After selecting option to edit working set I get a tree without anything selected (despite I am already in working set). Working set is being defined from scratch .

### Versions
* Atom: 1.6.2
* Nuclide: 0.130
* Client OS: OSX El Capitan 10.11.4

### Additional Details
* Installed packages (`apm ls --installed`):
- atom-beautify@0.29.2
- atom-material-syntax@0.4.6
- atom-material-syntax-dark@0.2.5
- atom-material-syntax-light@0.4.5
- atom-material-ui@1.2.10
- autocomplete-emojis@2.3.0
- behave-theme@1.6.0
- file-icons@1.7.1
- highlight-line@0.11.1
- highlight-selected@0.11.2
- indent-guide-improved@1.4.5
- jumpy@3.0.3
- language-babel@2.17.1
- linter@1.11.4
- linter-htmlhint@1.1.1
- linter-scss-lint@2.5.1
- linter-stylelint@2.3.0
- linter-xo@0.14.0
- merge-conflicts@1.4.1
- minimap@4.21.0
- minimap-find-and-replace@4.5.1
- minimap-git-diff@4.2.0
- minimap-highlight-selected@4.4.0
- minimap-selection@4.4.0
- northem-light-atom-syntax@0.18.0
- nucleus-dark-ui@0.7.16
- nuclide@0.130.0
- pigments@0.26.0
- sort-lines@0.14.0
- svg-preview@0.7.4
- tool-bar@0.4.0

**Comment by zertosh** [comment]
cc: @shushz

**Comment by shushz** [comment]
@Pszek thanks for reporting! It's a bug introduced in a recent refactoring.
