### ISSUE TITLE
Phantom hg files

### ISSUE THREAD

**Issue by wyqydsyq** [facebook/nuclide#457]
### Issue and Steps to Reproduce
I have a few Mercurial projects which I've been using with Nuclide without issue until the latest update, after updating, Nuclide keeps spawning and deleting `hg-checkexec-XXXXXX` files in the root directory of my projects.

For each Atom instance I have open with a hg project, it seems to keep spawning hg processes:
![image](https://cloud.githubusercontent.com/assets/621277/14549185/e0d4f5d6-02fc-11e6-8dc8-d511d75eb1a6.png)

Here's an example of the files being created (they're deleted almost instantly after creation, but Nautilus continues to show them until a manual refresh):
![image](https://cloud.githubusercontent.com/assets/621277/14549245/5d0e712c-02fd-11e6-9c2c-9b465515db9b.png)

### Expected Behavior
Nuclide should not be spawning and deleting `hg-checkexecXXXX` files

### Actual Behavior
Nuclide keeps spawning and deleting `hg-checkexecXXXX` files

### Versions
* Atom: 1.7.0
* Nuclide: 0.130.0
* Client OS: OpenSUSE Tumbleweed x64
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── atom-html-preview@0.1.19
├── autocomplete-html-entities@0.1.0
├── autocomplete-paths@1.0.2
├── color-picker@2.1.1
├── docblockr@0.7.3
├── goto-definition@1.1.14
├── haskell-grammar@0.4.0
├── highlight-line@0.11.1
├── highlight-selected@0.11.2
├── language-babel@2.17.2
├── language-ejs@0.2.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── minimap@4.21.0
├── minimap-cursorline@0.1.0
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.2.0
├── node-debugger@1.4.7
├── nuclide@0.130.0
├── pigments@0.26.0
├── project-manager@2.9.7
├── project-view@0.5.0
├── regex-railroad-diagram@0.16.0
├── sort-lines@0.14.0
└── tool-bar@0.4.0
```

**Comment by Daniel15** [comment]
Potentially the same root cause as #480

**Comment by zertosh** [comment]
Seems like this was fixed. See https://github.com/facebook/nuclide/issues/480#issuecomment-215628186. Please open a new issue if it's still happening.
