### ISSUE TITLE
Nuclide fails to show inline Hack msg with Atom 1.7.1 and Nuclide 0.130

### ISSUE THREAD

**Issue by ericqianli** [facebook/nuclide#459]
### Issue and Steps to Reproduce
I'm using client Nuclide to connect to a remote server, where hhvm is installed.
Hack inline errors/warning were correctly showing before on Atom 1.6.2 Nuclide 129. Once I updated to Atom 1.7.1 and Nuclide 130 it stopped working.

**Latest Update: I revert Atom to 1.6.2 and everything works again. I suspect there's some incompatibility between Atom 1.7.1 and Nuclide 0.130.**

I can repro all time. I don't know how you would repro though. You have to connect to my server I think. If you really need to do that let's discuss in the followup.

To repro on my side:
1. Kill all node on server, quit Atom on client.
2. Restart Atom, remote connect to my server code folder.
3. hh from server terminal, Hack errors do show up.
4. Nuclide form client doesn't show any Hack. (Flow does show)
<img width="929" alt="screen shot 2016-04-16 at 1 12 11 am" src="https://cloud.githubusercontent.com/assets/4008685/14579916/5cf70456-0370-11e6-8167-e6b93f6ee257.png">

Update:
I switched to another client machine and Nuclide from that client did show the Hack errors. So I think it's a client side problem. The server is working fine.
The problematic client is running on Atom 1.7.1 Nuclide 130
This working client is running on Atom 1.6.2 Nuclide 130
I suspect Atom 1.7.1 has some mystery here :/
<img width="705" alt="screen shot 2016-04-16 at 1 23 33 am" src="https://cloud.githubusercontent.com/assets/4008685/14579950/f8ef8792-0371-11e6-9eff-b774caa78702.png">

### Expected Behavior
Hack errors/warnings should show

### Actual Behavior
Hack errors/warnings didn't show

### Versions
* Atom: 1.7.1
* Nuclide: 0.130.0
* Client OS: OX X 10.11.4
* Server OS (optional): OX X 10.10.4

### Additional Details
* Installed packages (`apm ls --installed`):
├── ex-mode@0.8.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.17.2
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── nuclide@0.130.0
├── sort-lines@0.14.0
├── tool-bar@0.4.0
└── vim-mode@0.65.0

**Comment by zertosh** [comment]
cc: @peterhal

**Comment by ChrisReeves12** [comment]
I having problems with this as well.

**Comment by peterhal** [comment]
This was a transient incompatibility between hack and Nuclide. Let me know if you still experience issues.
