### ISSUE TITLE
Content Security Policy error in devtools (HackWorker.js). 

### ISSUE THREAD

**Issue by Vahanerevan** [facebook/nuclide#465]
Hi All.

Atom Version 1.7.2
OS X El Capitan 10.11.2.
clean Atom(no packages only nuclide).
I even reinstalled atom few times.

Nuclide was not working and I opened devtools and notices that error console is full of this messages.

Refused to create a child context containing 'blob:file%3A///c0c20fb8-492e-46ff-8dcf-36f635ceb5b7' because it violates the following Content Security Policy directive: "default-src *". Note that 'child-src' was not explicitly set, so 'default-src' is used as a fallback.
startWebWorker @ HackWorker.js:168HackWorker @ HackWorker.js:60LocalHackLanguage @ LocalHackLanguage.js:77createHackLanguage @ HackLanguage.js:128(anonymous function) @ HackLanguage.js:166step @ HackLanguage.js:175

Thank You.

**Comment by johnislarry** [comment]
Please include steps on how to reproduce this issue, what version of atom you're running, what version of Nuclide you're running, what packages you have installed, and any other information you think can help debug this.

**Comment by johnislarry** [comment]
When you created a new issue there was a template for how to report your problem.  Please use that template.

**Comment by Vahanerevan** [comment]
Sorry just pasted the text. was little sleepy.
Atom Version 1.7.2
OS X El Capitan 10.11.2.
clean Atom(no packages only nuclide).
I even reinstalled atom few times. 

Nuclide was  not working and I opened devtools and notices that I have full error console with this messages.

**Comment by zertosh** [comment]
I believe the @peterhal got rid of this. @Vahanerevan can you try nuclide@0.131.0?

**Comment by Vahanerevan** [comment]
Yes it's fine. Thank you.
Only now I got error when try to format the code.
Nuclide Format Code 

Uncaught (in promise) Error: hh_client error, args: [--format,1,1941](…)(anonymous function) @ HackHelpers.js:93step @ HackHelpers.js:161

[2016-04-20T21:15:29.019Z] [ERROR] nuclide - hh_client error, args: [--format,1,1941]
stdout: , stderr: /usr/local/bin/hh_client: unknown option '--format'.
Usage: /usr/local/bin/hh_client [COMMAND] [OPTION]... [WWW-ROOT]

Valid values for COMMAND:
	check		Shows current Hack errors
	start		Starts a Hack server
	stop		Stops a Hack server
	restart		Restarts a Hack server

Default values if unspecified:
	COMMAND		check
	WWW-ROOT	Current directory

Check command options:

  --status                 (mode) show a human readable list of errors (default)
  --type-at-pos            (mode) show type at a given position in file [line:character]
  --list-files             (mode) list files with errors
  --list-modes             (mode) list all files with their associated hack modes
  --auto-complete          (mode) auto-completes the text on stdin
  --colour                 
  --color                  (mode) pretty prints the file content showing what is checked (give '-' for stdin)
  --coverage               (mode) calculates the extent of typing of a given file or directory
  --find-refs              (mode) finds references of the provided method name
  --find-class-refs        (mode) finds references of the provided class name
  --identify-function      (mode) print the full function name at the position [line:character] of the text on stdin
  --search                 (mode) fuzzy search symbol definitions
  --search-class           (mode) fuzzy search class definitions
  --search-function        (mode) fuzzy search function definitions
  --search-typedef         (mode) fuzzy search typedef definitions
  --search-constant        (mode) fuzzy search constant definitions
  --outline                (mode) prints an outline of the text on stdin
  --inheritance-children   (mode) prints a list of all related classes or methods to the given class
  --inheritance-ancestors  (mode) prints a list of all related classes or methods to the given class
  --show                   (mode) show human-readable type info for the given name; output is not meant for machine parsing
  --lint                   (mode) lint the given list of files
  --lint-all               (mode) find all occurrences of lint with the given error code
  --version                (mode) show version and exit

  --logname                (mode) show log filename and exit

  --stats                  display some server statistics
  --json                   output json for machine consumption. (default: false)
  --retries                set the number of retries. (default: 800)
  --retry-if-init          retry if the server is initializing (default: true)
  --no-load                start from a fresh state
  --from                   set this so we know who is calling hh_client
  --timeout                set the timeout in seconds (default: no timeout)
  --autostart-server       automatically start hh_server if it's not running (default: true)

  --from-vim               (deprecated) equivalent to --from vim --retries 0 --retry-if-init false
  --from-emacs             (deprecated) equivalent to --from emacs
  --from-arc-diff          (deprecated) equivalent to --from arc_diff
  --from-arc-land          (deprecated) equivalent to --from arc_land
  --from-check-trunk       (deprecated) equivalent to --from check_trunk
  -help                    Display this list of options
  --help                   Display this list of options





Do I need to create other issue  for this error?

**Comment by Vahanerevan** [comment]
Any news or suggestions ?
Thank you .

**Comment by ChrisReeves12** [comment]
I'm getting this error as well. When running Atom/Nuclide in --dev mode, anytime I save the document, hover over some of my code, I keep getting these errors in the console:

```
HackWorker.js:154
Refused to create a child context containing 'blob:file%3A///6916c757-b823-4153-b984-55c8db804f55' because it violates the following Content Security Policy directive: "default-src *". Note that 'child-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by kilahm** [comment]
Running Nuclide 0.132.0, HHVM 3.12.1, OS X 10.10.5, I get the same error as @Vahanerevan about `--format` not being a valid option for `hh_client` when attempting to format my Hack code.

**Comment by ChrisReeves12** [comment]
Yes, upgraded to 3.132.0 and now I'm getting the same error as @Vahanerevan

**Comment by Vahanerevan** [comment]
Any new about format?

**Comment by peterhal** [comment]
This looks like your version of hack(aka hh_client) is outdated. Upgrading to the latest version of hack should take care of this.

**Comment by kilahm** [comment]
@peterhal It's interesting you say that because the most recent release [3.13.1](https://github.com/facebook/hhvm/commits/HHVM-3.13.1) does not include the commit that added the `--format` flag to `hh_client` (see https://github.com/facebook/hhvm/commit/53f1c4930468d4c80fe830ff59f2b63c4e73ba47).

I am currently running hhvm 3.13.1 on OSX 10.10.5, using the homebrew package.

```
$hhvm --version
HipHop VM 3.13.1 (rel)
Compiler: 1461888037_N
Repo schema: eb8835d623ac6f0b7fa8e384aed3fb6a152df724
```

```
$hh_client --version
 Apr 28 2016 16:38:50
```

Are you suggesting to use the current version of Nuclide that we must compile the master branch HEAD?

**Comment by Vahanerevan** [comment]
Seems it's not included for 

hh_format does the job. 
hh_format -i filename.
I just created a plugin that calls this with active file.

**Comment by peterhal** [comment]
This is long stale.
