### ISSUE TITLE
Fix debugger header

### ISSUE THREAD

**Issue by Mokto** [facebook/nuclide#466]
### Issue and Steps to Reproduce

Load debugger
### Expected Behavior

The console header should be fixed in debugged as it is in Chrome
### Actual Behavior

![capture d ecran 2016-04-21 a 14 31 52](https://cloud.githubusercontent.com/assets/5103928/14708849/c47f9744-07cd-11e6-939f-c1adebe34542.png)
![capture d ecran 2016-04-21 a 14 31 46](https://cloud.githubusercontent.com/assets/5103928/14708850/c48044c8-07cd-11e6-86ae-1f123fead899.png)
### Versions
- Atom: 1.7.2
- Nuclide: 0.131.0
- Client OS: MAC OS
- Server OS (optional):

Thanks ;)

**Comment by johnislarry** [comment]
Can you elaborate on what you mean by "Console Header", and "fixed in debugged".  I don't understand what the expected behavior should be.

**Comment by Mokto** [comment]
Yes sorry for not being understandable.

I often like to clear my chrome console. When you scroll down in your logs the header scrolls too. And you cannot click on ![capture d ecran 2016-04-21 a 19 21 38](https://cloud.githubusercontent.com/assets/5103928/14718315/42d8d81c-07f6-11e6-8503-df2af41383c6.png) anymore.

**Comment by johnislarry** [comment]
Ah I see.  The workaround is to use the "Console" tab up at the top of the devtools.  We have a lot of debugger UI work planned for the next few months so stay tuned.

**Comment by johnislarry** [comment]
The Chrome Devtools UI has been deprecated in favor of the new debugger UI, and in the new UI the Nuclide console's prompt has the behavior you want, i.e. the 'clear' button's position doesn't change
