### ISSUE TITLE
With react-native debugger, my app is a lot slower

### ISSUE THREAD

**Issue by Mokto** [facebook/nuclide#467]
### Issue and Steps to Reproduce

Load debugger with react-native
### Actual Behavior

My app is a lot more slow with the debugger
### Versions
- Atom: 1.7.2
- Nuclide: 0.131.0
- Client OS: MAC OS
### Additional Details
- I do not know if this is the case for everyone, but my app is a lot slower with built-in atom debugger than chrome classic debugger

**Comment by diogoviannaaraujo** [comment]
Yeah, on Android the speed difference is smaller but in iOS using Chrome is a huge speed improv
