### ISSUE TITLE
react native fb8 app demo  Error connecting to debugger UI.

### ISSUE THREAD

**Issue by ganvinalix** [facebook/nuclide#468]
fb8 node packager server use 8081,but when i run Nuclide react Native: start  debugging. atom show "Error connecting to debugger UI. make sure that port 8080 is open"!  is there some place  to set nuclide port value?

**Comment by matthewwithanm** [comment]
Hey @ganvinalix! The debugger and packager are supposed to used different ports; you don't want the debugger to use 8081. 

In the current release, 8080 is hardcoded for the debugger. 08d9363c364f4ef4ab449dceb322651186c81962 (which'll be in next week's release) changes this to a less common port. In the meantime, you'll need 8080 open for the debugger. You can see what's currently using it by running `lsof -i :8080`.

**Comment by ganvinalix** [comment]
thx , I got it.

**Comment by matthewwithanm** [comment]
Awesome. I'm gonna close this then 😊
