### ISSUE TITLE
Hyperclick 0.0.36 error : nuclide-analytics dependency 

### ISSUE THREAD

**Issue by yomybaby** [facebook/nuclide#470]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
Try to hyperclick (cmd+alt+enter or cmd+click)

### Expected Behavior
Tell us what should happen.
Underline appear. Do something (eg. go to definition)

### Actual Behavior
Tell us what happens instead.
Error alert: can't not found `hyperclick/node_modules/nuclide-analytics/lib/min.js`

### How to solve this issue
Add nuclide-analytics dependency  to https://github.com/facebooknuclideapm/hyperclick/blob/master/package.json

```
...
  "dependencies": {
    "nuclide-analytics": "0.0.35",
    "react-for-atom": "15.0.1-0"
  },
...
```

### Versions
* Atom: 1.7.2
* Nuclide: without Nuclide (only use Hyperclick)
* Client OS: OSX 10.11.4
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
≫ apm ls --installed
Community Packages (31) /Users/yomybaby/.atom/packages
├── Stylus@3.0.0
├── ascii-art@1.0.1
├── atom-beautify@0.29.7
├── atom-hot-package-loader@0.5.1
├── atom-save-all@0.4.1
├── atom-ternjs@0.14.1
├── autocomplete-paths@1.0.2
├── dash@1.6.0
├── docblockr@0.7.3
├── expand-region@0.2.4
├── highlight-line@0.11.1
├── highlight-selected@0.11.2
├── hyperclick@0.0.36
├── imdone-atom@1.3.29
├── js-hyperclick@1.4.2
├── language-ejs@0.2.0
├── language-gitignore@0.2.0
├── language-jade@0.7.1
├── last-cursor-position@0.9.0
├── linter@1.11.4
├── linter-jshint@2.1.0
├── marked@0.1.10
├── merge-conflicts@1.4.1
├── nuclide-move-pane@0.0.35
├── open-in-sourcetree@0.1.8
├── pigments@0.26.0
├── regex-railroad-diagram@0.16.0
├── tab-switcher@1.4.0
├── terminal-plus@0.14.5
├── ti-create@0.26.0
└── titanium-alloy@0.9.11

└── (empty)
```

**Comment by zertosh** [comment]
This is an issue with how Atom handles updates. If you restart Atom, it'll work again.

**Comment by yomybaby** [comment]
Ok! Thanks for let me know.
