### ISSUE TITLE
Failed to get targets from Buck

### ISSUE THREAD

**Issue by FlyingSeven** [facebook/nuclide#471]
### Issue and Steps to Reproduce
When i want to run the react native (iOS ) use the Buck , i do as the api says ,but it notice me that "Invalid .buckconfig", i am new to Buck .
### Expected Behaviour
Atom run my project.

### Actual Behavior
Failed to get targets from Buck.

### Versions
* Atom: 1.7.2
* Nuclide: newest
* Client OS: 10.11.1
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by johnislarry** [comment]
Where is your .buckconfig file and what are its contents?

**Comment by FlyingSeven** [comment]
Thanks for your reply, i just screen shot the directory and the content in the .buckconfig.
<img width="245" alt="screen shot 2016-04-26 at 2 19 25 pm" src="https://cloud.githubusercontent.com/assets/8542550/14808683/03ff6a4e-0bba-11e6-9ce6-70f7a9e3891f.png">
<img width="442" alt="screen shot 2016-04-26 at 2 19 35 pm" src="https://cloud.githubusercontent.com/assets/8542550/14808686/06bceea0-0bba-11e6-9777-360fec41866e.png">

**Comment by ricardopereira** [comment]
I'm having the same issue. Exactly the same setup.
What's the status on this?

**Comment by ricardopereira** [comment]
@FlyingSeven I think it's missing the `BUCK` file on `ios`. And you need to install `buck`: https://buckbuild.com/setup/install.html

**Comment by johnislarry** [comment]
Assigning Matthew for any Buck insight he might have.  What's the status on this @FlyingSeven?

**Comment by matthewwithanm** [comment]
Hey all! Can you try running buck from the command line and let us know what the output is?

**Comment by DominicTobias** [comment]
This is what I get in an untouched react-native app:

![screen shot 2016-05-27 at 17 26 54](https://cloud.githubusercontent.com/assets/760314/15614375/5b3397a2-2430-11e6-947a-f71ee91d6fad.png)
