### ISSUE TITLE
Failed afte connect to server

### ISSUE THREAD

**Issue by vladknp** [facebook/nuclide#473]
### Issue and Steps to Reproduce
Open config remote connect. Enter config data. After press button 'connect'.

### Actual Behavior
Success connect and show message:
You just connected to a remote project /home/ksmartme/pj/smartme/smartme but we recommend you remove this directory now because crucial features like synced remote file editing, file search, and Mercurial-related updates will not work.
Watchman Error:Remote Error: The client was ended processing message {"protocol":"service_framework3_rpc","type":"FunctionCall","function":"FileWatcherService/watchDirectoryRecursive","requestId":4,"args":["/home/ksmartme/pj/smartme/smartme"]}

### Versions
* Atom:1.7.2
* Nuclide:0.132.0
* Client OS:linuxMint 17.3
* Server OS (optional):linuxMint 17.3

### Additional Details
* Installed packages (`apm ls --installed`):
Community Packages (9) /home/my_user/.atom/packages
├── Remote-FTP@0.7.20
├── language-babel@2.18.1
├── language-jade@0.7.1
├── linter@1.11.4
├── linter-jshint@2.1.0
├── node-debugger@1.4.7
├── nuclide@0.132.0
├── pigments@0.26.0
└── react@0.15.0

└── (empty)

**Comment by hansonw** [comment]
This might've been safe to ignore. Were you able to do things remotely as usual after the error appeared?

**Comment by vladknp** [comment]
In the beginning, any changes are not causing the error persisted.
Updated Atom and npm on the server and the client.
Now you can work. Save files.
But at a connection to the server is still a warning appears:

> You just connected to a remote project /home/ksmartme/pj/smartme/smartme but we recommend you remove this directory now because crucial features like synced remote file editing, file search, and Mercurial-related updates will not work.
Watchman Error:Remote Error: The client was ended processing message {"protocol":"service_framework3_rpc","type":"FunctionCall","function":"FileWatcherService/watchDirectoryRecursive","requestId":4,"args":["/home/ksmartme/pj/smartme/smartme"]}

**Comment by hansonw** [comment]
Ah, okay. You can just close and ignore the message (although as mentioned, Nuclide may not be able to automatically update when you manually change files via the command line - e.g. via git commands, or using another editor).

You can also try installing Watchman to get full functionality and stop the warning. (instructions are here: https://facebook.github.io/watchman/docs/install.html)

**Comment by vladknp** [comment]
I use linuxMint 17.3. In the documents "Linux systems with inotify"
I installed the Watchman:
npm i -g watchman

 But message not hidden. Maybe systems not supported

**Comment by vladknp** [comment]
Ok. Thanks

**Comment by szach** [comment]
@hansonw - i'm also observing the same error despite installing watchman - thoughts?

**Comment by canselcik** [comment]
@szach I've been having the issue ever since I've started using Nuclide. Interestingly enough when I install and use `watchman` on the same host that I run `nuclide-start-server` on, it runs perfectly fine and prints a message when a change occurs on a file it's watching.
