### ISSUE TITLE
Unable to ignore files in nuclide-diagnostics

### ISSUE THREAD

**Issue by Aweary** [facebook/nuclide#478]
### Issue and Steps to Reproduce
No setting to ignore files/folders for `nuclide-diagnostics`

### Expected Behavior
Users should be able to specify globs for ignored file paths

### Actual Behavior
Users cannot

### Versions
* Atom: 1.7.2
* Nuclide: 0.134.0
* Client OS: OS X 10.11.1 (15B42)
* Server OS (optional):

### Additional Details
I'm not sure if this is a missing feature or a lack of documentation, but I can't find out how to do this and I'm getting way too many flow errors from my `node_modules` folder

**Comment by ssorallen** [comment]
For your additional details, having Flow errors in your 'node_modules' folder is a problem Nuclide itself has. We, however, now rely on a passing `flow` check for new internal commits and have made that possible by ignoring certain folders in [Nuclide's '.flowconfig'](https://github.com/facebook/nuclide/blob/affb470f86b60f907822627a86ab6dd6a05aba33/.flowconfig#L7-L11):

```
# annotated with `@flow` but have errors
.*/node_modules/babel-types/.*
.*/node_modules/fbjs/lib/.*
.*/node_modules/sabor/.*
.*/nuclide-node-transpiler/spec/fixtures/.*
```

I suggest ignoring failing folders so the output of Flow is always high signal.

**Comment by Aweary** [comment]
Thanks, I'll give that a try. Do you think nuclide's `.flowconfig` options should be exposed in the Atom package settings pane? That may be useful so people don't have to edit config files directly.

**Comment by ssorallen** [comment]
@Aweary Are you working from Nuclide source?

**Comment by nmote** [comment]
No, it shouldn't be exposed. Nuclide's `.flowconfig` is for the source code of Nuclide itself. It's not a `.flowconfig` that we apply to projects that end-users are working on. @ssorallen was just explaining that we have this same problem working on the Nuclide source, and explained what we have done to deal with it.

The Flow team has some plans to alleviate the `node_modules` problems. I'm not sure if there's an open issue but I do know they are working on this problem. Right now the setup is finicky, but @ssorallen is correct that the best solution is to edit your `.flowconfig`.

Ultimately this is an issue with Flow and not with Nuclide. Flow should only be reporting errors relevant to you and ignoring them from within Nuclide is only a bandaid.

**Comment by Aweary** [comment]
@nmote got it, I assumed @ssorallen meant that the nuclide package had an internal `.flowconfig` file used to run the flow type checks in Atom. I'm not using flow, but it seems we had an empty `.flowconfig` file in the repo from a previous implementation attempt. Removing it stopped the errors, so I assume flow is not run if no `.flowconfig` is found?

**Comment by nmote** [comment]
Right. Nuclide won't run Flow if there is no `.flowconfig`. Flow itself also won't run even if you try to start it from the command line.

**Comment by ssorallen** [comment]
Aha, glad you figured it out.

My comment about looking at Nuclide source came from the fact that this GitHub repo does not pass a Flow. There are 11 Flow errors due to our funny way of try/catching to see if internal modules exist. Separate issue though.

**Comment by Aweary** [comment]
@nmote so I noticed that even without a `.flowconfig` present in the working directory, nuclide is starting the flow server and its taking up quite a bit of resources.

<img width="960" alt="screen shot 2016-04-28 at 1 44 50 pm" src="https://cloud.githubusercontent.com/assets/6886061/14897397/7e13209e-0d47-11e6-8dde-8e4d9aad0b99.png">

**Comment by ssorallen** [comment]
@Aweary Is there a .flowconfig in any ancestor directory? Also, try running `killall flow` to make sure they aren't lingering Flow servers from when you had the .flowconfig file.

**Comment by Aweary** [comment]
@ssorallen there are no `.flowconfig` files in any ancestor directory (verified with `ag --hidden -g flowconfig`). Even after `killall flow` the flow server starts up again if I have nuclide enabled.

**Comment by nmote** [comment]
I can't repro. I made a directory with just a JS file and no `.flowconfig` and Flow does not start, and no Flow-related features are available (as expected). I also added a `.flowconfig`, observed that Nuclide started a Flow server, removed the `.flowconfig`, killed the Flow server, and verified that Nuclide did not start it back up again. I'm on master but this code really hasn't changed much at all recently.

Can you share the output of `ps -eaf | grep flow`?

**Comment by nmote** [comment]
Note that Nuclide does cache the locations of `.flowconfig` files for 30 seconds so after removing the `.flowconfig` so I would expect Nuclide to try to start Flow for 30 seconds after you remove it, at most.

This is also puzzling because Flow itself refuses to start if it can't find a `.flowconfig`. I just tried running `flow server` and it just complained that there was no `.flowconfig` file.

**Comment by Aweary** [comment]
IIt's definitely been more than 30 seconds. It seems to startup about 30-40 seconds after I start Atom.

`ps -eaf | grep flow` outputs:

```js
 1054 16499 16421   0  2:52PM ??         0:00.33 node /usr/local/bin/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16501 16499   0  2:52PM ??         0:03.26 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16512 16501   0  2:52PM ??         0:00.01 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16513 16501   0  2:52PM ??         0:00.01 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16514 16501   0  2:52PM ??         0:00.01 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16515 16501   0  2:52PM ??         0:00.01 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16516 16501   0  2:52PM ??         0:00.01 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16517 16501   0  2:52PM ??         0:00.00 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16518 16501   0  2:52PM ??         0:00.01 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16519 16501   0  2:52PM ??         0:17.62 /usr/local/lib/node_modules/flow-bin/vendor/flow
 1054 16564 16517   0  2:52PM ??         0:11.63 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16580 16514   0  2:52PM ??         0:09.13 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16582 16515   0  2:52PM ??         0:08.88 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16594 16516   0  2:52PM ??         0:05.92 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16633 16512   0  2:52PM ??         0:02.71 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16639 16513   0  2:53PM ??         0:01.57 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16646 16421   0  2:53PM ??         0:00.76 node /usr/local/bin/flow status --json /Users/brandon.dail/Development/frontend/js/app.js --retry-if-init false --retries 0 --no-auto-start --from nuclide
 1054 16647 16518   0  2:53PM ??         0:00.07 /usr/local/lib/node_modules/flow-bin/vendor/flow server --from nuclide --max-workers 7 /Users/brandon.dail
 1054 16649  1551   0  2:53PM ttys000    0:00.01 grep flow
```

**Comment by nmote** [comment]
And you're absolutely sure that `/Users/brandon.dail/.flowconfig` does not exist?

**Comment by Aweary** [comment]
Well, look at that, it does seem there is a `.flowconfig` file in the user folder apparently. I guess I should remove that. Removing it has fixed the issue for me. Does flow always check the user folder as well? It doesn't seem to say so in the docs.

**Comment by nmote** [comment]
It just looks upward in the directory tree from the current file until it finds a `.flowconfig`. It does not treat any folder specially, including the user folder.
