### ISSUE TITLE
Git status in Tree View is out-of-date

### ISSUE THREAD

**Issue by jsg2021** [facebook/nuclide#479]
### Issue and Steps to Reproduce
Open a Git project. Edit a file or two. Notice the status change in the tree view... commit using cli, or git-plus atom package, or any external tool.  Come back to atom, look at the tree view... still shows file status. .. type in another file. Status syncs up.

### Expected Behavior
Git status should update on when atom is refocused, or when Git repo is interacted with.

### Actual Behavior
Git status is stale in tree view.

### Versions
* Atom: 1.7.3
* Nuclide: 0.134.0
* Client OS: Mac OS X 10.11.4

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── autocomplete-emojis@2.3.0
├── autocomplete-modules@1.4.1
├── blame@0.10.0
├── color-picker@2.1.1
├── docblockr@0.7.3
├── editorconfig@1.4.1
├── file-icons@1.7.8
├── git-history@3.2.0
├── git-plus@5.13.4
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.18.2
├── language-gitignore@0.2.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.4
├── linter-eslint@7.2.1
├── merge-conflicts@1.4.2
├── nuclide@0.134.0
├── project-quick-open@0.5.0
├── sort-lines@0.14.0
├── split-diff@0.7.5
├── todo-show@1.5.0
├── toggle-quotes@1.0.0
└── tool-bar@0.4.0
```

**Comment by jsg2021** [comment]
Atom's own tree-view is always in sync.

**Comment by mostafaeweda** [comment]
I can't reproduce this neither on `Atom 1.6.2` not on `Atom 1.7.3` -- it seems to pick the changes and update correctly here. any indicators on when this happen? errors in the dev tools console?

**Comment by jsg2021** [comment]
I didn't have watchman installed... doh.

**Comment by jsg2021** [comment]
Nope... the updates are still out of sync sometimes. It's improved now, but still behind.
![example](https://cloud.githubusercontent.com/assets/577453/14923805/ff115400-0e04-11e6-98ca-cbd3e3d36a28.gif)
