### ISSUE TITLE
Errors in Diagnostics Table isn't updated correctly when closed

### ISSUE THREAD

**Issue by aifreedom** [facebook/nuclide#487]
### Issue and Steps to Reproduce
The errors in Diagnostics table isn't up-to-date: It's different from what's shown in the bottom left corner. But it's updated with a toggle on "Show only diagnostics for current file" or a resize of the window.

I'm not constantly getting this. To repro:
1. set up `.arclint` and make sure it works.
2. keep the diagnostics table closed and make an error in code, see the error count in status bar right.
3. toggle diagnostics window with `alt-shift-D`, see nothing in the window.

![image](https://cloud.githubusercontent.com/assets/70373/15090766/498156d2-13e8-11e6-88ef-537a8bccc719.png)

### Expected Behavior
What's shown in diagnostics table is always in sync with the error counts in the status bar.

### Actual Behavior
They differ. The status bar is correct but the content in diagnostics table isn't.

### Versions
* Atom: 1.7.3
* Nuclide: 0.135.0
* Client OS: Mac OS X 10.10.5
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (28) /Users/song_xie/.atom/packages
├── advanced-open-file@0.16.2
├── atom-fuzzy-grep@0.13.0
├── center-line@1.2.4
├── clipboard-plus@0.5.1
├── eclectic-syntax@0.2.1
├── environment@1.2.0
├── file-icons@1.7.10
├── git-plus@5.13.4
├── hard-wrap@1.0.1
├── highlight-selected@0.11.2
├── incremental-search@5.0.5
├── language-babel@2.19.4
├── merge-conflicts@1.4.2
├── minimap@4.23.5
├── minimap-find-and-replace@4.5.1
├── minimap-highlight-selected@4.4.0
├── multi-wrap-guide@0.23.5
├── nuclide@0.135.0
├── pane-layout-plus@0.7.3
├── pane-move-plus@0.3.1
├── pigments@0.26.2
├── project-manager@2.9.7
├── react@0.15.0
├── react-es6-snippets@0.3.0
├── run-command@0.3.2
├── sort-lines@0.14.0
├── tab-switcher@1.4.0
└── todo-show@1.6.0

└── (empty)
```
* This not only repros with `arc lint`, it also happens to `linter-eslint`. Actually, it first happened to me on `linter-eslint`. I suspected it was a compatibility issue between `linter-eslint` and `nuclide` first. But after setting up `arc lint`, everything was the same.

**Comment by nmote** [comment]
Yes, this is a problem with Nuclide diagnostics and not a compatibility issue with any other package. As a workaround you can check and then uncheck the "show only diagnostics for the current file" box which will force a refresh. I believe also that if you continue working, updates to the table will appear as expected.
