### ISSUE TITLE
Nuclide file-tree unable to re-enable

### ISSUE THREAD

**Issue by boopathi** [facebook/nuclide#49]
I disabled nudlide-file-tree to use tree-view, and then tried to switch back to nuclide-file-tree, but it doesn't get re-enabled.

**Comment by oclbdk** [comment]
Fixed with https://github.com/facebook/nuclide/commit/0942e4d0022644a6280565b9a5c5b75c5ac0dcc3

**Comment by willopez** [comment]
I still se the issue, even with the latest nuclide version...

**Comment by ssorallen** [comment]
The supported way to re-enable Atom's file-tree is to disable the nuclide-file-tree package. The nuclide-file-tree-deux package will be the supported version shortly.
