### ISSUE TITLE
Keybindings for navigating omnisearch result groups are broken or not intuitive

### ISSUE THREAD

**Issue by glortho** [facebook/nuclide#492]
### Issue and Steps to Reproduce
Invoke omnisearch and type something that will have results in multiple categories - tags, filenames, and recent files, for example.

### Expected Behavior
When in the last item of a group, I would expect the down arrow to take me to the first item in the next group. Same thing when arrowing up.

### Actual Behavior
When you hit the down arrow on the last item in a group, it returns you to the first item in that group. That's fine, though I would prefer it to take me to the first item in the next group. It gets wacky from there, though, because if you hit the up arrow on the first item in that group, it will take you to the *last* item of the *next* group. If you hit the down arrow on the last item in a group, it will take you to the *first* item of the *previous* group, if there is one.

### Versions
* Atom: 1.7.3
* Nuclide: 0.135.0
* Client OS: Mac OS 10.10.5

### Additional Details
* I'm assuming this is a bug, but fwiw I vote for down arrow and up arrow taking you across group boundaries, with cmd/ctrl/meta + up/down arrow jumping between groups.

**Comment by jgebhardt** [comment]
Thanks for reporting – this has been fixed in 995e17b554cf64e6709f8134b70574b89e112028.
