### ISSUE TITLE
 Cannot find module ... nuclide-debugger-node ...

### ISSUE THREAD

**Issue by pkwraphael** [facebook/nuclide#495]
### Issue and Steps to Reproduce

I can not speak English. excuse

Nuclide Debugger not working with error message.

http://nuclide.io/docs/platforms/react-native/#start-debugging

Come out this part during the execution.

Error: Cannot find module '/Users/pkw/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node_modules/v8-debug/build/debug/v0.7.0/node-v48-darwin-x64/debug.node'

Error: Cannot find module '/Users/pkw/.atom/packages/nuclide/pkg/nuclide-debugger-node/VendorLib/node_modules/v8-profiler/build/profiler/v5.5.0/node-v48-darwin-x64/profiler.node'

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom:1.7.3
* Nuclide:0.135.0
* Client OS:OS X El Capitan v10.11.4
* Server OS (optional):

* XCode version 7.3.1(7D1014)

### Additional Details
* Installed packages (`apm ls --installed`):

Community Packages (12) /Users/pkw/.atom/packages
build@0.62.0
haskell-grammar@0.4.0
highlight-selected@0.11.2
language-babel@2.20.8
language-ini@1.16.0
language-ocaml@1.1.2
language-thrift@1.0.2
last-cursor-position@0.9.0
minimap@4.23.5
nuclide@0.135.0
sort-lines@0.14.0
tool-bar@0.4.0

**Comment by johnhforrest** [comment]
I'm also seeing this on nuclide 0.136.0 when trying to debug a react native project

**Comment by zertosh** [comment]
We haven't added debug binaries for Node v6 yet. Maybe in next weeks release. If you start your React Native project with Node v4 or v5, it'll work.

**Comment by RinatMullayanov** [comment]
@zertosh I have same problem. 
OS: OS X El Capitan 10.11.5
Atom: 1.7.4
Node: v6.2.0
Nuclide: 0.139.0

**Comment by zertosh** [comment]
@RinatMullayanov, I'm aware of the problem, I suggest you try Node v4 or v5.

@matthewwithanm, we need to add v8-debug and v8-profiler for node 6. I took a quick look at this last week and it's not as simple as adding the bins. There are (minor) changes to the v8-debug binary that mean we also have to update the v8-debug js, and node-inspector. I'll take a look again today, but I don't know if you're actively touching the node-inspector/v8-debug/v8-profiler code.
