### ISSUE TITLE
Can't connect to a remote workspace with IPv6 IPs

### ISSUE THREAD

**Issue by jaredallard** [facebook/nuclide#502]
### Issue and Steps to Reproduce
1. Use an IPv6 IP as the addr.
2. ...
3. Reproduced.

### Expected Behavior
Should connect.

### Actual Behavior
![d17-05-16_t20-49-35](https://cloud.githubusercontent.com/assets/2391349/15346964/c2f7b4de-1c71-11e6-95a4-52cbab2d5dae.png)

That's all I know.

### Versions
* Atom: 1.7.3
* Nuclide: 0.138.0
* Client OS: Arch Linux
* Server OS (optional): Debian

### Additional Details
* Installed packages (`apm ls --installed`):

```bash
Community Packages (16) /home/vin/.atom/packages
├── git-plus@5.13.4
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── hydra-syntax-theme@1.3.0
├── language-babel@2.20.10
├── language-docker@1.1.6
├── language-ini@1.16.0
├── language-lua@0.9.4
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.4 (disabled)
├── linter-eslint@7.2.2
├── minimap@4.23.5
├── nuclide@0.138.0
├── sort-lines@0.14.0
└── tool-bar@0.4.0

└── (empty)
```

**Comment by shushz** [comment]
Yep, doesn't work. Thanks for reporting!

**Comment by shushz** [comment]
After a rather lengthy investigation it seems that it'll be too hard to support a secure connection to an IPv6 address (rather then a hostname), but the connection with an `-k` or a `--insecure` flag do work.

I don't think we can justify further investment in this use case at this time, so I'm closing this.
