### ISSUE TITLE
Server version is different than client version

### ISSUE THREAD

**Issue by jeanmichelcote** [facebook/nuclide#506]
### Expected Behavior
Use Atom-nuclide "remote connection" to work on a remote server to which I have the credentials.

### Actual Behavior
Followed the steps for installation at nuclide.io.
Everything went well.

Did the same for my server.

1. Open atom
2. go to "remote connection"
3. enter credentials with "remote server command" = nuclide-start-server
4. spat "Server version is different than client version" error.

### Versions
* Atom: **1.7.3**
* Nuclide: **138**
* Client OS: **OSX 10.11.5**
* Server OS (optional): **Linux UBU 3.19.0-59-generic #66~14.04.1-Ubuntu SMP Fri May 13 17:27:22 UTC 2016 i686 i686 i686 GNU/Linux**

### Additional Details
* Installed packages (`apm ls --installed`):  
└── nuclide@0.138.0                                                             
└── (empty)

**Comment by shushz** [comment]
What does the details section, the one below "Server version is different than client version" say?
Sometimes this error is caused by network issues and the details section should contain the original error code.

**Comment by shushz** [comment]
Confirmed as a network issue here: https://github.com/facebook/nuclide/issues/374#issuecomment-220489843
