### ISSUE TITLE
Unable to locate file with quick open

### ISSUE THREAD

**Issue by steblar** [facebook/nuclide#507]
Using Quick Open feature i expect to found 2 files ( index.php and index.php~) but search result show "no results".

![schermata 2016-05-20 alle 09 21 03](https://cloud.githubusercontent.com/assets/1799457/15420310/3379ae0a-1e6c-11e6-8dd0-1e514a11ac7d.png)

But on server ( i'm using remote-projects ) files exists:

![schermata 2016-05-20 alle 09 22 31](https://cloud.githubusercontent.com/assets/1799457/15420332/742a9bb2-1e6c-11e6-93aa-6a64ee82c0c5.png)

Other directory, same owner and permissions, files are showed on "Filenames" search.

What can be ?

Atom: 1.7.3
Nuclide ( on client ): 0.138.0
Nuclide ( on server ): 0.138.0
Initial Directory: /w3

Thanks

**Comment by shushz** [comment]
@steblar I can't repro that. Is there anything in the server or client log files? They are in the `<system-temp>/nuclide-<username>-logs/`

@hansonw do you have any ideas? Any information that could help with that?

**Comment by hansonw** [comment]
Hmm.. was this file recently added? Unfortunately, the file indexer we use in quick-open won't update itself unless you have Watchman installed (https://facebook.github.io/watchman/docs/install.html).

There are two workarounds for now:

1) remove/re-add the remote directory, or kill + restart the Nuclide server remotely
2) manually restart the file indexer process; `pkill -f nuclide-task/lib/bootstrap.js` should do it.

Sorry about the inconvenience. This is where the logic happens, if anyone feels like making a PR: https://github.com/facebook/nuclide/blob/master/pkg/nuclide-path-search/lib/FileSearch.js#L88

**Comment by steblar** [comment]
@hansonw watchman is installed correctly.
New and recently added files are showed correctly. Older files ( age > 1 month ) does not compare on search.

I give a try on your two workarounds

**Comment by steblar** [comment]
After some search we found:
`Failed to load native fuzzy matching. Falling back to JS implementation Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /nuclide-server/.npm_packages/lib/node_modules/nuclide/pkg/nuclide-fuzzy-native/VendorLib/fuzzy-native/build/fuzzy-native/v0.5.1/node-v48-linux-x64/fuzzy-native.node)`

File was:
`ls -al | grep libstdc
lrwxrwxrwx   1 root root       19 May  7 13:22 libstdc++.so.6 -> libstdc++.so.6.0.19
-rw-r--r--   1 root root   979056 May  7 14:11 libstdc++.so.6.0.19`

After an upgrade to g++ :

`ls -al | grep libstdc
lrwxrwxrwx   1 root root       19 May 13 06:21 libstdc++.so.6 -> libstdc++.so.6.0.22
-rw-r--r--   1 root root  1110280 May 13 06:36 libstdc++.so.6.0.22`

And quick open seems to found all files correctly.
