### ISSUE TITLE
Nuclide does not recognize files/folders 3 folders deep

### ISSUE THREAD

**Issue by lordlabakdas** [facebook/nuclide#509]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
I have a project folder which I tried importing into Nuclide on Atom which is 3 folders deep `src/src_a/src_b/src_c`. 

### Expected Behavior
All files and/or folders irrespective of the folder depth must be imported into the tree view of the Nuclide view of Atom

### Actual Behavior
Nuclide seems to stop importing files/folders that are greated than folder depth = 3. Included a screenshor from my project that show `src_c` not being part of the tree view but visible in the terminal view.

![nuclide_atom_issue](https://cloud.githubusercontent.com/assets/1252659/15454055/a5fbf460-1ff2-11e6-99c2-11f8cfecbd37.png)

### Versions
* Atom: 1.7.3
* Nuclide: 0.138.0
* Client OS: Ubuntu 14.04
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
* Hydrogen@0.9.1
* activate-power-mode@0.5.2
* advanced-open-file@0.16.3
* angularjs@0.3.4
* atom-beautify@0.29.7
* atom-ctags@4.5.2
* atomic-emacs@0.9.1
* autocomplete-python@1.7.3
* block-cursor@0.13.1
* emmet@2.4.3
* file-icons@1.7.12
* git-diff@1.0.1
* git-log@0.4.1
* git-plus@5.13.4
* git-time-machine@1.5.2
* highlight-selected@0.11.2
* imdone-atom@1.3.29
* imdone-atom-github@0.1.11
* indentation-indicator@0.6.0
* jumpy@3.0.3
* language-babel@2.21.1
* language-latex@0.6.1
* latex@0.32.0
* latex-autocomplete@0.4.3
* latexer@0.3.0
* linter@1.11.4
* minimap@4.24.0
* minimap-autohide@0.10.1
* minimap-cursorline@0.1.0
* minimap-find-and-replace@4.5.1
* nuclide@0.138.0
* pdf-view@0.50.0
* project-manager@2.9.7
* python-tools@0.6.7
* remote-edit@1.8.24
* script@3.7.1
* svn@0.0.10
* symbols-tree-view@0.12.0
* sync-settings@0.7.2
* tab-switcher@1.4.0
* tabs-to-spaces@1.0.2
* terminal-plus@0.14.5
* white-cursor@0.6.0

**Comment by ssorallen** [comment]
The 'src_b' folder doesn't appear expanded in your screenshot. Does 'src_c' show up when you expand 'src_b'?

**Comment by lordlabakdas** [comment]
Sorry about that, `src_c` does not show up during the initial import of the project.

I now checked again and it seems to show up after an Atom restart. Do not see this issue now.
