### ISSUE TITLE
Colors highlights remains on their place during scroll

### ISSUE THREAD

**Issue by lapanoid** [facebook/nuclide#510]
### Issue and Steps to Reproduce
Just installed nuclide no plugins, I am opening less file, and during scroll see strange artifacts.

### Expected Behavior
Colors highlights should scroll

### Actual Behavior
http://www.giphy.com/gifs/l0K40YpzDeTJcBpg4

### Versions
* Atom: 1.7.3
* Nuclide: 0.136.0
* Client OS: os x 10.11.4

### Additional Details
* Installed packages (`apm ls --installed`):

├── ask-stack@2.2.0
├── atom-beautify@0.29.1
├── atom-color-highlight@3.0.9
├── color-picker@2.1.1
├── compass@0.9.1
├── editor-stats@0.17.0
├── editorconfig@1.2.4
├── emmet@2.4.3
├── file-icons@1.7.1
├── gulp-control@0.3.3
├── highlight-line@0.11.1
├── jshint@1.8.5
├── linter@1.11.4
├── minimap@4.21.0
├── nuclide@0.136.0
├── project-manager@2.9.7
├── react@0.15.0
├── refactor@0.6.0
├── run-in-atom@1.0.4
├── seti-ui@0.7.1
├── terminal-status@1.6.8
└── travis-ci-status@1.0.0

**Comment by ssorallen** [comment]
The GIF looks like artifacts from the ['color-picker' package](https://atom.io/packages/color-picker). Nuclide doesn't have a feature involving colors like that.
