### ISSUE TITLE
React Native Server does not bind to Current Working Root

### ISSUE THREAD

**Issue by zhiquan-yu** [facebook/nuclide#511]
### Issue and Steps to Reproduce
1. Open a project named project1, then run Nuclide/React Native/Start Packager, it's OK.
2. Stop React Native Server, and close this tab.
3. Add project folder named project2, and set it to current working root, then run Nuclide/React Native/Start Packager, but it still look for js files in project1.

### Expected Behavior
In Step 3, React Native Server should look for js files in project2.

### Actual Behavior
It still look for js files in project1.

### Versions
* Atom: 1.7.3
* Nuclide: 0.138.0
* Client OS: OS X 10.11.5
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

├── atom-beautify@0.29.7
├── atom-material-syntax-light@0.4.5
├── atom-material-ui@1.2.11
├── atom-react-native-autocomplete@0.0.24
├── atom-react-native-css@1.1.0
├── atom-ternjs@0.14.1
├── atom-xcode@0.1.3
├── autocomplete-modules@1.4.1
├── autocomplete-paths@1.0.2
├── docblockr@0.7.3
├── editorconfig@1.4.1
├── file-icons@1.7.12
├── git-time-machine@1.5.2
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── js-hyperclick@1.4.2
├── jumpy@3.0.3
├── keyboard-scroll@0.4.0
├── language-babel@2.21.1
├── language-ini@1.16.0
├── language-javascript-jsx@0.3.7
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.4
├── linter-eslint@7.2.2
├── nuclide@0.138.0
├── react@0.15.0
├── regex-railroad-diagram@0.16.0
├── rename-tabs@0.1.1
├── sort-lines@0.14.0
├── sync-settings@0.7.2
├── todo-show@1.6.0
└── tool-bar@0.4.0

└── (empty)

--------------------------------

If I remove project folder project1, stop React Native Server, and close React Native Server Tab, then run Nuclide/React Native/Start Packager, it will be ok.
So I think Nuclide/React Native/Start Packager doesn't look for working sets.

**Comment by shushz** [comment]
You probably mean the Current Working Root and not Working Sets, as Working Sets is an entirely different feature used to filter out parts of the file-tree.

Yes, unfortunately this functionality is not connected to the React Native logic, at least not yet.

**Comment by matthewwithanm** [comment]
Hey @zhiquan-yu! This was fixed in a53a8b6418cc7e4c21df2586da746498fe632e45. Thanks for the report!
