### ISSUE TITLE
Java Support

### ISSUE THREAD

**Issue by mlannan** [facebook/nuclide#517]
Does Nuclide support Java development?

**Comment by nmote** [comment]
Not currently, but we have been wanting to develop at least some rudimentary Java support for some time. At the very least, it could help people who normally use Nuclide for other languages but are browsing or making small changes to Java code. We don't currently have plans to work on Java support but it is certainly on our wishlist.

**Comment by jgebhardt** [comment]
You can definitely "brows[e] or mak[e] small changes to Java code" in Nuclide. I'm closing this issue because it's not directly actionable.

**Comment by shushz** [comment]
We're working on a Java support, but at the moment it is far from being production-ready and heavily targets internal use cases. Once it's mature enough to be usable (and useful) for the general public we'll release it, but it's not in the near future.
