### ISSUE TITLE
Flow error message is not showing up in Nuclide diagnostics

### ISSUE THREAD

**Issue by yinanfang** [facebook/nuclide#521]
### Issue and Steps to Reproduce
Everything else in Nuclide is working except flow. The ESLint message is showing up so the console should be working fine. Flow works in command line so it should be fine. I don't know why the error message doesn't show up in the Nuclide console. Is there any way to debug this problem? I know you might need more information about this. Let me know what I need to do

![image](https://cloud.githubusercontent.com/assets/4115566/15634936/6778db70-259e-11e6-9061-03bbf3421edc.png)

### Expected Behavior
Whatever error message show up in the terminal should also be in the Nuclide console

### Actual Behavior
Error message showed up in the terminal but not in the Nuclide console

### Versions
* Atom: 1.7.4
* Nuclide: 0.139.0
* Client OS: MacOS X
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-beautify
├── color-picker@2.1.1
├── emmet@2.4.3
├── file-icons@1.7.13
├── file-types@0.5.1
├── firewatch-syntax@1.0.1
├── git-plus@5.14.0
├── gruvbox-syntax@2.4.1
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.4
├── linter-clang@3.4.4
├── linter-csslint@1.3.2
├── linter-eslint@7.2.2
├── linter-flake8@1.13.0
├── linter-htmlhint@1.1.4
├── linter-jsonlint@1.2.5
├── linter-php@1.2.0
├── linter-rubocop@0.4.7
├── linter-scss-lint@3.0.4
├── linter-shellcheck@1.2.0
├── linter-swiftc@2.0.0
├── merge-conflicts@1.4.3
├── minimap@4.24.3
├── minimap-linter@1.1.1
├── monokai@0.18.0
├── nuclide@0.139.0
├── pigments@0.28.1
├── project-manager@2.9.7
├── react@0.15.0
├── seti-ui@1.2.3
├── sort-lines@0.14.0
├── terminal-plus@0.14.5
├── tool-bar@0.4.0
├── travis-ci-status@1.1.1
└── vim-mode@0.65.1

└── (empty)

**Comment by nmote** [comment]
Could you include the following information:

- Exactly what Flow command you are using, and the directory in which you are running it (`pwd`)
- The exact output of that Flow command
- The contents of your `~/.atom/config.cson`

Could you also open the dev tools with cmd+alt+i, make sure you are on the console tab, and see whether any seemingly relevant errors are there? If you're not sure feel free to just paste an excerpt.

Lastly, have Flow errors ever worked for you in Nuclide?

**Comment by yinanfang** [comment]
@nmote I think I found the problem. It might be cause by the long startup time of Flow. When I found ESLint is working and Flow is not working, I keep restarting things and try to edit `.flowconfig` and so on. But when I give up trying and come back later, Flow just works well. 
Then I measure the time that it take to run the official example with npm:
`{"name": "get_started", "scripts": {"flow": "flow; test $? -eq 0 -o $? -eq 2"}}`
It take about 3-5 minutes
Is it possible to add some alert message in Nuclide saying that Flow is starting and not ready yet so that it would be more clear about why it doesn't work.

**Comment by nmote** [comment]
I think a message that pops up would be too disruptive but there is a spinner in the status bar that indicates when we are waiting on diagnostic results from Flow. Sometimes with long startup times the diagnostics request times out so I think we could change some things to make sure the indicator is always spinning if Flow is busy. However I don't like the idea of adding a disruptive notification. I'm open to ideas on how to make this clearer without annoying people, though.

**Comment by yinanfang** [comment]
I think a spinner in the status bar is great! Flow is just a small part of the IDE and I don't think it should have a huge pop up. Thanks for working on this issue and Nuclide. It's an amazing tool!
