### ISSUE TITLE
Drag & drop in nuclide-file-tree

### ISSUE THREAD

**Issue by MichaelCereda** [facebook/nuclide#524]
Seems impossible to me to drag and drop files on the file tree.
Sometimes is kind of frustrating, specially when you have to move a lot of files
I don't see any warning in my developer tools.

I'm wondering if this is a wanted behavior.
Thanks

**Comment by tyangliu** [comment]
Hi Michael,

I've been working on adding drag-and-drop to the file tree. I'll give an update when it's ready to go within one of the releases in the near future, stay tuned!

**Comment by MichaelCereda** [comment]
Oh.. Perfect .
File tree now feels very static.
I have some ideas in mind but at this point I'll wait until your update.
Thanks

**Comment by birdwell** [comment]
This is a pain for me also.

**Comment by tyangliu** [comment]
Drag and drop should be available in the newest release (0.146) :) Sorry it took a while to push out! Let me know if you have more feedback/suggestions.
