### ISSUE TITLE
nuclide-start-server: Permission denied

### ISSUE THREAD

**Issue by capouch** [facebook/nuclide#526]
CentOS 7.0 x64
Node v5.10.1
npm v3.8.3

I installed nuclide as root, `npm install -g nuclide`

As a non-root user, trying to run `nuclide-start-server` gives this error:
`$ nuclide-start-server 
/usr/local/bin/nuclide-start-server: line 13: scripts/nuclide_server_manager.py: Permission denied`

I see that the contents of ~/pkg/nuclide-server are owned by nobody:root.  

Changing the ownership of this directory to the same as the invoking user clears up the problem, but of course the next user who comes along is going to see it fail.

**Comment by hansonw** [comment]
What are the full permissions of `~/pkg/nuclide-server/scripts/nuclide_server_manager.py`? The read/execute bits for 'other' should be set (755).

**Comment by capouch** [comment]
-rwxr-xr-- 1 nobody root 16819 May 24 23:49 nuclide_server_manager.py

Turning on the o+x bit does fix the issue, but I uninstalled and reinstalled multiple times with the same permissions each time.

**Comment by hansonw** [comment]
Strange.. I believe the permissions are set to 755 by default. Could it have something to do with installing the package as root? I don't think that's necessary to get it to run.

**Comment by capouch** [comment]
@hansonw perhaps the install documentation should be changed to reflect that; it indicates that the package should be installed globally ATM.
