### ISSUE TITLE
Watchman trying to watch every file on the system?

### ISSUE THREAD

**Issue by capouch** [facebook/nuclide#528]
CentOS 7.0 x64
Node v5.10.1
npm v3.8.3

Found and fixed the permissions error on the server, and now after making a remote connection, I get this error on the local instance:

`Watchman Error:Remote Error: A non-recoverable condition has triggered. Watchman needs your help! The triggering condition was at timestamp=1464804801: inotify-add-watch(/home/brianc/PROJECTS/neal-sample/node_modules/core-js/library/core) -> The user limit on the total number of inotify watches was reached;`

Prior to this error, I got the same error, but pointing to a different directory tree full of node modules, which I deleted.  Now it found another repo and is complaining again.  Neither of the repos has anything to do with the project I'm trying to edit.

Looks like watchman is trying to watch every file on the filesystem?

**Comment by wez** [comment]
Please share the output from `watchman watch-list`, or if it won't let you run that, please share the contents of your state file; it can be found alongside the log file.  See https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs for information on how to locate that on your system.

**Comment by capouch** [comment]
It is watching my home directory, which because it is full of Node projects does indeed have thousands of files in it (lots of node_modules).

Is there any way to set it so that the watched tree only contains the files in the project of interest?  I wouldn't think I would be the only one to encounter this situation.

**Comment by wez** [comment]
Yep, take a look at these configuration options:

https://facebook.github.io/watchman/docs/config.html#root_files
https://facebook.github.io/watchman/docs/config.html#enforce_root_files

You can enable the default mode for this by creating the file `/etc/watchman.json` with these contents:

```
{"enforce_root_files": true}
```

This will cause watchman to only allow watching dirs that have a git or mercurial repo at their root, or that have a `.watchmanconfig` file at the root.  You can customize the `root_files` list to match whatever criteria make the most sense for your usage.

For this to take effect, especially as you are hitting system limits, you should run:

```
pkill watchman
rm /path/to/$USER-state/state
```

to ensure that all outstanding watches are cancelled (we'd normally just run `watchman watch-del-all`, but this won't function correctly while watchman is in a poisoned state).

Each time you change `/etc/watchman.json`, you will need to run `watchman shutdown-server` in order for those changes to take effect.

**Comment by capouch** [comment]
Awesome this worked just fine.  Hopefully this may help others who encounter this problem.
