### ISSUE TITLE
phatom space bar when hitting backspace

### ISSUE THREAD

**Issue by EMCP** [facebook/nuclide#535]
### Issue and Steps to Reproduce
while editing JSX or stylus files, there are times I'm hitting backspace and immediately following that something hits spacebar ... leaving me with the same thing.. I have to repeatedly hit it again and again until it stops fighting me

### Expected Behavior
I should just hit backspace and be done

### Actual Behavior
see above

### Versions
* Atom: 1.8.0
* Nuclide: 0.141.0
* Client OS: OSX 10.11.x
* Server OS (optional):

### Additional Details

```
Community Packages (17) ~/.atom/packages
├── Stylus@3.0.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.26.3
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── lint@0.0.1
├── linter@1.11.4
├── linter-eslint@7.2.2
├── linter-htmlhint@1.1.4
├── linter-jsonlint@1.2.5
├── linter-stylint@2.1.2
├── nuclide@0.141.0
├── sort-lines@0.14.0
├── terminal-plus@0.14.5
└── tool-bar@0.4.0

└── (empty)
```

**Comment by nmote** [comment]
I've never heard of this happening nor have I seen it myself. I'd be willing to bet that it's another package you have installed. Try disabling your non-nuclide packages, then restarting to make sure they are completely cleared, and if this still happens, please reopen.

**Comment by EMCP** [comment]
alright, I'll one-by-one test that out.  thanks
