### ISSUE TITLE
ES6 + JSX Linter stopped linting?

### ISSUE THREAD

**Issue by EMCP** [facebook/nuclide#536]
### Issue and Steps to Reproduce
this is a strange thing, and not sure what's up.. but suddenly noticed that Nuclide is no longer linting my `.jsx` files.  I've just been updating packages and not fiddling with any of my linter setup.

### Expected Behavior
if jsx linting is working, it should continue working in a project.. even when updating packages

### Actual Behavior
seems suddenly it's silently stopped working

### Versions
* Atom: 1.8.0
* Nuclide: 0.141.0
* Client OS: OSX 10.11.x
* Server OS (optional):

### Additional Details

```
Community Packages (17) ~/.atom/packages
├── Stylus@3.0.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.26.3
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── lint@0.0.1
├── linter@1.11.4
├── linter-eslint@7.2.2
├── linter-htmlhint@1.1.4
├── linter-jsonlint@1.2.5
├── linter-stylint@2.1.2
├── nuclide@0.141.0
├── sort-lines@0.14.0
├── terminal-plus@0.14.5
└── tool-bar@0.4.0

└── (empty)
```

**Comment by ssorallen** [comment]
Try disabling the 'linter' package. Nuclide and linter have overlapping functionality, and we discourage using both at the same time. See https://nuclide.io/docs/advanced-topics/linter-package-compatibility/

**Comment by EMCP** [comment]
unfortunately my project has stylus files, so to lint them I use `linter` and `linter-stylint`..

sounds like I'll get hit or miss support if I keep going this route?

**Comment by EMCP** [comment]
actually I noticed I'd had linter disabled as per suggestions

![screen shot 2016-06-13 at 6 25 28 pm](https://cloud.githubusercontent.com/assets/3691722/16033638/f6035652-31c1-11e6-8b66-370f801fcdea.png)

**Comment by nmote** [comment]
I don't think this is a Nuclide issue. You are using `linter-eslint`, which is not part of Nuclide, to run eslint. Nuclide displays the results from that, but nothing in that code has changed recently. I suspect a change either in your configuration or in `linter-eslint`.

One thing to check is what grammar is being used for your jsx files -- look in the bottom right of the status bar. Try changing it around to see if that helps. Try using the "JavaScript" language.
