### ISSUE TITLE
Irritating setting: "Warn when Flow is not found"

### ISSUE THREAD

**Issue by jhohlfeld** [facebook/nuclide#537]
### Issue and Steps to Reproduce
Nuclide raises an error when Flow is not installed but a .flowconfig was found.

The reason why I report this issue is that I do not expect errors when doing a Getting Started tutorial and following it step by step. This might be very confusing and may lead to the impression, nuclide is somehow broken.

Some background: The [react-native tutorial](http://facebook.github.io/react-native/releases/0.27/docs/getting-started.html#highly-recommended-installs) lists Flow as an optional Install (although called 'Highly recommended'). For optional Installs, I never expect getting errors.

Steps to reproduce:

0. Flow is NOT installed
1. Initialize a new react-native project (react-native@0.27.1)
  
  `react-native init ReactTest`

2. Open project in atom/nuclide
3. Add project folder
4. Open index.ios.js

### Expected Behavior

When following the Getting Started of React-native and Nuclide step-by-step, I do not expect to be confronted with red error boxes.

### Actual Behavior

I get a red error box with the warning: "Flow was not found..."

!["Flow was not found"](https://cloud.githubusercontent.com/assets/497141/15893761/1887f4ec-2d82-11e6-9855-ccabf0b9a7f4.png)

### Versions
* Atom: 1.8.0
* Nuclide: 0.141.0
* Client OS: Mac OSX 10.11.2
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (1) /Users/jakob/.atom/packages
└── nuclide@0.141.0

└── (empty)
```

**Comment by nmote** [comment]
Thanks for the feedback. I do think this message is valuable because otherwise people may expect Flow features to work and not understand why nothing is happening. However I agree that the red box is a bit jarring in this context. What if it were yellow (the ordinary warning color) instead? Would that feel better to you?

**Comment by jhohlfeld** [comment]
@nmote Sure, now that I know, it seems trivial to even bother. However, a nice chilly blue message would have done the job i guess. But as you said, for other use cases the alarming version might be more appropriate.

**Comment by nmote** [comment]
I think you're right -- a blue message would be less alarming. I can also reword it a little bit. It should get the point across without worrying people.

**Comment by nmote** [comment]
I just put up a change for review that makes it look like this:

<img width="463" src="https://cloud.githubusercontent.com/assets/7988361/15913833/49e059da-2d91-11e6-911a-b96a3b9b859a.png">

**Comment by jhohlfeld** [comment]
Wow, that's awesome!
Think this is much better. Nice to see things 'Flow' 😋

Am Donnerstag, 9. Juni 2016 schrieb Nat Mote :

> I just put up a change for review that makes it look like this:
>
>
> <https://cloud.githubusercontent.com/assets/7988361/15913833/49e059da-2d91-11e6-911a-b96a3b9b859a.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/facebook/nuclide/issues/537#issuecomment-224755904>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAeV9Rf6mugishDBfN0qKqzN84wBpq3bks5qJ0h3gaJpZM4Iw5Tt>
> .
>


-- 
~~~ Consider not printing this email ~~~
-----------------------------------------------------------
Jakob Hohlfeld • Fontanehof 7 • 38440 Wolfsburg • Germany
Phone: +49 (0)151 18565949 • http://www.netronaut.de
Jabber / Email: jakob.hohlfeld@netronaut.de
