### ISSUE TITLE
Website links broken?

### ISSUE THREAD

**Issue by rtorr** [facebook/nuclide#539]
### Issue and Steps to Reproduce
Go to https://nuclide.io/docs/languages/flow/
Look at the navigation on the left

![image](https://cloud.githubusercontent.com/assets/297045/15915249/9e934cde-2d9c-11e6-8276-494e8a101294.png)

None of the links appear.

![image](https://cloud.githubusercontent.com/assets/297045/15915266/ba027210-2d9c-11e6-927e-e7b6ab3f15f8.png)

### Expected Behavior
Should have links to other portions of the site

### Actual Behavior
No links shown

### Additional Details
* Latest chrome browser/OSX El Capitan

**Comment by jamesgpearce** [comment]
yep, can repro; thanks!

**Comment by matthewjohnston4** [comment]
Fixed :)
