### ISSUE TITLE
[docs] Rename Debug in Chrome to Debug JS Remotely

### ISSUE THREAD

**Issue by hramos** [facebook/nuclide#543]
### Issue and Steps to Reproduce

There's a minor docs issue in the React Native instructions. The 'Debug in Chrome' option in the Developer Menu has been renamed to 'Debug JS Remotely'. We need to update the screenshot and text in the [React Native guide](https://nuclide.io/docs/platforms/react-native/).
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

**Comment by JoelMarcey** [comment]
@hramos Hmmm.. strange. I don't get `Debug JS Remotely`. I still get `Debug in Chrome`. When I press `Cmd-D` in the iOS simulator, I see....

<img width="248" alt="screenshot 2016-06-28 14 28 27" src="https://cloud.githubusercontent.com/assets/3757713/16432953/9ba74304-3d3c-11e6-8b46-550e5b01d2e0.png">

Am I behind in a version or something?

**Comment by andresn** [comment]
![image](https://cloud.githubusercontent.com/assets/69597/18375427/f4ea707e-760a-11e6-9b58-081e6d13149b.png)
XCode 8 GM Seed

![image](https://cloud.githubusercontent.com/assets/69597/18375403/bc9c2e92-760a-11e6-9bc3-ff4a09ce9c2a.png)

**Comment by JoelMarcey** [comment]
I am going to leave this as a starter task that should be looked at in the next week or two.
