### ISSUE TITLE
Feature request: hover dialogue for hyperclick

### ISSUE THREAD

**Issue by chenglou** [facebook/nuclide#550]
I've found that my most common workflow with hyperclick is to jump to location, check some code, then jump back using some cursor history shortcut I have. If there was a way to get a preview of the destination location, I wouldn't have to do this.

Basically, type hint dialogue, but for content.

**Comment by bolinfest** [comment]
Check out `nuclide-datatip.provider`, right @jgebhardt?

**Comment by jgebhardt** [comment]
Yes, that should work. It would be nice to have a default hyperclick preview datatip for buffer locations, but it should be overrideable by packages with special hyperclick behavior.



Sent from my iPhone
On Jun 17, 2016, at 10:08, bolinfest <notifications@github.com<mailto:notifications@github.com>> wrote:


Check out nuclide-datatip.provider, right @jgebhardt<https://github.com/jgebhardt>?

-

**Comment by chenglou** [comment]
It'd be reaaaallly nice if one could recursively click inside the datatip to jump to another location

**Comment by jgebhardt** [comment]
💯
Curious what we should display in the preview window. "address" (path + line) and like 3 lines of context around the target location? What about external links– I'm thinking a preview might be overkill, and just the URL would be enough. BTW @shayne has already done some work on "definition previews", which are basically what we're talking about.

**Comment by phord** [comment]
ISTR that SlickEdit shows some intelligent context including preceding JavaDoc and definition spanning multiple lines if, say, the link is to a function whose definition takes several lines.

Eclipse goes one further letting you click in the tip window to give it focus and then scroll it like an editor.

**Comment by wbinnssmith** [comment]
Good news! This feature landed :)

You can now hold command while hovering to get a preview of a symbol!
