### ISSUE TITLE
hack - type coverage for global functions within namespaces

### ISSUE THREAD

**Issue by zerodiv** [facebook/nuclide#551]
### Issue and Steps to Reproduce

Getting: 'Un-type checked code. Consider adding type annotations.'

Create the following scripts within a .hhconfig enabled directory:

Namespaced class (bug-namespace-example.php):
```php
<?hh // strict

namespace foo;

// Attempted to import the global function via: \string and \HH\string
// use \string;

class foobar {
  public function nothingSpecial(): string {
    $className = get_class($this);
    return $className;
  }
}
```
Driver script (bug-namespace.php):
```php
#!/usr/local/bin/hhvm
<?hh

require_once dirname(__FILE__) . '/bug-namespace-example.php';

$baz = new \foo\foobar();
var_dump($baz->nothingSpecial());
```
### Expected Behavior
No type errors for global functions.

### Actual Behavior
3 type coverage errors for the get_class usage two for line 10, then one for 11.
![bug-namespace-example_php](https://cloud.githubusercontent.com/assets/196370/16157339/f5a03a1a-346c-11e6-9cd3-5bd09d3d0dfb.png)

### Versions
* Atom: 1.8.0
* Nuclide: 0.141.0
* Client OS: OS X 10.11.5 
* Server OS (optional): CentOS release 6.5 (Final)
* Server HHVM: HipHop VM 3.12.2-dev (rel)

### Additional Details
Community Packages (13) /Users/jorcutt/.atom/packages
├── auto-indent@0.5.0
├── docblockr@0.7.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.28.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── markdown-toc@0.4.1
├── nuclide@0.141.0
├── phpunit@1.2.0
├── sort-lines@0.14.0
└── tool-bar@0.4.0
└── (empty)

**Comment by nmote** [comment]
You've enabled display of uncovered regions by clicking the percentage in the status bar. Click it again to toggle this off.

These are different than ordinary typechecker errors -- they are simply informing you of areas where the typechecker doesn't know what types things have. I usually develop with this feature disabled, and then toggle it on when I want more information about which areas are covered by the type system.
