### ISSUE TITLE
Autocomplete not working for `AppRegistry`

### ISSUE THREAD

**Issue by imWildCat** [facebook/nuclide#557]
### Issue and Steps to Reproduce

I have installed `flow`, `watchman`, `nuclide` successfully, but autocomplete now working. 

As the gif below shows, when I typed `AppRegistry` directly, there was not suggestion.
![2016-06-22 17_45_29](https://cloud.githubusercontent.com/assets/2396817/16262193/29997204-38a1-11e6-88da-3abb626ab231.gif)

**Update:** Autocomplete worked with old version of react-native(0.22), but new version of react-native(0.28).

### Expected Behaviour
When I type `AppRegistry`, there will be suggestions.

### Actual Behaviour
No suggestion.

### Versions
* Atom: `1.8.0`
* Nuclide: `0.141.0`
* Client OS: `Mac OS X 10.11.5 (15F34)`
* Server OS (optional): none

### Additional Details
* Installed packages (`apm ls --installed`):
```bash
$ apm ls --installed
Community Packages (2) /Users/wildcat/.atom/packages
├── language-javascript-jsx@0.3.7
└── nuclide@0.141.0

└── (empty)
```

**Comment by nmote** [comment]
Flow handles all of our autocomplete for JS code, so this isn't an issue with Nuclide itself. I can tell from your gif that Flow autocomplete in general is working fine, so I think there is something going on with this specific case. If you're sure that it used to work, then something has regressed and it should be fixed.

Feel free to reopen on https://github.com/facebook/flow
