### ISSUE TITLE
Buck toolbar autocompletion is broken (No results found)

### ISSUE THREAD

**Issue by arielelkin** [facebook/nuclide#559]
### Issue and Steps to Reproduce
Can't run the iOS app on Simulator and debug it.

To reproduce:

1. Install React Native
1. Install Nuclide
1. Install Buck
1. This:

![image](https://cloud.githubusercontent.com/assets/1756909/16333846/c8b430f6-39fd-11e6-9fb0-208c22506c78.png)

Contents of `.buckconfig`:

```
[android]
  target = Google Inc.:Google APIs:23

[maven_repositories]
  central = https://repo1.maven.org/maven2
```

### Versions
* Atom: 1.8
* Nuclide: 0.147.0
* Client OS: OS X 10.11.5 and Xcode 7.3.1

### Additional Details
* Installed packages (`apm ls --installed`):
just nuclide.

**Comment by hansonw** [comment]
Hi @arielelkin, sorry about the misleading message: the autocompletion in the Buck targets is a little broken at the moment. You can enter the buck target as you would on the command line and ignore that message; pressing Run should work regardless. I'm working on a better autocomplete at the moment!

**Comment by arielelkin** [comment]
@hansonw thanks for your reply.

If I enter `ios` as the buck build target in the nuclide build bar:
![image](https://cloud.githubusercontent.com/assets/1756909/16563463/80f8f492-4202-11e6-8825-7ec0ad132241.png)

the Run button is greyed out and I can't press on it. Let me know if I'm doing something wrong, pls.

**Comment by Fandekasp** [comment]
I'm also confused. 
When creating a repo with `react-native init SampleAppMovies`, I can see some BUCK files in the android directory, but none in the ios one. 
[The documentation](https://nuclide.io/docs/platforms/react-native/#running-applications__buck-integration) says "Buck Integration currently only works with React Native iOS apps", which is weird (at first glance, I'd have thought the opposite). Why aren't any BUCK files in the ios dir ? How should we create them and what should we fill them with? 

I'll use the console for the time being, hopefully I can use the Atom buck build feature soon :) Thank you for your support!

**Comment by hansonw** [comment]
Hmm actually it looks like the `react-native init` script does not enable Buck for iOS at the moment.
Instead you should use the non-Buck instructions available here: https://nuclide.io/docs/platforms/react-native/#running-applications__command-line
