### ISSUE TITLE
Flow support on Windows

### ISSUE THREAD

**Issue by brummelte** [facebook/nuclide#561]
Nuclide can't find the flow executable on startup even though it is in the PATH.

This is because nuclide is using `which` in order to check if flow exists ([nuclide/pkg/nuclide-flow-base/lib/FlowHelpers.js:138](https://github.com/facebook/nuclide/blob/a72bc124a87efc08189f6d3904d90d17814fbaec/pkg/nuclide-flow-base/lib/FlowHelpers.js#L138)). On Windows it should use `where`.

**Comment by nmote** [comment]
We switched to the npm `which` package at one point, but had to roll it back because something broke (I don't remember what). It would be good to fix this across the board (IIRC there are several places where we use `which`), but I would also accept a PR to add a platform check to that function.

**Comment by oviava** [comment]
Guide to setting up flow on Windows: https://gist.github.com/oviava/9c7f0a5ec2fdcdc737b0a75239e6546f

**Comment by nmote** [comment]
This has been fixed
