### ISSUE TITLE
Please create new release of nuclide-ui-atom-input package

### ISSUE THREAD

**Issue by jurassix** [facebook/nuclide#563]
I'm working on an Atom plugin, developing with Atom+Nuclide. I'm depending on the __nuclide-ui-atom-input v0.0.35__ and __react-for-atom v15.0.2-1__. I'm getting an exception simply requiring _AtomInput_ from __nuclide-ui-atom__. 

When I debug _AtomInput_ is not requiring in React properly. It seems to be caused by an incorrect export of React from __react-for-atom__. I've tried downgrading my deps to __react-for-atom v0.14.3__, to match the deps from __nuclide-ui-atom-input__ but Nuclide is overriding the dependency back to React 15 (react-for-atom 0.15.x). 

I believe this issue can be resolved if a new version of _nuclide-ui-atom-input_ was published with the latest version of __react-for-atom__. Seems like the last version __0.0.35__ was published __2015-11-25T18:49:38.082Z__, and still requires React 14. 

**Atom Version**: 1.8.0
**System**: Mac OS X 10.10.5

### Stack Trace

Failed to activate the atom-refactoring-codemods package

```
At Super expression must either be null or a function, not undefined

TypeError: Super expression must either be null or a function, not undefined
  at _inherits (/Users/cayres/projects/atom-refactoring-codemods/node_modules/nuclide-ui-atom-input/lib/AtomInput.js:16:113)

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-linter-ice-standard, v2.0.0
language-apache, v1.5.0
language-babel, v2.28.0
language-cjsx, v0.3.0
language-graphql, v0.2.0
language-groovy, v0.6.0
linter, v1.11.14
nuclide, v0.147.0

# Dev
No dev packages
```

**Comment by ssorallen** [comment]
The 'nuclide-ui-atom-input' package is no longer supported. For the time being, you will need to copy Nuclide's AtomInput.js file into your package. We haven't yet determined a way to release Nuclide's React components for use in other packages.

**Comment by jurassix** [comment]
Thx for the update. I have copied it. Hopefully this will be available in the future, lots of good components here.

**Comment by ssorallen** [comment]
@jurassix Which other components have you found useful?

A primary issue we are investigating is having multiple versions of React across multiple Atom packages. [react-for-atom](https://github.com/jgebhardt/react-for-atom) aims to solve some of that issue, but it is not bulletproof.

**Comment by jurassix** [comment]
I see value in many of the nuclide-ui components. I definitely have plans to reuse [PanelComponent](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-ui/lib/PanelComponent.js). I may also use some of the diagnostic components. I'll update this thread as I build out my Atom plugin, with additional feedback on what I actually used.

**Comment by ssorallen** [comment]
@jurassix Great, thanks a lot. Would you mind putting your list of components into a new issue with an appropriate title so others can find it? Then we will know not to close it too.

**Comment by jurassix** [comment]
@ssorallen will do!
