### ISSUE TITLE
Connection to remote project breaks ability to run local commands

### ISSUE THREAD

**Issue by darrenkenny** [facebook/nuclide#566]
### Issue and Steps to Reproduce

I've used several Atom tools like terminal-plus and terminal-fusion, and when I run them
with nuclide installed without connecting to a remote project, they have no problems running
commands on Windows 8.1.

When I connect to a remote project though, I'm unable to start a new terminal session
instead they hang. On the console I see errors like not being able to execute CMD.EXE
(the default shell on Windows).

Somehow the connection to a remote project is interfering with the ability to 
execute local commands.

### Expected Behavior
Connecting to a remote system shouldn't interfere with the ability to run local commands on
Windows.

If the intent is that it would be starting the command remotely (which isn't obvious, but might
explain why it cannot find CMD.EXE) since the remote system is Linux here, then it should
at least explain this better in the errors, but also provide some way to override the shell being
used in this case from the Atom default to something like /bin/bash.

### Actual Behavior
Attempts by other packages to run remote commands fails.

### Versions
* Atom: 1.8.0
* Nuclide: 0.148
* Client OS:  Windows 8
* Server OS (optional): Linux Ubuntu 16.04

### Additional Details
* Installed packages (`apm ls --installed`):

Community Packages (15) C:\Users\<myuser>.atom\packages
├── autocomplete-python@1.8.1
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.29.1
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.14
├── merge-conflicts@1.4.4
├── nuclide@0.148.0
├── python-jedi@0.3.7
├── sort-lines@0.14.0
├── terminal-fusion@2.2.1
├── tool-bar@0.4.0
└── tool-bar-almighty@0.6.1

└── (empty)

I had a lot more packages installed, but after some prolonged frustration at sudden failure of
things that worked before, I fell back to a clean install and added things until I found a failure.

**Comment by hansonw** [comment]
Hey, I'm having trouble reproducing this (granted, I'm not using Windows). I'm using terminal-fusion with a Nuclide remote connection at the moment on Mac OS X and things are going fine.

Could you provide some more information perhaps?
1) Could you copy + paste the error logs from the console? or
2) Could you provide a screenshot of the terminal that appears with a remote connection open? If you can get it to appear at all.

**Comment by darrenkenny** [comment]
OK, I think I managed to figure this out - the issue seems to be that several of these packages will attempt to start a shell in the same directory as the open file. 

Only one package I saw had the easily accessible option to specify where to open it's terminal - changing away from the project or file location, but to a specific path - if I do that then the terminal
will successfully open.

What would be good here is if nuclide could provide some means to map the path to a location that packages can resolve - be it a /net location on Unix variants, or some mapped drive on Windows. That way if any non-nuclide Atom package attempts to obtain the path of the current buffer it would get something other than some virtual path that only nuclide supports or can resolve.

I guess this wouldn't be too unlike what Google Chrome provides in it's URL to Workspace mappings.

Actually, it wasn't just terminals that had problems - some of the linter related add-ons were also
generating errors on the console when attempting to run some external command like eslint, pep8, etc.

**Comment by nmote** [comment]
I doubt we're going to do that. We would either have to copy all of the files down to a temp directory (which won't work because we want to support very large repositories), or create a virtual filesystem that fetches files on demand (which would be cool, but would be a huge chunk of work that would be difficult to justify).

I think the solutions outlined in #516 will be the way forward. That way, third-party terminal packages that want to support Nuclide will have the means to do so. However it's unlikely that we will make the remote connection so transparent that all third-party packages work off-the-shelf.
