### ISSUE TITLE
Broken atom after update

### ISSUE THREAD

**Issue by chalda** [facebook/nuclide#567]
### Issue and Steps to Reproduce
Updated from 0.146 to 0.148
a bunch of other modules stopped working. In particular atom-eslint. Also now its complaining about incompatible packages React and Babel (i removed React for now). In general Atom is instantly slower and a bunch of stuff doesnt work that used to. I just uninstalled nuclide completely its still giving me a lot of issues (saying the folder isnt found).
### Expected Behavior
should work?

### Actual Behavior
doesnt work.

### Versions
* Atom: 1.8
* Nuclide: 0.146 -> 0.148
* Client OS: OSX capitan
* Server OS (optional):

### Additional Details
a bunch of these are disabled:
* Installed packages (`apm ls --installed`):
├── Sublime-Style-Column-Selection@1.5.1
├── Tern@0.8.0
├── activate-power-mode@0.5.2
├── atom-beautify@0.29.9
├── atom-ternjs@0.14.2
├── atom-typescript@8.11.0
├── auto-reveal-active-file@0.3.1
├── auto-reveal-in-sidebar@0.8.0
├── auto-update-packages@1.0.1
├── autocomplete-modules@1.5.2
├── autocomplete-plus@2.31.0
├── current-file-breadcrumb@0.1.2
├── emmet@2.4.3
├── fast-eslint@2.14.0
├── file-type-icons@1.3.0
├── grunt-runner@0.14.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── js-autoimport@0.5.1
├── jump-to-import@0.6.0
├── language-babel@2.29.1
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── line-diff-details@1.3.5
├── linter@1.11.14
├── linter-csslint@1.3.2
├── linter-eslint@7.2.4
├── linter-flow@5.4.0
├── linter-json-lint@0.1.1
├── merge-conflicts@1.4.4
├── mocha-test-runner@0.5.1
├── node-debugger@1.7.0
├── persistent-undo@1.2.0
├── pigments@0.29.3
├── pretty-json@1.4.1
├── react@0.15.0
├── sort-lines@0.14.0
├── todo-show@1.6.0
└── tool-bar@0.4.0

**Comment by nmote** [comment]
If you've uninstalled Nuclide and you're still having problems, I don't think it's a problem with Nuclide. Also, if we are going to help you, we need exact error text. Saying that "a bunch of stuff doesn't work" and paraphrasing error messages is not enough information.
