### ISSUE TITLE
Linter not running

### ISSUE THREAD

**Issue by jjh42** [facebook/nuclide#573]
### Issue and Steps to Reproduce
Previously, when using Atom/Nuclide my custom linters worked fine. Now, however, they seem to have stopped running. No errors are reported in the console, but the linters don't seem to run.

In particular a test linter I just made:
```
console.log('loading test linter')


module.exports =
  provideLinter: ->
    provider =
      name: 'testlint'
      providerName: 'testlint'
      grammarScopes: ['*']
      scope: 'file' #'file' # or 'project'
      lintOnFly: false
      lint: (textEditor) =>
        console.log('Linting!')
    console.log('Providing linter', provider)
    return provider
```

the modules loads and provideLinter is called (console shows `providing linter`), but when I save a file, lint never seems to be called on the provider (`Linter!` is never seen). My previously working linters don't seem to work anymore. I've tried editing both remote and local files, neither seems to result in the linter fire (it should work for any filetypes since I don't limit the grammar scope). Nuclide-diagnostics has legacy linters enabled (but not on-the-fly linting).

![image](https://cloud.githubusercontent.com/assets/371038/16570551/57416caa-423f-11e6-97d7-8b1edfe02432.png)

Maybe this is the same underlying cause as https://github.com/facebook/nuclide/issues/536. I don't have linter installed, and my linters previously worked with nuclide (but I'm not exactly sure when I noticed they stopped working).

### Versions
* Atom: 1.8.0
* Nuclide:
* Client OS: Mac OS 10.11.5

I've tried both remote and local files. Thanks for any suggestions.

**Comment by zertosh** [comment]
cc: @nmote

**Comment by nmote** [comment]
Note that Atom gets providers on startup even if nothing is consuming them. So the fact that `provide` is called doesn't actually indicate that anything is consuming it.

I don't think we ever implemented the `*` as a wildcard in `grammarScopes`. Take a look at the [type here](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-diagnostics-base/lib/main.js#L153). There's an alternative that we came up with. Just set `allGrammarScopes` to `true`. If you still have trouble after that, let us know.

**Comment by jjh42** [comment]
Ok. It does seem to fire now. I swear that this used to fire without that but ok, problem solved. Thanks.
