### ISSUE TITLE
Document new console components and the shortcut to toggle it.

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/nuclide#585]
Relevant commits:

3087b25b68e6ff7f80ad9448a4c9e0255ba17406 Provide service for registering executors [console 1/N]
d78f4b1e060df24178f4d0f8d0287a12bdfc08ef Add concept of current executor [console 2/N]
57d05330ae12fad472e7d5d14330d06bd4067539 Execute code [console 3/N]
7fb9322507ac349fd76c5c091d22dedab370ddfb Add new components for console UI [console 4/N]
b6d418894bd3fe8a68471af928874f264c989551 Integrate new components into console UI [console 5/N]
e93bbe4cd0d25bf442656cccc7b372441d96b59e Add shortcut for toggling console
7a66567e7bc079fa633a37a324588449c90a6045 nuclide-output -> nuclide-console

**Comment by zardra** [comment]
So, the toolbar button was added to the toolbar doc, and I updated the screenshot of the Console in the Debugger doc (under the Evaluation section), but perhaps something should be added to the Basics doc since this can be toggled on/off outside of the Debugger.

**Comment by JoelMarcey** [comment]
That's a good question. Will the console be used anywhere outside the debugger under normal circumstances. I was thinking Basics would be for those features that would be of everyday use, throughout your Nuclide session and workflow.

Maybe just having the toolbar button documented and for the debugger is ok.

You can probably add the toggler keyboard shortcut to the keyboard shortcuts doc. The shortcut is https://github.com/facebook/nuclide/commit/e93bbe4cd0d25bf442656cccc7b372441d96b59e.
