### ISSUE TITLE
Rework the documentation for the toolbar showing split.

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/nuclide#586]
<img width="74" alt="screenshot 2016-07-07 20 46 47" src="https://cloud.githubusercontent.com/assets/3757713/16674229/035a3d50-4484-11e6-8e33-dac11e96212b.png">

**Comment by zardra** [comment]
Got rid of whole toolbar screenshot and now simply show the individual buttons in the order they appear on the toolbar.
