### ISSUE TITLE
Document the Navigation Stack including keybindings

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/nuclide#587]
The nav stack package landed which enables forward/backwards browsing through your navigation history. If code navigation via hyperclick is like traversing hyperlinks, then navigation stack adds the backwards/forwards buttons. Currently these are mapped to `ctrl-,` and `ctrl-.`.

The key differences with packages like last-cursor-position is that it only records navigation moves like goto-definition and tab switching and not cursor moves. Also it restores the window scroll so that it preserves your visual memory of your history.

**Comment by phord** [comment]
On Linux these are bound to Ctrl-Shift-, and Ctrl-Shift-.  

They are assigned backwards, with `Ctrl-<` mapped to *Forward* and `Ctrl->` mapped to *Backward*.

Ctrl-< is already mapped to a core Atom feature.  It must be unmapped to be used as Navigate instead.

Adding this to my keymap.cson fixed these problems:

    '.platform-win32 atom-workspace, .platform-linux atom-workspace':
      'ctrl->': 'nuclide-navigation-stack:navigate-forwards'
      'ctrl-<': 'nuclide-navigation-stack:navigate-backwards'
    'atom-workspace atom-text-editor:not([mini])':
      'ctrl-<': 'unset!'

**Comment by phord** [comment]
This seems to be a dup of #909
