### ISSUE TITLE
Add dynamic filters to File Tree

### ISSUE THREAD

**Issue by nmn** [facebook/nuclide#602]
### Feature Request
It's great to create views for custom sets of files in the File Tree.

It would be great to add an option to create a group based on Rules.

For example:
1. All Files that match a regex.
2. All files currently edited in the Source Control
etc.

If nothing else, would love a view that can quickly show all the currently edited files.

**Comment by nmote** [comment]
The [working sets](https://nuclide.io/docs/features/working-sets/) feature gets you part of the way there. Extending it from manually-defined working sets to "smart" working sets would be awesome.

**Comment by zertosh** [comment]
Closing since this seems resolved by existing functionality.
