### ISSUE TITLE
Compatibility with package show-in-system

### ISSUE THREAD

**Issue by zaaack** [facebook/nuclide#603]
### Issue and Steps to Reproduce
[show-in-system](https://github.com/jerolimov/atom-show-in-system) package not working in nuclide's file tree
![image](https://cloud.githubusercontent.com/assets/5233940/16707434/b787e38c-45ff-11e6-9996-3402726b81df.png)

### Expected Behavior
open finder or explorer or gnome nautilus that contains this file
### Actual Behavior
Nothing,  only message in console 
```
Show in system: Path not found. File not saved?  /Users/z/.atom/packages/show-in-system/lib/show-in-system.coffee:48 

```

### Versions
* Atom: 1.8.0
* Nuclide: 0.150.0
* Client OS: MacOS and Deian sid
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by zertosh** [comment]
That package appears to be deprecated. The file-tree already has a ["Show In Finder" functionality](https://github.com/facebook/nuclide/blob/dd3fb245107946c4ed7a2fb4378a2d7035becfde/pkg/nuclide-file-tree/lib/FileTreeContextMenu.js#L298-L320). Try disabling show-in-system to see if our "Show In Finder" works for you.

**Comment by zaaack** [comment]
@zertosh  Thanks, that works perfectly!
