### ISSUE TITLE
React Native > Start Packager does nothing

### ISSUE THREAD

**Issue by shanecav** [facebook/nuclide#605]
### Issue and Steps to Reproduce
I have a fresh React Native project, with react-native-cli installed globally on Node v6.3.0. I can run `react-native run-ios` from the terminal with no issues - the packager opens in a new terminal window and the simulator runs with no issues.

However, if I try to do "Nuclide React Native: Start Packager" from within Atom, a blank Nuclide "Console" window appears, but it is not titled "React Native Server", and doesn't display anything:

![screen shot 2016-07-10 at 6 11 58 am](https://cloud.githubusercontent.com/assets/120918/16713448/560c8db8-4665-11e6-8bfc-a773a974ae0e.png)

If I click the "Showing: 4 Sources" button, the following window appears:

![screen shot 2016-07-10 at 6 13 35 am](https://cloud.githubusercontent.com/assets/120918/16713454/789ebbd0-4665-11e6-9def-d5b5cbc4995a.png)

When I click the "Start Process" button next to "React Native Packager", the button will very briefly turn to "Stop Process", but then instantly switch back to "Start Process", and nothing happens. I don't see any error messages.

### Expected Behavior
I expect the "React Native Server" window to appear [as detailed here](https://nuclide.io/docs/platforms/react-native/#react-native-server).

### Actual Behavior
I just see a blank Console window, as shown above, and nothing else happens.

### Versions
* Atom: 1.8.0
* Nuclide: 0.150.0
* Client OS: OSX 10.11.5
* Node: 6.3.0
* React Native: 0.29.0
* react-native-cli: 1.0.0

### Additional Details
Installed packages (`apm ls --installed`):
- atom-beautify@0.29.9
- atom-terminal-panel@4.4.4
- autoclose-html@0.23.0
- autocomplete-modules@1.5.2
- autocomplete-paths@1.0.2
- docblockr@0.7.3
- emmet@2.4.3
- file-icons@1.7.16
- haskell-grammar@0.4.0
- highlight-selected@0.11.2
- language-babel@2.31.0
- language-ini@1.16.0
- language-ocaml@1.1.2
- language-thrift@1.0.2
- less-than-slash@0.13.0
- linter@1.11.14
- linter-eslint@7.2.4
- merge-conflicts@1.4.4
- node-debugger@1.7.0 (this is disabled)
- nuclide@0.150.0
- oceanic-next@0.1.2
- pigments@0.31.1
- react@0.15.0
- sort-lines@0.14.0
- todo-show@1.6.0
- tool-bar@1.0.0

**Comment by shanecav** [comment]
I was able to solve this by entering the absolute path to my node executable in Nuclide's settings (under "React Native"). This may be because I'm using nvm? I'm able to see the correct path with `which node` from the terminal, but it seems like Nuclide isn't reaching that same path with `node`.

Although this basically seems to fix the issue, it actually still doesn't make the "React Native Server" window appear as expected. It's still just the basic Console window, but with the expected packager info displayed.

**Comment by schillerGao** [comment]
This problem has  blocked me for a weekend. so sad

**Comment by schillerGao** [comment]
when I closed the Chrome, it worked! hahha
