### ISSUE TITLE
Document Windows Support in Nuclide

### ISSUE THREAD

**Issue by JoelMarcey** [facebook/nuclide#606]
Right now we basically say Nuclide is not supported on Windows. While support is still not as rich as Mac OS X, for example, it has gotten better.

Remote development is close to on par. Local development needs work a bit, but is getting there. Let's get the docs updated to what is the current state of the world.

**Comment by JoelMarcey** [comment]
@vjeux installed Nuclide on Windows last night by following similar instructions like we have for macOS and Linux. 

We should document that we can install on Windows -- see which features are good now since this issue was made and what may need work still.

I also know @Daniel15 is a good resource for Windows (I believe he uses Nuclide on Windows sometimes).

**Comment by Daniel15** [comment]
> I also know @Daniel15 is a good resource for Windows (I believe he uses Nuclide on Windows sometimes).

I use it every day! 😄 

Works wonderfully for remote projects - For my work on www at Facebook, everything works perfectly.

It's not as solid for local projects - OmniSearch is broken for local projects for example (#554). Running Flow locally may work now as Flow has a Windows build, I haven't tested it though.
