### ISSUE TITLE
0.151.0 Update fails to install

### ISSUE THREAD

**Issue by habovh** [facebook/nuclide#608]
### Issue and Steps to Reproduce
Tried to update from 0.150.0 to 0.151.0 from Atom's update section.

### Expected Behavior
Update should work

### Actual Behavior
Update fails and leaves package in an inconsistent state

Message log:
```
Updating to “nuclide@0.151.0” failed.

ENOTEMPTY, rmdir '/Users/Jordan/.atom/packages/nuclide/pkg/nuclide-hg-conflict-resolver'
```

![capture d ecran 2016-07-13 a 11 15 02](https://cloud.githubusercontent.com/assets/4186230/16798293/9ec093e6-48eb-11e6-9842-4492ea21d8e3.png)

![capture d ecran 2016-07-13 a 11 15 13](https://cloud.githubusercontent.com/assets/4186230/16798294/a04b7a1e-48eb-11e6-8428-8b65533652d3.png)

### Versions
* Atom: 1.8.0
* Nuclide: 0.150.0
* Client OS: macOS Sierra 10.12 beta 2 (Build 16A239j)
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (29) /Users/Jordan/.atom/packages
├── atom-css-comb@3.1.0
├── atom-jade@0.3.0
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.2.13
├── blame@0.10.0
├── color-picker@2.2.2
├── emmet@2.4.3
├── expand-region@0.2.4
├── file-icons@1.7.16
├── firewatch-syntax@1.0.1
├── git-history@3.2.0
├── language-babel@2.31.0
├── linter@1.11.14
├── linter-eslint@7.2.4
├── local-history@3.3.0
├── minimap@4.24.7
├── minimap-highlight-selected@4.4.0
├── minimap-selection@4.4.0
├── monokai@0.18.0
├── motepair@0.21.0
├── native-ui@0.18.3
├── nuclide
├── open-recent@5.0.0
├── pretty-json@1.4.4
├── react@0.15.0
├── set-syntax@0.3.0
├── tool-bar@1.0.0
├── tool-bar-main@0.0.9
└── vim-mode@0.65.1

└── (empty)
```

**Comment by habovh** [comment]
# Update

Uninstalling nuclide after this failed update leads to another error:

```
Uninstalling “nuclide” failed.

Failed to delete nuclide: Does not exist
```

![capture d ecran 2016-07-13 a 11 21 07](https://cloud.githubusercontent.com/assets/4186230/16798353/ebf22ee0-48eb-11e6-92dc-3d2130d4d727.png)

**Comment by nmote** [comment]
This looks like an issue with Atom's install/update process, possibly caused by your beta OS but I don't know enough to really speculate on that.

Nuclide never removes its code itself. The update/install/uninstall process is handled by Atom and we have no control over it.
