### ISSUE TITLE
When import type not autocomplete

### ISSUE THREAD

**Issue by crisys11** [facebook/nuclide#609]
### Issue and Steps to Reproduce
When i import a type autocompletion not working

import code
```javascript
import type { Agent } from '/imports/types/Agents';
```
When i use the type nuclide not autocomplete
```javascript
(agent: Agent) => {
    agent.
 }
```
### Expected Behavior
When i type agent. i expect that suggest the attributes of type

### Actual Behavior
when i type agent. nothing happen.

### Versions
* Atom: 1.0.8
* Nuclide: 0.151.0
* Client OS: osx 10.11.5 

### Additional Details
if i open this on webstorm working.
* Installed packages (`apm ls --installed`):
── aligner-php@1.0.0
├── angularjs-styleguide-snippets@0.7.3
├── atom-beautify@0.29.9
├── atom-react-native-autocomplete@0.0.27
├── autocomplete-modules@1.5.2
├── autocomplete-paths@1.0.2
├── autocomplete-php@0.3.7
├── autocomplete-plus@2.31.1
├── csscomb@0.3.1
├── docblockr@0.7.3
├── editorconfig@1.4.1
├── emmet@2.4.3
├── file-icons@1.7.17
├── highlight-line@0.11.1
├── language-javascript-jsx@0.3.7
├── linter@1.11.14
├── linter-csslint@1.3.2
├── linter-eslint@7.2.4
├── linter-js-yaml@1.2.5
├── linter-jshint@2.1.0
├── linter-php@1.2.0
├── linter-phpcs@1.4.0
├── linter-phpmd@1.5.0
├── linter-scss-lint@3.0.4
├── nuclide@0.151.0
├── php-debug@0.2.3
├── pigments@0.31.1
└── project-manager@2.9.7

**Comment by johnislarry** [comment]
Are you actually on atom 1.0.8 or did you mean to type 1.8?  Does your project have any other flow errors?  Running `flow` from the project root might expose something

**Comment by crisys11** [comment]
My version is 1.8.0 if i run flow in root folder "No errors!"

**Comment by johnislarry** [comment]
Hmm ok.  Can you provide a real working code snippet that reproduces this issue?

**Comment by nmote** [comment]
Yeah, I also can't reproduce this. Please include a complete example.

**Comment by crisys11** [comment]
pardon the error is mine, forget to add @flow to the type file and this is the reason for not autocomplete
