### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '/nuclide:'

### ISSUE THREAD

**Issue by vtambourine** [facebook/nuclide#613]
### Issue and Steps to Reproduce
Mounting remote project folder and try to find something via Cmd+P. Red error splash notification appears:
![screen shot 2016-07-15 at 14 20 34](https://cloud.githubusercontent.com/assets/1044363/16874067/76ebd6ac-4a97-11e6-8fee-75b2fecd80f6.png)

### Expected Behavior
No errors appears. Fuzzy search works smoothly.

### Actual Behavior
Error appears when trying to fuzzy search files in the project directory when connected to remote project folder. However, file search seems working.

### Versions
* Atom: 1.8.0
* Nuclide: 0.155.0
* Client OS: Mac OS X 10.11.5
* Server OS (optional): CentOS 6

### Additional Details
Full stack trace available on corresponding Atom issue: https://github.com/atom/fuzzy-finder/issues/233

**Comment by johnislarry** [comment]
Does the error repro when you don't have a remote project added?  We don't use the fuzzy-finder package on the server so I don't think it's related to the remote connection.  It looks like the keybindings for Nuclide's quick-open are the same as atom's fuzzy-finder.  Does the modal that pops up when you use cmd+P or cmd+T look like the screenshots here:

https://nuclide.io/docs/features/quick-open/

**Comment by johnislarry** [comment]
Ok it looks like in the open source version we have this mapping:

cmd+T ---> opens quick-open (the nuclide package for search)
cmd+P ---> opens fuzzy-finder (the atom-provided package for search)

For searching remote projects, you need to use quick-open.  I would also argue that you should use it for local projects as well :)

**Comment by johnislarry** [comment]
I've left some comments on https://github.com/atom/fuzzy-finder/issues/233.  At this point I'm pretty convinced that the fix should be done on the fuzzy-finder side, and the workaround I've written above should work to get you going.  Closing this out now.
