### ISSUE TITLE
Debug remote connection problem: ssh agent failed

### ISSUE THREAD

**Issue by vtambourine** [facebook/nuclide#616]
I have to work with code on various CentOS 6 servers inside corporate network. Usually Nuclide remote folders works well, but sometimes I am facing ssh agent problem. Trying to connect to remote host I have only spinner spinning, and after cancelling the progress I get following red notification error:

```
Unexpected error occurred: [1m[31mYour ssh agent is not running, you will not be able to log into other hosts[0m scripts/nuclide_server_manager.py:377: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6 logger.warn('Failed to clean up old core dumps (%s)', e.message) .
```

I have no idea how to debug this. SSH seems working well, ssh-agent is on, all keys are forwarded. Can you please suggest what can I do to make Nuclide running?
### Versions
- Atom: 1.8.0, 1.9.0-beta
- Nuclide: 0.155.0
- Client OS: MacOS X 10.11.5
- Server OS (optional): CentOS 6

**Comment by johnislarry** [comment]
I think it's likely that https://github.com/facebook/nuclide/commit/56ab72c51a405a5a576466e684b3c074ef924a8e will solve this issue, but it's hard to say for sure.  It'll go out with the next release, which should be today or tomorrow.

**Comment by zertosh** [comment]
The problem is that something is echoing `Your ssh agent is not running, you will not be able to log into other hosts` while Nuclide is trying to ssh. Maybe something in your `bashrc`? Unfortunately, with the way we exchange keys, nothing can output anything, or it'll throw off SFTP.

**Comment by vtambourine** [comment]
@zertosh this is quite possible. Simple `ssh host` doesn't show that message. What command Nuclide run to establish connection? Can I run that command from terminal to see the output?

**Comment by vtambourine** [comment]
I tried to cleanup bash dotfiles to remove all possible output. Now I get just Nuclide error:
```
Unexpected error occurred: scripts/nuclide_server_manager.py:377: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6 logger.warn('Failed to clean up old core dumps (%s)', e.message).
```
