### ISSUE TITLE
Project reloaded with empty buffers (nuclide:/<host>/ in path) on Windows

### ISSUE THREAD

**Issue by darrenkenny** [facebook/nuclide#619]
### Issue and Steps to Reproduce
When I re-load Atom (1.8 or 1.9beta) after exiting, the buffers are re-opened, but the path
appears to be "nuclide:/<host>/<path>" instead of "nuclude://<host>/path".

On Windows, to reproduce, simply:
* connect to a remote project
* open several buffers
* reload the Atom window
* the buffers are re-opened at start-up, but are empty.

### Expected Behavior

I would have expected the path to be "nuclide://<host>/" so that the buffers are correctly
reloaded.

### Actual Behavior
Buffers loaded are empty, and the path in the tooltip appears to be "nuclude:/<host>/<path>"
which I'm guessing is why they get opened empty.

### Versions
* Atom: 1.8 or 1.9beta
* Nuclide: 1.55
* Client OS: Windows
* Server OS (optional): Ubuntu

**Comment by shushz** [comment]
Yes, I can repro that. Thanks for reporting!

**Comment by shushz** [comment]
Fixed by https://github.com/facebook/nuclide/commit/d353e32a3cd9c5d5a79c6bfa8e7ba1a239c55599
