### ISSUE TITLE
Outline view doesn't support describe.skip or it.skip

### ISSUE THREAD

**Issue by tleunen** [facebook/nuclide#620]
### Issue and Steps to Reproduce
I have JS mocha tests and the outline view is reporting everything correctly, except `describe.skip` and `it.skip`.

Note that `describe.only` and `it.only` are both supported.

### Expected Behavior
The outline view should display `describe.skip` and `it.skip`.

### Actual Behavior
The outline view does not display `describe.skip` and `it.skip`.

### Versions
* Atom: 1.8.0
* Nuclide: 0.155.0
* Client OS: MacOS

**Comment by nmote** [comment]
Feel free to put up a PR, should be trivial given the machinery I've created to support `it.only`, etc.
