### ISSUE TITLE
Create_package

### ISSUE THREAD

**Issue by ev1stensberg** [facebook/nuclide#624]
I'm trying to figure out how to create a new package inside `pkg`. Found this, but don't know how to use it. Do I need to run on an dev server or anything in order for it to work?

![skjermbilde 2016-07-22 kl 20 32 37](https://cloud.githubusercontent.com/assets/16735925/17067343/a07b321a-504b-11e6-8d7e-56f3ec2831eb.png)

**Comment by shushz** [comment]
Not on the dev server, just run it from the `nuclide` directory.
![screen shot 2016-07-22 at 11 58 18 am](https://cloud.githubusercontent.com/assets/8860623/17068062/9d888e6a-5003-11e6-8dac-815a440d530e.png)

**Comment by ev1stensberg** [comment]
Great, thanks @shushz ! 💙
