### ISSUE TITLE
Error connecting to AWS EC2 remote project. "bash: nuclide-start-server: command not found"

### ISSUE THREAD

**Issue by mengchantang** [facebook/nuclide#625]
### Issue and Steps to Reproduce

I am new in web developer and a occasional programmer for design work. Now I am setting up a free EC2 server on AWS. At the moment, I keep getting this message upon attempting to connect to the remote Nuclide server. 
![image](https://cloud.githubusercontent.com/assets/19785356/17077642/bdc34caa-50a4-11e6-8a99-a0a74d486530.png)

So I think I have solved most of the problem now:
Python, NPM, Node all updated to the Nuclide requirement. Watchman installed, version 4.6.0.
![image](https://cloud.githubusercontent.com/assets/19785356/17077661/a7346f86-50a5-11e6-86c5-3db39b5c079b.png)

Nuclide is also installed on the server side.
![image](https://cloud.githubusercontent.com/assets/19785356/17077748/acd4b33e-50a9-11e6-8740-421631f0a1e8.png)

Then I tried to connect from Nuclide with settings like this which leads me to the opening problem.
![image](https://cloud.githubusercontent.com/assets/19785356/17077667/1573b0d8-50a6-11e6-8e3d-e2badb6e1928.png)

These are the ports I opened from AWS EC2.
![image](https://cloud.githubusercontent.com/assets/19785356/17077671/4d727c1c-50a6-11e6-8fca-0bd16f37b6ee.png)
### Expected Behavior

Nuclide connects to the remote project server.
### Actual Behavior

Unexpected error occurred: bash: nuclide-start-server: command not found .
Original error message:
 bash: nuclide-start-server: command not found
![image](https://cloud.githubusercontent.com/assets/19785356/17077642/bdc34caa-50a4-11e6-8a99-a0a74d486530.png)
### Versions
- Atom: 1.8.0
- Nuclide: 0.157.0
- Client OS: OS El Capitan
- Server OS (optional):
### Additional Details
- Installed packages (`apm ls --installed`):

**Comment by shushz** [comment]
Could it be that you forgot to pass the `-g` param to the `npm install -g nuclide` command on the remote host?
You can also try giving the full absolute path to the `pkg/nuclide-server/nuclide-start-server` under the nuclide directory in the connection dialog.

**Comment by mengchantang** [comment]
Thanks! The full path solution worked. Now I have a new set of problems upon successful connection, this message showed up:

![image](https://cloud.githubusercontent.com/assets/19785356/17080423/d10bd7ac-50fc-11e6-877d-3c6fbe5df35d.png)

Message in full:

You just connected to a remote project / but we recommend you remove this directory now because crucial features like synced remote file editing, file search, and Mercurial-related updates will not work.
Watchman Error:Remote Error: unable to resolve root /: cannot watch "/" processing message {"protocol":"service_framework3_rpc","type":"call","method":"FileWatcherService/watchDirectoryRecursive","id":9,"args":{"directoryPath":"/"}} "Error: unable to resolve root /: cannot watch \"/\"\n at BunserBuf. (/usr/local/lib/node_modules/nuclide/node_modules/fb-watchman/index.js:95:23)\n at emitOne (events.js:96:13)\n at BunserBuf.emit (events.js:188:7)\n at BunserBuf.process (/usr/local/lib/node_modules/nuclide/node_modules/bser/index.js:289:10)\n at /usr/local/lib/node_modules/nuclide/node_modules/bser/index.js:244:12\n at _combinedTickCallback (internal/process/next_tick.js:67:7)\n at process._tickCallback (internal/process/next_tick.js:98:9)"

Can't think of why. I tried the following 
$ whereis watchman
watchman: /usr/local/bin/watchman
so it is in my $PATH

**Comment by shushz** [comment]
Nuclide relies on Watchman for the file system related notifications. If watchman is configured that it can't watch a certain directory, Nuclide will display the message above.
Please try mounting a non-root directory and also double check your watchman configuration.

**Comment by shushz** [comment]
Did it help?

**Comment by mengchantang** [comment]
Sorry have been swamped by other things. Will check this next week. Thanks for the help so far.

**Comment by junpengxiao** [comment]
I recently met a similar issue when setting nuclide server. nuclide-start-server cannot be found. If I use the full path, then the log shows node cannot be found.

I am not sure if this is because I have both .profile and .bashrc. It seems environment path isn't exported correctly.

If someone met the same issue as I did, it is better to just add brew path into system environment.
```
sudo emacs /etc/environment
# Add brew bin (the default one is /home/username/.linuxbrew/bin) into the PATH variable
sudo reboot
```

This will solve the issue.

**Comment by a2xchip** [comment]
Absolute path to nuclide-server will not help cause then you will got something like ```no such command nohup node``` it causes because of using non-standard path variables and non-interactive mode

To test variables path in non-interactive mod fast use:
```
ssh remote.server 'bash -l -c "node"'
# or
ssh remote.server 'bash -l -c "nuclide-start-server"'
```

my errors was caused by nvm node & npm installation all i did is relocated ```~/.bashrc``` includes of nvm putting them before script exit

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# script exits after lines below if mode noninteractive
[ -z "$PS1" ] && return

```

or 

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

other files like ~/.bash_profile are not sourced during non-interactive mode

**Comment by theFuzzyWarble** [comment]
I know this is an old post but thank you a2xchip, your last post led me to fix an issue I was having the past few days!
