### ISSUE TITLE
[feature request] Ability for nuclide-bookshelf to restore the correct atom panes configs

### ISSUE THREAD

**Issue by chenglou** [facebook/nuclide#626]
Right now bookshelf restores everything in a single pane. It'd be nice if my tabs & pane configs were remembered.

**Comment by shushz** [comment]
I think this design decision was done in the spirit of 80/20. Persisting a list of files is much simpler than layout and, unless you use split panes, the result is nearly indistinguishable.
Mostafa, the developer of it, would know more, but he's on PTO for the next month and I don't want to tag him :-)

**Comment by mostafaeweda** [comment]
I'm back and @shushz is pretty accurate, Atom has no easy API / way to save and restore pane layout, hence, I went ahead without it, but will probably add it in the future - thanks for your feedback.

**Comment by matthewwithanm** [comment]
I feel like this _should_ work (but it throws random errors):

```js
const serialized = atom.workspace.paneContainer.serialize();
// later...
atom.workspace.paneContainer.deserialize(serialized, atom.deserializers);
```

I wonder if the fact that it doesn't is an Atom bug or just not an intended usage.

**Comment by jgebhardt** [comment]
I like the idea, but this is not directly actionable right now, so I'm closing this issue. Feel free to open a PR! :-)
