### ISSUE TITLE
Nuclide reports React as not covered by Flow

### ISSUE THREAD

**Issue by cdchambers** [facebook/nuclide#627]
### Issue and Steps to Reproduce
I have a vanilla setup of Nuclide and Flow with a sample app.

`import React from 'react';

type MyComponentProps: {
  name: string,
}

class MyComponent extends React.Component<MyComponentProps> {
  render() {
    return (<div>this.props.name</div>);
  }
}`

### Expected Behavior
I would expect Nuclide to report 100% type coverage in the diagnostics pane.

### Actual Behavior
However, I got a warning saying the line below is not covered by Flow.
class MyComponent extends React.Component<MyComponentProps>

Is this a bug in Nuclide?

### Versions
* Atom: 1.8.0
* Nuclide: latest
* Client OS: OSX Yosemite
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by nmote** [comment]
We simply surface the data provided by Flow. I have noticed this same issue myself but I don't know the reason behind it. If you would like to pursue it, please re-open on https://github.com/facebook/flow
