### ISSUE TITLE
[Missing Feature] Open in new window. 

### ISSUE THREAD

**Issue by v3ss0n** [facebook/nuclide#629]
In atom default file tree , there is an option for opening in new window. it is lacking in nuclide.

**Comment by shushz** [comment]
Yes, Nuclide does not have a complete parity with Atom in its file-tree functionality. And in an IDE I feel such a feature is somewhat less necessary than in a text editor.
But we accept pull requests.

**Comment by v3ss0n** [comment]
I am in a hurry for a deadline.
I will look into it later.
For Linux user with tiling layout , it is much more useful vs pane splits. Can open multiple projects in Master-Slave Tiling window and letting wm manage for it is very powerful.
