### ISSUE TITLE
[windows] Nuclide fails to open remote files when restoring workspace state

### ISSUE THREAD

**Issue by billschaller** [facebook/nuclide#631]
### Issue and Steps to Reproduce
Use Nuclide on Windows
Open a file from a remote project.
Close Atom.
Reopen Atom. 

### Expected Behavior
The file should reopen properly when the IDE starts up.

### Actual Behavior
A tab for the file is opened, but the path looks like nuclide:\path\to\file.js instead of nuclide://path/to/file.js

### Versions
* Atom: 1.8.0
* Nuclide: 0.157.343xxxx
* Client OS: Windows
* Server OS (optional): CentOS 7

### Additional Details
The issue here is that when the workspace is serialized, each editor serializes with a TokenizedBuffer. Even though a NuclideTextBuffer and RemoteFile are created for remote files when you open them initially, the serialization via TokenizedBuffer doesn't store the necessary information to reliably reopen them when the IDE is restarted. 

When an editor pane is deserialized, it runs the TokenizedBuffer deserializer, which reopens each file as a regular TextBuffer with a File instead of a NuclideTextBuffer with a RemoteFile. Since the OS is Windows, the File object converts the nuclide:// URI into a windows file path, completely breaking the remote file functionality. I'm not sure how this works on Linux/Mac, but I assume there's a URI handler somewhere that knows to open the file correctly on those platforms when it has a nuclide:// URI.

To fix this, you probably need to create a NuclideTokenizedBuffer with a serializer/deserializer that recognizes the nuclide:// uri and opens a NuclideTextBuffer accordingly.

**Comment by billschaller** [comment]
Gah, this is a dupe of https://github.com/facebook/nuclide/issues/619 but I think the additional info might be helpful...

**Comment by billschaller** [comment]
@shushz ^

**Comment by shushz** [comment]
Yeah, the thing is - the remote connection might not be established yet at the moment the deserialization is performed. So once it is, there supposed to be a logic that goes over the editors and swaps the buffer and the file instances.
My guess, would be that this logic does not detect the paths properly because they were in the mean time somehow deformed. I'll try to look at that today.

**Comment by billschaller** [comment]
Can confirm - fixed in latest.
