### ISSUE TITLE
[bug] Sidebar sticks to cursor

### ISSUE THREAD

**Issue by stefanwuest** [facebook/nuclide#633]
### Issue and Steps to Reproduce
Trying to move the sidebar, it keeps sticking to my cursor until I close the application. I have found no way to "re-attach" it, so I have to restart Atom everytime. It seems to be a Nuclide issue — if I remove the Nuclide package, everything works fine.

### Versions
* Atom: 1.8.0
* Nuclide: 0.158.0
* Client OS: MacOS X 10.11.5

**Comment by bottledwalter** [comment]
We're having trouble repro'ing this. Are you able to consistently repro it?

The expected behavior is that the sidebar (the panel that contains the file tree) is merely resizable, but shouldn't be movable.

**Comment by stefanwuest** [comment]
Sorry, maybe I didn't express myself in the right way. I'm trying to resize the sidebar. Here's a screen capture. The cursor keeps sticking to the edge of the sidebar and won't let go.
![nuclide-sidebar-bug](https://cloud.githubusercontent.com/assets/5959858/17203982/012c4a58-54a3-11e6-80ce-6ae5a8799ba5.gif)

**Comment by matthewwithanm** [comment]
Hey @stefanwuest! We have another thread going on about this (#667) so I'm going to close this one. If you could help us get a repro, that would be SUPER appreciated!
