### ISSUE TITLE
 toggle distraction free mode

### ISSUE THREAD

**Issue by moogus** [facebook/nuclide#637]
No Issue I love this atom addon, but would appreciate a shortcut to toggle distraction free mode

**Comment by shushz** [comment]
You can configure one for yourself in Menu --> Atom --> Keymap. Something like:
```
'atom-workspace':
  'ctrl-shift-d': 'nuclide-distraction-free-mode:toggle'
```

**Comment by moogus** [comment]
amazing thanks
