### ISSUE TITLE
Empty error message

### ISSUE THREAD

**Issue by maxpv** [facebook/nuclide#640]
### Issue and Steps to Reproduce
After following the [official guidelines](https://nuclide.io/docs/features/remote/) for remote development, I came up with that error when I try to connect to my server :
![Unexpected error occured: 
Original message:](https://i.imgsafe.org/cf716d699d.png)

### Versions
* Atom: 1.8.0
* Nuclide: 0.158.0
* Client OS: Ubuntu 16.04 (live USB)
* Server OS (optional): CentOS 7.2

### Additional Details
* Installed packages (`apm ls --installed`):
nuclide@0.158.0
* Things I've checked : 
 * Credentials
  * Version compatibility 
  * Access rights
  * Ports on server

**Comment by bottledwalter** [comment]
The error message seems to originate [here](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-remote-projects/lib/notification.js#L43) which suggests you've got some ssh connection issue in your setup. Hope that helps!

**Comment by maxpv** [comment]
Thanks for your answer but that doesn't help, I triple checked my credential and my ssh connection. Everything is fine on that side. 

I randomly have some unknown command `nuclide-start-server`, by the way.
