### ISSUE TITLE
[nuclide-file-tree] Slows down startup time

### ISSUE THREAD

**Issue by boopathi** [facebook/nuclide#65]
![screenshot 2015-06-20 13 58 05](https://cloud.githubusercontent.com/assets/294474/8266611/6cab281c-1755-11e5-8e74-52d031821052.png)

Here it took almost 3s. And most of the time its usually more than a second.

**Comment by bolinfest** [comment]
We have made some critical fixes that should improve this. Can you try again with the latest Nuclide?

* Watchman performance fix: https://github.com/facebook/nuclide/commit/2318277b3d84a8868ba69d4fd761d27a46e10fd7
* More efficient use of React in the file tree: https://github.com/facebook/nuclide/commit/3d55c9037d1c08cb6c5e1cce457b01d1dbcc5648

(Note the React fix did not make it into Nuclide v0.0.24, but it will make it into the next versioned release.)

/cc @ssorallen

**Comment by ssorallen** [comment]
The nuclide-file-tree package has been rewritten since this issue was open. I'm going to close this, but feel free to re-open if you see problems with the new version.
