### ISSUE TITLE
flow not working with atom 1.9.0

### ISSUE THREAD

**Issue by zaaack** [facebook/nuclide#653]
### Issue and Steps to Reproduce
After I upgrade Atom editor to 1.9.0, I suddenly find out that the flow check or any flow hints are not working anymore, I tried many method(at first I thought there were conflicts between nuclide and eslint), until switch back 1.8.0 version, finnaly works again.
### Expected Behavior
Flow lint message and autocomplete

### Actual Behavior
Nothing, no error, no working.

### Versions
* Atom: 1.9.0
* Nuclide: 0.158.0
* Client OS: OSX EI Capitan 10.11.5 
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

Built-in Atom Packages (89)
├── about@1.5.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.1
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.31.0
├── autocomplete-snippets@1.11.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.41.0
├── bracket-matcher@0.82.1
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.22.0
├── exception-reporting@0.38.1
├── find-and-replace@0.198.0
├── fuzzy-finder@1.3.0
├── git-diff@1.1.0
├── go-to-line@0.31.0
├── grammar-selector@0.48.1
├── image-view@0.58.0
├── incompatible-packages@0.26.1
├── keybinding-resolver@0.35.0
├── language-c@0.52.1
├── language-clojure@0.21.0
├── language-coffee-script@0.47.0
├── language-csharp@0.12.1
├── language-css@0.36.2
├── language-gfm@0.86.0
├── language-git@0.13.0
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.22.0
├── language-javascript@0.119.0
├── language-json@0.18.0
├── language-less@0.29.3
├── language-make@0.22.2
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.35.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.45.0
├── language-ruby@0.68.5
├── language-ruby-on-rails@0.25.0
├── language-sass@0.52.0
├── language-shellscript@0.22.3
├── language-source@0.9.0
├── language-sql@0.21.1
├── language-text@0.7.1
├── language-todo@0.28.0
├── language-toml@0.18.0
├── language-xml@0.34.8
├── language-yaml@0.26.0
├── line-ending-selector@0.5.0
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.64.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.3.2
├── one-light-syntax@1.2.0
├── one-light-ui@1.3.2
├── open-on-github@1.2.0
├── package-generator@1.0.0
├── settings-view@0.238.0
├── snippets@1.0.2
├── solarized-dark-syntax@1.0.2
├── solarized-light-syntax@1.0.2
├── spell-check@0.67.1
├── status-bar@1.4.0
├── styleguide@0.46.0
├── symbols-view@0.113.0
├── tabs@0.98.0
├── timecop@0.33.1
├── tree-view@0.208.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (58) /Users/z/.atom/packages
├── AtomicChar@0.3.11
├── Remote-FTP@0.8.3
├── activate-power-mode@0.7.0
├── atom-beautify@0.29.10
├── atom-image-resize@0.3.0
├── atom-random-tips@0.7.0
├── atom-sync@0.7.3
├── atom-ternjs@0.14.2
├── atom-typescript@10.1.5
├── autocomplete-modules@1.5.2
├── autocomplete-paths@1.0.2
├── autocomplete-python@1.8.4
├── browser-plus@0.0.67
├── build@0.65.0
├── color-picker@2.2.2
├── docblockr@0.7.4
├── editorconfig@1.4.1
├── emmet@2.4.3
├── file-icons@1.7.17
├── git-status@0.3.4
├── git-time-machine@1.5.3
├── global-background@0.4.0
├── highlight-selected@0.11.2
├── hyperclick@0.0.37
├── jshint@1.8.5
├── jumpy@3.0.3
├── language-babel@2.32.1
├── linter@1.11.14
├── linter-eslint@7.2.4
├── linter-flow-plus@3.1.0
├── linter-pep8@1.3.0
├── linter-pylama@0.5.6
├── linter-pylint@1.2.1
├── linter-scss-lint@3.0.4
├── linter-stylelint@3.0.2
├── markdown-preview-plus@2.4.0
├── markdown-scroll-sync@2.1.2
├── markdown-writer@2.5.0
├── merge-conflicts@1.4.4
├── minimap@4.24.7
├── minimap-autohide@0.10.1
├── node-debugger@1.7.0
├── nuclide@0.158.0
├── pigments@0.31.2
├── project-manager@2.9.7
├── python-tools@0.6.8
├── qolor@0.2.2
├── react@0.15.0
├── regex-railroad-diagram@0.16.0
├── remote-sync@4.1.2
├── rest-client@1.2.0
├── script@3.8.3
├── show-in-system@0.4.0
├── sync-settings@0.7.2
├── tasks@2.6.0
├── terminal-plus@0.14.5
├── todo-show@1.7.0
└── toggle-slash@1.0.14

└── (empty)

**Comment by abalhier** [comment]
Same here for the same versions of Atom and Nuclide

**Comment by flegall** [comment]
Same problem here.

**Comment by despairblue** [comment]
Do you mean the type hints are not there at all?

**Comment by zaaack** [comment]
@despairblue yes，nothing about flow.

**Comment by peterhal** [comment]
Atom 1.9 breaks many Nuclide features. We are actively working on fixing them. Expect a Nuclide compatible with Atom 1.9 in a couple of weeks. 

Until then Atom 1.8 is the only supported version of Atom that Nuclide is compatible with.

**Comment by zaaack** [comment]
@peterhal Ok，thanks for your great work :   ) .

**Comment by alvaromb** [comment]
I can't get any autocompletion after upgrading to Nuclide 160 and Atom 1.9, even in Atom's safe mode. Can this issue be related?
