### ISSUE TITLE
Nuclide doesn't seem to respect .flowconfig ignores

### ISSUE THREAD

**Issue by justinwiley** [facebook/nuclide#654]
### Issue and Steps to Reproduce
I created a flow config containing:
```
[ignore]
<PROJECT_ROOT>/__tests__/.*
```

### Expected Behavior
Flow syntax highlighting and diagnostic warnings do not show up when viewing a file in `<PROJECT_ROOT>/__tests__/`

### Actual Behavior
Flow syntax highlighting and diagnostic warnings show up

### Versions
* Atom: 1.9.0
* Nuclide: 0.158.0
* Client OS: Mac OS Capitan 10.11.5
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

```
├── atom-beautify@0.29.10
├── atom-language-rust@0.8.1
├── atom-typescript@10.1.5
├── language-groovy@0.6.0
├── language-rust@0.4.6
├── linter@1.11.14
├── linter-eslint@7.2.4
├── nuclide@0.158.0
└── react@0.15.0

└── (empty)
```

**Comment by peterhal** [comment]
See #653. Nuclide is not compatible with Atom 1.9.
