### ISSUE TITLE
[nuclide-swift] Syntax Highlighting and Code Completion Unavailable

### ISSUE THREAD

**Issue by Ben-G** [facebook/nuclide#655]
### Issue and Steps to Reproduce

When building a Swift package syntax highlighting and code completion are not working, even though the build completes successfully.

![screen shot 2016-08-03 at 10 47 05 am](https://cloud.githubusercontent.com/assets/1423068/17375846/aa7232a8-5967-11e6-85d5-2a17dd46f2ec.png)

The source code from which I'm building is available in [this PR](https://github.com/ReSwift/ReSwift/pull/140).

### Expected Behavior
Syntax highlighting and code completion should be available for Swift source files that are part of the package.

### Actual Behavior
Syntax highlighting and code completion are not available.

### Versions
* Atom: 1.9.2
* Nuclide: Trunk
* Client OS: OS X 10.11.5
* Swift toolchain: Xcode 8 Beta 4 toolchain

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── git-blame@0.4.8
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.32.1
├── language-elm@1.5.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.4
├── linter-pep8@1.3.0
├── merge-conflicts@1.4.4
├── nuclide@0.159.0
├── sort-lines@0.14.0
└── tool-bar@1.0.0
```

**Comment by Ben-G** [comment]
Forgot to mention sourcekitten:

Using version `0.13.0`and location is `/usr/local/bin/sourcekitten`

**Comment by modocache** [comment]
@Ben-G thanks for the feedback! A few suggestions to troubleshoot:

- Off the bat, it's worth mentioning that nuclide-swift doesn't currently provide any syntax highlighting. The highlighting in the screenshots from [the documentation](https://nuclide.io/docs/languages/swift/) comes from a different Atom package called "language-swift". nuclide-swift will soon include "language-swift" as a "recommended package" -- in the meantime, you might want to try installing it yourself (since I usually use it in tandem with developing Swift support, it might be related to your issue).
- You'll need to build your project before Nuclide can provide autocompletion suggestions. Have you built your project via the Nuclide toolbar?

I'll try building ReSwift locally to see if I experience the same error.

**Comment by Ben-G** [comment]
@modocache Thanks for the quick response! Your comment on syntax highlighting makes sense!

Actually code completion does work. I was thrown off by the fact that I don't get any suggestions until I input a character after a `.` (in combination with the lack of syntax highlighting).

E.g. typing `self.` will not bring up any suggestions, but `self.s` will show suggestions. My bad!

Great work so far 👍

**Comment by modocache** [comment]
Awesome!! Thanks for the great bug report.

**Comment by modocache** [comment]
@Ben-G Hey, so autocompletion and everything is working, huh? How's the performance? Is it mostly accurate? How are the snippets and tab support working?

**Comment by Ben-G** [comment]
@modocache Yep, it is working!

**Performance/Accuracy**

So far it seems very accurate. Performance is fine overall; there seem to be some freezes here and there but I can’t reliably determine a pattern that triggers them.

**Autocompletion**

It’s super cool that there’s autocompletion for infix operators! The inlining of documentation in the suggestions is working well, too.

One of the biggest “issues” right now is the lack of autocompletion that would show all members of an instance as soon as the “.” is typed. E.g. having suggestions when typing `self.` would be very useful. I’m not sure if that’s only happening for my project or if that’s a known limitation as of know. As soon as I type an additional character (e.g. `self.s`) the suggestions work great.

**Snippets/Tabs**

Regarding snippets: I’m assuming you are referring to the standard Atom/Nuclide feature? I’ve only used Atom a tiny bit and haven’t used Nuclide before so I haven’t used the snippets features yet.

Regarding tabs: are you referring to formatting or support for working in multiple tabs?

**Other**

Also type hints don’t seem to be working for me (but might also be user error).

As mentioned, really new to Nuclide so I might just be missing some of the features. 

**Really great work so far, thank you!** 💯

**Comment by modocache** [comment]
By "snippets", I meant the fact that, when autocompleting a method, you can use the tab key to select each parameter:

1. Type `pokemon.att`, use the up/down keys to select the method you want to autocomplete, then press Enter.
2. The cursor will be placed at the spot where you can type the first parameter to the method.
3. Press Tab to go to the next parameter.

> Also type hints don’t seem to be working for me

Yeah, those aren't done yet. I'm trying to figure out why [I can't get SourceKitten demangling to work](https://twitter.com/modocache/status/760493238620946432), which I need for that feature. But soon!
