### ISSUE TITLE
Hack code diagnostics bug

### ISSUE THREAD

**Issue by onysko** [facebook/nuclide#657]
## Code Diagnostics behaviour
Some strange things happen with code diagnostics.

After opening project everything works fine (I see my error list works fine). Screenshot of normal behaviour:

![image](https://cloud.githubusercontent.com/assets/7703953/17401460/7ef3c872-5a56-11e6-9724-5589c96d380a.png)

But after 2 mins(or less or more) of coding nuclide freezes and stops working. I can't see code diagnostic updates after file saving (error list always stays empty or shows only last error/errors).
After that I can see my errors again only after full restart of Atom (with closing all the tabs only!!). Screenshot of this behaviour:

<img width="738" alt="screen shot 2016-08-04 at 15 23 12" src="https://cloud.githubusercontent.com/assets/7703953/17401647/6d333e8c-5a57-11e6-8988-734340c46c17.png">

### Environment
Atom (v 1.9.2) and Nuclide (v 0.158.0) on OSX El Capitan (v 10.11.5).
HipHop VM 3.13.1 (installed via brew).

**Comment by onysko** [comment]
After freezing I see one new Handles Child Process 'hh_client --json --retries 0 --retry-if-init false --from nuclide /path/to/project/'. And also code coverage tools freezed

**Comment by peterhal** [comment]
There are known incompatibilities between Atom 1.9 and Nuclide. We are actively working on them.

In the meantime, Atom 1.8.0 is the version of Atom compatible with Nuclide.
