### ISSUE TITLE
Nuclide datatip is to small to see anything but the first symbol

### ISSUE THREAD

**Issue by sigurdsvela** [facebook/nuclide#658]
### Issue and Steps to Reproduce
When hovering over a variable to get the data tip, it shows up, but with a very small with, see screenshot.

![screen shot 2016-08-04 at 13 56 59](https://cloud.githubusercontent.com/assets/5571884/17405273/2c6e44f2-5a5f-11e6-9ee1-33b43c46ed4e.png)

### Expected Behaviour
It should be wider

### Actual Behaviour
It's to narrow

### Versions
* Atom: 1.9.2
* Nuclide: 0.158.0
* Client OS: Mac OS X, 10.11.6

### Additional Details
* Installed packages: (Nuclide and it's recommended packages only) 
```
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.32.1
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── nuclide@0.158.0
├── sort-lines@0.14.0
└── tool-bar@1.0.0
```

**Comment by peterhal** [comment]
There are several known incompatibilities with Atom 1.9 and nuclide. We are actively working on them.

The currently supported version of Atom with Nuclide is 1.8.0.
