### ISSUE TITLE
Trying out Nuclide, Linting / Flow not working

### ISSUE THREAD

**Issue by stoplion** [facebook/nuclide#661]
Installed Nuclide for Atom, disabled the linter per instructions and also I've installed the linter (?) per instructions. Also I've generated an .eslintrc.js..

```
 module.exports = {
    "extends": "airbnb",
    "plugins": [
   "react"
  ]
};
```

..in my package.json, I have the following linters

```
"eslint": "^2.13.1",
    "eslint-config-airbnb": "^10.0.0",
    "eslint-plugin-babel": "^3.3.0",
    "eslint-plugin-import": "^1.12.0",
    "eslint-plugin-jsx-a11y": "^2.0.1",
    "eslint-plugin-react": "^6.0.0",
```

Using Flow

```
   @flow
var foo: number = '123424';
```

Using Flow *\* sometimes *\* works. Sometimes Flow works when I start Atom (and restart Flow server), other times not at all.

Using Lint Doesn't seem to work. 

I have eslint install globally. `v3.2.2`
Atom `1.9.6`

**Comment by nmote** [comment]
Nuclide doesn't have compatibility with ESLint built in. For that, we recommend the `linter-eslint` Atom package which will run ESLint and give us the messages to display.

Does Flow work from the command line? Can you paste the `nuclide-flow` section of your `~/.atom/config.cson` file, the version of Flow, and all the info requested in the issue template that appears when you click "new issue?"

Also note that we currently only support Atom 1.8, though I'm not aware of an issue like this with Atom 1.9.
