### ISSUE TITLE
File tree does not resize narrower than longest file name

### ISSUE THREAD

**Issue by kmiyashiro** [facebook/nuclide#665]
### Issue and Steps to Reproduce
Starting around 3 or 4 versions ago, the file tree would not resize smaller than the widest filename in the tree, nor would it scroll/overflow. If I tried to resize the file tree to be narrower, it would just push the left side of the tree past the window boundary and there would be no way to view it since it did not scroll horizontally.

As of 0.160, I can now resize the file tree, but if I resize it to be narrower than the widest filename, I cannot resize it to be wider again because I can't "grab" the edge anymore. I suspect this is because the file tree is still setting its width to be the size of the widest filename and is blocking the mouse from clicking on the edge of the pane. See screenshot for evidence.

Disabling Nuclide and using atom-file-tree works as expected.

![screen shot 2016-08-09 at 3 35 00 pm](https://cloud.githubusercontent.com/assets/71852/17536179/f8c8093e-5e47-11e6-893b-ac203a8f1041.png)

### Expected Behavior
Resize file tree pane without issues

### Actual Behavior
Cannot resize file tree, cannot click/drag on pane divider.

### Versions
* Atom: 1.9.7
* Nuclide: 0.160.0
* Client OS: OS X 10.11.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (22) /Users/kelly/.atom/packages
├── atom-beautify@0.29.10
├── atom-jade@0.3.0
├── color-picker@2.2.2
├── git-plus@5.16.2
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.32.2
├── language-ember-htmlbars@0.3.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-eslint@7.2.4
├── linter-jshint@2.1.0
├── linter-jsonlint@1.3.0
├── linter-ruby@1.2.2
├── merge-conflicts@1.4.4
├── nuclide@0.160.0
├── react@0.16.0
├── sort-lines@0.14.0
├── sync-settings@0.7.2
└── tool-bar@1.0.1

└── (empty)
```

**Comment by matthewwithanm** [comment]
Hey @kmiyashiro! This is an issue that was introduced by Atom 1.9 (we currently support 1.8).

Having said that, this should be fixed by 4e70e59930e1cdc7b75808f31a457076aec6642d and I'm putting together a release that includes that now.

**Comment by matthewwithanm** [comment]
Alright, v0.161.0 is out! Let me know if you still have issues (:

**Comment by kmiyashiro** [comment]
@matthewwithanm 🎉  thanks, that does indeed fix it! I think setting `overflow: auto` might be better to allow horizontal scrolling in the file tree, but this fixes my main problem.
