### ISSUE TITLE
Side bar readjusting on new patch

### ISSUE THREAD

**Issue by laynef** [facebook/nuclide#667]
### Issue and Steps to Reproduce

Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
1. Download package (Nuclide 0.161.0

When resizing side bar (the tree), it never stops adjusting and will not be able to reset the position you want. 
### Expected Behavior

Tell us what should happen.

When resizing the side bar (if I want it smaller or bigger), it should set at the position I put it in.
### Actual Behavior

Tell us what happens instead.

When resizing the side bar it continues to readjust and you can not access your open file coding window. Until you close the app, then the tree (side bar) is set to the position you last had it on.

I shouldn't have to close the app when I'm resizing the side bar to keep it at that position.
### Versions
- Atom: 1.9.8
- Nuclide: 0.161.0 (latest patch)
- Client OS: OS X El Capitan Version 10.11.6

Atom    : 1.9.8
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

apm  1.10.0
npm  2.13.3
node 0.10.40
python 2.7.10
git 2.9.1
### Additional Details
- Installed packages (`apm ls --installed`):

├── api-docs@0.0.6
├── ask-stack@2.2.0
├── atom-alignment@0.12.1
├── atom-beautify@0.29.10
├── atom-bootstrap4@1.4.0
├── atom-html-preview@0.1.22
├── atom-terminal-panel@4.4.4
├── auto-detect-indentation@1.1.0
├── autoclose-html@0.23.0
├── autosave-plus@0.5.2
├── color-picker@2.2.2
├── emmet@2.4.3
├── file-header@1.9.0
├── file-icons@1.7.18
├── file-types@0.5.4-p1
├── find-and-replace@0.201.0
├── git-plus@5.16.2
├── highlight-selected@0.11.2
├── javascript-snippets@1.2.1
├── linter@1.11.16
├── minimap@4.24.7
├── node-debugger@1.7.0
├── nuclide@0.161.0
├── open-in-browser@0.4.7
├── open-recent@5.0.0
├── pdf-view@0.50.0
├── pigments@0.31.2
├── project-plus@0.9.0
├── react@0.16.0
├── script@3.8.3
├── set-syntax@0.3.0
└── todo-show@1.7.0

This is the full .gif, if you watch it all the way through you will see that I must quit the app then reopen it to set the side bar position

![nuclide sidebar bug](https://cloud.githubusercontent.com/assets/14255968/17570709/64433692-5f02-11e6-9209-b9a425958872.gif)

**Comment by lfaler** [comment]
I wrote this same bug before and I never received any contact so I hope it gets through this time, this bug was on the last patch too, but has not been on all patches.

**Comment by matthewwithanm** [comment]
Sorry we missed your previous report @lfaler! 😞

We still haven't switched over to Atom 1.9 so it's possible that this is related to the Atom version, but I just tried to repro with both 1.9 and the 1.10 beta and couldn't.

Is it possible one of your other packages is interfering here? Also, do you see the same thing with other versions of Atom?

**Comment by lfaler** [comment]
It happens with just this package on my editor. No I didn't see this on Atom 1.8 but it was always a little tricky. It would be difficult to reset but not impossible.

**Comment by matthewwithanm** [comment]
None of us have been able to repro this so far…do you have any errors in the devtools console when you see this?

**Comment by frostpuppet** [comment]
This only happens to me on my dual monitor setup.  Without the second monitor Im not hitting this issue.

**Comment by lfaler** [comment]
I am using two monitors as well. Here is the error in the devtool console
![screen shot 2016-08-25 at 4 28 47 pm](https://cloud.githubusercontent.com/assets/14255968/17989275/097bab6e-6ae1-11e6-897f-8d27e6ffb32c.png)

**Comment by matthewwithanm** [comment]
@frostpuppet @stefanwuest Can you share which packages/versions you're using too? Even with two monitors, we haven't been able to repro.
