### ISSUE TITLE
Goto declaration on react-tag / property name / property value

### ISSUE THREAD

**Issue by vaukalak** [facebook/nuclide#669]
### Issue and Steps to Reproduce
Enable flow, type checks work in your file. press cmd, and hover a react tag, or it property

### Expected Behavior
This should navigate to the declaration of the tag / property.

### Actual Behavior
It navigates to react.js file, line 158 (`declare module react {`)
![0564a919632654483626dcaceaf86348](https://cloud.githubusercontent.com/assets/1864367/17732437/6cf5d66e-647a-11e6-9271-5e5d87dca3e3.gif)

### Versions
* Atom: 1.9.8
* Nuclide: 0.162.0
* Client OS: OS X El Capitan (10.11.3)
* Server OS (optional):

### Additional Details
```
├── auto-reveal-active-file@0.3.1
├── auto-reveal-in-sidebar@0.8.0
├── autosave@0.20.0
├── expose@0.12.1
├── file-templates@0.1.1
├── git-plus@5.16.2
├── git-time-machine@1.5.3
├── js-autoimport@0.5.1
├── language-cjsx@0.3.0
├── language-ejs@0.2.0
├── nuclide@0.162.0
├── preview@0.16.3
└── project-manager@1.15.11
```

**Comment by nmote** [comment]
This is an issue with Flow, which provides this functionality. More discussion in #353

**Comment by nmote** [comment]
Feel free to open or add to an issue on the Flow repo. I'm also pushing on them to get this fixed since I'm also frustrated by this problem.
