### ISSUE TITLE
Unable to delete file-tree items

### ISSUE THREAD

**Issue by aewing** [facebook/nuclide#67]
In any of my projects on Ubuntu 14.10, when right clicking a file from the context menu and selecting "Delete", a confirmation prompt is shown and then nothing happens. No error is displayed in the developer console, and the file is not deleted.

**Comment by aewing** [comment]
After getting some sleep I've noticed that this issue exists in the Atom file-tree as well. I believe it's related to https://github.com/atom/tree-view/issues/345

**Comment by ssorallen** [comment]
Thanks for tracking that down, @aewing. Nuclide's file tree is separate from Atom's, but I suspect they're doing the same thing and hitting the same bug.

**Comment by RoverWire** [comment]
I have the same issue, I can't delete files form tree-view :(

**Comment by oddityoverseer13** [comment]
:+1: Same issue

**Comment by mostafaeweda** [comment]
I'm sure this works now, closing - feel free to re-open if that's still the case.
