### ISSUE TITLE
Hover is way too small width

### ISSUE THREAD

**Issue by kasperpeulen** [facebook/nuclide#670]
### Issue and Steps to Reproduce
Install the latest atom + nuclide version on OSX. Hover over a variable:
![image](https://cloud.githubusercontent.com/assets/1035299/17755720/e7d06b22-64db-11e6-995b-f53b7c4d4cd9.png)

### Expected Behavior
I expected this:
![image](https://cloud.githubusercontent.com/assets/1035299/17755848/d6dfaa52-64dc-11e6-98d2-8b93a2aab9e3.png)

### Versions
* Atom: 1.9.8
* Nuclide: 0.162.0
* Client OS: OSX

### Additional Details

* Installed packages (`apm ls --installed`):
```
Dev Packages (1) /Users/Kasper/.atom/dev/packages
└── darkular-kasper-syntax@0.3.0
Community Packages (20) /Users/Kasper/.atom/packages
├── disable-keybindings@0.6.0
├── es6-snippets@0.3.0
├── file-type-icons@1.3.2
├── git-diff-details@1.3.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── intellij-idea-keymap@0.2.1
├── language-babel@2.32.2
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-eslint@7.2.4
├── merge-conflicts@1.4.4
├── nuclide@0.163.0
├── react-es6-snippets@0.3.0
├── sort-lines@0.14.0
├── standard-formatter@2.0.1
└── tool-bar@1.0.1
```

**Comment by nmote** [comment]
Known incompatibility with Nuclide and Atom 1.9.x. It was just fixed in 2b081d0f17b26a19b37df4ce01030ecf0b960a1a which will be out with the next Nuclide release.
