### ISSUE TITLE
Type hints are disappearing too quickly

### ISSUE THREAD

**Issue by alexeygolev** [facebook/nuclide#676]
### Issue and Steps to Reproduce
Hover on a js term that has an object type. The type hint will appear. Try to click a pin button or open up the object with the arrow button

### Expected Behavior
If I hover over the type hint it should probably stay on screen before I hover off so I can click either button

### Actual Behavior
The type hint disappears after a timeout when I hover off the the term

### Versions
* Atom: 1.9.9
* Nuclide: 0.165.0
* Client OS: Mac OS X 10.11.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── atom-keyboard-macros-vim@0.1.5
├── atom-reason@0.0.4
├── atom-reason-loader@0.3.0
├── atom-ternjs@0.14.2
├── autocomplete-haskell@0.6.6
├── autocomplete-modules@1.6.1
├── chester-atom-syntax@0.1.1
├── double-tag@0.4.0
├── dracula-theme@1.2.8
├── emmet@2.4.3
├── file-icons@1.7.18
├── flex-tool-bar@0.10.3
├── git-plus@5.16.2
├── haskell-ghc-mod@1.17.2
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── ide-haskell@1.8.1
├── ide-haskell-cabal@1.6.4
├── ide-haskell-repl@0.1.3
├── jumpy@3.0.3
├── language-babel@2.33.0
├── language-docker@1.1.7
├── language-graphql@0.2.0
├── language-haskell@1.9.7
├── language-ini@1.16.0
├── language-nginx@0.6.1
├── language-ocaml@1.1.2
├── language-reason@0.0.9
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-eslint@7.2.4
├── linter-sass-lint@1.7.0
├── markdown-writer@2.5.1
├── merge-conflicts@1.4.4
├── minimap@4.24.7
├── minimap-bookmarks@0.4.1
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.4.0
├── modular-snippets@0.1.2
├── native-ui@0.18.3
├── nuclide@0.165.0
├── oceanic-next@0.2.0
├── open-this@0.2.0
├── pigments@0.33.1
├── pomodoro@1.0.1
├── project-manager@2.9.7
├── redux-snippets@0.2.2
├── sepia-syntax@1.0.5
├── sort-lines@0.14.0
├── standardjs-snippets@2.4.0
├── terminal-plus@0.14.5
├── tidy-markdown@3.0.1
├── tool-bar@1.0.1
├── vim-mode-plus@0.51.0
├── vim-mode-plus-ex-mode@0.5.0
├── vim-mode-plus-move-to-symbols@0.1.5
├── vim-mode-plus-project-find-from-search@0.1.0
├── vim-mode-plus-subword-movement@0.2.2
└── zenburn@3.0.0

**Comment by nmote** [comment]
I have the same problem. Specifically my experience has been that while my cursor is moving over the type hint, it stays up. But as soon as my cursor stops (like right when I'm about to click the pin button), it disappears.

**Comment by jgebhardt** [comment]
@nmote yes, v0.166 contains the last remaining change needed to fix this.
@alexeygolev definitely report back if that is v0.166.0 does not fix this issue. 
Thanks!

**Comment by alexeygolev** [comment]
@jgebhardt amazing! thank you. Long type signatures overflow for me, but I guess this is about  #684

**Comment by nmote** [comment]
I pushed v0.166.0 minutes ago. Closing out.
