### ISSUE TITLE
NPM does not update to latest version (0.165.0)

### ISSUE THREAD

**Issue by wakahiu** [facebook/nuclide#677]
### I'm stuck at an older version of nuclide server  (0.161.0)
Running `npm -g outdated` shows that my nuclide server is at (0.161.0).

Package  | Current  |   Wanted  |   Latest  |   Location
__________|__________|___________|__________|__________
nuclide    |  0.161.0  |  0.161.0    |  0.165.0  |

### Expected Behavior
I'm trying to upgrade to the latest version (0.165.0) but whenever I do `sudo npm -g upgrade nuclide`, After that I should get

Package  | Current  |   Wanted  |   Latest  |   Location
__________|__________|___________|__________|__________
nuclide    |  0.165.0  |  0.165.0    |  0.165.0  |

### Actual Behavior
Nothing happens.  `npm -g outdated` returns the same result as before.

### Versions
* Atom: 1.9.9
* Nuclide: 0.161.0 - Server and 0.165.0 client
* Client OS: Unix Ubuntu
* Server OS (optional):

**Comment by nmote** [comment]
I'm not an expert on npm but v0.165.0 is published to npm so this doesn't sound like an issue on our end. It may be worth uninstalling and re-installing the nuclide package. When you install you can also specify a version via something like `npm install -g nuclide@0.165.0`. Hopefully that works.

**Comment by wakahiu** [comment]
Thanks. Commad `npm install -g nuclide@0.165.0` forced it up upgrade.
