### ISSUE TITLE
Collapse/Uncollapse all in file-tree

### ISSUE THREAD

**Issue by aewing** [facebook/nuclide#68]
The default behavior of the Atom file tree is to collapse/uncollapse a directory and all contained directories when the arrow icon is alt-clicked. Currently this is not happening for me in the default file tree on Ubuntu 14.04, Atom 0.205.0.

**Comment by ssorallen** [comment]
This is now in master. alt-click on directories recursively expands or collapses them.

Commit 4f640638480bc1177863547cb453c99c257f6f6d added the functionality.
