### ISSUE TITLE
React Native - Buck Integration, iOS

### ISSUE THREAD

**Issue by dili91** [facebook/nuclide#682]
Hi everybody, 
I'm trying to evaluate Nuclide IDE on a react-native project. I read [on your website](https://nuclide.io/docs/platforms/react-native/#buck-integration) that in order to enable all Nuclide's features I should build my iOS RN app with Buck.

> If you have built your React Native iOS application with Buck, you may be able to utilize the built-in Nuclide Buck integration to build and run your application.

How can I actually do it ? is there anywhere on the web a more detailed explanation of what does the statement

>  If you have built your React Native iOS application with Buck

means ?
In alternative, where can I find some examples ?

Thanks

**Comment by matthewwithanm** [comment]
Sorry for the delay, @dili91. Unfortunately, we don't currently have any resources about this, but the Buck team is looking into creating some. We're also hard at work on supporting non-Buck flows.

Sorry I don't have a better answer for this.
