### ISSUE TITLE
Debugger side pane "empty"

### ISSUE THREAD

**Issue by oreliable** [facebook/nuclide#683]
![nuclide-debugger-empty](https://cloud.githubusercontent.com/assets/12518506/18034730/42f972d4-6d45-11e6-9de8-e6209f324cf4.png)

The side pane of the debugger is empty when we toggle it (see screenshot).
# Additional info

We would like to use the node debugger.

We don't see anything pertaining to the `nuclide-debugger-node` ([internal?](https://nuclide.io/blog/2016/01/13/Nuclide-v0.111.0-The-Unified-Package/)) package in the Nuclide settings (though we do see settings for `nuclide-debugger-native` and `nuclide-debugger-php`), except for the "Enable the "nuclide-debugger-node" feature" (which is checked of course). This setting shows `Provides: __`.

The package is definitely there: `$HOME/.atom/packages/nuclide/pkg/nuclide-debugger-node`.

Because we have no way to define which `node` binary to use, we assume it tries the one in `PATH`.

We use node/6.4.0, but also tried v4.5.0 (LTS), as it isn't clear that Nuclide supports v6. The [changelog](https://github.com/facebook/nuclide/blob/v0.111.0/CHANGELOG.md) mentions all versions but v6, but [this commit](https://github.com/facebook/nuclide/commit/faeda71a87397dbd0c6a73cf8b5878fc3a54756f) suggests that it does ([relevant PR](https://github.com/facebook/nuclide/issues/495)).

We've tried a fresh atom install on three boxes using separate operating systems (Ubuntu, Fedora, Windows).

On Linux, we also tried symlinking `/usr/local/bin/node` in case it's hard-coded, along with a 0.10.42 version in `/usr/bin/node`.

It's not clear whether it uses the same Blink dev tools as those embedded in Atom (CTRL+SHIFT+I), so we've tried setting up both Chromium and the official Chrome build on the `PATH`.

[This](https://github.com/facebook/nuclide/issues/193) might be related.
# Bigger picture

We read [here](https://nuclide.io/docs/languages/flow/#debugging) that "The debugging of Flow through Node is a cornerstone of Nuclide. It serves as the example for the debugger at large [...]". Obviously, our experience doesn't seem to support that claim. Is this an isolated thing or is Nuclide still an experiment? If there is something we've missed, I suggest a little [documentation](https://nuclide.io/docs/features/debugger/) update and some helpful feedback on what to do on the debugger pane.

**Comment by psalz** [comment]
I can confirm that there appears to be a regression regarding the debugger, starting with version `0.164.0`. For now, you can work around this by installing an earlier version using apm: `apm install nuclide@0.163.0`!

**Comment by zaaack** [comment]
me, too.

**Comment by benjy** [comment]
I also have the same issue with 0.167.1, see attached screenshot from the console in dev mode.

<img width="1434" alt="nuclide-debugger-errors" src="https://cloud.githubusercontent.com/assets/863137/18436802/b5da8124-792c-11e6-9774-1cdf5fa10e19.png">

**Comment by pierr** [comment]
I run the same issus on version `nuclide@0.170.0`, any update on this ?

**Comment by pierr** [comment]
It seems related to https://github.com/facebook/nuclide/issues/707#issue-176573709

**Comment by johnislarry** [comment]
A lot of work has been done here, including launching a new UI for the debugger, and revamping the node debugging support.  Things should be up and running, but please open an issue if there are any problems, thanks!
