### ISSUE TITLE
Flow type preview tooltip should expand and linewrap or something

### ISSUE THREAD

**Issue by justinwoo** [facebook/nuclide#684]
### Issue and Steps to Reproduce

If you have any sufficiently long type (like the produce of multiple intersections or just big records), you end up with a small tooltip that cuts off.

![](https://raw.githubusercontent.com/justinwoo/flow-type-select-ordering/master/screenshots/matchesdefault.png)
### Expected/Actual Behavior

I would hope that this would either naively soft-wrap or add newlines after insections and expand the tooltip so that I can read the type.
### Versions
- Atom: 1.9.9
- Nuclide: 0.165
- Client OS: OSX

**Comment by alexeygolev** [comment]
Nuclide 0.168
Still present
