### ISSUE TITLE
[Nuclide-OCaml] How to set the priority of auto-complete?

### ISSUE THREAD

**Issue by liweijian** [facebook/nuclide#686]
### Issue and Steps to Reproduce
Auto-complete can save our time in most of the cases, but in some cases it doesn't.

### Expected Behavior
For example, `in` is very common in OCaml, when I typed `in` in Atom and press `enter`. It should only show `in`.

### Actual Behavior
<img width="508" alt="screen shot 2016-09-01 at 3 19 41 pm" src="https://cloud.githubusercontent.com/assets/19320783/18158827/4623aa22-7058-11e6-963a-a26d8fbc70bc.png">

It always shows `in_channel_length`.

### Versions
* Atom:1.9.8
* Nuclide:0.165.0
* Client OS:Mac OS X 10.11.6
* Server OS (optional):

### Additional Details

```shell
├── language-ocaml@1.1.2
├── nuclide@0.165.0
└── ocaml-indent@0.4.0

└── (empty)
```

**Comment by nmote** [comment]
We just get autocomplete results from ocamlmerlin. Nuclide itself knows very little about OCaml. I think your best bet would be to file a bug against ocamlmerlin.

Closing as I don't believe this is something we can change in Nuclide.
