### ISSUE TITLE
Find usages

### ISSUE THREAD

**Issue by vaukalak** [facebook/nuclide#689]
### Issue and Steps to Reproduce

There's no possibility to execute find usages operation.
### Expected Behavior

If the project is covered by flow, nuclide should find references to a class, property, file, method and display them in a list.
### Actual Behavior

Seems like feature is not implemented.
### Versions
- Atom: 1.10.0
- Nuclide: 0.162.0

**Comment by nmote** [comment]
As I said in #688 Flow does not support this operation. Nuclide has the UI for find references and it's used for Hack, but Flow does not provide this functionality. Once they do it will be easy to plumb it up to our UI.

**Comment by nmote** [comment]
Closing as this is a Flow issue, not Nuclide.

**Comment by vaukalak** [comment]
[https://github.com/facebook/flow/releases/tag/v0.38.0](https://github.com/facebook/flow/releases/tag/v0.38.0)
```
Local find references command: flow find-refs file line column - 
if there is a variable x at file:line:column,
then this command returns the location of x's 
definition and the location of all reads and writes to x.
```
is this what we need?

**Comment by nmote** [comment]
Nope, this only finds refs within a single file, not globally. @zertosh actually added a Nuclide setting to surface this functionality (Highlight identifier references under Flow). But it's currently pretty buggy and has surprising results which is why it's currently gated.

**Comment by nmote** [comment]
FYI I just updated https://github.com/facebook/flow/issues/2398. Support for this is imminent.
