### ISSUE TITLE
Outline view has stopped working

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#691]
### Issue and Steps to Reproduce
For some reason, Outline View has ceased to work. No matter what JS file I open in my React project, it just says "No outline available."

### Expected Behavior
Outline View should show list of component methods.

### Actual Behavior
"No outline available."

### Versions
* Atom: 1.10.0
* Nuclide: 0.166.0
* Client OS: Mac OS 10.11.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
├── autocomplete-modules@1.6.1
├── expose@0.12.1
├── git-time-machine@1.5.3
├── goto-definition@1.1.19
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── js-refactor@0.7.3
├── language-babel@2.36.3
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-eslint@7.2.4
├── merge-conflicts@1.4.4
├── minimap@4.25.0
├── nuclide@0.166.0
├── refactor@0.9.2
├── sort-lines@0.14.0
├── todo-show@1.7.0
└── tool-bar@1.0.1

└── (empty)
```

**Comment by jorfermo** [comment]
Same issue

**Versions**

- Atom: 1.8.0
- Nuclide: 0.166.0
- Client OS: Mac OS 10.11.6

**Additional Details**

- Installed packages (apm ls --installed):

├── atom-beautify@0.29.11
├── auto-detect-indentation@1.2.0
├── autoclose-html@0.23.0
├── autocomplete-json@5.1.0
├── autocomplete-paths@1.0.2
├── autocomplete-python@1.8.6
├── emmet@2.4.3
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── jquery-snippets@11.0.0
├── language-babel@2.37.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-csslint@1.3.2
├── linter-eslint@7.2.4
├── linter-htmlhint@1.3.0
├── linter-jshint@2.1.0
├── linter-pep8@1.3.1
├── merge-conflicts@1.4.4
├── monokai-seti@0.7.0
├── nuclide@0.166.0
├── open-recent@5.0.0
├── pigments@0.34.0
├── seti-ui@1.3.2
├── sort-lines@0.14.0
├── sync-settings@0.7.2
└── tool-bar@1.0.1

└── (empty)

**Comment by nmote** [comment]
Do you have Flow installed and accessible? If you have a Flow version specified in your `.flowconfig` file, is it the same version as what you have installed? Are other Flow features working?

**Comment by jorfermo** [comment]
In my case Flow is not installed

**Comment by nmote** [comment]
Okay, you need Flow for this. You should have received a popup explaining that Flow is not installed and how to install it.

**Comment by jorfermo** [comment]
I didn't get any notification. 

Do you want me to test something about it?

**Comment by nmote** [comment]
Yeah, that would be great. It should look like the blue box in #537, and should only appear once each Atom run (assuming you haven't disabled it). So, restart Atom and try to use outline view. If you don't get the message, and you haven't disabled it, that's weird.

**Comment by jorfermo** [comment]
I'm not getting that blue box when I start atom. Where can I check if I disabled it?

**Comment by nmote** [comment]
Yep, that's the relevant setting. I don't know why you're not getting the warning. Could it be that you actually had Flow installed, but it was the wrong version? We still don't warn if that happens, though I've been meaning to do it for a while.

**Comment by jorfermo** [comment]
I tried to run flow in the console and it said "command not found"

After npm install -g flow-bin:

$ flow
Could not find a .flowconfig in . or any of its parent directories.
See "flow init --help" for more info

So it seems it wasn't installed (Or it wasn't in $PATH)

**Comment by nmote** [comment]
Weird. I really don't know what could cause that, then. All my simple theories have been disproven so it's probably some unusual configuration I hadn't thought of or a weird bug. I don't know what other questions I can ask you so all I'll say is if you come across anything interesting that seems related to this, please let me know.

**Comment by jorfermo** [comment]
Ok :) 

Thanks for your help!

**Comment by nmote** [comment]
Closing since it appears in at least one case that Flow simply was not installed. The issue where a warning does not appear when that happens is separate.

**Comment by SudoPlz** [comment]
`npm install -g flow-bin` did it for me.

**Comment by swthate** [comment]
I have been experiencing the same issue for some time now. I tried your fix, @SudoPlz , and it worked!!

Maybe now I can finally make sense of these files...
