### ISSUE TITLE
Can't copy from diagnostics panel

### ISSUE THREAD

**Issue by vaukalak** [facebook/nuclide#693]
### Issue and Steps to Reproduce

Write a code that contains an error in flow. And open flow panel. Right click on error line.
### Expected Behavior

Should be opened context menu with possibility to copy error value.
### Actual Behavior

Nothing happens.
### Versions
- Atom: 1.10.0
- Nuclide: 0.162.0

**Comment by nmote** [comment]
There are limitations with Atom that make this painful. At one point we had a hack that made this work but an Atom update broke it. Honestly we are unlikely to get to fixing this.

Instead I recommend that you open the full error message by hovering over the red or orange triangle in the gutter at the line where the error is. Then there will be a copy button which will copy the full error text.

**Comment by jgebhardt** [comment]
@matthewwithanm fixed this in https://github.com/facebook/nuclide/commit/df3adb8eb18469a66dceff06610a49bbd7215872, and it just shipped in https://github.com/facebook/nuclide/releases/tag/v0.196.0.
