### ISSUE TITLE
Hack: Special-cased `idx` not generating errors

### ISSUE THREAD

**Issue by simonwelsh** [facebook/nuclide#7]
```hack
<?hh // strict

function a(): void {
  $a = idx([]);
}
```

Expected: `Too few arguments`
Actual: no error

```hack
<?hh // strict

function a(array<string, string> $v): int {
  return idx($v, 'hello', 'world');
}
```

Expected: `Invalid return type`
Actual: no error

**Comment by fredemmott** [comment]
Probably fixed by https://github.com/facebook/nuclide/commit/3ae2a3a9c5ac679ae983c88fba76ad9a919093ff

**Comment by ssorallen** [comment]
@simonwelsh, does that commit fix the issue for you?

**Comment by mostafaeweda** [comment]
I just tried it, and I'm now getting the proper expected errors
