### ISSUE TITLE
[docs][react native][getting started] Cmd + D does not show the debug menu

### ISSUE THREAD

**Issue by andresn** [facebook/nuclide#702]
I had to go into Xcode and select "Use Debug for command-line builds" (in XCode 8):

![image](https://cloud.githubusercontent.com/assets/69597/18375207/e4e49e36-7608-11e6-9945-65d8ccf5898b.png)

This might trip-up people new to all this. :/

Other than that, awesome work, particularly enjoying the inspector!

**Comment by matthewwithanm** [comment]
Thanks for the feedback @andresn! Even better stuff is on the way!

@frantic Any ideas about improving this?

**Comment by frantic** [comment]
What version of React Native is that? Seems to be a new thing in Xcode 8. Mind opening an issue for [React Native repo](https://github.com/facebook/react-native/issues)?

**Comment by andresn** [comment]
@frantic 0.33.0 and cross-referenced /\

**Comment by matthewwithanm** [comment]
Seems like this is more of a React Native issue, so I'm going to close this one. Thanks for reporting @andresn!
