### ISSUE TITLE
All icons are suddenly missing

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#703]
### Reproduction steps:
???

### Versions
* Atom: 1.10.2
* Nuclide: 0.167.1
* Client OS: Mac OS 10.11.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

```
Community Packages (21) /Users/samh/.atom/packages
├── autocomplete-modules@1.6.1
├── expose@0.12.1
├── git-time-machine@1.5.3
├── goto-definition@1.1.19
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── js-refactor@0.7.3
├── language-babel@2.37.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-eslint@7.3.0
├── merge-conflicts@1.4.4
├── minimap@4.25.0
├── nuclide@0.167.1
├── refactor@0.9.2
├── sort-lines@0.14.0
├── todo-show@1.7.0
└── tool-bar@1.0.1

└── (empty)
```

![image](https://cloud.githubusercontent.com/assets/12532733/18407498/1bba84ca-76c7-11e6-9f33-9673e0d0eb9f.png)

![image](https://cloud.githubusercontent.com/assets/12532733/18407507/4fa286e8-76c7-11e6-879f-4c0507379adc.png)

![image](https://cloud.githubusercontent.com/assets/12532733/18407512/65a00cb8-76c7-11e6-80a4-507708beac3e.png)

**Comment by ffxsam** [comment]
The icons came back randomly for a while, and now they're gone again (between restarts). No rhyme or reason.

**Comment by nmote** [comment]
This looks like an issue with either Atom or a theme, and not Nuclide. For example, we do not control the "About Atom" page which is also missing icons.
