### ISSUE TITLE
Nuclide doesn't auto-install dependency packages on Ubuntu 16.04

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#706]
### Issue and Steps to Reproduce
When installing Atom from scratch and then installing Nuclide via `apm install nuclide`, running Atom doesn't trigger the dependency auto-install.

### Versions
* Atom: 1.10.2
* Nuclide: 0.167.1
* Client OS: Ubuntu 16.04
* Server OS (optional):

Only package shown in `apm list --installed` is Nuclide.

**Comment by zertosh** [comment]
@ffxsam Are you referring to `tool-bar` and such? If so, we purposefully do not install them by default - if you'd like have them installed, enable "Install Recommended Packages on Startup" from Nuclide's settings.

**Comment by ffxsam** [comment]
Ahh, I missed that option! I seemed to remember it auto-installing.. I guess that's not the case :) Thanks!
