### ISSUE TITLE
Is nuclide-debugger-node no longer supported?

### ISSUE THREAD

**Issue by ultragtx** [facebook/nuclide#707]
### Issue and Steps to Reproduce
Although I can attach the debugger to a node process, but debugger features like break points do not work. 

Seems that most of the code in nuclide-debugger-node had been removed in https://github.com/facebook/nuclide/commit/2a88935844fe439fd30cbaa3328baaacc127959c, and now  the package provides/consumes nothing comparing with other debugger packages. 

PS. I know nothing about atom plugin, please forgive me if i am wrong.

### Versions
* Atom: 1.10.2
* Nuclide: 0.168.0
* Client OS: OSX 10.11.6

**Comment by johnislarry** [comment]
Hi @ultragtx, we're currently in the process of revamping our node debugger and in the churn of things it seems that we did in fact remove our entry point to the node debugger.  In the next two weeks, we're going to re-release the node debugger, and it will have the ability to debug node processes running locally, as well as server-side (via the nuclide server).  Thanks for your patience.
