### ISSUE TITLE
Default value returned by the JS executor for React Native is outdated

### ISSUE THREAD

**Issue by Rovack** [facebook/nuclide#709]
### Issue and Steps to Reproduce
When the executor can't handle a command, it returns a nested array containing 5 empty arrays. This is considered an invalid return value by the React Native app, since the 4th value is expected to be a number (see https://github.com/facebook/react-native/commit/2c6a81d4451e0c873ef2a39019122ca4879a4f77 for the corresponding change in the CLI debugger).
Consequently, the app displays the following error:

> Did not get valid calls back from JS: %s[[],[],[],[],[]]
> 
> run
> NativeRunnable.java:-2
> handleCallback
> Handler.java:739
> dispatchMessage
> Handler.java:95
> dispatchMessage
> MessageQueueThreadHandler.java:31
> loop
> Looper.java:148
> run
> MessageQueueThreadImpl.java:196
> run
> Thread.java:818

Getting this error, when the real problem might be the bridge not having been loaded properly in the context, or some unrecognized command, can be a red herring and make debugging very confusing.

### Expected Behavior
The default value returned by the executor, when `__fbBatchedBridge` can't handle a request from the app, should  be `[[], [], [], 0]`.

### Actual Behavior
The executor returns `[[],[],[],[],[]]`, and the app shows a strange error.

### Versions
* Atom: 1.10.2
* Nuclide: 0.167.1
* Client OS: OS X 10.11.6

### Additional Details
* Installed packages (`apm ls --installed`):

> ├── atom-hot-package-loader@0.5.1
> ├── haskell-grammar@0.4.0
> ├── highlight-selected@0.11.2
> ├── language-babel@2.37.1
> ├── language-ini@1.16.0
> ├── language-ocaml@1.1.2
> ├── language-swift@0.4.0
> ├── language-thrift@1.0.2
> ├── merge-conflicts@1.4.4
> ├── nuclide@0.167.1
> ├── sort-lines@0.14.0
> └── tool-bar@1.0.1
> 
> └── (empty)

**Comment by matthewwithanm** [comment]
Thanks @Rovack!
