### ISSUE TITLE
Debugger not working for me

### ISSUE THREAD

**Issue by fbunn** [facebook/nuclide#713]
### Issue and Steps to Reproduce

I tried two different React native applications.
Was able to connect to the debugger and set breakpoints, but execution never stops when my code hits them.

There's an error reported on startup:

Debugger.setDebuggerSettings failed.
Error: Not implemented

Debugger.setDebuggerSettings failed.
Error: Not implemented.
prelude_dev.js:4 Running application "try4" with appParams: {"rootTag":1,"initialProps":{}}. **DEV** === true, development-level warning are ON, performance optimizations are OFF
prelude_dev.js:4 action @ 23:39:22.754 STARTUP 
prelude_dev.js:4  prev state Object
### Expected Behavior

I expected breakpoints to work.
### Actual Behavior

Nothing. The debugger is connected and seems to behave. Just no breakpoints.
### Versions
- Atom: latest
- Nuclide: latest
- Client OS: El Capitan (OS X)
- Server OS (optional):
### Additional Details

Freds-MacBook-Pro:try4 fredbunn$ apm ls --installed
Community Packages (11) /Users/fredbunn/.atom/packages
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.40.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── nuclide@0.168.0
├── sort-lines@0.14.0
└── tool-bar@1.0.1

└── (empty)

**Comment by johnislarry** [comment]
Hi @fbunn, what does `node --version` report when run locally?

**Comment by mincedmit** [comment]
Is there any update on this?  We are using React Native 0.33, node 4.6.1, and OS X 10.11.6 and breakpoints also don't work.

It seems to connect but nothing happens at the breakpoint.

**Comment by bartonhammond** [comment]
+1

RN 0.37
Node 6.2.2
OS X 10.11.5

**Comment by jcollum** [comment]
Similar issue here. I can start the debugger but can't set breakpoints and the debugger will not stop, even if I put `debugger` statements in to the code. 

```
$ react-native --version
react-native-cli: 1.2.0
react-native: 0.38.0

$ versions
npm 3.10.8
node v6.9.1
OS Darwin ---- 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

**Comment by SudoPlz** [comment]
+1

RN: 0.39.0
node: v7.3.0
npm: 4.0.5
OSX: 10.12.2

**Comment by johnislarry** [comment]
I have a fix in review for this issue: https://github.com/facebook/nuclide/issues/900 which may impact this.

**Comment by mostafaeweda** [comment]
The new node debugger should've fixed this already.
