### ISSUE TITLE
Question: OmniSearch API?

### ISSUE THREAD

**Issue by StevenLangbroek** [facebook/nuclide#717]
Is it possible / allowed to patch into OmniSearch? We have quite elaborate relationship mapping between PHP, JS and SCSS files, and I would like to be able to show "related files" in OmniSearch. Any guidance would be greatly appreciated.

**Comment by viatsko** [comment]
It's possible:

```
  "providedServices": {
    "nuclide-quick-open-register-provider": {
      "description": "Register ourselves with the quick-open package",
      "versions": {
        "0.0.0": "registerProvider"
      }
    }
  }
```

**Comment by StevenLangbroek** [comment]
wow, thanks for the quick answer. could you point me to a sample file that populates it with something?

**Comment by StevenLangbroek** [comment]
Cool, thanks so much!
