### ISSUE TITLE
Flow errors are shown at a definition site

### ISSUE THREAD

**Issue by alexeygolev** [facebook/nuclide#718]
### Issue and Steps to Reproduce
Quite often flow won't show the errors at the call site. So unless you have "Show only diagnostics for current file" unchecked some of your code will look ok.
A good example would be trying to follow [this](https://medium.com/@gcanti/phantom-types-with-flow-828aff73232b#.6op1ajh6j) post. The errors will only be shown for the 'Data.js' file

### Expected Behavior
The errors should be shown at the call site

### Actual Behavior
 The errors are shown at the definition site

### Versions
* Atom: 1.10.2
* Nuclide: 0.168.0
* Client OS: MacOS X 10.11.6
* Server OS (optional):

**Comment by nmote** [comment]
Not a Nuclide issue. See #356 for an explanation.
