### ISSUE TITLE
Autocomplete (JS) doesn't work 90% of the time

### ISSUE THREAD

**Issue by mirokk** [facebook/nuclide#722]
### Issue and Steps to Reproduce
Autocomplete works only sometimes. Flow is configured properly and works, means when i save the file with an error it underlines the error. But no Autocomplete... Any idea what the problem might be?

### Expected Behavior
Tell us what should happen.

### Actual Behavior
Tell us what happens instead.

### Versions
* Atom: latest
* Nuclide: latest
* Client OS: Mac OS X 10.9.4
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── Remote-FTP@0.8.9
├── atom-dark-fusion-syntax@1.2.4
├── atom-ternjs@0.15.0
├── autocomplete-clang@0.10.0
├── autocomplete-json@5.1.0
├── autocomplete-modules@1.6.3
├── flow-ide@1.1.8
├── gpp-compiler@3.0.7
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.41.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-gcc@0.6.15
├── merge-conflicts@1.4.4
├── northem-dark-atom-syntax@0.21.0
├── northem-light-atom-syntax@0.20.0
├── nuclide@0.170.0
├── react@0.16.0
├── remote-edit@1.8.24
├── seti-ui-red@0.13.0
├── sort-lines@0.14.0
└── tool-bar@1.0.1

**Comment by hansonw** [comment]
You have the package `flow-ide` installed, which is probably not compatible with Nuclide. Could you try removing that and trying again?

**Comment by nmote** [comment]
I also wonder whether autocomplete-modules might interfere.

**Comment by mirokk** [comment]
I uninstalled both of them and still doesn't work.

**Comment by nmote** [comment]
Okay, can you give a specific case where it doesn't work and you expect it to? Can you describe the exact behavior that you observe? Are there some cases where autocomplete reliably works?

**Comment by mirokk** [comment]
Intended behaviour:
Typing this should create the suggestion "Component"
`// @flow
import React from 'react';
React.Compo`

Observed behaviour:
nothing happens. Unless i save the file, then it underlines the line. So Flow understands that there is no method or attribute React.Compo..

There are no cases where autocomplete reliably works (tried to find some patterns for a few days now), and as i had installed a few different plugins like ternjs in this few days, it might not even be Nuclide that ever worked.

**Comment by mirokk** [comment]
I've deactivated all plugins not related to nuclide. And now it works partially.. if i create a class with some methods, include this class in another file with import, then the autocomplete works. if I include React it still doesn't work.

    // @flow
    import React from 'react';
    import {Hallo} from './testclass';
    
    // Here it works
    Hallo.add(1, 4);
    Hallo.substract(2, 4);

    // Here it doesn't work
    React.Co

**Comment by nmote** [comment]
We get all our JS autocomplete directly from Flow, which does not provide autocomplete for React here. I bet it's related to https://github.com/facebook/flow/issues/2120. This isn't a Nuclide issue but feel free to reopen on the Flow repository.
