### ISSUE TITLE
Atom freezes with 100% CPU usage when opening preferences

### ISSUE THREAD

**Issue by DanielHoffmann** [facebook/nuclide#726]
### Issue and Steps to Reproduce
After doing a clean Atom install (deleting ~/.atom/) and installing Nuclide through `apm install nuclide`. Open Atom then open Preferences screen, atom freezes with 100% CPU usage.

### Expected Behavior
Preferences screen should open normally

### Actual Behavior
Atom freezes with 100% CPU usage

### Versions
* Atom: 1.10.2
* Nuclide: 0.170.0
* Client OS: OS X El Capitan (10.11.4)

### Additional Details
No other packages installed, completely clean install
Seems related to #84

**Comment by chrisjones-tripletri** [comment]
+1.  I installed atom for the first time this morning, then followed the instructions to install nuclide.  The install of nuclide itself seemed to crash, and then the editor crashes anytime I open it.  It eventually displays an "Editor not responding" message.

**Comment by DanielHoffmann** [comment]
To me the Nuclide install didn't seem to crash, but the `apm install nuclide` did exit without any messages (not sure if that is the expected behavior)

**Comment by hansonw** [comment]
Hmm I managed to reproduce this. It looks like when Atom opens an `atom://` URI, it adds an `atom:` project - then we try to detect the nearest HG repository with `findHgRepository`, which enters an infinite loop.

@mostafaeweda or @shushz, any idea what the best fix is?

<img width="767" alt="screen shot 2016-09-21 at 11 57 39 am" src="https://cloud.githubusercontent.com/assets/577378/18724816/9e673f74-7ff2-11e6-953f-55f9d390a68d.png">

**Comment by shushz** [comment]
Substitution of `nuclideUri.join(workingDirectoryPath, '..')` with `nuclideUri.dirname(workingDirectoryPath)` should do it, I think.

**Comment by zertosh** [comment]
@shushz This is a bug in `nuclideUri.join` because `path.join('/', '..') === '/`.

**Comment by mostafaeweda** [comment]
@zertosh that's happening with `atom://` uris, not local paths.

--> I have a fix coming for this in the works.

**Comment by zertosh** [comment]
@mostafaeweda I know, `nuclideUri.join` removes the protocol part and is supposed to run a vanilla `path.join` on the rest, so the expected behavior should be `nuclideUri.join('atom:///', '..') === 'atom:///')`

**Comment by zertosh** [comment]
I looked at `nuclideUri` and it's assuming that the scheme is always `nuclide://` - seems odd.
