### ISSUE TITLE
Will not typecheck flow file on windows.

### ISSUE THREAD

**Issue by cameron-martin** [facebook/nuclide#728]
### Issue and Steps to Reproduce

Try to open a flow file.

Here are the messages in the console:

C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:18.620Z] [INFO] nuclide - [unknown]: Flow server in C:\Users\camer\Sources\SetupWizard
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:18.758Z] [ERROR] nuclide - Unknown return code from Flow: undefined
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:18.760Z] [ERROR] nuclide - Unknown return code from Flow: undefined
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:18.761Z] [ERROR] nuclide - Flow failed: flow status --json C:\Users\camer\Sources\SetupWizard\src\index.js. Error: {"stdout":"","stderr":"","errorCode":"ENOENT","errorMessage":"spawn flow ENOENT"}
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:18.761Z] [ERROR] nuclide -  Object
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:18.833Z] [WARN] nuclide -  Object
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:18.836Z] [ERROR] nuclide - Unknown return code from Flow: undefined
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:18.836Z] [ERROR] nuclide - Flow failed: flow dump-types --json C:\Users\camer\Sources\SetupWizard\src\index.js. Error: {"stdout":"","stderr":"","errorCode":"ENOENT","errorMessage":"spawn flow ENOENT"}
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:20.840Z] [ERROR] nuclide - Unknown return code from Flow: undefined
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:20.841Z] [ERROR] nuclide - Flow failed: flow type-at-pos --json --path C:\Users\camer\Sources\SetupWizard\src\index.js 3 14. Error: {"code":"EPIPE","errno":"EPIPE","syscall":"write"}
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:21.119Z] [ERROR] nuclide - Unknown return code from Flow: undefined
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:21.119Z] [ERROR] nuclide - Flow failed: flow type-at-pos --json --path C:\Users\camer\Sources\SetupWizard\src\index.js 3 14. Error: {"code":"EPIPE","errno":"EPIPE","syscall":"write"}
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:23.105Z] [ERROR] nuclide - Unknown return code from Flow: undefined
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:49:23.105Z] [ERROR] nuclide - Flow failed: flow type-at-pos --json --path C:\Users\camer\Sources\SetupWizard\src\index.js 1 9. Error: {"code":"EPIPE","errno":"EPIPE","syscall":"write"}
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:55:28.868Z] [ERROR] nuclide - Unknown return code from Flow: undefined
C:\Users\camer.atom\packages\nuclide\pkg\nuclide-logging\lib\consoleAppender.js:39 [2016-09-22T07:55:28.871Z] [ERROR] nuclide - Flow failed: flow dump-types --json C:\Users\camer\Sources\SetupWizard\src\index.js. Error: {"stdout":"","stderr":"","errorCode":"ENOENT","errorMessage":"spawn flow ENOENT"}

Running these commands from the command line works as expected.
### Expected Behavior

Type errors should be shown.
### Actual Behavior

No type errors are shown.
### Versions
- Atom: 1.10.2
- Nuclide: 0.170.0
- Client OS: Windows 10
### Additional Details
- Installed packages (`apm ls --installed`):

├── activate-power-mode@0.9.0
├── atom-material-ui@1.3.6
├── autocomplete-erlang@1.1.2
├── clipboard-plus@0.5.1
├── color-picker@2.2.2
├── docblockr@0.8.5
├── ide-flow@0.8.0
├── language-babel@2.41.0
├── language-batch@0.3.3
├── language-cshtml@0.2.1
├── language-erlang@3.0.0
├── language-nginx@0.6.1
├── linter@1.11.16
├── linter-eslint@7.3.2
├── minimap@4.25.0
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.1
├── minimap-linter@1.6.0
├── minimap-pigments@0.2.1
├── nuclide@0.170.0
├── pigments@0.34.0
├── todo-show@1.7.0
└── toggle-quotes@1.0.0

└── (empty)

**Comment by hansonw** [comment]
Nuclide is indicating that it can't find flow (ENOENT). You can either add it to your PATH or set its location manually in Nuclide Settings.

**Comment by nmote** [comment]
Also note that our Windows support in general is iffy, though improving. So there might be some issues at play here that we aren't aware of.

**Comment by cameron-martin** [comment]
Flow is on my path. When I execute `require('process').env.PATH` in the atom developer tools, I get the following response:

```
"C:\Users\camer\Sources\SetupWizard\bin\;C:\Users\camer\Sources\SetupWizard\bin\..\node_modules\.bin;..."
```

When I set a breakpoint in the `asyncExecute` function in `pkgs/commons-node/process.js`, the call to `which flow` returns 

```
C:\Users\camer\Sources\SetupWizard\node_modules\.bin\flow
C:\Users\camer\Sources\SetupWizard\node_modules\.bin\flow.cmd
```

Then I get a subsequent call to `asyncExecute` where the `command` variable is set to `"flow"`, with various arguments. This call then returns the `ENOENT`.

**Comment by nmote** [comment]
This is very interesting, thanks for digging in. We just use `where`/`which` to check that Flow is installed. We don't actually use the full path to the binary that we receive from it. I assumed that if it's on the PATH, just executing `flow` would allow the system to find the binary. This assumption works for OS X/Linux but evidently not for Windows?

The second issue is unfortunate but I think I understand what's going on. We use the same codepath whether you specify a full path or just leave it as "flow" which is the default. One Linux/OS X you can call `which` with a full path to a binary or just a command name, and it works fine either way. Evidently `where` doesn't like that.

**Comment by sparcut** [comment]
Getting the same sort of errors, any solutions or progress towards?

**Comment by nmote** [comment]
No, frankly we aren't very focused on local Windows development. I'd be happy to discuss solutions and review PRs but I'm not going to spend time solving this myself in the foreseeable future.
