### ISSUE TITLE
Change timeout for Flow popup hints?

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#732]
### Issue and Steps to Reproduce
Flow type popups happen too quickly and tend to get in the way. I'll move the mouse to a certain spot to move the cursor, and the Flow hint pops up, forcing me to move the mouse away for a moment then move it back to click.

![licecap](https://cloud.githubusercontent.com/assets/12532733/18761478/f9001ef2-80b9-11e6-89cc-443d0d3d9964.gif)

### Versions
* Atom: 1.10.2
* Nuclide: 0.170.0
* Client OS: Mac OS 10.11.6
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

```
├── autocomplete-modules@1.6.3
├── expose@0.12.1
├── git-time-machine@1.5.3
├── goto-definition@1.1.19
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── js-refactor@0.7.3
├── language-babel@2.42.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.16
├── linter-eslint@7.3.2
├── merge-conflicts@1.4.4
├── minimap@4.25.0
├── nuclide@0.170.0
├── nuclide-test-runner-jest@0.3.0
├── refactor@0.9.2
├── sort-lines@0.14.0
├── todo-show@1.7.0
└── tool-bar@1.0.1
```

**Comment by hansonw** [comment]
@jgebhardt: I assume you're looking at this?

**Comment by jgebhardt** [comment]
@ffxsam You can configure the delay in the Nuclide settings ("Datatip debounce delay"). Please report back if that didn't fix it. Thanks!

**Comment by ffxsam** [comment]
@jgebhardt Thanks, that works! However, it also increases the time it takes for the tip to go away when I mouse off of it, which doesn't seem right.
