### ISSUE TITLE
Add a grep-based omnisearch provider

### ISSUE THREAD

**Issue by fredemmott** [facebook/nuclide#752]
### Issue and Steps to Reproduce

Hit command-T, start typing something from inside a file
### Expected Behavior

Get results; ideally use `git grep`/`hg grep` as appropriate, but fall back to plain old `grep`
### Actual Behavior

No results based on file contents
### Versions
- Atom: 1.10.2
- Nuclide:  0.171.40040796

**Comment by zertosh** [comment]
`hg grep` sounds reasonable, not sure who'd get around to it though.

**Comment by fredemmott** [comment]
Not ideal as it involves setup but you can use https://github.com/etsy/hound thanks to @skevy at exponent:

1. create a directory to hold your hound configuration and data
2. create a config.json directory with your repostories
3. run hound
4. Install https://github.com/exponent/nuclide-hound-provider (with https://github.com/exponent/nuclide-hound-provider/pull/1 unless you work at exponent)

Example for (2): https://github.com/etsy/hound/blob/master/config-example.json

My full example for 2 & 3:

```
Freds-Mac-Pro:hound fred$ cat config.json
{
    "max-concurrent-indexers" : 2,
    "dbpath" : "/data",
    "repos" : {
        "HackCodegen" : {
          "url" : "file:///Users/fred/hackdev/hack-codegen"
        }
    }
}
Freds-Mac-Pro:hound fred$ docker run -d -p 6080:6080 --name hound -v $(pwd):/var/data -v /Users/fred/hackdev/:/Users/fred/hackdev etsy/hound
```

**Comment by a20012251** [comment]
Solved with https://nuclide.io/blog/2017/08/31/Code-Search/
