### ISSUE TITLE
Bug in file tree sorting

### ISSUE THREAD

**Issue by albenik** [facebook/nuclide#753]
### Issue and Steps to Reproduce
Create project directory with structure similar to:
```
project_folder
    src
        Root.js
        Root.dev.js
        Root.prod.js
```

Add created `project_folder` to Nuclide with `Add Project Folder` menu

### Expected Behavior
Files should be sorted by their names except extension at first

1. Root.js
2. Root.dev.js
3. Root.prod.js

### Actual Behavior
Files sorted by full name with extension

1. Root.dev.js
2. Root.js
3. Root.prod.js

(.dev.js before  .js)

### Versions
* Atom: 1.10.2
* Nuclide: 0.171.0
* Client OS: macOS 10 Sierra
* Server OS (optional): none

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (5) /Users/username/.atom/packages
├── editorconfig@1.4.1
├── merge-conflicts@1.4.4
├── nuclide@0.171.0
├── ssh-config@0.10.1
└── svg-preview@0.10.0
└── (empty)
```

**Comment by zertosh** [comment]
I just did some testing. Atom, Sublime, Finder and `ls`, all sort like how Nuclide is sorting. However, VSCode is sorting how you're suggesting. tbh, I'm a little surprised by VSCode's sorting, I don't expect it at all. Is this something from the Windows world? cc: @shushz

**Comment by albenik** [comment]
Hmmm, I am using macOS and just testing `ls`it works as you said.
Very, very surprised!

Ok, I agree, Nuclide sorts files in native manner. So it is correct behaviour for Nuclide...

But it is counter-intuitive and ugly for me... sadness :(

**Comment by shushz** [comment]
So, in case anyone cares, on Windows too `dir`, Eclipse, IntelliJ, Visual Studio, Explorer and Free Commander use same sorting as Nuclide. I did find one program that uses the other sorting - Far Manager.
