### ISSUE TITLE
Outline not working with destructive assignments

### ISSUE THREAD

**Issue by kuuup-at-work** [facebook/nuclide#754]
### Issue and Steps to Reproduce
![screenshot from 2016-09-30 16-37-28](https://cloud.githubusercontent.com/assets/7289171/18995491/acabc230-872c-11e6-88a7-7a827177526f.png)

### Expected Behavior
All created consts should be displayed

### Actual Behavior
Just the keyword `const` appears

### Versions
* Atom: 1.10.2
* Nuclide: 0.171.0
* Client OS: Ubuntu Desktop 16.04
* Server OS (optional):

**Comment by nmote** [comment]
What version of Flow do you have? With v0.32 I actually observe an error and no outline.

Anyway this would be a pretty easy PR if you'd like to contribute. Otherwise I'll probably get to it in the next week or two.

**Comment by kuuup-at-work** [comment]
I use Flow 0.32 and there is no error. I'd love to contribute but I'm not sure if I'll find out how this stuff works :smirk:

**Comment by nmote** [comment]
I'm fixing this today

**Comment by kuuup-at-work** [comment]
Thx! Updated to 0.178.0 and it works nicely 👍
