### ISSUE TITLE
Add way to disable Task Runner Toolbar by default

### ISSUE THREAD

**Issue by ffxsam** [facebook/nuclide#768]
### Issue and Steps to Reproduce

Swift toolbar is open by default on new projects (or folders where Atom has not run before). Even if I toggle to hide it, when Atom is run in a new folder, it appears again.
### Versions
- Atom: 1.10.2
- Nuclide: 0.174.0
- Client OS: Mac OS 10.11.6
- Server OS (optional):
### Additional Details
- Installed packages (`apm ls --installed`):

```
├── autocomplete-modules@1.6.7
├── expose@0.12.1
├── git-time-machine@1.5.3
├── goto-definition@1.1.19
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── js-refactor@0.7.3
├── language-babel@2.43.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.18
├── linter-eslint@7.3.2
├── merge-conflicts@1.4.4
├── minimap@4.25.0
├── nova-atom-syntax@1.3.1
├── nova-atom-ui@1.2.3
├── nuclide@0.174.0
├── nuclide-test-runner-jest@0.3.0
├── refactor@0.9.2
├── sort-lines@0.14.0
├── todo-show@1.7.0
└── tool-bar@1.0.1
```

**Comment by ffxsam** [comment]
In addition, it takes two attempts at choosing "Toggle Swift Toolbar" to actually hide it.

**Comment by ffxsam** [comment]
It says "Task runner is now displayed by default" - but the Swift toolbar is showing. That would make more sense to me if a majority of Nuclide users were using it for Swift.

**Comment by matthewwithanm** [comment]
Hey @ffxsam! So here's how it works: the task runner is shown by default and it tries to pick the most relevant task for you.

Since the Swift toolbar hasn't (yet) been updated to indicate that it's not relevant, that one winds up getting selected. If you hide it, that will be serialized with the project though.

Having to toggle it twice is definitely a bug. Does that repro consistently for you?

**Comment by ffxsam** [comment]
>Having to toggle it twice is definitely a bug. Does that repro consistently for you?

Yep, every time.

PS: I noticed for each folder Atom is run in, it remembers the open files, and if the Swift toolbar is open. Where is that information stored exactly?

**Comment by stephenkingsley** [comment]
I think Swift toolbar show by default is let me bother. can fix this problem? or add a config choice.

**Comment by teknologist** [comment]
Can we have a preference to just hide that toolbar by default ?
For us doing just javascript dev, it's useles and annoying to have to hide it (once or twice) everytime we launch atom...

**Comment by matthewwithanm** [comment]
> Yep, every time.

Can you file another issue for that? I can't repro so any debugging info you could provide would be 💯.

> PS: I noticed for each folder Atom is run in, it remembers the open files, and if the Swift toolbar is open. Where is that information stored exactly?

That uses Atom's workspace serialization. It's stored in `~/Library/Application Support/Atom` IIRC.

**Comment by ffxsam** [comment]
>That uses Atom's workspace serialization. It's stored in ~/Library/Application Support/Atom IIRC.

I don't think that's it. I did a `grep -ri` in that folder for some of my project names, and nothing turned up. I'm just looking for a way I can reset Atom's "memory" of a specific folder.

**Comment by matthewwithanm** [comment]
Sorry, it's stored in IndexedDB. You can clear it by running `atom --clear-window-state` or via the resources tab in the Developer Tools.

**Comment by moogus** [comment]
happens to me too, every time I open I open Atom

**Comment by Yu-w** [comment]
Same here, super annoying, have to hide task runner bar every time I open Atom.

**Comment by elsigh** [comment]
It only happens for me when Atom crashes and I have to rec-create my project from scratch. And it always takes two toggles for me too.

**Comment by harrislapiroff** [comment]
This toolbar also appears every time I open Atom (despite hiding it every time) and does not have any tasks I need for javascript dev.

**Comment by matthewwithanm** [comment]
Thanks, all. We know about the issue and I'm working on the fix now.

**Comment by matthewwithanm** [comment]
Sorry I forgot to report back on this one! Hopefully you noticed that it's not automatically showing that toolbar anymore (:

lmk if there are still remaining issues.

**Comment by ffxsam** [comment]
@matthewwithanm I sure did, thanks! You rock! 🍻
