### ISSUE TITLE
Add "Reveal in file tree" to text editor tab context menus

### ISSUE THREAD

**Issue by oclbdk** [facebook/nuclide#77]
The tab of each text editor should have the context menu item.

It's not just a matter of adding the following entry to `menus/tree-view.cson`:

```coffeescript
'context-menu':
  # Show this in the active tab.
  'atom-pane[data-active-item-path] .tab.active': [
    {'label': 'Reveal in File Tree', 'command': 'nuclide-file-tree:reveal-active-file'}
  ]
```

Then the item will appear at the top of the menu which can be unintuitive. We need to figure out a way to control the ordering of the menu items.

**Comment by ssorallen** [comment]
This could instead use the same selector that the 'tabs' package does: `.tab`.

Nuclide's file-tree could add an entry in keymaps.cson and listen for a new command called something like `'nuclide-file-tree:reveal-tab-file'` and assume it needs to look up the path to reveal on the tab's data-path.

**Comment by millermedeiros** [comment]
FYI, there is a plan to add ordering to the menu items (https://github.com/atom/atom/issues/6270) but it looks like it is still not working for some reason.. for the moment we can simply do:

```diff
diff --git a/fbobjc/Tools/Nuclide/pkg/nuclide/file-tree/menus/nuclide-file-tree.cson b/fbobjc/Tools/Nuclide/pkg/nuclide/file-tree/menus/nuclide-file-tree.cson
--- a/fbobjc/Tools/Nuclide/pkg/nuclide/file-tree/menus/nuclide-file-tree.cson
+++ b/fbobjc/Tools/Nuclide/pkg/nuclide/file-tree/menus/nuclide-file-tree.cson
@@ -2,3 +2,7 @@
   'atom-pane[data-active-item-path] atom-text-editor': [
     {'command': 'nuclide-file-tree:reveal-active-file', 'label': 'Reveal in File Tree'}
   ]
+
+  'atom-pane[data-active-item-path] .tab': [
+    {'command': 'nuclide-file-tree:reveal-active-file', 'label': 'Reveal in File Tree'}
+  ]
```

the Atom documentation says that the [context-menu is built following the menu load order](https://atom.io/docs/v1.0.19/hacking-atom-package-word-count#context-menu) - testing on my local Atom (OS X) the "Reveal in File Tree" is placed after the "split" options and just before the "Reopen Closed Tab" option, which is fine to me.

**Comment by ssorallen** [comment]
This was added in commit https://github.com/facebook/nuclide/commit/6555291ad129445bb8801aea101c71acc1f9e767
