### ISSUE TITLE
Hack: strict mode requiring types not enforced

### ISSUE THREAD

**Issue by simonwelsh** [facebook/nuclide#8]
```hack
<?hh // strict

function a($v) {}
```

Expected:
* `Was expecting a return type hint`
* `Was expecting a type hint`

Actual: no errors

**Comment by fredemmott** [comment]
Probably fixed by https://github.com/facebook/nuclide/commit/3ae2a3a9c5ac679ae983c88fba76ad9a919093ff

**Comment by ssorallen** [comment]
@simonwelsh, does the commit that @fredemmott mention fix the issue for you?

**Comment by mostafaeweda** [comment]
I just confirmed that 3ae2a3a fixes it.
