### ISSUE TITLE
Filetree performance is horrible with many uncommitted files (see video)

### ISSUE THREAD

**Issue by LegNeato** [facebook/nuclide#827]
### Issue and Steps to Reproduce

After I updated Nuclide (after maybe a month) the filetree is basically unusable. Here is a video of me scrolling up and down:

https://sendvid.com/ymvipwc8

It lags for a second after the scroll, then chunkily jumps.

No remote projects, all local. Let me know what I can get you to debug. I don't have time to bisect right now unfortunately.
### Expected Behavior

It should be fast / smooth.
### Actual Behavior

Chunky.
### Versions
- Atom: 1.11.2
- Nuclide: 0.176.0
- Client OS: Mac OS X 10.11.1
- Server OS (optional):
### Additional Details

```
Community Packages (8)
├── language-babel@2.45.0
├── language-terraform@0.7.4
├── linter@1.11.18
├── linter-eslint@8.0.0
├── minimap@4.25.5
├── nuclide@0.176.0
├── nuclide-test-runner-jest@0.3.0
└── tool-bar@1.0.1
```

**Comment by nmote** [comment]
This is weird. We all use this every day and haven't noticed this. Could you [capture a CPU profile](http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance) so we can take a look?

Also CC @shushz

**Comment by LegNeato** [comment]
CPU profile:

http://filebin.ca/2zazuINSzlzj/CPU-20161024T100903.cpuprofile

**Comment by shushz** [comment]
The slow part seems to be rendering the Uncommitted changes section. Specifically the `ChangedFilesList`. @jgebhardt, could you take a look?

In the mean time, @LegNeato, could you please try disabling the "Show uncommitted changes" setting in Nuclide settings and see whether it helps?

**Comment by LegNeato** [comment]
Ah, I was running some generation scripts and have 10956 uncommitted files in the repo. So this is likely not a regression. The uncommitted files are all under one directory that isn't displayed or expanded in the file tree so I would expect Nuclide to still be able to handle it.

@shushz Turning off "Show uncommitted changes"  does indeed fix the slowdown.

**Comment by jgebhardt** [comment]
@aadisriram we should limit the max number of files shown in the uncommitted changes list.

**Comment by bgdavidx** [comment]
+1, hd the same issue. Disabling "Show Uncommitted Changes" fixed the slowdown.

**Comment by aadisriram** [comment]
This has been fixed, the number of files shown by default has been restricted to 50 with the option for the user to see more.
