### ISSUE TITLE
Quick open on large code bases

### ISSUE THREAD

**Issue by jacobdufault** [facebook/nuclide#83]
The `filelist` for quick open gets stuck loading a very large code base, ie, Chromium. The native/regular one works fine (but it is a little laggy when typing). I've let it sit and do its thing for ~20 minutes.

I don't see any errors. I'm running on ubuntu.

**Comment by bolinfest** [comment]
To confirm, you're using `cmd-t` to use Nuclide's file opener rather than `cmd-p` for Atom's, correct?

Approximately how many files is Chromium, and are you on an SSD?

**Comment by jacobdufault** [comment]
Correct, I am using `cmd-t`. The UI looks similar to the one in the README and is visibly different from `cmd-p`.

Yep, I'm on an SSD.

For the file count, around 500,000.
```
/work/chrome/src$ find . -type f | wc -l
543942
```

**Comment by simonwelsh** [comment]
We're seeing the same thing in our code base. Only has ~30,000 files, running on a SSD.

**Comment by bolinfest** [comment]
Hmm, do you have [Watchman](https://facebook.github.io/watchman/) v3.2.0 or later installed? We call that out as required for our [Mecurial support](https://github.com/facebook/nuclide/tree/master/pkg/nuclide/hg-repository), but perhaps we missed that here?

**Comment by jacobdufault** [comment]
Installed it, but it didn't appear to change anything.

**Comment by bolinfest** [comment]
@simonwelsh How about you? ~30,000 files doesn't seem like all that much. Though from our testing, 500,000 files should also work. (I think it should take 30s at most to initially index the path names.)

Could there be any weird symlink loops that we are not traversing responsibly?

**Comment by simonwelsh** [comment]
Installing Watchman has the file list show up :)

**Comment by jacobdufault** [comment]
```
TASK(981): uncaughtException: { [Error: EXDEV: cross-device link not permitted, rename '/tmp/nuclide-node-transpiler115523-981-1iiz309' -> '~/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/nuclide-node-transpiler/babel-cache/564aa7208191ab5835e8b76ad7973252d24e0b92/d922337f311d15c072e4c8da176392ac689a7726']
  errno: -18,
  code: 'EXDEV',
  syscall: 'rename',
  path: '/tmp/nuclide-node-transpiler115523-981-1iiz309',
  dest: '~/.atom/packages/nuclide-quick-open/node_modules/nuclide-client/node_modules/nuclide-server/node_modules/nuclide-node-transpiler/babel-cache/564aa7208191ab5835e8b76ad7973252d24e0b92/d922337f311d15c072e4c8da176392ac689a7726' }
```

This message popped up in the developer tools console.

**Comment by bolinfest** [comment]
OK, so currently it seems like we have two separate issues here:

1. @simonwelsh We should update our setup instructions to tell people to install Watchman. (Though I want to double-check that that is what fixed things for you.)
2. @jacobdufault We should either pre-transpile our Babel files or provide better tolerance for this type of error (or be sure to choose a temp directory that is on the same device as the `babel-cache` directory).

**Comment by simonwelsh** [comment]
I stopped and uninstalled Watchman, restarted Atom, `ctrl-alt-T` then never stops spinning.

Re-installed Watchman, restarted Atom, `ctrl-alt-T` now shows results

**Comment by ssorallen** [comment]
@jacobdufault The error you pasted looks like it's Node's fs.rename failing when attempting to move temporary files across partitions: https://stackoverflow.com/questions/12196163/node-js-fs-rename-doesnt-work

This is happening in babel-cache.js: https://github.com/facebook/nuclide/blob/master/pkg/nuclide/node-transpiler/lib/babel-cache.js#L95

**Comment by chrisfarms** [comment]
:+1: installing watchman + restart atom resolved this here too.

**Comment by ev-tt** [comment]
I opened another issue, I have a lot smaller codebase , just 1700 files totalling 50mb.

**Comment by jssln** [comment]
@ev-tt, do you have Watchman installed?

**Comment by joshdcomp** [comment]
Had the same problem with a Wordpress repo—I installed Watchman and restarted Atom, the file list populated much faster. Is there a way for nuclide-quick-open to detect whether Watchman is installed or not and push a warning message? For such a simple fix, It's a little difficult to diagnose.

**Comment by tylermauthe** [comment]
Installing Watchman fixed this issue for me also :+1:

**Comment by mostafaeweda** [comment]
I believe looking up large number of files has improved a lot since reporting this. /cc @jgebhardt
