### ISSUE TITLE
TypeError: Generator is already running

### ISSUE THREAD

**Issue by admmasters** [facebook/nuclide#832]
### Issue and Steps to Reproduce

Try using any of the Flow features through Nuclide.
No autocompletion or diagnosis UI.
### Expected Behavior

Diagnosis and autocompletion should work - like it did prior to the Babel 5 -> Babel 6. d99970c8ab29906384f009b76b0bcc9ca80010cd commit.
### Actual Behavior

Nothing - no autocompletion or diagnosis occurring.
Stacktrace:

```
async-to-generator.js:11 Uncaught (in promise) TypeError: Generator is already running
  at undefined.next (<anonymous>:null:null)
  at step (/Users/***/Developer/nuclide/node_modules/async-to-generator/async-to-generator.js:11:30)
  at /Users/***/Developer/nuclide/node_modules/async-to-generator/async-to-generator.js:21:13
  at process._tickCallback (internal/process/next_tick.js:103:7)
[ERROR] nuclide - Error from provider for source.js.jsx TypeError: Cannot read property 'value' of null
  at step (/Users/***/Developer/nuclide/node_modules/async-to-generator/async-to-generator.js:12:27)
  at /Users/***/Developer/nuclide/node_modules/async-to-generator/async-to-generator.js:21:13
```
### Versions
- Atom: 1.11.2
- Nuclide: Master
- Client OS: OSX
- Server OS (optional):
### Additional Details

├── autocomplete-json@5.1.0
├── autocomplete-modules@1.6.7
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.45.0
├── language-elm@1.5.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.18
├── linter-eslint@8.0.0
├── merge-conflicts@1.4.4
├── nuclide@0.176.0
├── nuclide-format-js@0.0.36
├── oceanic-next@0.4.0
├── sort-lines@0.14.0
└── tool-bar@1.0.1

**Comment by nmote** [comment]
I saw this issue on the Atom 1.12 beta but I'm using Atom 1.11.2 without any issues. @zertosh do you have any ideas what might be going on here?

**Comment by zertosh** [comment]
No idea - I've only seen this in Atom 1.12.0. @admmasters can you repro consistently in 1.11.2?

**Comment by zertosh** [comment]
Turns out it is https://bugs.chromium.org/p/v8/issues/detail?id=5322. We're working with the Atom team to figure out what to do, since other's are likely to hit this issue in Atom 1.12.0

**Comment by zertosh** [comment]
Here's the issue tracking this in Atom https://github.com/atom/atom/issues/13073

**Comment by nmote** [comment]
Still thought it's an open question why this would be happening on Atom 1.11.2...

**Comment by zertosh** [comment]
I can't repro in Atom 1.11.2

**Comment by jgebhardt** [comment]
@admmasters This issue was identified as being exposed in Atom 1.12. We've never had reports of this before, and the error signature is pretty unique. Is it possible that the version you reported is incorrect? Please do the following:

1. If using Atom 1.12.x, make sure you're running at least 1.12.0-beta5, which fixes the underlying issue
2. If using Atom 1.11.x, you should not see this error at all. If you do, please re-open this issue.

Thanks!

**Comment by admmasters** [comment]
Apologies I've been offline for a while. Both are installed, I generally use 1.11, but I've updated nuclide and it appears to be working now in both. Sorry for the delay, I'm fairly certain I tested it in both and it was the same error, but you are probably right. Apologies for the noise.
