### ISSUE TITLE
Nuclide does not autocomplete built-in APIs

### ISSUE THREAD

**Issue by allenylzhou** [facebook/nuclide#842]
### Issue and Steps to Reproduce

Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).
Start typing window.al or new Buf
### Expected Behavior

Tell us what should happen.
I would expect autocomplete to prompt me with window.alert and new Buffer
### Actual Behavior

Tell us what happens instead.
Nothing happens
### Versions
- Atom: 1.11.2
- Nuclide: 0.177.0
- Client OS: Mac OS X Yosemite 10.10.5
- Server OS (optional):
### Additional Details
- Installed packages (`apm ls --installed`):

└── nuclide@0.177.0

└── (empty)

I've tried this with two projects.
One is a React-Native starter project
Another is a Webpack starter project.
Both are very bare bones at this time.

**Comment by nmote** [comment]
Please fill in the requested version information and add some details about your project (e.g. which language, etc.)

**Comment by allenylzhou** [comment]
I've updated op with more details.

**Comment by nmote** [comment]
Do you have Flow installed?

**Comment by nmote** [comment]
This is likely just because Flow was not installed.
