### ISSUE TITLE
PHP/HHVM debugger "Attach" does not work (does not listen on port)

### ISSUE THREAD

**Issue by jesseschalken** [facebook/nuclide#844]
### Issue and Steps to Reproduce
- Create a remote PHP project.
- Open the Nuclide Debugger, select Type: PHP and Action: Attach.
  ![image](https://cloud.githubusercontent.com/assets/1559204/19761387/6f77865a-9c81-11e6-92b7-75a16f76e454.png)
- Try to connect to the debugger port on the server with `nc -v localhost 9000`.
### Expected Behavior
- Nuclide should wait for connections to port `9000` on the server and the connection from `nc` should succeed.
### Actual Behavior
- The debug panel opens on the right, but nothing happens.
  ![image](https://cloud.githubusercontent.com/assets/1559204/19761407/8d57ae84-9c81-11e6-8378-2db4f0655e07.png)
- The connection from `nc` fails.

```
nc: connect to localhost port 9000 (tcp) failed: Connection refused
```
- `nc` can even start listening on port `9000` with `nc -l 9000` as proof that Nuclide did not even open the port.
### Versions
- Atom: 1.11.2
- Nuclide: 0.177.0
- Client OS: Ubuntu 16.04 LTS
- Server OS (optional): Ubuntu 16.04 LTS (same host)
### Additional Details
- Installed packages (`apm ls --installed`):

```
Community Packages (2) /home/user/.atom/packages
├── nuclide@0.177.0
└── tool-bar@1.0.1

└── (empty)
```

**Comment by johnislarry** [comment]
Well that's no good.  Is there anything interesting in your logfile?  It should be in `/tmp/nuclide-unixname-logs/`, the relevant lines should be prefixed with `nuclide-debugger-php`

**Comment by jesseschalken** [comment]
This was in the log file:

```
[2016-10-27T18:52:58.651Z] [ERROR] nuclide-debugger-php - Exception handling command 26: Error: xdebug ports are equal in attach mode Error: xdebug ports are equal in attach mode
    at ConnectionMultiplexer.listen (/usr/lib/node_modules/nuclide/pkg/nuclide-debugger-php-rpc/lib/ConnectionMultiplexer.js:172:15)
    at DebuggerHandler._resume (/usr/lib/node_modules/nuclide/pkg/nuclide-debugger-php-rpc/lib/DebuggerHandler.js:303:35)
    at /usr/lib/node_modules/nuclide/pkg/nuclide-debugger-php-rpc/lib/DebuggerHandler.js:132:17
    at DebuggerHandler.handleMethod (/usr/lib/node_modules/nuclide/pkg/nuclide-debugger-php-rpc/lib/DebuggerHandler.js:176:7)
    at /usr/lib/node_modules/nuclide/pkg/nuclide-debugger-php-rpc/lib/MessageTranslator.js:134:23
```

Changing the launch port from 9000 back to 10112 (the default) fixes it. Debugging still doesn't work, but it's at least listening for connections now. (I changed the launch port from the default in an attempt to fix debugging, without realising I had just broken it further.)

It would have been nice if that `Error: xdebug ports are equal in attach mode` message appeared in the UI.

**Comment by mostafaeweda** [comment]
Plz try the latest Nuclide (where a ton of improvements were made) to see if this is still an issue.
