### ISSUE TITLE
double clicking files in the tree view should make the preview tab permanent

### ISSUE THREAD

**Issue by despairblue** [facebook/nuclide#85]
See https://github.com/atom/tabs/issues/156 and https://github.com/atom/tabs/commit/73658a9391ce91aa60c43dd710b3a6fc4c816df9

**Comment by ssorallen** [comment]
Thanks. I'd like to make the file tree open files on single click as well to support Atom's preview tabs. We will take a look at this.

**Comment by ssorallen** [comment]
Fixed with commit https://github.com/facebook/nuclide/commit/893af8f365ef4cbfed26cb439c332b2d44a0f851.
