### ISSUE TITLE
Atom very slow when Nuclide is enabled

### ISSUE THREAD

**Issue by Maxwell2022** [facebook/nuclide#858]
### Issue and Steps to Reproduce
When enabling Nuclide (v0.178.0), I can barely work. Expending the file tree is taking few seconds.
If I disable Nuclide Atom is back to life, no more lag.

### Expected Behavior
Nuclide should not have that much impact on Atom performance

### Actual Behavior
Very slow response time in IDE

### Versions
* Atom: 1.11.2
* Nuclide: 0.178.0
* Client OS: MacOS Sierra 10.12.1 (16B2555)
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

```
├── atom-beautify@0.29.13
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.3.6
├── atom-react-native-autocomplete@0.0.27
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.45.0
├── language-ini@1.16.0
├── language-javascript-jsx@0.3.7
├── language-ocaml@1.1.2
├── language-swift@0.4.0
├── language-thrift@1.0.2
├── linter@1.11.18
├── linter-eslint@8.0.0
├── linter-jshint@3.0.1
├── merge-conflicts@1.4.4
├── minimap@4.25.6
├── nuclide@0.178.0
├── nuclide-format-js@0.0.36
├── pretty-json@1.6.1
├── seti-ui@1.3.2
├── sort-lines@0.14.0
└── tool-bar@1.0.1
```

**Comment by nmote** [comment]
While some loss of performance over stock Atom is unfortunately expected, it certainly shouldn't be crippling.

If you grab a [CPU profile](http://flight-manual.atom.io/hacking-atom/sections/debugging/#diagnose-runtime-performance) and post it somewhere where we can get it, we can see if there are any obvious problems.

It may also help if you shared details about your workflow (at the very least, what language(s) you are working in and if there are any specific Nuclide features you have open).

**Comment by SRandazzo** [comment]
@Maxwell2022 I had the same issue after upgrading.

I closed atom and deleted `~/.atom/storage`, emptied trash and relaunched atom.

My issue is now solved

Hope this helps you or anyone else!

**Comment by mostafaeweda** [comment]
We fixed big perf issues in the latest Nuclide release as well.
