### ISSUE TITLE
Can nuclide be used for commercial purpose ?

### ISSUE THREAD

**Issue by user-12345** [facebook/nuclide#864]
### I did not find a license for Nuclide
First off, thumbs up for the incredible editor, Nuclide. 

### My commercial activities might include:
1) creating and selling WordPress themes and plugins.
2) creating and selling other software.

### My questions is:
can i use Nuclide for commercial purpose ?
It would be nice if a someone from Nuclide could answer me that.

Thank you,
Regards.

**Comment by jgebhardt** [comment]
I am not a lawyer, but generally speaking, yes, you should be able to use Nuclide for the activities you listed. Relevant excerpt from the license:
```
[...] Subject to your compliance with these terms, you are
hereby granted a non-exclusive, worldwide, royalty-free copyright license to
(1) use and copy the Software; [...] 
```
Please be sure check out the complete Nuclide license (https://github.com/facebook/nuclide/blob/master/LICENSE) for details.
