### ISSUE TITLE
Quick Launch link is broken in the docs

### ISSUE THREAD

**Issue by vitaut** [facebook/nuclide#866]
Quick Launch link (https://nuclide.io/docs/features/quick-open/docs/quick-start/getting-started/#quick-launch-menu) is broken in https://nuclide.io/docs/features/quick-open/#toggling.

**Comment by johnislarry** [comment]
@zardra can you please take a look, thanks

**Comment by zardra** [comment]
Sorry, looks like it was missing a slash in the path.  PR coming.
