### ISSUE TITLE
Hyperlink cmd-click not working

### ISSUE THREAD

**Issue by habovh** [facebook/nuclide#868]
I'm trying to get the **`CMD`** **`click`** to work with Nuclide, but everytime I hover something with `cmd` key pressed, 2 errors shows up in the console:

```
[2016-11-09T09:23:59.313Z] [ERROR] nuclide - Unknown return code from Flow: 8
[2016-11-09T09:23:59.314Z] [ERROR] nuclide - Flow failed: flow type-at-pos --json --path /path/to/file.js 25 69. Error: {"stdout":"","stderr":".flowconfig:20 Error parsing value for \"esproposal.class_instance_fields\". Unsupported value: \"enable\". Supported values are: warn, ignore\n","exitCode":8}
```

I first thought it was related to this issue: #92, but it turns out this has been fixed long ago.

The result is my mouse cursor displaying a blue spinning wheel for a fraction of a second, then go back to normal.

I never got the **`CMD`** **`click`** to work since at least 4 months, and some friends of mine have the exact same issue despite having a different environment.

### Versions
* Atom: 1.11.2
* Nuclide: 0.180.0
* Flow: 0.18.1
* Client OS: macOS Sierra 10.12.1 (16B2555)

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (41) /Users/Jordan/.atom/packages
├── atom-css-comb@3.1.0
├── atom-jade@0.3.0
├── atom-material-syntax@0.4.6
├── blame@0.10.0
├── color-picker@2.2.2
├── emmet@2.4.3
├── expand-region@0.2.5
├── file-icons@1.7.24
├── firewatch-syntax@1.0.1
├── git-history@3.2.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── hyperclick@0.0.39
├── language-babel@2.47.0
├── language-ini@1.16.0
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@1.11.18
├── linter-eslint@8.0.0
├── local-history@3.4.1
├── markdown-preview-plus@2.4.0
├── merge-conflicts@1.4.4
├── minimap@4.25.6
├── minimap-highlight-selected@4.4.0
├── minimap-selection@4.4.0
├── monokai@0.18.0
├── motepair@0.22.0
├── native-ui@0.19.1
├── nuclide@0.180.0
├── nuclide-format-js@0.0.36
├── open-recent@5.0.0
├── pretty-json@1.6.1
├── react@0.16.1
├── set-syntax@0.3.2
├── seti-syntax@1.0.1
├── seti-ui@1.3.2
├── sort-lines@0.14.0
├── tool-bar@1.0.1
├── tool-bar-main@0.0.10
└── vim-mode@0.65.1

└── (empty)
```

**Comment by habovh** [comment]
Ok, simply reading the log output entirely made me realise I actually had a configuration file error in `.flowconfig`. However, fixing the errors does not fix the issue, as now I don't have any error in the console, but `Hyperclick` is still not working as expected: nothing happens on **`CMD`** **`click`**...

**Comment by habovh** [comment]
# Update 2
Updating flow to a more recent version (0.34.0) appears to fix the issue. Closing this issue to keep as a reference if somebody encounters the same error.

**Comment by johnislarry** [comment]
@habovh We recently dropped support for some older versions of flow.  Looks like you've already figured this out, sorry for the inconvenience!

**Comment by habovh** [comment]
Yep, was my bad, sorry about that!
Like I said, I'm just leaving this here in case someone encounters a similar issue :)
