### ISSUE TITLE
Add Watchman to setup instructions

### ISSUE THREAD

**Issue by ssorallen** [facebook/nuclide#87]
Watchman is required for Nuclide, but it is not currently mentioned in the [setup doc](http://nuclide.io/docs/setup/). Add information on how to install and verify it.

Installing Watchman seemed to fixed issues that came up in #83.

**Comment by joshuahhh** [comment]
Note: After running into the problem mentioned in #83, I ran `brew install watchman`. Using the search tool then gave the message `Watchman version: 3.0.0 does not support watch-project`. So I ran `brew install --HEAD watchman`, and that fixed the problem.

tl;dr -- the latest version of watchman in Homebrew isn't new enough for nuclide.

**Comment by ssorallen** [comment]
@joshuahhh, try running `brew update` first. `brew info watchman` lists 3.2.0 as the latest version for me. [`watch-project`](https://facebook.github.io/watchman/docs/cmd/watch-project.html) was added in 3.1.0, so a normal Homebrew install should get you a sufficiently new version.

**Comment by joshuahhh** [comment]
@ssorallen ohhhhhhhh cool good to know. thanks. :smile:

**Comment by schmod** [comment]
Also, Linux setup instructions for Watchman.

**Comment by constantx** [comment]
get latest version of watchman with `brew upgrade && brew upgrade watchman`

**Comment by ssorallen** [comment]
@constantx I think you want `brew update && brew upgrade watchman`. `update` updates Homebrew itself, and `upgrade watchman` scopes upgrades to just Watchman.

**Comment by constantx** [comment]
thanks @ssorallen :) edited

**Comment by simonwelsh** [comment]
@schmod Those would be the compiling from source instructions.

**Comment by jssln** [comment]
This is now in the "System Requirements" section of the nuclide README (https://github.com/facebook/nuclide). We should point http://nuclide.io/docs/setup/ at that.
