### ISSUE TITLE
Deprecated selector in `nuclide/pkg/hyperclick/styles/hyperclick.less`

### ISSUE THREAD

**Issue by styx** [facebook/nuclide#871]
In `nuclide/pkg/hyperclick/styles/hyperclick.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .editor-contents--private .highlight.hyperclick > .region` => `atom-text-editor.editor .editor-contents--private .highlight.hyperclick > .region`

* `atom-text-editor:not([mini]).hyperclick::shadow .editor-contents--private` => `atom-text-editor:not([mini]).hyperclick.editor .editor-contents--private`

* `atom-text-editor:not([mini]).hyperclick-loading::shadow .editor-contents--private` => `atom-text-editor:not([mini]).hyperclick-loading.editor .editor-contents--private`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jgebhardt** [comment]
This was fixed in [this week's v0.198.0 release ](https://github.com/facebook/nuclide/releases/tag/v0.198.0).

**Comment by cbrnr** [comment]
@jgebhardt any chance these changes will go into a new release of the package used in Atom (i.e. the read-only mirror) anytime soon?

**Comment by jgebhardt** [comment]
@cbrnr which package are you referring to? Can you point me to it? Thanks.

**Comment by cbrnr** [comment]
Atom's hyperclick package is pointing to the read-only mirror repo, so this needs to be synced with the latest release. No idea why there is this mirror in the first place, but here's the related issue in that repo: https://github.com/facebooknuclide/hyperclick/issues/5
