### ISSUE TITLE
Deprecated selector in `nuclide/pkg/nuclide-code-highlight/styles/highlight.less`

### ISSUE THREAD

**Issue by styx** [facebook/nuclide#872]
In `nuclide/pkg/nuclide-code-highlight/styles/highlight.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .highlight.nuclide-code-highlight-marker > .region` => `atom-text-editor.editor .highlight.nuclide-code-highlight-marker > .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jgebhardt** [comment]
This was fixed in [this week's v0.198.0 release ](https://github.com/facebook/nuclide/releases/tag/v0.198.0).
