### ISSUE TITLE
Deprecated selector in `nuclide/pkg/nuclide-datatip/styles/nuclide-datatip.less`

### ISSUE THREAD

**Issue by styx** [facebook/nuclide#873]
In `nuclide/pkg/nuclide-datatip/styles/nuclide-datatip.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .nuclide-datatip-highlight-region > .region` => `atom-text-editor.editor .nuclide-datatip-highlight-region > .region`

* `atom-text-editor::shadow .nuclide-datatip-highlight-region-active > .region` => `atom-text-editor.editor .nuclide-datatip-highlight-region-active > .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by johnislarry** [comment]
Excellent, yes we will be testing our build in the coming weeks with the new v1.13 atom beta and this will definitely be addressed.

**Comment by jgebhardt** [comment]
This was fixed in [this week's v0.198.0 release ](https://github.com/facebook/nuclide/releases/tag/v0.198.0).
