### ISSUE TITLE
Go to definition outside of file

### ISSUE THREAD

**Issue by joshg111** [facebook/nuclide#879]
Does Nuclide support go to definition for symbols where the definition is outside of the current file where go to definition was clicked? Right now go to definition works great for symbols which exist in the same file, but I haven't seen an example of it working for the out of file case.  

[The following code is taken from this start kit.](https://github.com/LeoLeBras/react-native-redux-starter-kit/tree/next)

The file where I do go to definition:
```javascript
/* @flow */

import React from 'react'
import { Button, Text, View } from 'react-native'
import styles from './styles'

type Props = {
  decrement: Function,
  increment: Function,
  value: number,
}

const Counter = (props: Props): React$Element<any> => {
  const { decrement, increment, value } = props
  return (
    <View style={styles.container}>
      <Button
        onPress={decrement}
        title="-"
        accessibilityLabel="Decrease counter value"
      />
       // The following line I click go to definition on value for styles.value
      <Text style={styles.value}>{value}</Text> 
      <Button
        onPress={increment}
        title="+"
        accessibilityLabel="Increase counter value"
      />
    </View>
  )
}

Counter.defaultProps = {
  value: 0,
}

export default Counter
```

Here's the other file with the styles and the value definition inside of styles:
```javascript
/* @flow */

import { StyleSheet } from 'react-native'

const styles = StyleSheet.create({
  container: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  value: {
    width: 40,
    textAlign: 'center',
  },
})

export default styles
```

**Comment by johnislarry** [comment]
To be clear, you are selecting 'Go to Declaration' in the right-click menu, is that correct?  If you do this in the first file over the symbol `styles` it should move the cursor to the import line, and this is the expected behavior.  Is it not doing that?  What is the behavior you're seeing?

**Comment by joshg111** [comment]
You are correct in saying that I am selecting 'Go to Declaration', sorry for being unclear. You are also correct in saying that if I select 'Go to Declaration' on the `styles` symbol it will move the cursor to the import line. 

What I'm saying is that when selecting 'Go to Declaration' on the `value` attribute of `styles` nothing is happening. The expected behavior from my perspective is that the cursor will be moved to the appropriate file and will be on the declaration of the `value` attribute of `styles` in that file. Or if the file is not already opened, then it should be opened, and the cursor moved accordingly.

**Comment by johnislarry** [comment]
Gotcha, a workaround is to use hyperclick.  Hold cmd, hover the mouse over the symbol until it underlines, and then click, and it should jump to where the symbol is defined.  Not sure why Go to Declaration doesn't work, @nmote may know more.

**Comment by joshg111** [comment]
I'm on ubuntu 16.04.1, and I have tried both 'Go to Declaration' and ctrl-click, but neither are working for me. Btw, ctrl-click is what i was using for my testing of other symbols which have declarations in the same file. Those are working fine, just not going outside the file. I'm pretty new to flow and nuclide, maybe I'm missing something. Did it work in your environment with these two files?

**Comment by joshg111** [comment]
Also, when I hold control and hover over the other symbols which have declarations in the same file I see the cursor turns into the "hand pointer", but for the out of file declaration I never see the "hand pointer" when i hover over it holding ctrl.

**Comment by nmote** [comment]
The 'Go to Declaration' item in the context menu is provided by the symbols-view package which ships with Atom, and we have no control over it. It is based on ctags and is not very reliable. It's also not extensible so we can't override its functionality without resorting to some ugly hacks.

Our replacement is hyperclick, which uses ctrl+click on Linux.

I haven't pulled down your code to confirm, but my suspicion is that Flow simply isn't able to track the `value` property through the `StyleSheet.create()` call. Try temporarily replacing that with just a plain old object and let us know if hyperclick starts working.

Another thing you can do is look at the type coverage (click the percentage in status bar). If it says that `styles.value` is uncovered then it confirms my theory.

Let us know what you find.

**Comment by joshg111** [comment]
I tried creating a plain object, and the hyper click works, so I think you're right.

**Comment by nmote** [comment]
Great, thanks for following up. May be worth opening an issue on the React Native repo. I don't know what the state of integration between RN and Flow is.
