### ISSUE TITLE
Include WakaTime Atom package in nuclide

### ISSUE THREAD

**Issue by alanhamlett** [facebook/nuclide#89]
https://atom.io/packages/wakatime

**Comment by simonwelsh** [comment]
Why? You can install additional packages alongside Nuclide.

**Comment by ssorallen** [comment]
Wakatime looks interesting, but we will leave it up to individual developers to add that to their Atom install. Time tracking in an IDE is interesting but not a necessity.

**Comment by alanhamlett** [comment]
Wanted to try my luck at turning every Facebook employee into a [WakaTime](https://wakatime.com) user :wink:
