### ISSUE TITLE
How to manage rules for Python flake8?

### ISSUE THREAD

**Issue by tuanh118** [facebook/nuclide#895]
### Issue and Steps to Reproduce
**Issue:** I've tried looking into nuclide's settings but could not find any linting settings. Not sure if the linter-flake8 package is supposed to be used by nuclide, or should I manage nuclide linting settings somewhere else, but linter-flake8 atom package's settings do not seem to affect nuclide linting warnings. 
**Steps:** This is just one example code
1. Go to linter-flake8 atom package's settings, add E501 to 'Ignore Error Codes.'
![flake8_settings](https://cloud.githubusercontent.com/assets/3454845/20439945/83fa4398-ad83-11e6-8c81-6279de2bf3b7.png)

2. Create a new Python file, type in a very long line to see the warning.
![flake8_symptom](https://cloud.githubusercontent.com/assets/3454845/20439946/840733fa-ad83-11e6-86f2-3dc5462f64f4.png)

### Versions
* Atom: 1.13.0-beta3
* Nuclide: 0.183.0
* Client OS: Ubuntu 16.04
* Server OS (optional):

**Comment by hansonw** [comment]
I would recommend setting this with flake8's built in configuration mechanism - adding a `.flake8` file to your project root. You can also create a `~/config/.flake8` config file for all projects. Nuclide and linter-flake8 will both respect this by virtue of flake8 picking this up.

You can then indicate ignored rules with

```
[flake8]
ignore = E501
```

See http://flake8.pycqa.org/en/latest/user/configuration.html.

**Comment by tuanh118** [comment]
@hansonw Thank you for the link. It works for me! Just for the record, the "User" configuration file is `~/.config/flake8` instead of `~/config/.flake8`
