### ISSUE TITLE
Deprecated selector in `nuclide/pkg/nuclide-type-hint/styles/nuclide-type-hint.less`

### ISSUE THREAD

**Issue by elvisblanco1993** [facebook/nuclide#898]
In `nuclide/pkg/nuclide-type-hint/styles/nuclide-type-hint.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.nuclide-type-hint-text-editor atom-text-editor::shadow .editor-contents--private` => `.nuclide-type-hint-text-editor atom-text-editor.editor .editor-contents--private`

* `.nuclide-type-hint-text-editor atom-text-editor::shadow .scroll-view .horizontal-scrollbar` => `.nuclide-type-hint-text-editor atom-text-editor.editor .scroll-view .horizontal-scrollbar`

* `.nuclide-type-hint-text-editor atom-text-editor::shadow .scrollbar-corner` => `.nuclide-type-hint-text-editor atom-text-editor.editor .scrollbar-corner`

* `atom-text-editor::shadow .nuclide-type-hint-highlight-region > .region` => `atom-text-editor.editor .nuclide-type-hint-highlight-region > .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by jgebhardt** [comment]
This was fixed in [this week's v0.198.0 release ](https://github.com/facebook/nuclide/releases/tag/v0.198.0).
