### ISSUE TITLE
Failed to activate the nuclide-click-to-symbol package

### ISSUE THREAD

**Issue by npu3paka** [facebook/nuclide#90]
The error is:
.atom/packages/nuclide-click-to-symbol/lib/ClickToSymbol.js: Unexpected character '@' (40:2)
>   38 |   }
   39 | 
'> 40 |   @trackTiming()
     |   ^
  41 |   findClickableRangesAndCallback(...args): Promise {
  42 |     return this._findClickableRangesAndCallback.apply(this, args);
  43 |   }

It happened when i opened xCode Project on Objective-C, wrote 1 line of Obj-C and saves the file.

**Comment by scv119** [comment]
@npu3paka which version of Atom are you using? I think upgrade Atom to 0.209.0 or higher could solve this problem.

**Comment by npu3paka** [comment]
I'm using 0.211.0 version of Atom.

**Comment by JanJakes** [comment]
Same problem here, version 0.211.0 as well.

**Comment by RamIdeas** [comment]
If I open the dev tools after installing nuclide and pause on uncaught exceptions, I can catch this error:

``` js
{
    exitCode: 1,
    stderr: '[31m
npm ERR! git fetch -a origin (https://github.com/kevinsawicki/jasmine-node.git) fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\<username>\\AppData\\Local\\atom\\app-0.211.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\<username>\\AppData\\Local\\atom\\app-0.211.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\<username>\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\<username>\\.atom\\.apmrc" "install" "C:\\Users\\<username>\\AppData\\Local\\Temp\\d-115524-8592-1gm5wn9\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: fatal: Unable to find remote helper for 'https'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

[39m
',
    stdout: 'Installing nuclide-click-to-symbol@0.0.21 to C:\Users\<username>\.atom\packages [31mfailed
[39m'
}
```

I'm also using version 0.211.0

**Comment by scv119** [comment]
@npu3paka @JanJakes Sorry I haven't got time looking into this and I can't reproduce this locally. Do you have a full stack trace of the error so I could see if the babel is outdated?

**Comment by mostafaeweda** [comment]
this package doesn't even longer exist, replaced by hyperclick and working fine
