### ISSUE TITLE
License seems less than "open"

### ISSUE THREAD

**Issue by sclaxton** [facebook/nuclide#903]
This issue was prompted by the recent [discussion on hacker news ](https://news.ycombinator.com/item?id=13015035) about the license for the new FB mobile animations library [Keyframes](https://github.com/facebookincubator/Keyframes). Keyframes originally had the same license that Nuclide currently has. After a lot of discussion on HN, [the open source team at FB approved](https://news.ycombinator.com/item?id=13015035#13018383) moving the library to a BSD license. I would argue that this has set a precedent for reconsidering Nuclide's license.

So can Nuclide be moved to a BSD license?

**Comment by jamesgpearce** [comment]
Hey @sclaxton, unfortunately we have to use a slightly different license for some of our projects and we're not currently in a position to change this. I am taking your feedback on board though...
