### ISSUE TITLE
Outline view is not working (no outline available)

### ISSUE THREAD

**Issue by collector1871** [facebook/nuclide#905]
### Expected Behavior
Outline view for *.php file(s) with class, methods, (meaby) private variables, namespaces...

### Actual Behavior
"No outline available"

### Versions
* Atom: 1.12.5
* Nuclide: newest
* Client OS: Linux, Debian testing
* Server OS (optional):

### Additional Details

Hi, I have php files with classes, methods, namespaces - and outline view is just not working.
(alt+o)

How can install/activate it ?

**Comment by nmote** [comment]
You need to install hack: https://nuclide.io/docs/languages/hack/

**Comment by cristiantx** [comment]
It's not working for me either. Even after install hack
@collector1871 how did you solve it?
Is there any additional step required after install?
