### ISSUE TITLE
Number of child processes growing out of control

### ISSUE THREAD

**Issue by yianL** [facebook/nuclide#907]
### Issue and Steps to Reproduce

I seldom turn off my laptop as I just put it to sleep after work and wake it up when I start my day, and it has been working without problems until recently. I had to reboot my laptop every 2-3 days for the past month due to significant slow-downs after a while. After some investigation, I track it down to Nuclide, and it seems to be spawning child processes over and over again without terminating them properly. (or it could be the child process counter's giving wrong information)

![nucilde_process](https://cloud.githubusercontent.com/assets/741612/20689512/a76c3abc-b57a-11e6-94fc-e5a6a7495a53.gif)

As you can see in the GIF attached, simply by staying in the health monitor page, my child process count grow steadily over time, eating up system resource and memory. I really enjoyed Atom/Nuclide, and would hate to switch to another text editor, but I think I'll try to use another editor to see if Nuclide is the one to blame.

### Versions
* Atom: 1.12.6
* Nuclide: 0.184.0
* Client OS: macOS 10.12.1

### Additional Details
* Installed packages (`apm ls --installed`):
├── activate-power-mode@1.1.0
├── advanced-open-file@0.16.4
├── angularjs@0.3.5
├── anypoint-ui-ide-tools@0.0.1
├── atom-spotified@0.7.0
├── atom-ternjs@0.16.1
├── atom-typescript@10.1.12
├── autocomplete-modules@1.6.7
├── base16-eighties-dark@2.1.1
├── block-cursor@0.13.1
├── color-picker@2.2.3
├── dash@1.7.0
├── editorconfig@2.0.5
├── emmet@2.4.3
├── expand-selection-to-quotes@0.11.0
├── file-icons@1.7.25
├── firewatch-syntax@1.0.1
├── flex-tool-bar@0.11.0
├── git-control@0.8.2
├── git-plus@5.25.5
├── haskell-grammar@0.4.0
├── highlight-line@0.11.1
├── highlight-selected@0.11.2
├── imdone-atom@2.0.19
├── language-babel@2.48.5
├── language-fish-shell@1.0.5
├── language-ini@1.16.0
├── language-javascript-jxa@0.2.8
├── language-matlab@0.2.1
├── language-ocaml@1.1.2
├── language-postcss@1.3.0
├── language-scala@1.1.8
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@1.11.18
├── linter-eslint@8.0.0
├── linter-jshint@3.0.1
├── linter-scss-lint@3.0.4
├── linter-stylelint@3.6.0
├── merge-conflicts@1.4.4
├── minimap@4.25.6
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.3.1
├── minimap-hide@0.3.0
├── minimap-highlight-selected@4.4.0
├── nuclide@0.184.0
├── nuclide-format-js@0.0.36
├── pdf-view@0.53.0
├── pigments@0.37.0
├── pretty-json@1.6.1
├── preview@0.17.0
├── project-manager@3.3.3
├── script@3.11.1
├── sort-lines@0.14.0
├── svg-preview@0.10.0
├── symbols-tree-view@0.13.2
├── sync-settings@0.7.2
├── terminal-plus@0.14.5
├── toggle-quotes@1.0.0
├── tool-bar@1.0.1
└── travis-ci-status@1.3.0

**Comment by yianL** [comment]
Update: seems like Nuclide is not the one at fault here. There is something weird when my laptop recovers from sleep, cannot run `ps` in the terminal for some reason, and then the whole system just slows down gradually. Will keep investigating. 😞

**Comment by nmote** [comment]
Still, the video you posted doesn't look right. Let us know if you uncover anything else that might be useful. I can't really tell what might be going on from the info here. Using `pstree` might be enlightening.

**Comment by nmote** [comment]
I let Nuclide sit on the health panel for a while and didn't see the number of child processes growing. Something is definitely strange here.

**Comment by yianL** [comment]
Almost certain [Hyper](https://hyper.is/) is causing the weird performance degradation here. There seemed to be some issues running HyperTerm in OSX Sierra. I went back to iTerm2 and haven't seen the broken behavior in the past 24 hrs.

Will close this issue for now. :)
