### ISSUE TITLE
hyperclick:confirm-cursor doesn't work with last-cursor-position

### ISSUE THREAD

**Issue by dongz9** [facebook/nuclide#908]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

I noticed last-cursor-position doesn't work properly when I jump to the definition of C++ functions using nuclide's hyperclick:confirm-cursor. 

### Expected Behavior
Tell us what should happen.

When jumping back from the definition of a function, the cursor should be on where the function is called.

### Actual Behavior
Tell us what happens instead.

When I jump back, the cursor is always in the correct file, but not necessary the correct position.

### Versions
* Atom: 1.12.6
* Nuclide: 0.184.0
* Client OS: macOS 10.12.1 
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by nmote** [comment]
last-cursor-position isn't our package, nor do we support it. We do have something similar.  Check out the 'nuclide-navigation-stack' commands.

**Comment by dongz9** [comment]
It works, thanks! I would suggest updating your website because it recommends last-cursor-position.

**Comment by nmote** [comment]
haha oops. @joelmarcey could you follow up?

**Comment by JoelMarcey** [comment]
https://github.com/facebook/nuclide/pull/909
