### ISSUE TITLE
isFlowInstalled() returns false

### ISSUE THREAD

**Issue by Nexi** [facebook/nuclide#91]
I have got flow installed on my system (Ubuntu 12.04) but this function isFlowInstalled()
located in LocalFlowService.js returns false every time when executed. 

In this section of the function below always goes inside catch statement with e.exitCode equals 1...
```
try {
      await asyncExecute("which", [path]);
      return true;
    } catch (e) {
      return false;
    }
```

**Comment by Nexi** [comment]
Magic happened, just moved flow binary in /usr/local/bin and now it works.

**Comment by ssorallen** [comment]
How did you install Flow? It'd be great to find out if Nuclide's check fails on any OS with a standard Flow install.

**Comment by nmote** [comment]
What was the result of `which flow` on your system before you moved it? If it's on your `PATH`, we should be finding it here.

I'm glad you found a workaround. Another possible workaround is to simply set the path to flow in the settings for the nuclide-flow package.

**Comment by Nexi** [comment]
> How did you install Flow?

I just unzipped the flow zip (which I downloaded from the site) inside my 'home' directory and set the path in  ~/.bashrc to point that unzipped flow binary  

> What was the result of which flow on your system before you moved it?

Before I moved it, the result of the top command was:
```
/home/niki/fb-flow/flow
```

inside this directory: '/home/niki/fb-flow/flow' was my flow binary.

The most interesting part is that when flow binary was inside home directory, flow type checker in Atom wasn't working. Then I saw this (https://github.com/73rhodes/Sublime-Flow, "It's recommended to install flow to /usr/local/bin/.") and I moved the binary in '/usr/local/bin/' (respectively I changed the path to point this new location) and then it already was working ...

**Comment by nmote** [comment]
`.bashrc` is only run when you start `bash`. Any changes it makes to the `PATH` variable only affect that shell and the processes that it spawns. So, if you start Atom from outside the command line, it will not pick up on any changes to the `PATH` that you have made in your `.bashrc`. That means it won't look in the location where you have installed Flow.

There are a couple solutions for this:
* Install Flow to a typical location (you discovered this).
* Go into the settings for the nuclide-flow package and specify the absolute path to the Flow binary.

I will test and make sure that this theory is correct, and then I will update the documentation to include this information.

**Comment by jssln** [comment]
To add on to @nmote's comment, the `nuclide-flow` "pathToFlow" config only specifies the path to the Flow binary for local files. We've started to talk about creating configs on the server, but for now, for remote files you will have to put flow on your PATH or put it in a 'typical location'.

**Comment by jssln** [comment]
@Nexi feel free to re-open this if you have more questions. It looks like the immediate problem is resolved.
