### ISSUE TITLE
[Windows] "Flow was not found" no matter what

### ISSUE THREAD

**Issue by JohnLouderback** [facebook/nuclide#911]
### Issue and Steps to Reproduce
I have Flow installed, I have it in my path, but Nuclide insists that it is not found. Additionally, I've run the `where flow` command and have hard set the path to the flow executable to no luck, and I've also tried setting the setting to find flow-bin locally (after installing it locally) also to no avail.

### Expected Behavior
Flow should work and I should not receive a message.

### Actual Behavior
I see a message from Nuclide which reads: "Flow was not found when attempting to start it in..."
![image](https://cloud.githubusercontent.com/assets/4743179/20781675/ec44cfe6-b741-11e6-9f1c-92e12b611ca7.png)

### Versions
* Atom: 1.13.0-beta6
* Nuclide: version 0.186.0
* Client OS: Windows
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
```
Community Packages (15) C:\Users\John\.atom\packages
├── atom-visual-studio-code-ui@1.3.4
├── file-icons@1.7.25
├── flat-ui-dark@0.0.0
├── minimap@4.26.4
├── minimap-cursorline@0.2.0
├── minimap-find-and-replace@4.5.1
├── minimap-git-diff@4.3.1
├── minimap-highlight-selected@4.4.0
├── minimap-linter@1.6.0
├── minimap-pigments@0.2.1
├── minimap-selection@4.4.0
├── nuclide@0.186.0
├── pigments@0.38.0
├── set-syntax@0.3.2
└── zentabs@0.8.7
```

**Comment by nmote** [comment]
Unfortunately our Windows support isn't very good. We have people using Nuclide on Windows as a client for remote development on a Linux machine, but local Windows development isn't in a very good state. I'll happily review a PR if you figure out how to solve this issue, but we aren't going to work on it ourselves in the near future.

**Comment by JohnLouderback** [comment]
I could make an honest attempt, though I'm not sure I have the time. Could you point me in the direction of where, in the code, the flow path is established and invoked?

**Comment by nmote** [comment]
Yeah, I think the best place to start would be to look at the [`canFindFlow` function](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-flow-rpc/lib/FlowExecInfoContainer.js#L165). I expect that's returning false, which means something is going wrong in the [`which` utility](https://github.com/facebook/nuclide/blob/master/pkg/commons-node/which.js) which we've halfheartedly attempted to make compatible with Windows.

That should give you a good place to start. I'm happy to answer questions when I can. I should be able to get back to you pretty quickly here during normal working hours on the west coast.

**Comment by cdrini** [comment]
It looks like the issue is in `FlowExecInfoContainer.js::getFlowVersionInformation`, which is trying to run `require('child_process').execFile('flow', ['version', '--json'])`, which gives `Error: spawnSync flow ENOENT`.

I can't run any of my npm globals from `execFile` (or `exec`) without attaching `.cmd`. I.e. this works:

```js
require('child_process').execFile('flow.cmd', ['version', '--json'])
```

This might be a node issue, but python behaves the same way, so I imagine it's not.

**Comment by NikaBuligini** [comment]
@cdrini, thanks!

attaching `.cmd` solved my problem

**Comment by sdwilsh** [comment]
The other tricky part here is the simple fix of adding `.cmd` to the end if you are on a windows system won't work; we'd need to figure out if it's a remote project or local one first, and base the decision on the location of the actual file.
