### ISSUE TITLE
Show diagnostics messages on inline element hover

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/nuclide#914]
It's not actually an issue, but a question: how to configure nuclide to show diagnostic popup on inline element hover like in [this video](https://twitter.com/dan_abramov/status/797147802728022016) (datatip & diagnostics message are combined and shown when inline element is hovered).

I have `nuclide-datatip` & `nuclide-diagnostics-datatip-provider` on, it shows datatip on hover, but to get error messages I still have to hover red arrow in gutter.

```shell
$ apm ls --installed
Community Packages (33) /Users/Alex/.atom/packages
├── advanced-open-file@0.16.4
├── autocomplete-paths@1.0.2
├── color-picker@2.2.3
├── custom-title@1.0.1
├── file-icons@1.7.25
├── flex-tool-bar@0.11.0
├── git-blame@0.4.11
├── highlight-selected@0.11.2
├── language-applescript@0.3.0
├── language-babel@2.48.5
├── language-docker@1.1.7
├── language-jade@0.7.2
├── language-nginx@0.6.2
├── language-pug@0.0.19
├── language-slim@0.5.0
├── linter@1.11.18
├── linter-docker@0.1.4
├── linter-eslint@8.0.0
├── linter-flow@5.5.0
├── linter-scss-lint@3.0.4
├── linter-stylelint@3.6.0
├── maximize-panes@0.2.0
├── merge-conflicts@1.4.4
├── nice-index@1.0.5
├── nucleus-dark-ui@0.10.19
├── nuclide@0.181.0
├── nuclide-test-runner-jest@0.3.0
├── pretty-json@1.6.1
├── set-syntax@0.3.2
├── todo-show@1.8.0
├── tool-bar@1.0.1
├── vim-mode@0.65.2
└── zentabs@0.8.7
```

**Comment by alexfedoseev** [comment]
@nmote Sorry, for the late response. TBH my only experience in hacking the Atom was in https://github.com/facebook/nuclide/pull/877, so I can hardly imagine the quality & amount of work needs to be done here. That being said if it's something I can implement in a few weekends, I can jump on it. Otherwise, it might take forever to finish as I'm quite slammed on the primary project.

**Comment by nmote** [comment]
I think it's not trivial, but it could be done incrementally. At the very least, something that lets non-fb users enable features hidden behind gatekeepers (or even just this specific one) would be nice. Anyway you are certainly under no obligation to contribute, I just like to suggest it when it's not clear how long it will take the core team to get to something.

**Comment by alexfedoseev** [comment]
Closing as it was released, thanks!

**Comment by Zerim** [comment]
@alexfedoseev Could you clarify what specifically was released? Is there a command now that I can hook up to a keyboard shortcut that will let me toggle the visibility of a diagnostics message where my cursor is w/o hovering in the red gutter? (And if so what is it called please).
