### ISSUE TITLE
Ability to turn off atom sidebar hiding

### ISSUE THREAD

**Issue by kvieira90** [facebook/nuclide#917]
### Issue and Steps to Reproduce
Describe your issue and tell us how to reproduce it (include screenshots and/or any console messages).

The issue I'm having is when I turn off Nuclide's tree view, there is no way to stop it from hiding Atom's tree view on load. Turn off Nuclide tree view, turn on Atom tree view, close app, re-open, tree view is gone. I then have to go to preferences and re-turn on tree view every time I want to use the app. 

### Expected Behavior
Tell us what should happen.

There should be some way to turn off Nuclide's tree view and in doing so, keep the normal tree view active. I'm forced to keep going to preferences and turning the normal tree view back on. 

### Actual Behavior
Tell us what happens instead.

Tree view is missing on startup when I turn off Nuclides and turn Atom's back on

### Versions
* Atom:
* Nuclide:
* Client OS:
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by shushz** [comment]
In the Nuclide package settings (not Nuclide's custom, but that in Atom's settings for Nuclide package), towards the end, you have the option to disable the "nuclide-file-tree-feature". Unchecking it should prevent it from messing with the built-in tree view.
