### ISSUE TITLE
Deleting a file from Uncommitted Changes doesn't update UC files tree

### ISSUE THREAD

**Issue by phord** [facebook/nuclide#918]
### Issue and Steps to Reproduce
Delete a file from tree view.  The file element is not removed from Uncommitted Changes until the tree is refreshed by some other event.

![1481066997734](https://cloud.githubusercontent.com/assets/123908/20948474/2da1cfee-bbc9-11e6-8621-93aff9de11f0.gif)

### Expected Behavior
Deleting a file should remove that file from the tree view wherever it exists.

### Versions
* Atom: 1.12.6
* Nuclide: 0.186.0
* Client OS: Ubuntu 16.10

### More info
Deleting a file from the folder view seems to update Uncommitted Changes automatically, if not immediately.

**Comment by phord** [comment]
As shown in the demo, deleting a file from FOLDERS tree view does remove the file from the UNCOMMITTED CHANGES tree view as well.  But when the file is delete from UNCOMMITTED CHANGES, it is only removed from the FOLDERS view until some other event causes the UNCOMMITTED CHANGES view to be refreshed.

**Comment by mostafaeweda** [comment]
Is this a git or mercurial repository?

**Comment by phord** [comment]
This is a Git repository.

**Comment by aadisriram** [comment]
@phord going through your video, the issue that I see is the lack of progress updates that makes it look like it isn't working. You are right, it does what for the repo status to update before updating the uncommitted changes. From the video it seems like the delete is indeed removing the files. Is there any problem other than the slow update of uncommitted changes that i'm not understanding?

**Comment by phord** [comment]
The video is a maybe a little too fast to show it, but when I deleted the first file, it _never_ was removed from the list until I took some further action that caused a refresh. The *file* was actually deleted right away, but the *file list* never updated.

However, I'm not able to reproduce it now.  Maybe it cleaned up in 0.188 already.
