### ISSUE TITLE
Feature Request: Hyperclick - Go back to where you clicked

### ISSUE THREAD

**Issue by deiga** [facebook/nuclide#921]
### Issue and Steps to Reproduce
Clicking anything like a function declaration jumps you to a new location without any good way of returning to where you were before.

### Expected Behavior
Hyperclick should include a keybinding to `Go Back To Last Cursor Position` or something like it

### Actual Behavior
No keybinding exists

**Comment by nmote** [comment]
https://nuclide.io/docs/help/faq/#how-can-i-jump-to-the-last-cursor-position-in-a-file

**Comment by deiga** [comment]
@nmote Thanks for that link. Unfortunately that doesn't really solve the problem as it would require me to install the whole of nuclide. My request was specifically for the `hyperclick` package to include this functionality

**Comment by nmote** [comment]
Unfortunately we don't currently support the standalone hyperclick package. We may split certain parts of Nuclide back out at some point in the future, but right now it's just not worth the extra overhead for us.
