### ISSUE TITLE
Flow was not found when attempting to start it in ...

### ISSUE THREAD

**Issue by martin-cech** [facebook/nuclide#922]
### Issue and Steps to Reproduce
I'm seeing this message after opening Atom. 

I do have flow installed, it is in PATH, I tried manually setting the path in nuclide settings to "c:\Users\<me>\AppData\Roaming\npm\node_modules\flow-bin\flow-win64-v0.33.0\flow.exe", I do have .flowConfig correctly set. When I run `flow` in the console it works. Nuclide just keeps saying it cannot see Flow and shows the error message. This started happening after I updated nuclide package (not sure which version I had before).

### Expected Behavior
Flow errors should be displayed in Nuclide.

### Actual Behavior
Nuclide doesn't seem to find Flow even though it is installed and I can successfully run `flow` in the console.

### Versions
* Atom: 1.12.7
* Nuclide: 0.188.0
* Client OS: Win 10
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by nmote** [comment]
Dup of #911
