### ISSUE TITLE
Is the connection between Nuclide and Nuclide Server on port 9090 encrypted?

### ISSUE THREAD

**Issue by jesseschalken** [facebook/nuclide#927]
I couldn't find any mention of this in the documentation, but for the common use case of editing proprietary code on a remote server over the Internet, it will be important that the connection be encrypted.

Thanks

**Comment by hansonw** [comment]
Yes! Here's a detailed rundown of what happens with the default configuration:

1) We establish an SSH connection to your remote server and then execute `nuclide-start-server` (or whatever you type into the Remote Connection dialog). [[1]](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-remote-connection/lib/SshHandshake.js)
2) [nuclide-start-server](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-server/nuclide-start-server) then starts up [nuclide_server_manager.py](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-server/scripts/nuclide_server_manager.py#L289), which [randomly generates a HTTPS certificate, signing authority and client key](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-server/scripts/nuclide_certificates_generator.py). Unless you pass `--insecure`, of course.
3) The [Nuclide server uses these certificates to start an HTTPS WebSocket server](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-server/lib/NuclideServer.js#L68). The cert/CA/key is then passed back over the SSH connection and stored in the Atom client, and also encrypted and saved in the OS keychain for easy reconnection.
4) Finally, client side, the [`NuclideSocket`](https://github.com/facebook/nuclide/blob/master/pkg/nuclide-server/lib/NuclideSocket.js#L121) class uses these credentials to establish the HTTPS WebSocket connection. All client-server Nuclide interactions go through this connection.

**Comment by jesseschalken** [comment]
Thanks @hansonw
