### ISSUE TITLE
Hyperclick not working

### ISSUE THREAD

**Issue by nickcharles** [facebook/nuclide#929]
### Issue and Steps to Reproduce
I've got a relatively new project and hyperclick isn't working. Unsure what to do to start debugging the issue. It looks like there is a very tiny response when I use the hotkey but it immediately fails and cannot link me to anything. Hyperclick is indeed working if I set up a brand new project.

### Versions
* Atom: 1.12.7
* Nuclide: 0.189.0
* Client OS: OS X 10.11.6

### Additional Details
* Installed packages (`apm ls --installed`):

├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.48.5
├── language-graphql@0.7.0
├── language-ini@1.17.0
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── nuclide@0.189.0
├── nuclide-format-js@0.0.36
├── sort-lines@0.14.0
└── tool-bar@1.0.1

└── (empty)

**Comment by hansonw** [comment]
You'll have to be more specific. What language does your project use? Ideally could you provide a link to the github repo, if it's open source?

Also try looking in the devtools (cmd-opt-i) for any errors/warnings.

**Comment by nickcharles** [comment]
React native project, it's not open source however. I'll take a look at the devtools as soon as I finish up with lunch, that sounds like just what I need.

**Comment by hansonw** [comment]
OK. Note that Hyperclick relies on Flow for Javascript projects, so make sure that's set up and enabled for your files (i.e. they have the `@flow` header.)

**Comment by nickcharles** [comment]
Hmm it could be our lack of flow completion then. I'll look into it, closing this for now and might get back to it later.

Thanks!
