### ISSUE TITLE
Reveal in File-Tree toggles file tree in latest release

### ISSUE THREAD

**Issue by moogus** [facebook/nuclide#939]
### Issue and Steps to Reproduce
Since the latest version of nuclide when I use the right click tab functionality "reveal in file tree" the file tree visual now toggles open-closed.

![reveal_1](https://cloud.githubusercontent.com/assets/4889659/21256976/4e88dd14-c36d-11e6-8572-009848b34d27.png)

![reveal_2](https://cloud.githubusercontent.com/assets/4889659/21256979/5117075e-c36d-11e6-9892-4c2be461d815.png)
 

### Expected Behaviour
Should show file in file explorer.

### Actual Behaviour
Tell us what happens instead.

### Versions
* Atom: 1.12.7
* Nuclide: 0.192
* Client OS: mac
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):

**Comment by hansonw** [comment]
This is fixed in ef68b6517b860; unfortunately it wasn't patched into v0.192. It will be fixed next week for sure, but in the meantime the Command Palette "Reveal Active File" (cmd-shift-\) should probably work correctly.

**Comment by moogus** [comment]
Great stuff thanks
