### ISSUE TITLE
How to debug with `nodemon`? The breakpoint doesn't hit

### ISSUE THREAD

**Issue by spacegoing** [facebook/nuclide#942]
### Issue and Steps to Reproduce
I'm a JS noob looking for some help:-) I'm trying to learn nuclide's debugger follow the official doc. The source code is from [flow's five examples'](https://github.com/facebook/flow/tree/master/examples) `hello.js`.

I started with executing the following command:
`nodemon ./01_HelloWorld/hello.js --exec babel-node`

Then I successfully attached the debugger to this process. The console also printed 
`Starting debugger agent.
Debugger listening on 127.0.0.1:5858`

I added a breakpoint on the 4th line `return x*10`. However, no matter what I do the program just doesn't hit the breakpoint. 

I know that in google dev tools the program will hit breakpoints after `refresh`. How can I do something similar to `refresh`? Would you please tell me what's the next step should I do? Many thanks!

**Comment by hansonw** [comment]
Our node debugging support is very much experimental. It seems that it doesn't respond to console commands yet, but I managed to trigger a breakpoint by pressing pause and then continue (play) to resume the process. Maybe @yinghuitan can comment on other features.

**Comment by spacegoing** [comment]
@hansonw  Thanks for your reply. Did you run it through `nodemon`? I did the same thing (pressing pause and then continue (play)) but still nothing happened.

**Comment by hansonw** [comment]
Ah, that might be trickier. Can you try `nodemon` with the `--debug` flag (provide a port)? I'm not sure if we'll be able figure out the port, but it's worth a try.
