### ISSUE TITLE
Disturbed layout

### ISSUE THREAD

**Issue by scazzy** [facebook/nuclide#944]
Reproduce:

Clicked on `Uncommited changes` in left panel.
Tried to resolve by:
a. Resizing atom, toggling full-screen
b. Clicking other tabs and options, toggling other panes

![image](https://cloud.githubusercontent.com/assets/1681586/21360852/abf6b38e-c707-11e6-9808-c30a8bcb75d5.png)

**Comment by aadisriram** [comment]
I've seen this happen a couple of times with atom 1.10 if i'm right, but its not really a problem with uncommitted changes and its some interactions between the toolbar, file tree and atom together that is causing it. I was unable to narrow it down and find the exact issue as it wasn't a reproable case. Is this a 100% repro for you?
