### ISSUE TITLE
Tree view scrolling not working if tree-ignore is installed

### ISSUE THREAD

**Issue by derwaldgeist** [facebook/nuclide#948]
### Issue and Steps to Reproduce
* Add the tree-ignore plugin and use .atomignore to ignore some files
* Install Nuclide and restart Atom
* Open a project with a long list of folders

### Expected Behavior
You can scroll through the whole list of folders

### Actual Behavior
After scrolling about 1/3 down, the treeview jumps back to top, so it is impossible to scroll the whole way down. 

Notes: Tree scrolling will work after Nuclide has been freshly installed. But as soon as you reload Atom, the errorneous behaviour starts. You can also force the problem by disabling and re-enabling tree-ignore. The standard treeview works as expected, if I enable it in parallel. If I am using a working set, scrolling works until I open too many folders. There seems to be a certain limit of files that have to be visible to trigger the problem.

### Versions
* Atom: 1.12.7
* Nuclide: 0.194.0
* Client OS: MacOS X El Capitan
* Server OS (optional):

### Additional Details
* Installed packages (`apm ls --installed`):
├── Atom-Syntax-highlighting-for-Sass@0.5.0
├── ScssBundle@0.5.0
├── Stylus@3.1.0
├── atom-beautify@0.29.14
├── atom-bootstrap3@1.2.12
├── atom-handlebars@1.3.0
├── atom-html-preview@0.1.22
├── atom-material-syntax@0.4.6
├── atom-material-ui@1.3.8
├── atom-sync@0.7.3
├── atom-typescript@10.1.13
├── autoclose-html@0.23.0
├── autocomplete-html-entities@0.1.0
├── autocomplete-modules@1.6.7
├── autocomplete-paths@1.0.5
├── autocomplete-sass@0.1.0
├── better-handlebars@0.1.1
├── block-travel@1.0.5
├── bottom-dock@0.4.4
├── browser-plus@0.0.87
├── color-picker@2.2.3
├── copy-file-contents@0.3.0
├── cssbeautify@1.3.0
├── devdocs@0.2.1
├── docblockr@0.9.1
├── file-icons@1.7.25
├── fold-comments@0.6.0
├── fold-functions@0.4.4
├── git-control@0.8.2
├── git-history@3.2.0
├── git-plus@6.3.0
├── git-time-machine@1.5.4
├── incremental-search@5.2.1
├── js-autoimport@0.5.1
├── jsformat@0.9.3
├── jshint@1.8.6
├── jsonlint@1.1.4
├── language-SCSS@0.4.0
├── language-babel@2.48.5
├── language-gradle@0.0.3
├── language-mongodb@0.3.1
├── language-spacebars@0.2.2
├── line-count@0.5.0
├── linter@1.11.18
├── linter-manager@0.2.12
├── linter-rorybot@1.1.2
├── linter-scss-lint@3.0.4
├── linter-swiftc@2.0.0
├── markdown-folder@0.5.0
├── markdown-format@2.5.1
├── markdown-preview-plus
├── meteor-api@2.20.0
├── meteor-assist@0.3.0
├── meteor-helper@0.29.0
├── meteor-snippets@0.5.0
├── minimal-syntax@0.16.0
├── minimal-syntax-dark@0.5.2
├── minimap-cursorline@0.2.0
├── minimap-pigments@0.2.2
├── nav-panel@0.0.11
├── nucleus-dark-ui@0.10.19
├── nuclide@0.194.0
├── pane-split-moves-tab@0.1.0
├── peacock-syntax@1.4.0
├── peacocks-in-space-syntax@0.5.3
├── pigments@0.37.0
├── preview-plus@1.2.7
├── project-manager@3.3.3
├── project-view@0.6.1
├── quick-editor@0.4.3
├── react@0.16.1
├── remote-edit@1.8.24
├── sort-lines@0.14.0
├── spacegray-dark-neue-syntax@1.3.0
├── spacegray-dark-neue-ui@1.6.0
├── ssh-config@0.10.1
├── svn@0.0.13
├── symbol-gen@1.3.1
├── symbols-tree-view@0.13.2
├── tidy-markdown@3.0.1
├── todo-manager@0.2.10
├── todo-show@1.8.0
├── tree-ignore@0.6.2
├── tree-view-filter@0.4.1
├── turbo-javascript@1.4.0
└── zentabs@0.8.7

**Comment by mostafaeweda** [comment]
Nuclide deactivates the default Atom file tree package on initialization as nuclide brings its own file tree implementation (that works with remote projects).
https://github.com/facebook/nuclide/blob/master/pkg/nuclide-file-tree/lib/main.js#L304-L348
Since you disabled all of nuclide manually, I'd recommend that you enable Atom's file tree manually too - sorry for the inconvenience.

**Comment by shushz** [comment]
Sorry, I don't see myself getting to support that. This plugin modifies the DOM directly in the file-tree `display:none`ing its elements. Since Nuclide's file-tree is windowed this just would not work not to mention mess the internal positioning logic.
