### ISSUE TITLE
Use an OSI-approved license

### ISSUE THREAD

**Issue by Calinou** [facebook/nuclide#95]
It goes without saying that this software would be better off with an OSI-approved license.

Using the [MIT license](opensource.org/licenses/MIT) makes sense, so that Atom can take code freely from it.

**Comment by jamesgpearce** [comment]
Thanks for the comment! We look at a bunch of different licenses for projects like this and we settled on the present one for various reasons. If there are priority things that you think we should be working with GitHub to upstream, please let us know - we do that as much as possible where we can.

**Comment by bolinfest** [comment]
Closing as @jamesgpearce explained the current status.

**Comment by pombredanne** [comment]
:+1: the license of this project is weird at best and not really open at all. It feels like a candy in a glass box. You can look but you cannot touch. :|
