### ISSUE TITLE
Memory leak due to CodeHighlightManager

### ISSUE THREAD

**Issue by maxbrunsfeld** [facebook/nuclide#953]
### Issue and Steps to Reproduce

I believe Nuclide has a memory leak. To reproduce:

1. Open a large file
2. Close the file
3. Repeat the above two steps many times.
4. Look at Atom's memory usage in `Activity Monitor`

### Expected Behavior

With no files currently open, Atom should use a few hundred megabytes of memory.

### Actual Behavior

Atom uses a lot more memory than that. With Nuclide disabled though, this doesn't happen.

### Versions

* Atom: 1.13
* Nuclide: 0.194.0
* Client OS: Mac OS 10.11.6

### Additional Details

I think the `CodeHighlightManager` retains editors through [the two subscriptions](https://github.com/facebook/nuclide/blob/540ec03d7f7b86923e32d0504b09d977f7287158/pkg/nuclide-code-highlight/lib/CodeHighlightManager.js#L32) that it registers in its `observeTextEditors` callback. You might need to remove these subscriptions when the editor is destroyed, using `TextEditor.onDidDestroy`.

We realize that these kinds of leaks are very easy to create. There are two outstanding PRs to reduce their user-facing impact:

https://github.com/atom/atom/pull/13523
https://github.com/atom/text-buffer/pull/193

Thanks!

/cc @nathansobo

**Comment by maxbrunsfeld** [comment]
I wrote up [a little document about this](https://gist.github.com/maxbrunsfeld/d3671eb644e54d251b43c0093a7fa466) that we will soon incorporate into the flight manual. It looks like in most places, Nuclide already does the right thing.

**Comment by johnislarry** [comment]
Thanks @maxbrunsfeld!  I just landed the fix and it'll be in this week's release.  That doc was helpful :)

**Comment by maxbrunsfeld** [comment]
Nice! Thanks @johnislarry.
