### ISSUE TITLE
How to start Debugging React Native Application with Android Studio AVD (Android Virtual Device)

### ISSUE THREAD

**Issue by pdarde** [facebook/nuclide#956]
### Issue and Steps to Reproduce
Hi, I'm not able to debug my application within Nuclide. I'm working with Linux Elementary and Atom Nuclide. I'm trying to debug with the following steps.

1. Open Android Studio and AVD running. 

2. Open Nuclide and start packager from menu 'Nuclide' -> 'React Native' -> 'Start Packager'. 
All works fine until here. I can see my nuclide console starting my application from 'npm start'.

3. I start my app from terminal running 'react-native run-android'. My app runs ok on AVD emulator.

4. I open the menu 'Nuclide' -> 'React Native' -> 'Start Debugger'. Debugger remains to wait for a process to be attached.

5. I open the menu 'Nuclide' -> 'Debugger' -> 'Launch/Attach', here, prompts a modal window to me. However, if I choose **React Native** from the **type** dropdown, I can only see the option **local**  in the  'connection' dropdown. Here, I cannot move on. 

Can someone help me, please? 

### Expected Behavior
I expect to attach my application process to debug.

### Actual Behavior
I cannot find my application process to attach.

### Versions
* Atom: 1.12.4
* Nuclide:
* Client OS: Linux Elementary

**Comment by haitaoli** [comment]
You need to "Start remote JS debugging" from context menu when app is running.

**Comment by johnislarry** [comment]
You can start the RN debugger in a much simpler way from the command palette.  Open the command palette with `cmd+shift+P`, and search for 'React Native' to find the 'Start React Native Debugger' command.

**Comment by johnislarry** [comment]
Historically this RN debugger has given users some trouble, see https://github.com/facebook/nuclide/issues/900.  If you want to try an experimental debugger, you can choose `iOS Webkit Debug Proxy` in the debugger selection modal `cmd+shift+A`.  In the latest release this is renamed to the more appropriate `Mobile JS`.  Feel free to re-open if none of these suggestions work for you!
