### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by RamIdeas** [facebook/nuclide#96]
I installed atom 0.211.0 and then installed the nuclide-installer package.

It churned the CPU, as expected thanks to the note in the README about babel transforming the js files (side note: why transpile on each users' machine and not before releasing the package?)

I then decided to have a peek in the dev tools and saw an uncaught error:

``` js
{
    exitCode: 1,
    stderr: '[31m
npm ERR! git fetch -a origin (https://github.com/kevinsawicki/jasmine-node.git) fatal: Unable to find remote helper for 'https'
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\<username>\\AppData\\Local\\atom\\app-0.211.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\<username>\\AppData\\Local\\atom\\app-0.211.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\<username>\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\<username>\\.atom\\.apmrc" "install" "C:\\Users\\<username>\\AppData\\Local\\Temp\\d-115524-8592-1gm5wn9\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: fatal: Unable to find remote helper for 'https'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

[39m
',
    stdout: 'Installing nuclide-click-to-symbol@0.0.21 to C:\Users\<username>\.atom\packages [31mfailed
[39m'
}
```

I also mentioned this in #90 but it seems the problem wasn't specific to `nuclide-click-to-symbol`. After opening powershell and runnings `apm install nuclide-click-to-symbol` I reloaded atom and saw the exact same error except the `stdout` property mentioned `nuclide-code-format`. Repeating this process, the subsequent errors were for `nuclide-diff-view`, `nuclide-file-tree`, `nuclide-flow`, `nuclide-hack`, `nuclide-hg-repository`, `nuclide-quick-open`, and `nuclide-remote-projects`.

My main reason for pointing this out is that .jsx files don't seem to be recognised and selecting 'JavaScript' as the file format (as opposed to 'Auto Detect') doesn't highlight jsx tags.

As far as I can tell no perceivable extra features have been added to atom, except the file-tree font size looks smaller.

**Comment by ssorallen** [comment]
This looks related to the Windows + Git installation problem: https://github.com/facebook/nuclide/issues/56#issuecomment-111715649

Shipping transpiled code is something we have discussed, but it is not yet in the works.

**Comment by ssorallen** [comment]
This problem also occurred for some users when installing Atom: https://github.com/npm/npm/issues/5346 It appears related to how Git was installed and whether it has support for "https" repos.

**Comment by RamIdeas** [comment]
I installed git using the Github for Windows installer -- not sure what the problem could be since all repos I clone use the https:// url from the browser...

So I uninstalled Atom and Github for Windows just in case and deleted the respective folders from AppData.

Reinstalled both but had the exact same problem in regards to the https helper error. I then dug through the atom folders and found `C:\Users\<username>\.atom\.apm\_git-remotes\https-github-com-kevinsawicki-jasmine-node-git-38e2b399`.

So I cloned "https://github.com/kevinsawicki/jasmine-node" using the Github GUI Client and copied the downloaded files into the folder above.

Reloading atom then churned the CPU for over 20 minutes (on a quad-core 3.4GHz i5, really?) and with no further manual steps the nuclide packages show up in atoms settings page.

But still no jsx support? Is that a unix only feature??

**Comment by ssorallen** [comment]
@jgebhardt, are you familiar with JSX language support in Atom or Nuclide? Nuclide ships Hack support via https://atom.io/packages/nuclide-language-hack, but I'm unaware of how JSX is handled.

**Comment by cjgendron** [comment]
@RamIdeas, are you running the commands with administrative privileges? https://github.com/npm/npm/issues/5346 mentions this as the solution for a lot of commenters.

**Comment by RamIdeas** [comment]
That thread was mentioning building atom from source. I just installed it via the clickonce installer. I did *try* cloning and building from source, with administrative privileges, but that just lead to issues from node-gyp which is notoriously dodgy on windows.

Any commands I typed into powershell (regarding nuclide) never really failed, anyway. Errors only showed when starting atom. But on my reinstall, after manually cloning jasmine-node, there are no errors. Atom starts. Nuclide packages all seem installed. Just no JSX highlighting, no alt+click to jump to definition, etc...

**Comment by RamIdeas** [comment]
I feel I should mention that I have iojs installed and whenever an application wants to use node, it uses the node.exe from iojs which is just an exact copy of iojs.exe

**But** the process transpiling for ages when I started atom after installing nuclide was an actual node.exe found at `C:\Users\<username>\AppData\Local\atom\app-0.211.0\resources\app\apm\bin` and is v0.10.35

**Comment by ALF-er** [comment]
@RamIdeas Launch atom As Admin, worked for me

**Comment by bolinfest** [comment]
@RamIdeas I believe this is because you do not have `git` on your `%PATH%`, as required by https://github.com/facebook/nuclide/#building-from-source. As noted in https://github.com/facebook/nuclide/issues/56#issuecomment-119373196, I have removed the `git` requirement for end-users of Nuclide, but it still applies for people who are trying to hack on Nuclide itself.

**Comment by RamIdeas** [comment]
@bolinfest definitely had `git` in my PATH. I had a feeling `apm` wasn't -- well it was, but might have been truncated out as there seems to be an arbitrary 1024 character limit that applies only in ’some' programs. So I cleaned out the junk from my PATH variable but still no dice.

@ALF-er Run As Administrator made no noticeable difference.

I've just been using atom and other apm packages such as `react` and `atom-ternjs` -- only issue is ternjs doesn't really support es6 -- which I make heavy use of.

Tbh, I don't even know what I was expecting from nuclide -- I was intrigued by anything that could ease my react webapp development. Right now, I guess I'm just waiting for TypeScript 1.6 so I can go back to a reliable IDE but still use generators and other ES6 goodness!
