### ISSUE TITLE
website: images and links are broken due to extra /nuclide/ in the URL

### ISSUE THREAD

**Issue by nzmichaelh** [facebook/nuclide#967]
To reproduce:

* Visit https://nuclide.io/
* See the logo is broken (links to https://nuclide.io/nuclide/static/logo_nav.png)
* Click 'Docs' in the top nav bar
* See a 404 on https://nuclide.io/nuclide/docs/

**Comment by JoelMarcey** [comment]
This is fixed now. I have to fix this manually for the time being. Due to an issue we are trying to work with GitHub to get fixed. Hopefully this problem is resolved permanently early next week.

**Comment by JoelMarcey** [comment]
Sorry for the inconvenience.
