### ISSUE TITLE
Nuclide flow cannot work

### ISSUE THREAD

**Issue by Saviio** [facebook/nuclide#97]
Hi

I'm really like the Nuclide-flow function, but when I follow the guide and finish the installation, I cannot get error highlighting. However, if I install "linter-plus" package, after I save the JS file, atom will display the check message but the behaviour still not like demo what was shown in official site. Unfortunately the "click-to-define" function not worked either.

I'm pretty sure that flow was installed in my computer(via homebrew), and I already executed the " flow init " in the project path.

Did I miss anything？

OS: OSX 10.9
Atom version:0.211

**Comment by aewing** [comment]
You'll have to provide more information than this. Which OS are you using? Is Flow installed and available on your path? Are you getting any errors in the console in Atom?

**Comment by Saviio** [comment]
Hi @aewing

Sorry for fast click, I added my detail, do you have any suggestion?

**Comment by nmote** [comment]
> atom will display the check message but the behaviour still not like demo what was shown in official site

Can you clarify? Does it display Flow errors, but differently than the screenshots, or does it not display them at all? If it doesn't display them at all, this might be related to #91.

**Comment by Saviio** [comment]
Hi @nmote

see 
linter-plus: [enable]
![k](https://cloud.githubusercontent.com/assets/3467408/8334685/cc8ca9b2-1acb-11e5-8fa0-3ab612ebb54a.png)

linter-plus: [disable]
![p](https://cloud.githubusercontent.com/assets/3467408/8334694/d545dd44-1acb-11e5-910a-8d8c9add321c.png)

**Comment by aewing** [comment]
linter-plus is a newer package and from what I understand linter-plus is in a transitional phase and will soon be merged into atom-linter, so I am sure this is the reason for the optional (though strongly suggested) designation in the README.

**Comment by nmote** [comment]
@Saviio: Thank you for the detailed comment. There are a couple things going on here:

* On Monday we moved from linter to linter-plus, which accounts for the difference in UI. Unfortunately the Flow docs were not updated along with this change. That would also explain why it didn't work at all without the linter-plus package. CC @oclbdk -- should linting work without the linter-plus package? If not, should we update the documentation and make sure that linter-plus is installed?
* Click-to-define not working is being tracked in #92.

**Comment by nmote** [comment]
I'm going to close this since it looks like these are the only two issues here.
