### ISSUE TITLE
Nuclide C++ RUN/BUILD with BUCK

### ISSUE THREAD

**Issue by theobouwman** [facebook/nuclide#971]
I want to build and run C++ programs from Nuclide using Buck.
The problem is that I don't know how to setup a simple Buck configuration file in Nuclide to build and then run a `.cpp` file.

So does someone have a suggestion?

**Comment by hansonw** [comment]
Check out the example in https://buckbuild.com/rule/cxx_binary.html for a example of a simple binary using Buck (https://buckbuild.com/setup/install.html).
The output should be in `buck-out/gen/echo` or similar.

**Comment by theobouwman** [comment]
I am able to build my project from within Nuclide and this is my code:
```
#include <iostream>
using namespace std;

int main() {
   cout << "Hello World";
   return 0;
}
```
But `Clang` gives me a warning at line 1:
```
Diagnostics are disabled due to lack of compilation flags. Build this file with Buck, or create a compile_commands.json file manually.: /development/projects/cpp/first_project/first.cpp:1
```
even when it is build with Buck.

And I can't run my project with from within Nucline using the Buck Task Runner but I can run it with the Buck CLI: `buck run :first`.

**Comment by hansonw** [comment]
The "run" workflow isn't supported for binaries yet, unfortunately. (We find that many binaries require some kind of piping to be useful, so we haven't found this to be a pressing need).

Could you try "Nuclide > Clang > Clean and Rebuild" from the menu to see if that fixes the warning? Otherwise, try opening the dev console (cmd+alt+i) to see if there's any messages that indicate why the flags couldn't be found.

**Comment by theobouwman** [comment]
Your solution `Nuclide > Clang > Clean and Rebuild` fixed the error message. 👍 
So am I right that it's currently not possible to run a c++ program form Nuclide?

**Comment by stepanhruda** [comment]
In the next release, you will be able to run c++ binaries through the buck task runner.

(fixed by https://github.com/facebook/nuclide/commit/65a89584e6a3554d5cd67532715942b9a76e0cc6)

**Comment by skywhat** [comment]
Here is a good example to start.
https://hackernoon.com/how-to-create-a-buck-based-c-c-project-38b85273d6a6
