### ISSUE TITLE
Split right from context menu not working

### ISSUE THREAD

**Issue by moogus** [facebook/nuclide#972]
### Issue and Steps to Reproduce
Hello

_Latest version of nuclide fixes the show in file tree, but breaks the split conext menu function._

#### Go to the file tree right click for context menu select split right:

![spli_1](https://cloud.githubusercontent.com/assets/4889659/21800795/13f34096-d717-11e6-8d53-2b61090fef7b.png)

#### This is what you get:

![spli_2](https://cloud.githubusercontent.com/assets/4889659/21800853/524d62c2-d717-11e6-898e-6c4fa2068eb2.png)

### Expected Behavior
should open the selected file in a split window

### Actual Behavior
adds an empty panel in the file tree 

### Versions
* Atom:latest (not beta)
* Nuclide:latest
* Client OS:OSX

### Additional Details
* Installed packages (`apm ls --installed`):
[all atom settings](https://gist.github.com/moogus/68ad9382e046e7c289fe)

**Comment by matthewwithanm** [comment]
Hi @moogus! I don't think the file tree ever had a context menu item like you describe, did it? The items you're seeing are entirely new ones that come as a result of putting the file tree into a panel. This way, users can have more control over their workspace (for example, by dragging the source control tab below the the file tree).

**Comment by moogus** [comment]
Hi 

Ok I've had one for as long as I can remember.  Don't think it's from an add-on.  Have you tried a right click in the file tree as in the images?

**Comment by moogus** [comment]
![split](https://cloud.githubusercontent.com/assets/4889659/21840776/32c16b4a-d7d7-11e6-95e9-cc2cb2228590.png)


Just installed a vanilla version of atom on a vm, the context menu in the file tree is an atom standard feature.

**Comment by matthewwithanm** [comment]
Oh, I see. We have that under the "Split" submenu.

Yeah, this is confusing.

**Comment by matthewwithanm** [comment]
@shushz How do you think we should resolve this? My first inclination is that we should keep the separate "Split" items (mirroring the regular Atom menu). Then they would override the same-named items added for the `atom-pane` selector.

It's a little weird that the same label does different things, but Atom's the same way so…

**Comment by matthewwithanm** [comment]
@moogus Thanks for the screenshot btw!

**Comment by matthewwithanm** [comment]
Should be fixed by 2e08e5327f3ed0e2cf49aa9de20bb45eca1f03e4. Thanks again @moogus!

**Comment by moogus** [comment]
Thanks
