### ISSUE TITLE
Task Runner vs CLI speed

### ISSUE THREAD

**Issue by theobouwman** [facebook/nuclide#973]
Running `buck build :app` is 2 to 3 times faster then using the Buck Task Runner Build option.

Why is this?

**Comment by hansonw** [comment]
Oof, looks like just getting the Buck Websocket port takes 1-2 seconds on a Mac. I can probably add an option to skip that, since it's not super critical.

**Comment by theobouwman** [comment]
@hansonw it actually takes 15 seconds to compile a 12 line program..

**Comment by hansonw** [comment]
dc829a14ea4ea60b9355b9123a48883dbed3f5b2 and 20e02820661bdccfee320bdb2493ed29b3e0f3f6 should go a long way towards fixing this. They should be coming out next week
