### ISSUE TITLE
Deprecated selector in `nuclide/pkg/nuclide-ui/styles/CodeSnippet.less`

### ISSUE THREAD

**Issue by mgigirey** [facebook/nuclide#975]
In `nuclide/pkg/nuclide-ui/styles/CodeSnippet.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.nuclide-ui-code-snippet atom-text-editor .highlight.code-snippet-highlight .region,
.nuclide-ui-code-snippet atom-text-editor::shadow .highlight.code-snippet-highlight .region` => `.nuclide-ui-code-snippet atom-text-editor .highlight.code-snippet-highlight .region,
.nuclide-ui-code-snippet atom-text-editor.editor .highlight.code-snippet-highlight .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by zertosh** [comment]
Yup, thanks! See ea2580d2e8cbe1918f154af6980b55e09b379449. It'll be out in next week's release.
