### ISSUE TITLE
Deprecated selector in `nuclide/pkg/nuclide-diff-view/styles/gutter.atom-text-editor.less`

### ISSUE THREAD

**Issue by codethebeard** [facebook/nuclide#976]
In `nuclide/pkg/nuclide-diff-view/styles/gutter.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.nuclide-diff-view-navigation-target.added,
.nuclide-diff-view-navigation-target.syntax--added` => `.nuclide-diff-view-navigation-target.syntax--added,
.nuclide-diff-view-navigation-target.syntax--added`

* `.nuclide-diff-view-navigation-target.removed,
.nuclide-diff-view-navigation-target.syntax--removed` => `.nuclide-diff-view-navigation-target.syntax--removed,
.nuclide-diff-view-navigation-target.syntax--removed`

* `.nuclide-diff-view-navigation-target.modified,
.nuclide-diff-view-navigation-target.syntax--modified` => `.nuclide-diff-view-navigation-target.syntax--modified,
.nuclide-diff-view-navigation-target.syntax--modified`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by zertosh** [comment]
Dupe #975.
