### ISSUE TITLE
Can't run `Nuclide React Native: Start Packager` from new install

### ISSUE THREAD

**Issue by hborders** [facebook/nuclide#977]
### Issue and Steps to Reproduce
1. I created a react-native project using the [Hello World example](https://facebook.github.io/react-native/docs/tutorial.html)
1.1. As part of the tutorial, I installed `node` and `watchman` with `brew`.
2. As suggested by the last page of the tutorial, I installed Nuclide and tried to debug my project there.
3. I downloaded Atom for Mac OS X.
4. I installed Nuclide via Settings->Install [as instructed](https://nuclide.io/docs/editor/setup/#macos__prerequisites).
5. I opened my project directory in Nuclide
6. I ran `Nuclide React Native: Start Packager`

### Expected Behavior
I expected my application to start [as the guide shows](https://nuclide.io/docs/platforms/react-native/#running-applications__react-native-packager).

### Actual Behavior
I get the following error in the console:
```
An unexpected error occurred while running the React Native Packager process:

**spawn node ENOENT**
```
and the following pop-up:
<img width="465" alt="error-while-running-the-react-native-packager-process" src="https://cloud.githubusercontent.com/assets/166391/21860102/c767e608-d7f4-11e6-82e9-b39f86757d02.png">

### Versions
* Atom: 1.13.0
* Nuclide: 0.197.0
* Client OS: Mac OS X 10.11.6
* Server OS (optional):

### Additional Details
├── haskell-grammar@0.4.0
├── highlight-selected@0.11.2
├── language-babel@2.49.4
├── language-graphql@0.8.0
├── language-ini@1.17.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── merge-conflicts@1.4.4
├── nuclide@0.197.0
├── nuclide-format-js@0.0.36
├── set-syntax@0.3.2
├── sort-lines@0.14.0
└── tool-bar@1.0.1

**Comment by hborders** [comment]
I tried uninstalling `node` and `watchman` from `brew`, but it didn't change anything.

**Comment by hborders** [comment]
I installed Xcode, Command Line Tools, Atom, and Nuclide in a fresh OS X 10.11.6 VM (I didn't install homebrew, node, or anything else) and I get the same error. I must be missing a step in your instructions somewhere.

**Comment by hborders** [comment]
I saw in the [Nuclide Debugging documentation](https://nuclide.io/docs/platforms/react-native/#debugging), there is an explicit step saying I need to install react native, so I did that using `brew` and `npm`, and now things work on my VM.

**Comment by hborders** [comment]
I finally got it working on my main machine by giving nuclide the fully qualified path of my `node` binary: `/usr/local/bin/node`. I have no idea why it couldn't find it.

**Comment by matthewwithanm** [comment]
Sorry for the slow response, but glad you figured it out! It should work fine as long as node's on your PATH (Atom tries to construct the correct PATH variable).
