### ISSUE TITLE
Outline View not working in Python

### ISSUE THREAD

**Issue by wynsmart** [facebook/nuclide#987]
### Issue and Steps to Reproduce
Open a Python source code file with atom, then toggle on the Outline View, it shows nothing.
![screen shot 2017-01-17 at 9 17 26 am](https://cloud.githubusercontent.com/assets/5366347/22024145/fb23369a-dc96-11e6-9710-21e495efaffd.png)

### Expected Behavior
There should be structured bookmarks listed in the view.

### Actual Behavior
The list is empty

### Versions
* Atom: 1.13.0 (x64)
* Nuclide: 0.197.0
* Client OS: MacOSX 10.12.2

**Comment by shushz** [comment]
I can't repro that 😦 

@wynsmart, could you please attach the logs? They are under <system-temp-folder>/nuclide-<username>-logs. You can print the system temp folder with `node -p "os.tmpdir()"` if you have node installed or by opening devtools in Atom (Cmd-Opt-i) and issuing a `require('os').tmpdir()` command in the console.

**Comment by shushz** [comment]
Oh, maybe it's related to a fix in https://github.com/facebook/nuclide/pull/985

**Comment by wynsmart** [comment]
Hi @shushz, I've found the cause in more details.
It performs good when I use default Python (/usr/bin/python) in MacOS. The problem occurs when I use a virtualenv exported Python3. I used virtualenv to generate a folder contains Python3 stuff, then added that to PATH, in order to override the default version (not activate the virtualenv, exec bin directly). Here's the console outputs.

(BTW, I also find that the autocomplete not working. It seems they are related issues)

![screen shot 2017-01-19 at 4 26 15 pm](https://cloud.githubusercontent.com/assets/5366347/22126017/067f4abe-de64-11e6-9ae7-6c5ee62abb66.png)

**Comment by shushz** [comment]
It seems to have been fixed in a PR merged this week: https://github.com/facebook/nuclide/pull/968
Let's see whether it repros in next week's release (v0.201.0)

**Comment by wynsmart** [comment]
I just updated to 0.201.0, and the issue is resolved.
Thanks~

**Comment by shushz** [comment]
Cool. Thanks for the confirmation. 😃
