### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by roselind** [facebook/nuclide#990]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:43:14)
MarkerLayer.markPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-layer.js:204:24)
DisplayMarkerLayer.markBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-marker-layer.js:94:62)
TextEditor.markBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1761:38)
<unknown> (/Users/zhangxiaojing/.atom/packages/nuclide/pkg/nuclide-debugger-atom/lib/BreakpointDisplayController.js:249:43)
Set.forEach (native)
```

**Comment by shushz** [comment]
CC @johnislarry - according to the stack trace it's the debugger.

**Comment by johnislarry** [comment]
A quick look doesn't show that we're assigning any custom properties to the marker that I can see.  I think it's likely that there is a codepath inside atom that can assign custom properties to a marker.  A google search for similar issues turns up a lot of different results:

https://www.google.com/search?q=github+atom+issue+Function.extractParams

Closing this out as a wontfix, feel free to re-open if there is more compelling evidence that we're actually violating this deprecation.
