### ISSUE TITLE
File delete with osx BACKSPACE not working

### ISSUE THREAD

**Issue by aight8** [facebook/nuclide#991]
### Issue and Steps to Reproduce
Disabled all plugins. Use only nuclide. Click on a file and hit backspace. The delete dialog which appears normally is not showed.

### Expected Behavior
Show the delete dialog.

### Actual Behavior
It's not showing the delete dialog.

### Versions
* Atom: 1.13.0
* Nuclide: 0.199
* Client OS: macOS

**Comment by shushz** [comment]
File-tree has an automatic file search - if you focus the file tree and start typing it'll start matching only files with names containing the typed string. You can also backspace to delete characters from that filter. Having backspace suddenly delete a file would probably not be a good experience.

The file can be deleted by hitting the "delete" key. You can also change the keybinding of the `nuclide-file-tree:remove` command to something else, if "delete" is not convenient.

**Comment by aight8** [comment]
Uh this makes sense! I was so focused on the other feature I not recognized that ;)
Then it's not valid here: https://nuclide.io/docs/editor/keyboard-shortcuts/

**Comment by shushz** [comment]
Thanks! Will fix.

**Comment by aight8** [comment]
However.. I made a little research to accomplish the goal to delete a file with cmd-backspace.
I found this one which treats the same behaviour (https://github.com/facebook/nuclide/blob/master/pkg/nuclide-file-tree/keymaps/nuclide-file-tree.json#L27)
```
'nuclide-file-tree':
  'cmd-backspace': 'nuclide-file-tree:remove'
```
But this not works - it happen nothing.
The event is caught in the key binding resolver.

**Comment by shushz** [comment]
No problem 😃  Yeah, it can be tricky sometimes.
