### ISSUE TITLE
change line length to disable nuclide-python warnings

### ISSUE THREAD

**Issue by kracwarlock** [facebook/nuclide#997]
### Issue and Steps to Reproduce
`nuclide-python` gives Warnings like `line too long (117 > 79 characters)`
how can this line length limit be increased?

**Comment by matthewwithanm** [comment]
Hi @kracwarlock! Nuclide will search for [`.flake8` config files][1]. We don't (currently) support `setup.cfg` or `tox.ini`, but we should. PRs welcome!

[1]: http://flake8.pycqa.org/en/latest/user/configuration.html

**Comment by kracwarlock** [comment]
So, using `.flake8` worked!
However each `flake8` error now also appears duplicated as a warning.
