### ISSUE TITLE
Diagnostics panel is cutting Flow errors description

### ISSUE THREAD

**Issue by montogeek** [facebook/nuclide#998]
### Issue and Steps to Reproduce
I am using Nuclide with Flow, when you open the Diagnostics panel, the Description column is cutting Flow errors, like this:
![image](https://cloud.githubusercontent.com/assets/1002461/22249320/87cee35e-e210-11e6-83f7-f852fae5eef8.png)
This also happen when you select "Show only diagnostics for this file":
![image](https://cloud.githubusercontent.com/assets/1002461/22249326/96de602c-e210-11e6-86a6-3eabd83b1b1a.png)

But the inline errors show the error message fully:
![image](https://cloud.githubusercontent.com/assets/1002461/22249345/a6922cec-e210-11e6-9082-2a3d4fb2e708.png)

There is a lot of space to show the full error message in the Description column

I could work on its fix

### Expected Behavior
Description column in Diagnostic panel should show full Flow error message

### Actual Behavior
Description column in Diagnostic panel is cutting Flow error message

### Versions
* Atom: 1.13.0
* Nuclide: 201
* Client OS: OSX Sierra

### Additional Details
* Installed packages (`apm ls --installed`):
<details>
Community Packages (39) /Users/montogeek/.atom/packages
├── Zen@0.16.4
├── atom-material-ui@1.3.9
├── docblockr@0.9.1
├── duotone-dark-red-syntax@0.3.2
├── editorconfig@2.2.0
├── emmet@2.4.3
├── enzyme-snippets@0.1.0
├── file-icons@2.0.12
├── filesize@2.0.4
├── git-plus@7.2.0
├── haskell-grammar@0.4.0
├── highlight-selected@0.12.0
├── jump-to-line@0.2.0
├── language-babel@2.49.4
├── language-graphql@0.8.0
├── language-ini@1.17.0
├── language-lua@0.9.11
├── language-ocaml@1.1.2
├── language-swift@0.5.0
├── language-thrift@1.0.2
├── linter@1.11.21
├── linter-eslint@8.0.0
├── material-ui@1.0.9
├── merge-conflicts@1.4.4
├── nuclide@0.201.0
├── nuclide-format-js@0.0.36
├── oceanic-next@1.0.0
├── one-dark-vivid-syntax@1.7.1
├── pigments@0.38.0
├── pretty-json@1.6.1
├── project-manager@3.3.3
├── react-es6-snippets@0.3.0
├── set-syntax@0.3.2
├── seti-ui@1.4.0
├── sort-lines@0.14.0
├── synced-sidebar@0.4.3
├── tool-bar@1.0.1
├── vim-mode-plus@0.80.0
└── wakatime@6.0.12
</details>

**Comment by matthewwithanm** [comment]
@nmote Thoughts?

**Comment by nmote** [comment]
Check out the "Show full diagnostic traces" setting. IIRC it's not the default just because it takes up a lot more room, and the diagnostics panel is intended as an overview.

**Comment by montogeek** [comment]
Thanks

**Comment by mwalkerwells** [comment]
Wow, super helpful. I wish this was on by default....or at least easier to toggle on & off in the Diagnostics view.

**Comment by nmote** [comment]
@mwalkerwells I don't believe it should be on by default but I would happily review a PR to add a toggle switch for it, next to the "show only diagnostics for current file" one

**Comment by montogeek** [comment]
That would be cool

**Comment by mwalkerwells** [comment]
@nmote There you go!
